import { _uiDictionary } from "./i18n";
import { DEFAULT_RECOMMENDATIONS } from "./recommendation-defaults";
import type { UILanguage } from "./ui-prefs";

export function buildKnowledgeBase(lang: UILanguage): string {
  const dict = _uiDictionary[lang] ?? _uiDictionary.en;

  const calcEntries = Object.entries(dict)
    .filter(([k]) => k.startsWith("calc."))
    .map(([k, v]) => `${k.replace("calc.", "")}: ${v}`);

  const recEntries = DEFAULT_RECOMMENDATIONS.map((r) => {
    const title = r.title[lang] || r.title.en || Object.values(r.title)[0];
    const text = r.text[lang] || r.text.en || Object.values(r.text)[0];
    return `[${r.source}] (${r.category} / ${r.modality}) ${title}: ${text}`;
  });

  const supplementary = buildSupplementaryData(lang);

  return [
    "=== CALCULATOR & QUICK REFERENCE DATA ===",
    calcEntries.join("\n"),
    "",
    "=== KEY CLINICAL VALUES (from calculator tables) ===",
    supplementary,
    "",
    "=== CLINICAL RECOMMENDATIONS ===",
    recEntries.join("\n"),
  ].join("\n");
}

function buildSupplementaryData(lang: UILanguage): string {
  const L = {
    es: {
      aortaTitle: "DIÁMETROS AÓRTICOS NORMALES",
      segment: "Segmento", male: "Hombre", female: "Mujer", aneurysm: "Umbral aneurisma",
      washoutTitle: "LAVADO ADRENAL (CT)",
      apw: "APW (lavado absoluto)", rpw: "RPW (lavado relativo)",
      adenoma: "Adenoma", indeterminate: "Indeterminado", suspicious: "Sospechoso",
      tiradsTitle: "ACR TI-RADS — PUNTUACIÓN POR CATEGORÍA",
      bosniak: "CLASIFICACIÓN BOSNIAK 2019",
      piradsTitle: "PI-RADS v2.1 — PROBABILIDAD DE CÁNCER CLÍNICAMENTE SIGNIFICATIVO",
    },
    en: {
      aortaTitle: "NORMAL AORTIC DIAMETERS",
      segment: "Segment", male: "Male", female: "Female", aneurysm: "Aneurysm threshold",
      washoutTitle: "ADRENAL WASHOUT (CT)",
      apw: "APW (absolute percentage washout)", rpw: "RPW (relative percentage washout)",
      adenoma: "Adenoma", indeterminate: "Indeterminate", suspicious: "Suspicious",
      tiradsTitle: "ACR TI-RADS — SCORE BY CATEGORY",
      bosniak: "BOSNIAK 2019 CLASSIFICATION",
      piradsTitle: "PI-RADS v2.1 — PROBABILITY OF CLINICALLY SIGNIFICANT CANCER",
    },
    pt: {
      aortaTitle: "DIÂMETROS AÓRTICOS NORMAIS",
      segment: "Segmento", male: "Homem", female: "Mulher", aneurysm: "Limiar de aneurisma",
      washoutTitle: "LAVAGEM ADRENAL (TC)",
      apw: "APW (lavagem absoluta)", rpw: "RPW (lavagem relativa)",
      adenoma: "Adenoma", indeterminate: "Indeterminado", suspicious: "Suspeito",
      tiradsTitle: "ACR TI-RADS — PONTUAÇÃO POR CATEGORIA",
      bosniak: "CLASSIFICAÇÃO BOSNIAK 2019",
      piradsTitle: "PI-RADS v2.1 — PROBABILIDADE DE CÂNCER CLINICAMENTE SIGNIFICATIVO",
    },
  };
  const l = L[lang] || L.en;

  return [
    `${l.aortaTitle}:`,
    `${l.segment} | ${l.male} (cm) | ${l.female} (cm) | ${l.aneurysm}`,
    "Aortic root (sinuses of Valsalva) | 3.4–3.7 | 3.0–3.3 | > 4.5 cm",
    "Sinotubular junction | 2.9–3.2 | 2.6–2.9 | —",
    "Mid-ascending aorta | 3.0–3.5 | 2.7–3.2 | > 4.5 cm",
    "Aortic arch | 2.5–3.0 | 2.3–2.7 | > 4.0 cm",
    "Aortic isthmus | 2.0–2.5 | 1.8–2.3 | —",
    "Mid-descending aorta | 2.3–2.8 | 2.1–2.5 | > 4.0 cm",
    "Suprarenal aorta | 2.0–2.5 | 1.8–2.2 | > 3.5 cm",
    "Infrarenal aorta | 1.7–2.1 | 1.5–1.8 | > 3.0 cm",
    "",
    "AORTIC ANEURYSM SURGICAL THRESHOLDS (ACC/AHA 2022):",
    "Aortic root > 5.5 cm (Marfan > 5.0 cm; Loeys-Dietz 4.0–4.5 cm)",
    "Ascending aorta > 5.5 cm (BAV > 5.0–5.5 cm)",
    "Aortic arch > 5.5 cm",
    "Descending thoracic > 5.5–6.0 cm (TEVAR > 5.5 cm)",
    "Infrarenal AAA > 5.5 cm (M) / > 5.0 cm (F) (EVAR > 5.5 cm)",
    "",
    "AORTIC ARCH VARIANTS:",
    "Normal arch (3 vessels) ~70%: BT, LCCA, LSA separate from arch",
    "Bovine arch ~20–27%: common origin BT+LCCA or LCCA from BT",
    "Aberrant right subclavian ~1–2%: RSA distal to LSA, retroesophageal (Kommerell diverticulum)",
    "Left vertebral from arch ~5%: LVA arises directly from arch between LCCA and LSA",
    "Right-sided arch ~0.1%: arch crosses to right, look for vascular ring",
    "",
    `${l.washoutTitle}:`,
    `${l.apw}: ≥ 60% = ${l.adenoma} | 40–59% = ${l.indeterminate} | < 40% = ${l.suspicious}`,
    `${l.rpw}: ≥ 40% = ${l.adenoma} | < 40% = ${l.suspicious}`,
    "Unenhanced density ≤ 10 HU = lipid-rich adenoma (no washout needed)",
    "Formula: APW = ((enhanced − delayed) / (enhanced − unenhanced)) × 100",
    "Formula: RPW = ((enhanced − delayed) / enhanced) × 100",
    "",
    `${l.tiradsTitle}:`,
    "TR1 (benign): 0 points → no FNA",
    "TR2 (not suspicious): 2 points → no FNA",
    "TR3 (mildly suspicious): 3 points → FNA if ≥ 2.5 cm, follow-up if ≥ 1.5 cm",
    "TR4 (moderately suspicious): 4–6 points → FNA if ≥ 1.5 cm, follow-up if ≥ 1.0 cm",
    "TR5 (highly suspicious): ≥ 7 points → FNA if ≥ 1.0 cm, follow-up if ≥ 0.5 cm",
    "",
    `${l.piradsTitle}:`,
    "PI-RADS 1: very low (< 5%)",
    "PI-RADS 2: low (5–15%)",
    "PI-RADS 3: intermediate (15–30%)",
    "PI-RADS 4: high (30–70%)",
    "PI-RADS 5: very high (> 70%)",
    "",
    `${l.bosniak}:`,
    "I: simple cyst (< 1% malignancy) → no follow-up",
    "II: minimally complex (< 5%) → no follow-up",
    "IIF: mildly complex (5–10%) → follow-up",
    "III: indeterminate (40–60%) → surgery or active surveillance",
    "IV: clearly malignant (> 80%) → surgery",
    "",
    "BI-RADS v2025 CATEGORIES:",
    "0a: incomplete — needs additional conventional imaging",
    "0b: incomplete — needs prior exams for comparison",
    "1: negative (0% malignancy)",
    "2: benign (0%)",
    "3: probably benign (0–2%) → short-interval follow-up",
    "4a: low suspicion (2–10%)",
    "4b: moderate suspicion (10–50%)",
    "4c: high suspicion (50–95%)",
    "5: highly suggestive of malignancy (> 95%) → biopsy",
    "6: known biopsy-proven malignancy",
    "",
    "LI-RADS (ACR) CATEGORIES:",
    "LR-1: definitely benign",
    "LR-2: probably benign",
    "LR-3: intermediate probability",
    "LR-4: probably HCC",
    "LR-5: definitely HCC (APHE + washout/capsule + threshold growth)",
    "LR-M: probably malignant, not HCC-specific",
    "LR-TIV: tumor in vein",
    "",
    "LUNG-RADS v1.1 CATEGORIES:",
    "1: negative — no lung nodules (< 1% malignancy)",
    "2: benign appearance — solid < 6 mm, part-solid < 6 mm, GGN < 30 mm (< 1%)",
    "3: probably benign — solid 6–8 mm, part-solid ≥ 6 mm total < 6 mm solid, new GGN ≥ 30 mm (1–2%)",
    "4A: suspicious — solid 8–15 mm, growing < 8 mm, part-solid ≥ 6 mm solid (5–15%)",
    "4B: suspicious — solid ≥ 15 mm, growing ≥ 8 mm (> 15%)",
    "4X: suspicious with additional features (> 15%)",
    "",
    "O-RADS MRI CATEGORIES:",
    "1: normal ovary (< 0.5% malignancy)",
    "2: almost certainly benign (< 1%)",
    "3: low risk (1–5%)",
    "4: intermediate risk (10–50%)",
    "5: high risk (> 50%)",
    "",
    "CAROTID STENOSIS (NASCET):",
    "Normal: PSV < 125, EDV < 40, ICA/CCA ratio < 2.0",
    "< 50%: PSV < 125, EDV < 40, ICA/CCA < 2.0",
    "50–69%: PSV 125–230, EDV 40–100, ICA/CCA 2.0–4.0",
    "≥ 70%: PSV > 230, EDV > 100, ICA/CCA > 4.0",
    "",
    "ASPECTS (Alberta Stroke Program Early CT Score):",
    "Regions: C (caudate), L (lentiform), IC (internal capsule), I (insular ribbon), M1–M6 (MCA cortex)",
    "Score 10 = normal, 0 = complete MCA territory infarct",
    "≤ 5: large infarct core (poor outcome with thrombolysis)",
    "> 7: small infarct core (favorable for intervention)",
    "",
    "SPINAL CANAL STENOSIS (Schizas et al., Spine 2010):",
    "Grade A (A1–A4): no stenosis — CSF clearly visible around rootlets",
    "Grade B: moderate — rootlets occupy entire canal but can be individualized",
    "Grade C: severe — rootlets not individually visible, some CSF present",
    "Grade D: extreme — no CSF signal, complete compression",
    "",
    "FORAMINAL STENOSIS (Lee/Wildermuth):",
    "Grade 0: normal — perineural fat surrounds root",
    "Grade 1: mild — perineural fat obliteration, root size preserved",
    "Grade 2: moderate — root deformity/flattening, fat partially effaced",
    "Grade 3: severe — root collapsed/not visible",
    "",
    "PEDIATRIC HIP ULTRASOUND — GRAF CLASSIFICATION (DDH):",
    "Type Ia: α ≥ 60° — mature, normal",
    "Type Ib: α ≥ 60° — mature with blunt bony rim",
    "Type IIa: α 50–59° — physiologic immaturity (< 3 months)",
    "Type IIb: α 50–59° — ossification delay (> 3 months)",
    "Type IIc: α 43–49° — critical, cartilaginous roof deficient",
    "Type D: α 43–49° — decentering, unstable",
    "Type IIIa/b: α < 43° — dislocated, cartilaginous roof displaced",
    "Type IV: α < 43° — dislocated, labrum interposed",
  ].join("\n");
}
