import { DEFAULT_RECOMMENDATIONS } from "./recommendation-defaults";

type Lang = "es" | "en" | "pt";

export function buildKnowledgeBase(lang: Lang): string {
  const recEntries = DEFAULT_RECOMMENDATIONS.map((r) => {
    const title = r.title[lang] || r.title.en || Object.values(r.title)[0];
    const text = r.text[lang] || r.text.en || Object.values(r.text)[0];
    return `[${r.source}] (${r.category} / ${r.modality}) ${title}: ${text}`;
  });

  const clinicalData = buildClinicalReferenceData(lang);

  return [
    "=== RADIOLOGY CALCULATOR & QUICK REFERENCE DATA ===",
    clinicalData,
    "",
    "=== CLINICAL RECOMMENDATIONS (evidence-based management) ===",
    recEntries.join("\n"),
  ].join("\n");
}

export function buildClinicalReferenceData(lang: Lang): string {
  const L = {
    es: {
      aortaTitle: "DIÁMETROS AÓRTICOS NORMALES",
      segment: "Segmento", male: "Hombre", female: "Mujer", aneurysm: "Umbral aneurisma",
      washoutTitle: "LAVADO ADRENAL (CT)",
      apw: "APW (lavado absoluto)", rpw: "RPW (lavado relativo)",
      adenoma: "Adenoma", indeterminate: "Indeterminado", suspicious: "Sospechoso",
      tiradsTitle: "ACR TI-RADS — PUNTUACIÓN POR CATEGORÍA",
      bosniak: "CLASIFICACIÓN BOSNIAK 2019",
      piradsTitle: "PI-RADS v2.1 — PROBABILIDAD DE CÁNCER CLÍNICAMENTE SIGNIFICATIVO",
      fleischnerTitle: "CRITERIOS FLEISCHNER 2017 — SEGUIMIENTO DE NÓDULOS PULMONARES",
      lowRisk: "bajo riesgo", highRisk: "alto riesgo",
      noFollowUp: "No requiere seguimiento", optional12: "TC opcional a 12 meses",
      fu612: "TC en 6-12 meses", fu1824: "considerar TC 18-24 meses",
      fu36: "TC en 3-6 meses", fu1218: "TC 12-18 meses después",
      pet: "considerar PET/TC o biopsia",
      subsolid: "Nódulos subsólidos (vidrio deslustrado / parcialmente sólidos)",
      ggn: "Vidrio deslustrado puro (GGN)", partSolid: "Parcialmente sólido",
      solidStable: "SÓLIDO estable ≥ 3 años → no más seguimiento necesario",
      subsolidStable: "SUBSÓLIDO / VIDRIO DESLUSTRADO: seguimiento recomendado durante mínimo 5 años por riesgo de crecimiento lento",
    },
    en: {
      aortaTitle: "NORMAL AORTIC DIAMETERS",
      segment: "Segment", male: "Male", female: "Female", aneurysm: "Aneurysm threshold",
      washoutTitle: "ADRENAL WASHOUT (CT)",
      apw: "APW (absolute percentage washout)", rpw: "RPW (relative percentage washout)",
      adenoma: "Adenoma", indeterminate: "Indeterminate", suspicious: "Suspicious",
      tiradsTitle: "ACR TI-RADS — SCORE BY CATEGORY",
      bosniak: "BOSNIAK 2019 CLASSIFICATION",
      piradsTitle: "PI-RADS v2.1 — PROBABILITY OF CLINICALLY SIGNIFICANT CANCER",
      fleischnerTitle: "FLEISCHNER 2017 CRITERIA — PULMONARY NODULE FOLLOW-UP",
      lowRisk: "low risk", highRisk: "high risk",
      noFollowUp: "No routine follow-up", optional12: "Optional CT at 12 months",
      fu612: "CT at 6-12 months", fu1824: "consider CT at 18-24 months",
      fu36: "CT at 3-6 months", fu1218: "CT at 12-18 months after",
      pet: "consider PET/CT or biopsy",
      subsolid: "Subsolid nodules (ground-glass / part-solid)",
      ggn: "Pure ground-glass nodule (GGN)", partSolid: "Part-solid",
      solidStable: "SOLID nodule stable ≥ 3 years → no further follow-up needed",
      subsolidStable: "SUBSOLID / GROUND-GLASS: follow-up recommended for minimum 5 years due to risk of slow growth",
    },
    pt: {
      aortaTitle: "DIÂMETROS AÓRTICOS NORMAIS",
      segment: "Segmento", male: "Homem", female: "Mulher", aneurysm: "Limiar de aneurisma",
      washoutTitle: "LAVAGEM ADRENAL (TC)",
      apw: "APW (lavagem absoluta)", rpw: "RPW (lavagem relativa)",
      adenoma: "Adenoma", indeterminate: "Indeterminado", suspicious: "Suspeito",
      tiradsTitle: "ACR TI-RADS — PONTUAÇÃO POR CATEGORIA",
      bosniak: "CLASSIFICAÇÃO BOSNIAK 2019",
      piradsTitle: "PI-RADS v2.1 — PROBABILIDADE DE CÂNCER CLINICAMENTE SIGNIFICATIVO",
      fleischnerTitle: "CRITÉRIOS FLEISCHNER 2017 — SEGUIMENTO DE NÓDULOS PULMONARES",
      lowRisk: "baixo risco", highRisk: "alto risco",
      noFollowUp: "Sem seguimento de rotina", optional12: "TC opcional em 12 meses",
      fu612: "TC em 6-12 meses", fu1824: "considerar TC em 18-24 meses",
      fu36: "TC em 3-6 meses", fu1218: "TC em 12-18 meses depois",
      pet: "considerar PET/TC ou biópsia",
      subsolid: "Nódulos subsólidos (vidro fosco / parcialmente sólidos)",
      ggn: "Vidro fosco puro (GGN)", partSolid: "Parcialmente sólido",
      solidStable: "SÓLIDO estável ≥ 3 anos → sem mais seguimento necessário",
      subsolidStable: "SUBSÓLIDO / VIDRO FOSCO: seguimento recomendado durante mínimo 5 anos por risco de crescimento lento",
    },
  };
  const l = L[lang] || L.en;

  return [
    "=== INDEX OF AVAILABLE TOPICS (search by name) ===",
    "Fleischner 2017 | BTS 2015 | Interstitial lung disease (ILD) | Lung-RADS v2022 | Lung-RADS follow-up & recategorization | Lung-RADS stable nodule | Lung-RADS growing nodule | Lung-RADS GGN management | Lung-RADS part-solid | Lung-RADS new nodule | Lung-RADS resolving nodule | Lung-RADS 4X | Perifissural nodule | LI-RADS v2018 | LI-RADS major features | BI-RADS v2025 | O-RADS MRI | TI-RADS | PI-RADS v2.1 | CAD-RADS 2.0 | Bosniak 2019 | Adrenal washout | Aortic diameters | Aortic dissection Stanford/DeBakey | Arch variants | NASCET carotid stenosis | Peripheral artery disease | Resistive index (renal) | Renal transplant US | Thyroid incidentals | Thyroid volume | Prostate volume | Adrenal incidentals | Liver incidentals | Renal cyst | Ovarian incidentals | Gallbladder polyps | Diverticulitis | Breast density | Breast screening | Breast US lexicon | Mediastinal lymph nodes | ASPECTS | Fazekas white matter | Spinal canal stenosis | Foraminal stenosis | Disc nomenclature | Cerebral vascular territories | Complex infarcts | Fisher SAH | Brain tumors WHO | CT perfusion | Demyelinating diseases | Neurodegenerative diseases | Neck anatomy | Cardiac MRI | MRI shoulder | MRI knee | MRI ankle | MRI thigh & leg | Rotator cuff | On-track/Off-track glenoid | Bone tumors | Vertebral fractures | Whole aorta CTA | Pediatric CXR | Pediatric hydronephrosis | Pediatric tumors | Cryptorchidism | Transfontanellar US | Hip US DDH | Testicular torsion | Pancreatic cysts | Renal volume TKV (Mayo classification) | Lung TNM staging | Larynx TNM staging | Nodule doubling time | T1/T2 mapping & ECV | Canadian CT Head Rule | Wells PE | Wells DVT | Alvarado | Tokyo cholecystitis | Canadian C-Spine / NEXUS | PECARN | SF Syncope Rule CHESS | HEART Score",
    "=== END INDEX ===",
    "",
    `${l.fleischnerTitle}:`,
    `SOLID NODULES:`,
    `< 6 mm, ${l.lowRisk}: ${l.noFollowUp}`,
    `< 6 mm, ${l.highRisk}: ${l.optional12}`,
    `6-8 mm, ${l.lowRisk}: ${l.fu612}; ${l.fu1824}`,
    `6-8 mm, ${l.highRisk}: ${l.fu612}; ${l.fu1824}`,
    `> 8 mm: ${l.fu36}; ${l.pet}`,
    `${l.subsolid}:`,
    `${l.ggn} < 6 mm: ${l.noFollowUp}`,
    `${l.ggn} ≥ 6 mm: ${l.fu612}; then every 2 years for 5 years`,
    `${l.partSolid} < 6 mm: ${l.noFollowUp}`,
    `${l.partSolid} ≥ 6 mm: ${l.fu36}; if solid component ≥ 6mm → ${l.pet}`,
    `STABILITY RULES (IMPORTANT — different for solid vs subsolid):`,
    `${l.solidStable}`,
    `${l.subsolidStable}`,
    `Multiple nodules: follow-up based on the most suspicious nodule`,
    "",
    `${l.aortaTitle}:`,
    `${l.segment} | ${l.male} (cm) | ${l.female} (cm) | ${l.aneurysm}`,
    "Aortic root (sinuses of Valsalva) | 3.4–3.7 | 3.0–3.3 | > 4.5 cm",
    "Sinotubular junction | 2.9–3.2 | 2.6–2.9 | —",
    "Mid-ascending aorta | 3.0–3.5 | 2.7–3.2 | > 4.5 cm",
    "Aortic arch | 2.5–3.0 | 2.3–2.7 | > 4.0 cm",
    "Aortic isthmus | 2.0–2.5 | 1.8–2.3 | —",
    "Mid-descending aorta | 2.3–2.8 | 2.1–2.5 | > 4.0 cm",
    "Suprarenal aorta | 2.0–2.5 | 1.8–2.2 | > 3.5 cm",
    "Infrarenal aorta | 1.7–2.1 | 1.5–1.8 | > 3.0 cm",
    "",
    "AORTIC ANEURYSM SURGICAL THRESHOLDS (ACC/AHA 2022):",
    "Aortic root > 5.5 cm (Marfan > 5.0 cm; Loeys-Dietz 4.0–4.5 cm)",
    "Ascending aorta > 5.5 cm (BAV > 5.0–5.5 cm)",
    "Aortic arch > 5.5 cm",
    "Descending thoracic > 5.5–6.0 cm (TEVAR > 5.5 cm)",
    "Infrarenal AAA > 5.5 cm (M) / > 5.0 cm (F) (EVAR > 5.5 cm)",
    "",
    "AORTIC ANEURYSM FOLLOW-UP INTERVALS:",
    "< 4.0 cm (AAA): US every 2-3 years",
    "4.0–4.9 cm: US or CT every 12 months",
    "5.0–5.4 cm: US or CT every 6 months",
    "Rapid growth (> 0.5 cm/6 months or > 1 cm/year): surgical evaluation",
    "",
    "AORTIC DISSECTION (Stanford / DeBakey):",
    "Stanford A: involves ascending aorta ± distal extension → emergency surgery",
    "Stanford B: only descending aorta (distal to left subclavian) → medical management; TEVAR if complicated",
    "DeBakey I: ascending to at least arch (may extend to descending)",
    "DeBakey II: limited to ascending aorta",
    "DeBakey III: limited to descending aorta (IIIa: to diaphragm; IIIb: below)",
    "",
    "AORTIC ARCH VARIANTS:",
    "Normal arch (3 vessels) ~70%: BT, LCCA, LSA separate from arch",
    "Bovine arch ~20–27%: common origin BT+LCCA or LCCA from BT",
    "Aberrant right subclavian ~1–2%: RSA distal to LSA, retroesophageal (Kommerell diverticulum)",
    "Left vertebral from arch ~5%: LVA arises directly from arch between LCCA and LSA",
    "Right-sided arch ~0.1%: arch crosses to right, look for vascular ring",
    "",
    `${l.washoutTitle}:`,
    `${l.apw}: ≥ 60% = ${l.adenoma} | 40–59% = ${l.indeterminate} | < 40% = ${l.suspicious}`,
    `${l.rpw}: ≥ 40% = ${l.adenoma} | < 40% = ${l.suspicious}`,
    "Unenhanced density ≤ 10 HU = lipid-rich adenoma (no washout needed)",
    "Formula: APW = ((enhanced − delayed) / (enhanced − unenhanced)) × 100",
    "Formula: RPW = ((enhanced − delayed) / enhanced) × 100",
    "",
    `${l.tiradsTitle}:`,
    "TR1 (benign): 0 points → no FNA",
    "TR2 (not suspicious): 2 points → no FNA",
    "TR3 (mildly suspicious): 3 points → FNA if ≥ 2.5 cm, follow-up if ≥ 1.5 cm",
    "TR4 (moderately suspicious): 4–6 points → FNA if ≥ 1.5 cm, follow-up if ≥ 1.0 cm",
    "TR5 (highly suspicious): ≥ 7 points → FNA if ≥ 1.0 cm, follow-up if ≥ 0.5 cm",
    "",
    "THYROID VOLUME CALCULATION:",
    "Formula: Volume (mL) = length × width × AP × 0.524 (per lobe)",
    "Normal total volume: 6–15 mL (women < 18 mL, men < 25 mL)",
    "",
    `${l.piradsTitle}:`,
    "PI-RADS 1: very low (< 5%)",
    "PI-RADS 2: low (5–15%)",
    "PI-RADS 3: intermediate (15–30%)",
    "PI-RADS 4: high (30–70%)",
    "PI-RADS 5: very high (> 70%)",
    "",
    "PROSTATE VOLUME & PSA DENSITY:",
    "Formula: Volume (mL) = length × width × AP × 0.524",
    "PSA density = PSA / volume",
    "PSA density < 0.10: low risk",
    "PSA density 0.10–0.15: intermediate",
    "PSA density > 0.15: elevated risk (consider biopsy)",
    "",
    `${l.bosniak}:`,
    "I: simple cyst (< 1% malignancy) → no follow-up",
    "II: minimally complex (< 5%) → no follow-up",
    "IIF: mildly complex (5–10%) → follow-up",
    "III: indeterminate (40–60%) → surgery or active surveillance",
    "IV: clearly malignant (> 80%) → surgery",
    "",
    "BI-RADS v2025 CATEGORIES:",
    "0a: incomplete — needs additional conventional imaging",
    "0b: incomplete — needs prior exams for comparison",
    "1: negative (0% malignancy)",
    "2: benign (0%)",
    "3: probably benign (0–2%) → short-interval follow-up 6 months",
    "4a: low suspicion (2–10%) → biopsy",
    "4b: moderate suspicion (10–50%) → biopsy",
    "4c: high suspicion (50–95%) → biopsy",
    "5: highly suggestive of malignancy (> 95%) → biopsy",
    "6: known biopsy-proven malignancy",
    "",
    "LI-RADS (ACR LI-RADS v2018) CATEGORIES:",
    "LR-NC: non-categorizable (inadequate technical quality)",
    "LR-1: definitely benign",
    "LR-2: probably benign",
    "LR-3: intermediate probability → return in 3-6 months",
    "LR-4: probably HCC → multidisciplinary discussion",
    "LR-5: definitely HCC (APHE + washout/capsule + threshold growth) → treat as HCC",
    "LR-M: probably malignant, not HCC-specific → biopsy or multidisciplinary",
    "LR-TIV: tumor in vein → treat as HCC with vascular invasion",
    "",
    "LI-RADS MAJOR FEATURES FOR HCC DIAGNOSIS:",
    "APHE (non-peripheral arterial phase hyperenhancement): enhancement greater than surrounding liver, non-peripheral/non-rim",
    "Washout: hypoenhancement in portal venous or delayed phase relative to liver",
    "Enhancing capsule: smooth peripheral rim of enhancement in portal venous or delayed phase",
    "Threshold growth: increase ≥ 50% in ≤ 6 months",
    "Size ≥ 10 mm: required for LR-5; < 10 mm cannot be LR-5",
    "",
    "LI-RADS DIAGNOSTIC TABLE (observation with APHE):",
    "< 10 mm + no additional features = LR-3 | +1 feature (washout OR capsule OR growth) = LR-4 | +≥2 features = LR-4",
    "10–19 mm + no additional features = LR-3 | +1 feature = LR-4 | +≥2 features = LR-5",
    "≥ 20 mm + no additional features = LR-4 | +1 feature = LR-5 | +≥2 features = LR-5",
    "",
    "LUNG-RADS v2022 (ACR Lung Cancer Screening) — also known as: Lung RADS, LungRADS:",
    "Lung-RADS 0: incomplete — prior not available → compare with prior",
    "Lung-RADS 1: negative — no nodules (< 1%) → annual LDCT",
    "Lung-RADS 2: benign — solid < 6 mm, part-solid < 6 mm, GGN < 30 mm (< 1%) → annual LDCT",
    "Lung-RADS 3: probably benign — solid 6–8 mm, part-solid ≥ 6 mm with solid < 6 mm, GGN ≥ 30 mm (1–2%) → 6-month LDCT",
    "Lung-RADS 4A: suspicious — solid 8–15 mm, new solid 4–8 mm, part-solid solid 6–8 mm (5–15%) → 3-month LDCT or PET/CT",
    "Lung-RADS 4B: suspicious — solid ≥ 15 mm, new/growing ≥ 8 mm, part-solid solid ≥ 8 mm (> 15%) → CT ± PET/CT, tissue sampling",
    "Lung-RADS 4X: category 3/4 with suspicious features (> 15%) → tissue sampling",
    "Lung-RADS S: clinically significant incidental finding → as indicated",
    "",
    "LUNG-RADS v2022 — FOLLOW-UP MANAGEMENT & RECATEGORIZATION RULES:",
    "",
    "STABLE SOLID NODULE on subsequent screening:",
    "Solid nodule 6–8 mm (category 3) stable at 6-month LDCT → downgrade to category 2 → resume annual LDCT",
    "Solid nodule 8–15 mm (category 4A) stable at 3-month LDCT → remains 4A, repeat LDCT at 6 months from baseline; if still stable at 6 months → downgrade to category 3 → 6-month follow-up; if stable at 12 months from baseline → downgrade to category 2 → annual LDCT",
    "Solid nodule ≥ 15 mm (category 4B) stable after biopsy/PET showing benign → downgrade to category 2 or 3 depending on clinical context",
    "",
    "STABLE GROUND-GLASS NODULE (GGN) on subsequent screening:",
    "GGN < 30 mm (category 2) stable → continue annual LDCT; stable GGN at category 2 does NOT need escalation regardless of duration",
    "GGN ≥ 30 mm (category 3) stable at 6-month LDCT → continue annual LDCT as category 2; a pure GGN that remains stable and purely ground-glass for ≥ 1 year can be considered benign behavior → category 2 → annual LDCT",
    "GGN that has been stable for multiple years → very low malignancy risk, continue annual screening; long-term stability (≥ 2–3 years) in pure GGN supports benign etiology (focal fibrosis, atypical adenomatous hyperplasia)",
    "Important: stable pure GGN does NOT require biopsy; stability is reassuring",
    "",
    "STABLE PART-SOLID NODULE on subsequent screening:",
    "Part-solid ≥ 6 mm with solid component < 6 mm (category 3) stable at 6 months → continue annual LDCT as category 2",
    "Part-solid with solid component 6–8 mm (category 4A) stable at 3 months → repeat at 6 months; if stable at 6 months → category 3; if stable at 12 months → category 2 → annual",
    "Part-solid with solid component ≥ 8 mm (category 4B) → requires tissue sampling; if biopsy benign and stable → downgrade per clinical judgment",
    "Part-solid nodule: the SOLID COMPONENT size drives the category, not the total nodule size",
    "",
    "GROWING NODULE — RECLASSIFICATION RULES:",
    "Any nodule that grows (≥ 1.5 mm increase in mean diameter) on follow-up → upgrade category",
    "Growing solid < 8 mm → reclassify as 4A (new solid 4–8 mm rule)",
    "Growing solid ≥ 8 mm → reclassify as 4B",
    "Growing GGN that remains pure ground-glass → reclassify as 4A if newly ≥ 30 mm; growth alone in pure GGN is less concerning than development of solid component",
    "GGN that develops a NEW solid component → reclassify as part-solid → apply part-solid rules (4A if solid < 6 mm new, 4A/4B based on solid component size)",
    "Any growing nodule with suspicious morphology (spiculation, irregular margins, lymphadenopathy) → consider 4X regardless of size",
    "",
    "NEW NODULE on subsequent screening (not present on prior):",
    "New solid < 4 mm → category 2 → annual LDCT",
    "New solid 4–8 mm → category 4A → 3-month LDCT",
    "New solid ≥ 8 mm → category 4B → CT ± PET/CT, tissue sampling",
    "New part-solid → apply part-solid rules based on solid component size",
    "New GGN < 30 mm → category 2 → annual; New GGN ≥ 30 mm → category 3 → 6-month LDCT",
    "",
    "RESOLVING NODULE:",
    "Nodule that decreases in size or resolves → likely inflammatory/infectious → downgrade; if completely resolved → category 1",
    "Partially resolved solid nodule → downgrade by one category; continue follow-up until stable or resolved",
    "GGN that resolves → confirms benign etiology (transient inflammation) → category 1 → resume annual",
    "",
    "CATEGORY 4X — SUSPICIOUS FEATURES (any category 3 or 4 can be upgraded to 4X):",
    "Suspicious features include: spiculated margins, growing, lymphadenopathy, direct invasion of adjacent structures, apical/scar-adjacent location with distortion",
    "4X modifier applied when clinical/imaging features suggest higher malignancy risk than size alone would indicate",
    "4X management: tissue sampling consideration regardless of size",
    "",
    "PERIFISSURAL NODULES (PFN) — special consideration:",
    "Solid triangular/lentiform nodule attached to fissure → likely intrapulmonary lymph node",
    "PFN < 10 mm → category 2 regardless of other size criteria → annual LDCT",
    "PFN ≥ 10 mm or atypical morphology → apply standard solid nodule rules",
    "",
    "LUNG-RADS GENERAL PRINCIPLES:",
    "Always use the HIGHEST applicable category when multiple nodules present",
    "Volumetric measurement preferred over linear when available; volume doubling time (VDT) < 400 days is suspicious",
    "Mean diameter = (long axis + short axis) / 2; growth = ≥ 1.5 mm increase in mean diameter",
    "Part-solid: category determined by SOLID COMPONENT size, not total size",
    "GGN (pure ground-glass): generally more indolent than solid; long-term stability is reassuring",
    "Screening interval resets when category changes",
    "",
    "O-RADS MRI 2022 (ACR Ovarian-Adnexal Reporting) — also known as: ORADS, O-RADS:",
    "O-RADS 1: normal ovary (< 0.5%) → routine care",
    "O-RADS 2: almost certainly benign — simple cyst, endometrioma without solid, dermoid (< 1%) → optional follow-up",
    "O-RADS 3: low risk — fibroma-like (T2 dark, low DWI), multilocular thin-walled, smooth wall + TIC type 1 (1–5%) → follow-up MRI 12 weeks",
    "O-RADS 4: intermediate risk — thick wall/septa ≥ 3mm, irregular wall, smooth + TIC type 2/3 (10–50%) → surgical evaluation",
    "O-RADS 5: high risk — irregular + high DWI + TIC type 3, peritoneal implants (> 50%) → gynecologic oncology",
    "",
    "CAROTID STENOSIS (NASCET) — DOPPLER US CRITERIA:",
    "Normal: PSV < 125 cm/s, EDV < 40 cm/s, ICA/CCA ratio < 2.0",
    "< 50% stenosis: PSV < 125, EDV < 40, ICA/CCA < 2.0",
    "50–69%: PSV 125–230, EDV 40–100, ICA/CCA 2.0–4.0",
    "≥ 70%: PSV > 230, EDV > 100, ICA/CCA > 4.0",
    "Near-occlusion (> 95%): variable low-velocity flow",
    "Occlusion: no flow detected",
    "",
    "PERIPHERAL ARTERY DISEASE (Fontaine / Rutherford):",
    "Fontaine I / Rutherford 0: asymptomatic",
    "Fontaine IIa / Rutherford 1: mild claudication",
    "Fontaine IIb / Rutherford 2-3: moderate-severe claudication",
    "Fontaine III / Rutherford 4: ischemic rest pain",
    "Fontaine IV / Rutherford 5: minor tissue loss",
    "Fontaine IV / Rutherford 6: major tissue loss / gangrene",
    "",
    "DVT/PE CLASSIFICATION:",
    "PE location: saddle (main PA bifurcation), central (main/lobar), lobar, segmental, subsegmental",
    "RV strain signs: RV/LV ratio > 1.0, septal bowing, IVC reflux",
    "",
    "ASPECTS (Alberta Stroke Program Early CT Score):",
    "Regions: C (caudate), L (lentiform), IC (internal capsule), I (insular ribbon), M1–M6 (MCA cortex)",
    "Score 10 = normal, 0 = complete MCA territory infarct",
    "≤ 5: large infarct core (poor outcome with thrombolysis)",
    "> 7: small infarct core (favorable for intervention)",
    "",
    "FAZEKAS SCALE (white matter disease):",
    "Grade 0: none or single punctate lesion",
    "Grade 1: multiple punctate lesions",
    "Grade 2: beginning confluent lesions (bridging)",
    "Grade 3: large confluent areas",
    "",
    "SPINAL CANAL STENOSIS (Schizas et al., Spine 2010):",
    "Grade A (A1–A4): no stenosis — CSF clearly visible around rootlets",
    "Grade B: moderate — rootlets occupy entire canal but can be individualized",
    "Grade C: severe — rootlets not individually visible, some CSF present",
    "Grade D: extreme — no CSF signal, complete compression",
    "",
    "FORAMINAL STENOSIS (Lee/Wildermuth):",
    "Grade 0: normal — perineural fat surrounds root",
    "Grade 1: mild — perineural fat obliteration, root size preserved",
    "Grade 2: moderate — root deformity/flattening, fat partially effaced",
    "Grade 3: severe — root collapsed/not visible",
    "",
    "DISC NOMENCLATURE (Fardon et al., Spine J 2014):",
    "Normal disc: no extension beyond vertebral body margins",
    "Bulge: circumferential symmetrical extension > 50% of disc circumference",
    "Protrusion: focal extension with base wider than apex in at least one plane",
    "Extrusion: extension with base narrower than apex, or migrated material",
    "Sequestration: extruded fragment with no continuity with parent disc",
    "",
    "PEDIATRIC HIP ULTRASOUND — GRAF CLASSIFICATION (DDH):",
    "Type Ia: α ≥ 60° — mature, normal",
    "Type Ib: α ≥ 60° — mature with blunt bony rim",
    "Type IIa: α 50–59° — physiologic immaturity (< 3 months), observe",
    "Type IIb: α 50–59° — ossification delay (> 3 months), treat",
    "Type IIc: α 43–49° — critical, cartilaginous roof deficient",
    "Type D: α 43–49° — decentering, unstable → Pavlik harness",
    "Type IIIa/b: α < 43° — dislocated, cartilaginous roof displaced → Pavlik harness or surgery",
    "Type IV: α < 43° — dislocated, labrum interposed → surgical reduction",
    "",
    "INTERSTITIAL LUNG DISEASE PATTERNS (ATS/ERS 2022):",
    "UIP (usual interstitial pneumonia):",
    "  Typical: subpleural basal predominant honeycombing ± traction bronchiectasis",
    "  Probable: subpleural basal predominant reticular pattern with traction bronchiectasis, no honeycombing",
    "  Indeterminate: subpleural but not basal predominant, or features of other patterns",
    "  Alternative diagnosis: features suggesting other diagnoses (mosaic attenuation, GGN predominance, centrilobular nodules)",
    "Hypersensitivity Pneumonitis (ATS/JRS 2020):",
    "  Typical: mid-lung predominance, mosaic attenuation/air trapping + fibrotic features",
    "  Compatible: fibrotic features without typical HP distribution",
    "  Indeterminate: features overlap with other fibrotic ILDs",
    "",
    "INCIDENTAL LIVER LESIONS (ACR Incidental Findings Committee 2017):",
    "Simple cyst: any size → no follow-up needed",
    "Typical hemangioma: < 3 cm → no follow-up | ≥ 3 cm → no follow-up if typical; MRI if atypical",
    "FNH-like (homogeneous enhancement, central scar): any size → no follow-up if typical; hepatobiliary MRI if uncertain",
    "Indeterminate hypodense lesion: < 1 cm → no follow-up if low risk | 1–1.5 cm → follow-up at 6 months if low risk, multiphase MRI if high risk | > 1.5 cm → multiphase MRI",
    "",
    "RENAL LESION CHARACTERIZATION (CT):",
    "Simple cyst criteria: water density (0–20 HU), no enhancement, thin wall, no septation",
    "Enhancement threshold: > 20 HU increase post-contrast = enhancing (suspicious)",
    "Homogeneously > 70 HU on unenhanced CT: hyperdense cyst (Bosniak II)",
    "",
    "RESISTIVE INDEX (Doppler) — RI = (PSV − EDV) / PSV:",
    "Renal artery: normal RI 0.50–0.70 | ≥0.70 suggests nephropathy/stenosis",
    "Hepatic artery: normal RI 0.55–0.80 | <0.50 (tardus-parvus) suggests proximal stenosis",
    "Splenic artery: normal RI 0.50–0.70 | comparable to renal in practice",
    "Internal carotid artery (ICA): normal RI 0.50–0.70 | low RI in low-resistance territory",
    "Ophthalmic artery: normal RI 0.65–0.75 | flow reversal suggests severe ICA stenosis",
    "Uterine artery (non-pregnant): normal RI 0.80–0.90 | decreases in pregnancy (0.50–0.60 in 3rd trimester)",
    "Umbilical artery (2nd-3rd trimester): normal RI 0.55–0.70 | absent/reversed diastole = fetal compromise",
    "Fetal MCA: normal RI 0.70–0.80 | ↓RI indicates fetal hemodynamic redistribution",
    "",
    "TRANSPLANT DOPPLER US — HEPATIC TRANSPLANT (ACR Appropriateness Criteria 2022; AIUM):",
    "Hepatic artery RI: normal 0.50–0.80 | >0.80 rejection/thrombosis; <0.50 tardus-parvus (stenosis)",
    "Hepatic artery PSV: normal 30–100 cm/s | <30 cm/s low flow; >200 cm/s stenosis",
    "Hepatic artery acceleration time (AT): normal < 0.08 s | ≥0.08 s (tardus-parvus) → hepatic artery stenosis",
    "Portal vein velocity: normal 20–40 cm/s | <20 cm/s stenosis/partial thrombosis",
    "Portal flow direction: normal hepatopetal | hepatofugal or absent = thrombosis/portal hypertension",
    "Hepatic vein waveform: normal triphasic/biphasic | monophasic = rejection/congestion",
    "",
    "TRANSPLANT DOPPLER US — RENAL TRANSPLANT (ACR Appropriateness Criteria 2022; AIUM):",
    "Transplant renal artery RI: normal 0.50–0.80 | >0.80 rejection/ATN; <0.50 proximal stenosis",
    "Renal artery PSV (anastomosis): normal < 200 cm/s | >200 cm/s or ratio >3:1 = stenosis",
    "Segmental artery RI: normal 0.50–0.70 | >0.80 or tardus-parvus → stenosis/rejection",
    "Renal vein flow: normal continuous antegrade | absent/reversed = venous thrombosis",
    "Acceleration time (AT): normal < 0.07 s | ≥0.07 s → renal artery stenosis",
    "",
    "CAD-RADS 2.0 — CORONARY ARTERY DISEASE REPORTING (Cury RC et al., Radiology 2022):",
    "CAD-RADS 0: 0% stenosis — no plaque or stenosis → no further workup",
    "CAD-RADS 1: 1–24% — minimal stenosis → preventive therapy",
    "CAD-RADS 2: 25–49% — mild stenosis → preventive therapy",
    "CAD-RADS 3: 50–69% — moderate stenosis → consider functional assessment",
    "CAD-RADS 4A: 70–99% — severe stenosis (1-2 vessels) → consider ICA / revascularization",
    "CAD-RADS 4B: LM ≥50% or 3-vessel ≥70% — severe (left main or 3-vessel) → consider ICA / revascularization",
    "CAD-RADS 5: 100% — total occlusion → consider ICA / revascularization",
    "Modifiers: /S (stent), /G (graft), /V (vulnerable plaque: positive remodeling, low attenuation, napkin-ring, spotty calcification), /I (non-diagnostic), /E (exception: anomaly, aneurysm, dissection)",
    "Plaque burden (new in 2.0): P1 (mild, 1-2 segments), P2 (mild, ≥3 segments), P3 (moderate, 25-49% per segment), P4 (extensive, ≥4 segments or ≥2 with P3)",
    "",
    "MYOCARDIAL ENHANCEMENT PATTERNS — CARDIAC MRI (Mahrholdt H et al., Eur Heart J 2005; Kim RJ et al., Circulation 1999):",
    "Late Gadolinium Enhancement (LGE) patterns:",
    "Ischemic (subendocardial → transmural): follows coronary territory → acute/chronic MI",
    "Mid-wall (mesocardial): interventricular septum → DCM, chronic myocarditis, sarcoidosis",
    "Epicardial: inferolateral wall → acute myocarditis, sarcoidosis",
    "Diffuse subendocardial: global circumferential → amyloidosis (+ difficulty nulling myocardium)",
    "RV insertion points: anterior & inferior RV-LV junctions → HCM, pulmonary hypertension",
    "Patchy/multifocal: variable location → sarcoidosis, myocarditis",
    "Mid-wall basal inferolateral: specific pattern → Anderson-Fabry disease",
    "",
    "AHA 17-SEGMENT MODEL — CORONARY TERRITORIES (Cerqueira MD et al., Circulation 2002):",
    "LAD territory: segments 1 (basal anterior), 2 (basal anteroseptal), 7 (mid anterior), 8 (mid anteroseptal), 13 (apical anterior), 14 (apical septal), 17 (apex)",
    "RCA territory: segments 3 (basal inferoseptal), 4 (basal inferior), 9 (mid inferoseptal), 10 (mid inferior), 15 (apical inferior)",
    "LCx territory: segments 5 (basal inferolateral), 6 (basal anterolateral), 11 (mid inferolateral), 12 (mid anterolateral), 16 (apical lateral)",
    "Basal ring: 6 segments (60° each) | Mid ring: 6 segments | Apical ring: 4 segments (90° each) | Apex: segment 17",
    "",
    "PANCREATIC CYSTIC LESION CHARACTERISTICS (ACR Incidental Findings 2017 / Fukuoka IAP 2017):",
    "Incidental cyst management by size:",
    "< 1.5 cm: no follow-up or MRI at 1 year if risk factors",
    "1.5–2.5 cm: MRI at 1 year, then every 2 years if stable (up to 5 years)",
    "> 2.5 cm: MRI at 6 months, then annually; refer to GI/surgery",
    "Worrisome features (solid component, Wirsung > 5mm, caliber change): surgical referral; consider EUS + FNA",
    "",
    "Cyst types — differential characteristics:",
    "SCN (serous cystadenoma): microcystic/honeycomb, central scar ± stellate calcification | any location (most common: head) | no duct communication | very low malignant potential (< 1%)",
    "MCN (mucinous cystic neoplasm): macrocystic, thick wall, peripheral calcification, no duct communication | body/tail | no duct communication | moderate malignant potential (15-20%)",
    "BD-IPMN (branch duct): cluster of cysts communicating with branch duct, normal Wirsung | head (uncinate) | yes (branch duct) | low-moderate (15-25%)",
    "MD-IPMN (main duct): Wirsung ≥ 5 mm segmental or diffuse ± mural nodules | any location | yes (main duct) | high (40-70%); surgery recommended",
    "SPN (solid pseudopapillary neoplasm): well-encapsulated solid-cystic mass, hemorrhagic component | body/tail | no | low (10-15%); young women",
    "",
    "Fukuoka / IAP 2017 criteria:",
    "Worrisome features: cyst ≥ 3 cm, thickened/enhancing wall, non-enhancing mural nodule, Wirsung 5-9 mm, abrupt caliber change, lymphadenopathy, elevated CA 19-9, growth ≥ 5 mm/2 years",
    "High-risk stigmata: enhancing mural nodule ≥ 5 mm, Wirsung ≥ 10 mm, obstructive jaundice with cystic lesion in pancreatic head",
    "",
    "TESTICULAR TORSION — ULTRASOUND DIAGNOSIS (ACR Appropriateness Criteria 2022 / Blaivas M et al., Acad Emerg Med 2001):",
    "Color Doppler absent/reduced flow: absence or marked reduction of flow in affected testis vs contralateral → cardinal finding; sensitivity 86-100%",
    "Whirlpool sign: twisted spermatic cord visible as spiral on ultrasound → pathognomonic of torsion",
    "Enlarged testis: diffuse enlargement, heterogeneous echogenicity (edema/hemorrhage) → edema from venous congestion",
    "Reactive hydrocele: fluid between layers of tunica vaginalis → frequent; nonspecific",
    "Scrotal wall thickening: increased cutaneous and subcutaneous thickness ipsilateral → reactive edema",
    "Enlarged epididymis: edematous and hypoechoic epididymis → associated venous congestion",
    "",
    "Testicular torsion timing & prognosis:",
    "< 6 hours: salvage rate > 90%",
    "6-12 hours: salvage rate ~50%",
    "> 24 hours: salvage rate < 10%",
    "SURGICAL EMERGENCY — do not delay for imaging if clinical suspicion is high",
    "",
    "BTS 2015 — INCIDENTAL PULMONARY NODULE GUIDELINES (Callister et al., Thorax 2015):",
    "SOLID NODULES:",
    "< 5 mm (< 80 mm³): no follow-up",
    "5-6 mm (80-300 mm³): CT at 1 year",
    "6-8 mm (300-500 mm³): CT at 3 and 12 months; consider PET if stable or growing",
    "> 8 mm (> 500 mm³): contrast-enhanced CT ± PET/CT ± biopsy",
    "SUBSOLID NODULES:",
    "GGN < 5 mm: no follow-up",
    "GGN ≥ 5 mm: CT at 3 months, then annual up to 4 years",
    "Part-solid (any size): CT at 3 months; if persistent, manage as suspicious",
    "",
    "INCIDENTAL THYROID NODULE (ACR 2015):",
    "Low sonographic risk: FNA if ≥ 2.5 cm; follow-up if 1.5-2.4 cm",
    "Moderate risk: FNA if ≥ 1.5 cm; follow-up if 1.0-1.4 cm",
    "High risk: FNA if ≥ 1.0 cm",
    "Suspicious features: microcalcifications, solid component, taller-than-wide, extrathyroidal extension",
    "Patient < 35 years: consider FNA at lower size thresholds",
    "",
    "MEDIASTINAL LYMPH NODE STATIONS (IASLC, Rusch et al., J Thorac Oncol 2009):",
    "Station 1: supraclavicular/low cervical — above clavicle, lower border of cricoid",
    "Station 2: upper paratracheal — between manubrium and trachea/BCT intersection",
    "Station 3a: prevascular — anterior to SVC and aorta | 3p: retrotracheal — posterior to trachea",
    "Station 4: lower paratracheal — 4R: between BCT and azygos; 4L: between BCT and carina",
    "Station 5: subaortic (AP window) — lateral to ligamentum arteriosum",
    "Station 6: para-aortic — anterior/lateral to ascending aorta",
    "Station 7: subcarinal — below carina, medial to both main bronchi",
    "Station 8: paraesophageal — adjacent to esophagus, below carina",
    "Station 9: pulmonary ligament — within inferior pulmonary ligament",
    "Station 10: hilar — adjacent to main bronchus and hilar vessels; 11-14: interlobar, lobar, segmental, subsegmental",
    "",
    "INCIDENTAL ADRENAL NODULES (ACR Incidental Findings Committee 2017):",
    "Homogeneous ≤ 10 HU, < 4 cm: benign adenoma — no follow-up",
    "Homogeneous > 10 HU, < 4 cm: CT washout or chemical shift MRI",
    "≥ 4 cm: consider biopsy/surgery; hormonal workup",
    "Heterogeneous, irregular, or growing: biopsy or resection; consider PET/CT",
    "",
    "GALLBLADDER POLYPS (Wiles et al., Radiology 2017 / ESG-ESGAR 2022):",
    "< 5 mm, no risk factors: no follow-up",
    "5-9 mm, no risk factors: US at 1 year, then every 2 years up to 5 years",
    "5-9 mm, with risk factors: US at 6 months, then annually up to 5 years",
    "≥ 10 mm: cholecystectomy",
    "Growth ≥ 2 mm on follow-up: surgical referral (cholecystectomy)",
    "Risk factors: age > 50, sessile polyp, PSC, Indian/Native American ethnicity, coexisting gallstones",
    "",
    "INCIDENTAL OVARIAN LESIONS (ACR 2020, Patel et al., JACR 2020):",
    "PREMENOPAUSAL:",
    "Simple cyst < 5 cm: physiologic — no follow-up",
    "Simple cyst 5-7 cm: US at 6-12 weeks",
    "Simple cyst > 7 cm: US or MRI",
    "Hemorrhagic cyst < 5 cm: US at 6-12 weeks",
    "Hemorrhagic cyst ≥ 5 cm: US or MRI at 6-12 weeks",
    "Complex lesion (any size): MRI or dedicated US; refer to gynecology",
    "POSTMENOPAUSAL:",
    "Simple cyst < 3 cm: no follow-up",
    "Simple cyst 3-7 cm: annual US",
    "Simple cyst > 7 cm: MRI or US + referral",
    "Complex lesion (any size): MRI or dedicated US; refer to gynecology",
    "",
    "ACUTE DIVERTICULITIS CLASSIFICATION (Hinchey/Modified):",
    "Stage 0: mild clinical — confined to colon wall",
    "Stage Ia: confined pericolic inflammation/phlegmon",
    "Stage Ib: confined pericolic abscess (< 4 cm)",
    "Stage II: pelvic, distant intra-abdominal, or retroperitoneal abscess",
    "Stage III: generalized purulent peritonitis",
    "Stage IV: generalized fecal peritonitis",
    "CT findings: uncomplicated = wall thickening + pericolic fat stranding | abscess = fluid collection with rim enhancement | perforation = free extraluminal air | fistula = tract to bladder/vagina | obstruction = stricture",
    "",
    "ACR BI-RADS BREAST DENSITY:",
    "A (almost entirely fatty): mammographic sensitivity ~85%",
    "B (scattered fibroglandular): sensitivity ~80%",
    "C (heterogeneously dense): sensitivity ~65%",
    "D (extremely dense): sensitivity ~50% — consider supplemental screening",
    "",
    "BREAST SCREENING BY RISK LEVEL (ACR):",
    "Average risk (no high-risk factors): annual mammography from age 40",
    "Intermediate risk (15-20% lifetime): annual mammography ± MRI per clinical judgment",
    "High risk (≥ 20% lifetime, BRCA, chest radiation ages 10-30): annual mammography + annual MRI from age 25-30",
    "",
    "BI-RADS US LEXICON:",
    "Shape: benign = oval/round; suspicious = irregular",
    "Orientation: benign = parallel (wider than tall); suspicious = not parallel (taller than wide)",
    "Margins: benign = circumscribed; suspicious = spiculated/angular/microlobulated",
    "Echogenicity: benign = anechoic/hyperechoic; suspicious = complex hypoechoic",
    "Posterior features: benign = no shadowing/posterior enhancement; suspicious = posterior acoustic shadowing",
    "",
    "BREAST IMPLANT COMPLICATIONS (ACR):",
    "Intact implant: routine follow-up; MRI at 5-6 years post-placement and every 2-3 years",
    "Intracapsular rupture: linguine sign, keyhole sign; silicone within capsule → elective surgery",
    "Extracapsular rupture: silicone outside capsule, may migrate → surgical explantation recommended",
    "Capsular contracture: Baker I-IV; Baker III-IV → consider capsulectomy/replacement",
    "BIA-ALCL: late seroma > 1 year → aspirate for cytology with CD30; refer to oncology",
    "",
    "CEREBRAL VASCULAR TERRITORIES:",
    "ACA: medial frontal lobe, cingulate, anterior corpus callosum",
    "MCA superior division: lateral frontal cortex, anterior parietal, insula",
    "MCA inferior division: lateral temporal cortex, posterior parietal, angular gyrus",
    "MCA lenticulostriate perforators: basal ganglia (putamen, globus pallidus, caudate), internal capsule",
    "PCA: occipital lobe, medial inferior temporal, thalamus (perforators)",
    "Basilar perforators: central pons, midbrain",
    "PICA: posteroinferior cerebellum, dorsolateral medulla (Wallenberg)",
    "AICA: anteroinferior cerebellum, lateral pons, inner ear",
    "SCA: superior cerebellum, superior cerebellar peduncles",
    "",
    "CEREBRAL ANEURYSM — MANAGEMENT BY SIZE (AHA/ASA 2015 / ISUIA 2003):",
    "< 3 mm: generally observation if asymptomatic; follow-up in 1-3 years",
    "3-6 mm anterior: imaging follow-up; treat if risk factors (smoking, HTN, family history)",
    "3-6 mm posterior: consider treatment; higher rupture risk than anterior",
    "7-12 mm: treatment generally recommended (endovascular or surgical)",
    "13-24 mm: high rupture risk; treatment recommended",
    "≥ 25 mm (giant): very high risk; urgent treatment required",
    "",
    "MODIFIED FISHER SCALE (SAH vasospasm risk):",
    "Grade 0: no SAH or IVH — low vasospasm risk",
    "Grade 1: focal or diffuse thin SAH (< 1 mm) without IVH — low risk",
    "Grade 2: focal or diffuse thin SAH with IVH — moderate risk",
    "Grade 3: thick cisternal clot (≥ 1 mm) without IVH — high risk",
    "Grade 4: thick cisternal clot with IVH — very high risk",
    "",
    "BRAIN TUMORS — WHO 2021 CNS GRADES:",
    "Grade 1: meningioma (grade I), pilocytic astrocytoma, schwannoma",
    "Grade 2: diffuse astrocytoma, oligodendroglioma, atypical meningioma",
    "Grade 3: anaplastic astrocytoma, anaplastic oligodendroglioma, anaplastic meningioma",
    "Grade 4: glioblastoma, DIPG, medulloblastoma, atypical teratoid/rhabdoid tumor",
    "",
    "CT BRAIN PERFUSION (CTP):",
    "Parameters: CBF (cerebral blood flow), CBV (cerebral blood volume), MTT (mean transit time), TTP (time to peak, bilaterally symmetric), Tmax (max time residue function)",
    "Ischemic core: ↓↓CBF + ↓↓CBV → irreversible infarct",
    "Ischemic penumbra: ↓CBF + preserved CBV → at-risk tissue, potentially salvageable",
    "Benign oligemia: mildly ↓CBF + normal CBV → mild hypoperfusion, no infarct risk",
    "DAWN trial (6-24h): clinical-imaging mismatch: NIHSS ≥10 + core <21-51 mL by age",
    "DEFUSE trial (6-16h): perfusion mismatch: penumbra/core ≥1.8, core <70 mL, Tmax>6s vol <180 mL",
    "",
    "COMPLEX INFARCT SYNDROMES:",
    "Wallenberg (PICA/lat. medulla): ipsi Horner + facial hypoesthesia / contra thermoalgesia",
    "Dejerine (medial medulla): ipsi tongue deviation + contra hemiparesis + contra proprioceptive loss",
    "Weber (ventral midbrain): ipsi CN III palsy + contra hemiparesis",
    "Claude (dorsal midbrain): ipsi CN III palsy + contra ataxia/tremor (no hemiparesis)",
    "Benedikt (midbrain tegmentum): ipsi CN III palsy + contra involuntary movements ± hemiparesis",
    "Millard-Gubler (ventral pons): ipsi CN VI and VII palsy + contra hemiparesis",
    "Foville (dorsal pons): ipsi conjugate gaze palsy + ipsi facial palsy + contra hemiparesis",
    "Locked-in (bilateral ventral pons): quadriplegia + anarthria; only vertical eye movements preserved",
    "Artery of Percheron: bilateral paramedian thalamic DWI ± V-sign midbrain FLAIR → decreased consciousness + vertical gaze palsy",
    "Top-of-basilar: bilateral thalami/midbrain/occipital/superior cerebellum DWI → coma + visual deficits + ophthalmoplegia",
    "Cortical watershed: parasagittal ACA/MCA or temporo-occipital MCA/PCA → systemic hypotension / carotid stenosis",
    "Deep watershed: corona radiata chain parallel to ventricle → microembolism + carotid stenosis",
    "Olivary hypertrophy: T2 hyperintense enlarged inferior olive (Guillain-Mollaret triangle) → appears ~1 month post-insult",
    "Wallerian degeneration: T2 hyperintense ipsilateral cerebral peduncle/pons → weeks-months post infarct",
    "",
    "DEMYELINATING DISEASES:",
    "MS: ovoid periventricular plaques, Dawson fingers, central vein sign, open ring enhancement; DIS: ≥1 T2 in ≥2 of 5 regions (periventricular, juxtacortical, infratentorial, spinal, optic nerve)",
    "McDonald 2024: DIT via simultaneous enhancing+non-enhancing or CSF OCBs; CVS (≥5 lesions with central vein) 98% specificity; PRL (paramagnetic rim) ~100% specificity",
    "NMOSD (Devic): LETM ≥3 segments (central cord), area postrema lesion, AQP4-IgG+; LETM + area postrema = pathognomonic",
    "MOGAD: fluffy cortical lesions, conus H-sign, bilateral anterior optic neuritis with perineural enhancement",
    "ADEM: large bilateral poorly defined WM lesions, thalamic/BG involvement, simultaneous enhancement, monophasic post-infectious",
    "PML: asymmetric subcortical WM involving U-fibers, no mass effect, no enhancement, DWI at advancing edge; immunocompromised (HIV, natalizumab)",
    "Osmotic demyelination: T2 trident sign in central pons sparing periphery; rapid Na+ correction",
    "Marchiafava-Bignami: T2/FLAIR in central corpus callosum (sandwich sign); chronic alcoholism",
    "Baló concentric sclerosis: alternating concentric T2 rings (bullseye); aggressive MS variant",
    "SUSAC: central callosal snowball lesions; triad = encephalopathy + branch retinal artery occlusion + sensorineural hearing loss",
    "",
    "NEURODEGENERATIVE DISEASES:",
    "Alzheimer: medial temporal/hippocampal atrophy; Scheltens MTA ≥1 (<75y), ≥2 (≥75y); dilated temporal horns",
    "FTD behavioral: bilateral frontal + anterior temporal atrophy with posterior sparing",
    "FTD semantic: temporal pole knife-blade atrophy, usually left-predominant → loss of word meaning",
    "FTD nonfluent: left perisylvian (posterior frontoinsular) atrophy → agrammatic speech",
    "Lewy body: preserved hippocampi (unlike AD) + visual hallucinations + parkinsonism",
    "Parkinson: loss of swallow tail sign (nigrosome-1) on SWI 3T; Se ~100%, Sp ~95%",
    "MSA-C: hot cross bun sign in pons (T2) + cerebellar/peduncular atrophy; Sp 97%",
    "MSA-P: lateral putaminal T2 hyperintense rim + putaminal atrophy; poor L-dopa response",
    "PSP: hummingbird sign (sagittal midbrain atrophy); morning glory sign (axial); midbrain/pons ratio <0.15; early falls",
    "CBD: asymmetric frontoparietal atrophy contralateral to clinical side; alien limb",
    "Huntington: caudate atrophy (box-car ventricles); bilateral; CAG ≥36",
    "ALS: bilateral corticospinal tract T2 hyperintensity (PLIC, corona radiata); motor band sign on SWI",
    "CJD: cortical ribboning on DWI + caudate/putamen DWI restriction; bilateral pulvinar = vCJD (Sp 98%); rapid dementia",
    "Normal pressure hydrocephalus: Evans index >0.3, DESH pattern (dilated Sylvian + tight convexity), callosal angle <90°; triad = gait + dementia + incontinence",
    "",
    "NECK ANATOMY — SPACES & LYMPH NODE STATIONS:",
    "Pharyngeal mucosal: mucosa, Waldeyer ring, constrictors → SCC, lymphoma, abscess",
    "Parapharyngeal: fat, V3 branches → displaced by adjacent masses; lipoma, sarcoma",
    "Masticator: masseter, pterygoids, mandible, V3 → odontogenic abscess, perineural V3",
    "Parotid: parotid gland, VII, retromandibular vein → pleomorphic adenoma, Warthin, mucoepidermoid",
    "Carotid: ICA, IJV, CN IX-XII, sympathetic chain → paraganglioma, schwannoma, metastatic LN",
    "Retropharyngeal: Rouvière nodes, fat → retropharyngeal abscess, metastatic LN",
    "Prevertebral: muscles, vertebral body → spondylodiscitis, metastasis, chordoma",
    "Posterior cervical: fat, XI, level V nodes → lymphadenopathy, lipoma, lymphoma",
    "Lymph node levels: Ia (submental), Ib (submandibular), IIa/b (upper jugular), III (middle jugular), IV (lower jugular), Va/b (posterior triangle), VI (central), VII (superior mediastinum)",
    "Pharynx: nasopharynx (torus tubarius, Rosenmüller fossa), oropharynx (tonsils, tongue base), hypopharynx (pyriform sinuses)",
    "Larynx: supraglottis (epiglottis, false cords), glottis (true vocal cords), subglottis (below cords → inferior cricoid)",
    "",
    "MRI SHOULDER ANATOMY:",
    "Rotator cuff: supraspinatus (greater tuberosity sup. facet, coronal T2 FS), infraspinatus (middle facet, axial/coronal T2 FS), subscapularis (lesser tuberosity, axial T2 FS), teres minor (inferior facet, coronal/sagittal T2 FS)",
    "Labrum: anterior + IGHL/MGHL, posterior, superior (SLAP) + biceps; best = axial T1 FS with MR arthrography",
    "",
    "ROTATOR CUFF CLASSIFICATIONS:",
    "Partial tears (Ellman): Grade 1 (minimal fraying), Grade 2 (up to 50% thickness), Grade 3 (> 50% without full disruption)",
    "Full-thickness by size: small (< 1 cm), medium (1-3 cm), large (3-5 cm), massive (> 5 cm)",
    "Retraction (Patte): Stage 1 (stump proximal to insertion), Stage 2 (at humeral head), Stage 3 (at/medial to glenoid)",
    "Fatty infiltration (Goutallier): 0 (normal), 1 (minimal streaks), 2 (fat < muscle), 3 (fat = muscle), 4 (fat > muscle)",
    "",
    "MRI KNEE ANATOMY:",
    "Menisci: medial (C-shaped), lateral (O-shaped); low T1/T2 signal",
    "Meniscal signal grades: I (globular intrameniscal, no tear), II (linear intrameniscal, no tear), III (signal reaching articular surface = tear)",
    "Ligaments: ACL (sagittal T2 FS/coronal), PCL (sagittal T2), MCL (coronal T2 FS), LCL (coronal T2 FS)",
    "Cartilage: coronal/sagittal PD FS — Outerbridge grades I-IV",
    "",
    "MRI ANKLE ANATOMY:",
    "Tendons: Achilles (posterior, no synovial sheath), tibialis posterior (posteromedial), FDL (posteromedial), FHL (posterior between talar tubercles), peroneus longus/brevis (posterolateral), tibialis anterior (anteromedial)",
    "Ligaments: ATFL, CFL, PTFL (lateral), deltoid (medial); best: axial/coronal T2 FS",
    "Medial mnemonic (ant→post): Tom, Dick ANd Harry = Tib. post., FDL, Artery/Nerve, FHL",
    "",
    "MRI THIGH & LEG — AXIAL ANATOMY:",
    "Thigh anterior: quadriceps + sartorius → femoral n. (L2-L4)",
    "Thigh medial: adductors + gracilis + pectineus → obturator n. (L2-L4)",
    "Thigh posterior: semimembranosus, semitendinosus, biceps femoris → sciatic n. (L4-S3)",
    "Leg anterior: tibialis ant., EHL, EDL → deep peroneal n.",
    "Leg lateral: peroneus longus/brevis → superficial peroneal n.",
    "Leg deep posterior: tibialis post., FDL, FHL → tibial n.",
    "Leg superficial posterior: gastrocnemius, soleus, plantaris → tibial n.",
    "",
    "BONE TUMORS DIAGNOSTIC CHEAT SHEET:",
    "By age: 0-10y benign = simple bone cyst, eosinophilic granuloma; malignant = Ewing, neuroblastoma mets",
    "10-30y benign = osteochondroma, enchondroma, GCT, ABC; malignant = osteosarcoma, Ewing",
    "30-40y benign = enchondroma, GCT, vertebral hemangioma; malignant = chondrosarcoma, bone lymphoma",
    "> 40y benign = hemangioma, enchondroma; malignant = metastasis, myeloma, chondrosarcoma",
    "By location: epiphysis = chondroblastoma, GCT; metaphysis = osteochondroma, osteosarcoma; diaphysis = Ewing, fibrous dysplasia",
    "Matrix: chondroid (arcs/rings) = enchondroma/chondrosarcoma; osteoid (dense, cloud-like) = osteosarcoma; ground-glass = fibrous dysplasia",
    "Periosteal reaction: solid/thick = benign/slow; lamellated (onion-skin) = Ewing/osteomyelitis; sunburst = osteosarcoma/metastasis",
    "",
    "VERTEBRAL FRACTURES CLASSIFICATIONS:",
    "Genant: G0 (normal), G1 (mild, 20-25% height loss), G2 (moderate, 25-40%), G3 (severe, >40% / vertebra plana)",
    "AO Spine: A0 (minor, spinous/transverse), A1 (compression one endplate), A2 (split fracture), A3 (incomplete burst), A4 (complete burst both endplates)",
    "AO Spine B: B1 (Chance fracture), B2 (PLC disruption), B3 (anterior hyperextension through disc)",
    "AO Spine C: translation/rotation injury — any A or B + displacement in any plane",
    "",
    "WHOLE AORTA CTA — MEASUREMENT LANDMARKS:",
    "Root (sinuses of Valsalva): max sinus-to-sinus (double oblique)",
    "STJ: junction between sinuses and tubular ascending",
    "Mid-ascending: at PA bifurcation level",
    "Proximal arch: origin of brachiocephalic trunk",
    "Mid-arch: between left CCA and left subclavian",
    "Isthmus: distal to left subclavian origin",
    "Descending: at left atrium/carina level",
    "Suprarenal/infrarenal: above/below renal arteries",
    "Key findings checklist: root/ascending (diameters, ectasia, BAV, dissection) | arch (variants, great vessel stenosis, coarctation) | descending (atheroma, ulcer, IMH, endograft) | abdominal (celiac/SMA/renal stenosis) | iliac (aneurysm, stenosis) | wall (calcification, thrombus, thickening, aortitis)",
    "",
    "PEDIATRIC CHEST X-RAY:",
    "Normal thymus: sail sign, wave sign (< 2 years); absent in neonato = consider DiGeorge",
    "RDS (HMD): diffuse ground-glass, air bronchograms, low volume (preterm)",
    "TTN: cisural fluid, mild cardiomegaly, hyperinflation, resolves 24-48h (term, C-section)",
    "MAS: hyperinflation, patchy atelectasis, pneumothorax risk (post-term)",
    "Bronchiolitis (< 2 years, RSV): hyperinflation, peribronchial thickening, subsegmental atelectasis",
    "Round pneumonia (< 8 years): round opacity simulating mass, lower lobes",
    "Foreign body (1-3 years): unilateral air trapping on expiration, obstructive emphysema",
    "Cardiothoracic ratio: < 0.60 neonates, < 0.55 > 1 year",
    "",
    "PEDIATRIC HYDRONEPHROSIS:",
    "SFU grading: 1 (mild pelvis dilation), 2 (pelvis + some calices), 3 (pelvis + all calices, normal parenchyma), 4 (severe + parenchymal thinning)",
    "Renal pelvis APD prenatal: 2nd trimester normal < 4 mm, mild 4-7, moderate 7-10, severe > 10 mm",
    "3rd trimester normal < 7 mm, mild 7-10, moderate 10-15, severe > 15 mm",
    "Neonatal/postnatal normal < 10 mm, mild 10-15, moderate 15-20, severe > 20 mm",
    "UTD classification: P1 (low risk, no caliceal dilation), P2 (intermediate, caliceal dilation), P3 (high risk, abnormal parenchyma)",
    "",
    "PEDIATRIC TUMORS BY AGE:",
    "< 1 year: neuroblastoma (suprarenal, crosses midline, calcifications 90%, encases vessels), sacrococcygeal teratoma (mixed solid-cystic)",
    "1-5 years: Wilms (intrarenal, pseudocapsule, renal vein/IVC thrombus), hepatoblastoma (solid heterogeneous, elevated AFP), rhabdomyosarcoma (head/neck/GU, invasive)",
    "5-10 years: lymphoma (anterior mediastinal mass, sandwich pattern), posterior fossa tumors (medulloblastoma = vermis, ependimoma = exits 4V foramina)",
    "> 10 years: osteosarcoma (metaphysis, sunburst, Codman triangle), Ewing (diaphysis, onion-skin periosteal), germ cell tumors (mediastinum/gonads/pineal)",
    "Key DDx: neuroblastoma vs Wilms: NB crosses midline + encases vessels; Wilms displaces vessels + pseudocapsule",
    "",
    "CRYPTORCHIDISM — ULTRASOUND (AUA/EAU Guidelines):",
    "Canalicular (72%): testis between internal and external inguinal ring",
    "Inguinal superficial (20%): superficial to external ring, ectopic",
    "Abdominal (8%): not visible on US; requires MRI or laparoscopy",
    "Prescrotal: upper scrotum, retractile testis",
    "Measurement: volume = L × W × AP × 0.52; atrophy if < 50% of contralateral",
    "Malignancy risk: undescended testis = 5-10× risk of testicular tumor; seminoma most common",
    "",
    "TRANSFONTANELLAR US — NEONATAL BRAIN (Papile et al., J Pediatr 1978):",
    "Germinal matrix hemorrhage (Papile): Grade I (subependymal only), Grade II (IVH < 50% ventricle, no dilation), Grade III (IVH > 50% + ventricular dilation, hydrocephalus 50-80%), Grade IV (intraparenchymal hemorrhagic infarct, severe sequelae)",
    "Periventricular leukomalacia (de Vries): Grade I (transient periventricular echogenicity < 7 days), Grade II (persistent > 7 days, small frontoparietal cysts), Grade III (extensive cysts fronto-parieto-occipital), Grade IV (diffuse subcortical cysts + porencephaly)",
    "Reference measurements: ventricular index (Levene) < 13 mm at term; frontal horn width < 3 mm; ventricle/hemisphere ratio < 0.35; 3rd ventricle < 3 mm",
    "",
    "ON-TRACK / OFF-TRACK — GLENOID BONE LOSS ASSESSMENT (Di Giacomo et al., JBJS 2014; Yamamoto et al., AJSM 2007):",
    "Used for: anterior shoulder instability — determines if Hill-Sachs lesion will engage with glenoid defect during abduction/external rotation",
    "Glenoid Track = 0.83 × glenoid width − bone loss (mm)",
    "HSI = Hill-Sachs interval (width of Hill-Sachs lesion on axial, mm)",
    "If HSI > Glenoid Track → OFF-TRACK = engaging Hill-Sachs → consider Latarjet/bone graft",
    "If HSI ≤ Glenoid Track → ON-TRACK = non-engaging → Bankart repair may suffice",
    "",
    "RENAL VOLUME & TKV — POLYCYSTIC KIDNEY DISEASE (Irazabal MV et al., JASN 2015):",
    "Kidney volume formula (ellipsoid): V = (π/6) × L × W × D (in cm → result in mL)",
    "TKV = total kidney volume = right kidney volume + left kidney volume",
    "htTKV = height-adjusted TKV = TKV / height (in meters)",
    "Mayo Imaging Classification (htTKV-based, predicts progression rate):",
    "Class 1A: slow growth (~1.5%/year) | 1B: low growth (~3%/year) | 1C: moderate (~4.5%/year) | 1D: fast (~6%/year) | 1E: very fast (>6%/year)",
    "Boundary formula: htTKV ≤ 150 × e^(rate × age) for each class threshold",
    "Clinical use: Mayo class 1C–1E may benefit from tolvaptan therapy; 1A–1B have favorable prognosis",
    "",
    "LUNG CANCER TNM STAGING (IASLC 9th edition, 2024):",
    "T staging:",
    "T1a: ≤ 1 cm | T1b: > 1–2 cm | T1c: > 2–3 cm",
    "T2a: > 3–4 cm | T2b: > 4–5 cm | T2 also if: main bronchus involvement (any location), visceral pleural invasion, or atelectasis/pneumonitis extending to hilum",
    "T3: > 5–7 cm, or invasion of chest wall/pericardium/phrenic nerve, or separate nodule in same lobe",
    "T4: > 7 cm, or invasion of diaphragm/mediastinum/heart/great vessels/trachea/RLN/esophagus/vertebral body/carina, or separate nodule in different ipsilateral lobe",
    "N staging:",
    "N0: no nodal metastasis",
    "N1: ipsilateral peribronchial and/or ipsilateral hilar nodes (stations 10–14)",
    "N2: ipsilateral mediastinal and/or subcarinal nodes (stations 2–9 ipsilateral)",
    "N3: contralateral mediastinal/hilar, or ipsilateral/contralateral scalene/supraclavicular nodes",
    "M staging:",
    "M1a: contralateral lung nodule, pleural/pericardial nodules, malignant pleural/pericardial effusion",
    "M1b: single extrathoracic metastasis (single organ)",
    "M1c: multiple extrathoracic metastases (single or multiple organs)",
    "Stage groupings: IA1 (T1a N0 M0), IA2 (T1b N0), IA3 (T1c N0), IB (T2a N0), IIA (T2b N0), IIB (T1-T2 N1 or T3 N0), IIIA (T1-T2 N2 or T3 N1 or T4 N0-N1), IIIB (T1-T2 N3 or T3-T4 N2), IIIC (T3-T4 N3), IVA (M1a-M1b), IVB (M1c)",
    "",
    "LARYNGEAL CANCER TNM STAGING (AJCC 8th ed, 2017):",
    "SUPRAGLOTTIC T staging:",
    "T1: one subsite, normal vocal cord mobility",
    "T2: invades > 1 subsite of supraglottis or glottis, without cord fixation",
    "T3: cord fixation, or invades postcricoid area/pre-epiglottic space/paraglottic space, or minor thyroid cartilage erosion",
    "T4a: through thyroid cartilage, and/or invades trachea, soft tissues of neck, deep/extrinsic tongue muscles, strap muscles, thyroid, or esophagus",
    "T4b: prevertebral space, mediastinal structures, or encases carotid artery",
    "GLOTTIC T staging:",
    "T1a: one cord, normal mobility | T1b: both cords, normal mobility",
    "T2: extends to supraglottis/subglottis, or impaired cord mobility",
    "T3: cord fixation, or paraglottic space invasion, or minor thyroid cartilage erosion",
    "T4a/b: same as supraglottic",
    "SUBGLOTTIC T staging:",
    "T1: limited to subglottis | T2: extends to cords ± impaired mobility",
    "T3: cord fixation | T4a/b: same as supraglottic",
    "N staging (HPV−): N1 ipsi ≤ 3 cm, N2a ipsi 3–6 cm, N2b ipsi multiple ≤ 6 cm, N2c bilateral/contra ≤ 6 cm, N3a > 6 cm, N3b clinical ENE",
    "",
    "NODULE DOUBLING TIME (DT) — GROWTH ASSESSMENT:",
    "Formula: DT = (Δt × ln2) / ln(V₂/V₁) where Δt = time between scans, V = volume",
    "Volume formula for spherical nodule: V = (π/6) × d³",
    "Quick estimate: diameter increase of 26% ≈ volume doubling",
    "Interpretation: DT < 100 days = likely malignant (aggressive) | DT 100–400 days = indeterminate (consider biopsy) | DT 400–600 days = likely benign (slow growth, but part-solid/GGN may have long DT and still be malignant) | DT > 600 days = likely benign",
    "Important: subsolid nodules (GGN/part-solid) may have DT of 800–1400 days and still be malignant (lepidic adenocarcinoma); do NOT use solid nodule DT thresholds for subsolid nodules",
    "VDT < 400 days in solid nodule: Fleischner/BTS recommend short-interval follow-up or tissue sampling",
    "",
    "T1/T2 MAPPING & ECV — CARDIAC MRI REFERENCE VALUES:",
    "Native T1 values (normal myocardium):",
    "1.5T: 950–1050 ms (varies by vendor/sequence; ShMOLLI ~960 ms, MOLLI ~1030 ms)",
    "3T: 1100–1250 ms (ShMOLLI ~1170 ms, MOLLI ~1200 ms)",
    "Elevated native T1: edema, fibrosis, amyloidosis, iron overload is LOW T1",
    "Low native T1: iron overload (< 900 ms at 1.5T), Anderson-Fabry (↓ inferolateral), lipomatous metaplasia",
    "Native T2 values: 1.5T: 45–55 ms | 3T: 40–50 ms",
    "Elevated T2: edema (acute myocarditis, acute MI, takotsubo, transplant rejection)",
    "ECV (extracellular volume fraction): normal 25–30% | elevated > 30%: fibrosis, amyloidosis, edema",
    "ECV formula: ECV = (1 − hematocrit) × (ΔR1_myocardium / ΔR1_blood) where ΔR1 = (1/post-T1) − (1/native-T1)",
    "Clinical use: ECV > 40% strongly suggests amyloidosis; diffuse fibrosis (DCM, HCM, aortic stenosis) ECV 30–40%",
    "",
    "=== URGENT IMAGING CRITERIA / CLINICAL DECISION RULES ===",
    "",
    "CANADIAN CT HEAD RULE (Stiell et al., Lancet 2001):",
    "Indication: minor head injury (GCS 13–15) in adults. Determines need for head CT.",
    "HIGH-RISK criteria (neurosurgical intervention):",
    "1. GCS < 15 at 2 hours post-injury",
    "2. Suspected open or depressed skull fracture",
    "3. Signs of basilar skull fracture (hemotympanum, raccoon eyes, CSF otorrhea/rhinorrhea, Battle sign)",
    "4. ≥ 2 episodes of vomiting",
    "5. Age ≥ 65 years",
    "ANY high-risk criterion → CT indicated immediately",
    "MEDIUM-RISK criteria (brain injury on CT):",
    "1. Anterograde amnesia ≥ 30 minutes from event",
    "2. Dangerous mechanism (pedestrian struck, ejected from vehicle, fall > 1 m or 5 stairs)",
    "ANY medium-risk criterion → CT indicated",
    "NO criteria met → CT not indicated; clinical observation",
    "Sensitivity: 100% for neurosurgical cases, 98.4% for clinically important brain injury",
    "",
    "WELLS SCORE — PULMONARY EMBOLISM (Wells et al., 1998):",
    "Clinical signs/symptoms of DVT: +3 points",
    "PE is most likely diagnosis: +3 points",
    "Heart rate > 100 bpm: +1.5 points",
    "Immobilization ≥ 3 days or surgery in past 4 weeks: +1.5 points",
    "Previous DVT/PE: +1.5 points",
    "Hemoptysis: +1 point",
    "Active cancer (treatment in past 6 months): +1 point",
    "Interpretation: > 6 points = high probability (~40–50% PE risk) → CT pulmonary angiography",
    "2–6 points = intermediate → D-dimer; if positive → CTA",
    "< 2 points = low → D-dimer for exclusion; if negative, PE excluded",
    "",
    "WELLS SCORE — DEEP VEIN THROMBOSIS (Wells et al., 2003):",
    "Active cancer: +1 | Paralysis/paresis/recent immobilization of lower limb: +1",
    "Bedridden > 3 days or major surgery recently: +1 | Tenderness along deep venous system: +1",
    "Entire leg swelling: +1 | Calf > 3 cm vs contralateral: +1",
    "Pitting edema (symptomatic leg only): +1 | Collateral superficial veins (non-varicose): +1",
    "Previously documented DVT: +1 | Alternative diagnosis equally or more likely: −2",
    "Interpretation: ≥ 3 = high probability (~75% DVT) → urgent duplex US",
    "1–2 = moderate → D-dimer; if positive → duplex US",
    "≤ 0 = low → D-dimer for exclusion",
    "",
    "ALVARADO SCORE — APPENDICITIS (MANTRELS, Alvarado 1986):",
    "Migration of pain to RLQ: +1 | Anorexia: +1 | Nausea/vomiting: +1",
    "RLQ tenderness: +2 | Rebound tenderness: +1 | Temperature ≥ 37.3°C: +1",
    "Leukocytosis > 10,000: +2 | Neutrophil left shift: +1",
    "Total: /10. Interpretation:",
    "7–10: high probability → surgery or CT to confirm",
    "5–6: intermediate → abdominopelvic CT indicated to confirm or exclude",
    "0–4: low probability → clinical observation",
    "",
    "TOKYO GUIDELINES CHOLECYSTITIS (TG18, Yokoe et al., J Hepatobiliary Pancreat Sci 2018):",
    "A. Local signs: Murphy sign, RUQ mass/pain, RUQ tenderness",
    "B. Systemic signs: fever > 38°C, elevated CRP, leukocytosis > 10,000",
    "C. Imaging: wall thickening > 4 mm, pericholecystic fluid, distention, sonographic Murphy, stones/sludge",
    "Definite diagnosis: A + B + C all present",
    "Suspected: (A or B) + C",
    "Severity: Grade I (mild) → early laparoscopic cholecystectomy | Grade II (moderate, ≥ 2 of: WBC > 18k, palpable mass, symptoms > 72h, marked local inflammation) → surgery with support | Grade III (severe, organ dysfunction) → stabilization + percutaneous drainage",
    "",
    "CANADIAN C-SPINE RULE / NEXUS (Stiell 2001 / Hoffman 2000):",
    "Indication: cervical spine trauma in alert, stable adults. Determines need for cervical CT.",
    "Canadian C-Spine Rule (3 steps):",
    "Step 1 — High-risk factors (any → CT indicated): age ≥ 65, dangerous mechanism (fall > 1 m, axial load, high-speed collision, bicycle, recreational vehicle), paresthesias in extremities",
    "Step 2 — Low-risk factors (allow ROM assessment): simple rear-end collision, sitting in ED, ambulatory at any time, delayed onset neck pain, no midline tenderness",
    "Step 3 — If low-risk factor present: can the patient actively rotate neck 45° left and right? Yes → CT not indicated; No → CT indicated",
    "NEXUS Criteria (5 criteria, any positive → CT indicated):",
    "1. Midline cervical tenderness | 2. Evidence of intoxication | 3. Altered level of alertness (GCS < 15) | 4. Focal neurological deficit | 5. Painful distracting injury",
    "If ALL 5 NEXUS criteria negative → cervical CT not indicated",
    "Sensitivity: Canadian Rule 99.4%, NEXUS 99.6% for clinically significant cervical spine injury",
    "",
    "PECARN PEDIATRIC HEAD CT RULE (Kuppermann et al., Lancet 2009):",
    "Indication: children with minor head trauma (GCS 14–15). Determines need for head CT.",
    "AGE < 2 YEARS:",
    "High-risk (→ CT recommended): GCS < 15 (altered mental status), palpable skull fracture",
    "Intermediate (→ observation vs CT): altered behavior per parents, non-frontal scalp hematoma (occipital/parietal/temporal), LOC ≥ 5 seconds, not acting normally, severe mechanism (fall > 0.9 m)",
    "No criteria → CT not needed (ciTBI risk < 0.02%)",
    "AGE ≥ 2 YEARS:",
    "High-risk (→ CT recommended): GCS < 15, altered mental status, signs of basilar skull fracture",
    "Intermediate (→ observation vs CT): LOC, vomiting, severe mechanism (fall > 1.5 m), severe headache",
    "No criteria → CT not needed (ciTBI risk < 0.02%)",
    "ciTBI = clinically important traumatic brain injury (death, neurosurgery, intubation > 24h, admission ≥ 2 nights)",
    "",
    "SAN FRANCISCO SYNCOPE RULE — CHESS (Quinn et al., Ann Emerg Med 2004):",
    "Indication: syncope evaluation. Determines if workup/imaging is indicated.",
    "CHESS criteria (any positive = high risk):",
    "C — History of congestive heart failure",
    "H — Hematocrit < 30%",
    "E — Abnormal ECG (new change or non-sinus rhythm)",
    "S — Shortness of breath (at presentation)",
    "S — Systolic BP < 90 mmHg (at triage)",
    "≥ 1 criterion = high risk: serious 30-day adverse event risk; imaging workup indicated (CT/MRI head, echocardiography)",
    "0 criteria = low risk (< 2%): safe discharge with outpatient follow-up",
    "Sensitivity 96%, specificity 62% for 30-day serious outcomes",
    "",
    "HEART SCORE — CHEST PAIN (Six et al., Neth Heart J 2008):",
    "Indication: acute chest pain in ED. Determines cardiac workup/imaging need.",
    "H — History: 0 = slightly suspicious, 1 = moderately, 2 = highly suspicious",
    "E — ECG: 0 = normal, 1 = non-specific abnormality, 2 = significant ST deviation",
    "A — Age: 0 = < 45, 1 = 45–64, 2 = ≥ 65",
    "R — Risk factors (HTN, DM, smoking, dyslipidemia, obesity, family history): 0 = none known, 1 = 1–2 factors, 2 = ≥ 3 or known CAD",
    "T — Troponin: 0 = ≤ normal limit, 1 = 1–3× normal, 2 = > 3× normal",
    "Total: /10. Interpretation:",
    "0–3: low risk (MACE ~1.7%) → consider early discharge, outpatient follow-up",
    "4–6: moderate risk (MACE ~16.6%) → admission, monitoring, non-invasive study (coronary CTA)",
    "7–10: high risk (MACE ~50%) → urgent catheterization / coronary CTA",
    "MACE = major adverse cardiac events (MI, PCI, CABG, death)",
    "=== CALCULABLE FORMULAS (you can perform these calculations when the user provides measurements) ===",
    "",
    "ELLIPSOID VOLUME (for organs and masses):",
    "Formula: Volume (mL) = L × W × AP × 0.524 (equivalent to π/6 × L × W × AP)",
    "Applicable to: prostate, thyroid lobes, testes, kidneys, adrenal glands, masses, cysts",
    "Units: all dimensions in cm → result in mL (= cm³)",
    "",
    "PROSTATE VOLUME & PSA DENSITY:",
    "Volume (mL) = L × W × AP × 0.524",
    "PSA density = PSA (ng/mL) / Volume (mL)",
    "Normal volume: < 30 mL | PSA density threshold: ≥ 0.15 ng/mL/mL is suspicious (PI-RADS consideration)",
    "",
    "THYROID VOLUME:",
    "Volume per lobe (mL) = L × W × AP × 0.524",
    "Total volume = right lobe + left lobe (isthmus not included)",
    "Normal total: 6–15 mL (women < 18 mL, men < 25 mL)",
    "",
    "TESTICULAR VOLUME:",
    "Volume (mL) = L × W × AP × 0.52",
    "Normal adult: 15–25 mL per testis | Atrophy if < 50% of contralateral",
    "",
    "ADRENAL WASHOUT (CT):",
    "APW (absolute) = ((enhanced HU − delayed HU) / (enhanced HU − unenhanced HU)) × 100",
    "RPW (relative) = ((enhanced HU − delayed HU) / enhanced HU) × 100",
    "APW ≥ 60% = adenoma | RPW ≥ 40% = adenoma | Unenhanced ≤ 10 HU = lipid-rich adenoma (no washout needed)",
    "",
    "NODULE VOLUME (spherical approximation):",
    "Volume (mm³) = π/6 × diameter³ = 0.524 × d³ (when only one diameter is given)",
    "Volume (mm³) = π/6 × d1 × d2 × d3 (when three diameters are given)",
    "",
    "NODULE VOLUME DOUBLING TIME (VDT):",
    "Formula: VDT (days) = (Δt × ln2) / ln(V2/V1)",
    "Where: Δt = days between measurements, V1 = initial volume, V2 = final volume",
    "If only diameters given: Volume = π/6 × d³ (convert diameter to volume first)",
    "Interpretation: VDT < 400 days = suspicious for malignancy | VDT 400–600 = indeterminate | VDT > 600 = likely benign",
    "Note: VDT < 20 days suggests infection/inflammation, not cancer",
    "",
    "MEAN NODULE DIAMETER:",
    "Mean diameter = (long axis + short axis) / 2",
    "Growth = ≥ 1.5 mm increase in mean diameter (Lung-RADS criterion)",
    "",
    "RESISTIVE INDEX (RENAL DOPPLER):",
    "RI = (peak systolic velocity − end diastolic velocity) / peak systolic velocity",
    "Normal RI: 0.50–0.70 | RI > 0.70 = elevated (obstruction, renal disease, transplant rejection)",
    "",
    "CAROTID STENOSIS (NASCET):",
    "% Stenosis = ((D_normal − D_stenosis) / D_normal) × 100",
    "Where D_normal = diameter of normal distal ICA, D_stenosis = diameter at narrowest point",
    "",
    "AORTIC SIZE INDEX:",
    "ASI (cm/m²) = aortic diameter (cm) / BSA (m²)",
    "BSA (Du Bois) = 0.007184 × height_cm^0.725 × weight_kg^0.425",
    "ASI interpretation: < 2.75 = low risk | 2.75–4.24 = moderate | ≥ 4.25 = high risk (for ascending aorta)",
    "",
    "CALCULATION INSTRUCTIONS:",
    "When the user gives you measurements, PERFORM the calculation step by step:",
    "1. Identify which formula applies",
    "2. Show the formula with the user's numbers substituted",
    "3. Show the arithmetic step by step",
    "4. Give the final result with units and clinical interpretation from the KB",
    "Example: 'prostate 4.5 × 3.2 × 3.8 cm' → V = 4.5 × 3.2 × 3.8 × 0.524 = 28.7 mL → normal (< 30 mL)",
    "=== END CALCULABLE FORMULAS ===",
  ].join("\n");
}
