import { DEFAULT_RECOMMENDATIONS } from "./recommendation-defaults";

type Lang = "es" | "en" | "pt";

export function buildKnowledgeBase(lang: Lang): string {
  const recEntries = DEFAULT_RECOMMENDATIONS.map((r) => {
    const title = r.title[lang] || r.title.en || Object.values(r.title)[0];
    const text = r.text[lang] || r.text.en || Object.values(r.text)[0];
    return `[${r.source}] (${r.category} / ${r.modality}) ${title}: ${text}`;
  });

  const clinicalData = buildClinicalReferenceData(lang);

  return [
    "=== RADIOLOGY CALCULATOR & QUICK REFERENCE DATA ===",
    clinicalData,
    "",
    "=== CLINICAL RECOMMENDATIONS (evidence-based management) ===",
    recEntries.join("\n"),
  ].join("\n");
}

function buildClinicalReferenceData(lang: Lang): string {
  const L = {
    es: {
      aortaTitle: "DIÁMETROS AÓRTICOS NORMALES",
      segment: "Segmento", male: "Hombre", female: "Mujer", aneurysm: "Umbral aneurisma",
      washoutTitle: "LAVADO ADRENAL (CT)",
      apw: "APW (lavado absoluto)", rpw: "RPW (lavado relativo)",
      adenoma: "Adenoma", indeterminate: "Indeterminado", suspicious: "Sospechoso",
      tiradsTitle: "ACR TI-RADS — PUNTUACIÓN POR CATEGORÍA",
      bosniak: "CLASIFICACIÓN BOSNIAK 2019",
      piradsTitle: "PI-RADS v2.1 — PROBABILIDAD DE CÁNCER CLÍNICAMENTE SIGNIFICATIVO",
      fleischnerTitle: "CRITERIOS FLEISCHNER 2017 — SEGUIMIENTO DE NÓDULOS PULMONARES",
      lowRisk: "bajo riesgo", highRisk: "alto riesgo",
      noFollowUp: "No requiere seguimiento", optional12: "TC opcional a 12 meses",
      fu612: "TC en 6-12 meses", fu1824: "considerar TC 18-24 meses",
      fu36: "TC en 3-6 meses", fu1218: "TC 12-18 meses después",
      pet: "considerar PET/TC o biopsia",
      subsolid: "Nódulos subsólidos (vidrio deslustrado / parcialmente sólidos)",
      ggn: "Vidrio deslustrado puro (GGN)", partSolid: "Parcialmente sólido",
      solidStable: "SÓLIDO estable ≥ 3 años → no más seguimiento necesario",
      subsolidStable: "SUBSÓLIDO / VIDRIO DESLUSTRADO: seguimiento recomendado durante mínimo 5 años por riesgo de crecimiento lento",
    },
    en: {
      aortaTitle: "NORMAL AORTIC DIAMETERS",
      segment: "Segment", male: "Male", female: "Female", aneurysm: "Aneurysm threshold",
      washoutTitle: "ADRENAL WASHOUT (CT)",
      apw: "APW (absolute percentage washout)", rpw: "RPW (relative percentage washout)",
      adenoma: "Adenoma", indeterminate: "Indeterminate", suspicious: "Suspicious",
      tiradsTitle: "ACR TI-RADS — SCORE BY CATEGORY",
      bosniak: "BOSNIAK 2019 CLASSIFICATION",
      piradsTitle: "PI-RADS v2.1 — PROBABILITY OF CLINICALLY SIGNIFICANT CANCER",
      fleischnerTitle: "FLEISCHNER 2017 CRITERIA — PULMONARY NODULE FOLLOW-UP",
      lowRisk: "low risk", highRisk: "high risk",
      noFollowUp: "No routine follow-up", optional12: "Optional CT at 12 months",
      fu612: "CT at 6-12 months", fu1824: "consider CT at 18-24 months",
      fu36: "CT at 3-6 months", fu1218: "CT at 12-18 months after",
      pet: "consider PET/CT or biopsy",
      subsolid: "Subsolid nodules (ground-glass / part-solid)",
      ggn: "Pure ground-glass nodule (GGN)", partSolid: "Part-solid",
      solidStable: "SOLID nodule stable ≥ 3 years → no further follow-up needed",
      subsolidStable: "SUBSOLID / GROUND-GLASS: follow-up recommended for minimum 5 years due to risk of slow growth",
    },
    pt: {
      aortaTitle: "DIÂMETROS AÓRTICOS NORMAIS",
      segment: "Segmento", male: "Homem", female: "Mulher", aneurysm: "Limiar de aneurisma",
      washoutTitle: "LAVAGEM ADRENAL (TC)",
      apw: "APW (lavagem absoluta)", rpw: "RPW (lavagem relativa)",
      adenoma: "Adenoma", indeterminate: "Indeterminado", suspicious: "Suspeito",
      tiradsTitle: "ACR TI-RADS — PONTUAÇÃO POR CATEGORIA",
      bosniak: "CLASSIFICAÇÃO BOSNIAK 2019",
      piradsTitle: "PI-RADS v2.1 — PROBABILIDADE DE CÂNCER CLINICAMENTE SIGNIFICATIVO",
      fleischnerTitle: "CRITÉRIOS FLEISCHNER 2017 — SEGUIMENTO DE NÓDULOS PULMONARES",
      lowRisk: "baixo risco", highRisk: "alto risco",
      noFollowUp: "Sem seguimento de rotina", optional12: "TC opcional em 12 meses",
      fu612: "TC em 6-12 meses", fu1824: "considerar TC em 18-24 meses",
      fu36: "TC em 3-6 meses", fu1218: "TC em 12-18 meses depois",
      pet: "considerar PET/TC ou biópsia",
      subsolid: "Nódulos subsólidos (vidro fosco / parcialmente sólidos)",
      ggn: "Vidro fosco puro (GGN)", partSolid: "Parcialmente sólido",
      solidStable: "SÓLIDO estável ≥ 3 anos → sem mais seguimento necessário",
      subsolidStable: "SUBSÓLIDO / VIDRO FOSCO: seguimento recomendado durante mínimo 5 anos por risco de crescimento lento",
    },
  };
  const l = L[lang] || L.en;

  return [
    "=== INDEX OF AVAILABLE TOPICS (search by name) ===",
    "Fleischner 2017 | BTS 2015 | Lung-RADS v2022 | LI-RADS v2018 | BI-RADS v2025 | O-RADS MRI | TI-RADS | PI-RADS v2.1 | CAD-RADS 2.0 | Bosniak 2019 | Adrenal washout | Aortic diameters | NASCET carotid stenosis | Peripheral artery disease | Thyroid incidentals | Adrenal incidentals | Renal cyst | Ovarian incidentals | Gallbladder polyps | Diverticulitis | Breast density | Breast screening | Breast US lexicon | Breast implants | Mediastinal lymph nodes | Cerebral vascular territories | Cerebral aneurysm | Fisher SAH | Brain tumors WHO | CT perfusion | Complex infarct syndromes | Demyelinating diseases (MS, NMOSD, MOGAD, ADEM, PML) | McDonald 2024 | Neurodegenerative diseases | Neck anatomy | MRI shoulder | MRI knee | MRI ankle | MRI thigh muscles | Rotator cuff | Bone tumors | Vertebral fractures | Whole aorta CTA | Pediatric CXR | Pediatric hydronephrosis | Pediatric tumors | Cryptorchidism | Transfontanellar US | Testicular torsion | Pancreatic cysts",
    "=== END INDEX ===",
    "",
    `${l.fleischnerTitle}:`,
    `SOLID NODULES:`,
    `< 6 mm, ${l.lowRisk}: ${l.noFollowUp}`,
    `< 6 mm, ${l.highRisk}: ${l.optional12}`,
    `6-8 mm, ${l.lowRisk}: ${l.fu612}; ${l.fu1824}`,
    `6-8 mm, ${l.highRisk}: ${l.fu612}; ${l.fu1824}`,
    `> 8 mm: ${l.fu36}; ${l.pet}`,
    `${l.subsolid}:`,
    `${l.ggn} < 6 mm: ${l.noFollowUp}`,
    `${l.ggn} ≥ 6 mm: ${l.fu612}; then every 2 years for 5 years`,
    `${l.partSolid} < 6 mm: ${l.noFollowUp}`,
    `${l.partSolid} ≥ 6 mm: ${l.fu36}; if solid component ≥ 6mm → ${l.pet}`,
    `STABILITY RULES (IMPORTANT — different for solid vs subsolid):`,
    `${l.solidStable}`,
    `${l.subsolidStable}`,
    `Multiple nodules: follow-up based on the most suspicious nodule`,
    "",
    `${l.aortaTitle}:`,
    `${l.segment} | ${l.male} (cm) | ${l.female} (cm) | ${l.aneurysm}`,
    "Aortic root (sinuses of Valsalva) | 3.4–3.7 | 3.0–3.3 | > 4.5 cm",
    "Sinotubular junction | 2.9–3.2 | 2.6–2.9 | —",
    "Mid-ascending aorta | 3.0–3.5 | 2.7–3.2 | > 4.5 cm",
    "Aortic arch | 2.5–3.0 | 2.3–2.7 | > 4.0 cm",
    "Aortic isthmus | 2.0–2.5 | 1.8–2.3 | —",
    "Mid-descending aorta | 2.3–2.8 | 2.1–2.5 | > 4.0 cm",
    "Suprarenal aorta | 2.0–2.5 | 1.8–2.2 | > 3.5 cm",
    "Infrarenal aorta | 1.7–2.1 | 1.5–1.8 | > 3.0 cm",
    "",
    "AORTIC ANEURYSM SURGICAL THRESHOLDS (ACC/AHA 2022):",
    "Aortic root > 5.5 cm (Marfan > 5.0 cm; Loeys-Dietz 4.0–4.5 cm)",
    "Ascending aorta > 5.5 cm (BAV > 5.0–5.5 cm)",
    "Aortic arch > 5.5 cm",
    "Descending thoracic > 5.5–6.0 cm (TEVAR > 5.5 cm)",
    "Infrarenal AAA > 5.5 cm (M) / > 5.0 cm (F) (EVAR > 5.5 cm)",
    "",
    "AORTIC ANEURYSM FOLLOW-UP INTERVALS:",
    "< 4.0 cm (AAA): US every 2-3 years",
    "4.0–4.9 cm: US or CT every 12 months",
    "5.0–5.4 cm: US or CT every 6 months",
    "Rapid growth (> 0.5 cm/6 months or > 1 cm/year): surgical evaluation",
    "",
    "AORTIC DISSECTION (Stanford / DeBakey):",
    "Stanford A: involves ascending aorta ± distal extension → emergency surgery",
    "Stanford B: only descending aorta (distal to left subclavian) → medical management; TEVAR if complicated",
    "DeBakey I: ascending to at least arch (may extend to descending)",
    "DeBakey II: limited to ascending aorta",
    "DeBakey III: limited to descending aorta (IIIa: to diaphragm; IIIb: below)",
    "",
    "AORTIC ARCH VARIANTS:",
    "Normal arch (3 vessels) ~70%: BT, LCCA, LSA separate from arch",
    "Bovine arch ~20–27%: common origin BT+LCCA or LCCA from BT",
    "Aberrant right subclavian ~1–2%: RSA distal to LSA, retroesophageal (Kommerell diverticulum)",
    "Left vertebral from arch ~5%: LVA arises directly from arch between LCCA and LSA",
    "Right-sided arch ~0.1%: arch crosses to right, look for vascular ring",
    "",
    `${l.washoutTitle}:`,
    `${l.apw}: ≥ 60% = ${l.adenoma} | 40–59% = ${l.indeterminate} | < 40% = ${l.suspicious}`,
    `${l.rpw}: ≥ 40% = ${l.adenoma} | < 40% = ${l.suspicious}`,
    "Unenhanced density ≤ 10 HU = lipid-rich adenoma (no washout needed)",
    "Formula: APW = ((enhanced − delayed) / (enhanced − unenhanced)) × 100",
    "Formula: RPW = ((enhanced − delayed) / enhanced) × 100",
    "",
    `${l.tiradsTitle}:`,
    "TR1 (benign): 0 points → no FNA",
    "TR2 (not suspicious): 2 points → no FNA",
    "TR3 (mildly suspicious): 3 points → FNA if ≥ 2.5 cm, follow-up if ≥ 1.5 cm",
    "TR4 (moderately suspicious): 4–6 points → FNA if ≥ 1.5 cm, follow-up if ≥ 1.0 cm",
    "TR5 (highly suspicious): ≥ 7 points → FNA if ≥ 1.0 cm, follow-up if ≥ 0.5 cm",
    "",
    "THYROID VOLUME CALCULATION:",
    "Formula: Volume (mL) = length × width × AP × 0.524 (per lobe)",
    "Normal total volume: 6–15 mL (women < 18 mL, men < 25 mL)",
    "",
    `${l.piradsTitle}:`,
    "PI-RADS 1: very low (< 5%)",
    "PI-RADS 2: low (5–15%)",
    "PI-RADS 3: intermediate (15–30%)",
    "PI-RADS 4: high (30–70%)",
    "PI-RADS 5: very high (> 70%)",
    "",
    "PROSTATE VOLUME & PSA DENSITY:",
    "Formula: Volume (mL) = length × width × AP × 0.524",
    "PSA density = PSA / volume",
    "PSA density < 0.10: low risk",
    "PSA density 0.10–0.15: intermediate",
    "PSA density > 0.15: elevated risk (consider biopsy)",
    "",
    `${l.bosniak}:`,
    "I: simple cyst (< 1% malignancy) → no follow-up",
    "II: minimally complex (< 5%) → no follow-up",
    "IIF: mildly complex (5–10%) → follow-up",
    "III: indeterminate (40–60%) → surgery or active surveillance",
    "IV: clearly malignant (> 80%) → surgery",
    "",
    "BI-RADS v2025 CATEGORIES:",
    "0a: incomplete — needs additional conventional imaging",
    "0b: incomplete — needs prior exams for comparison",
    "1: negative (0% malignancy)",
    "2: benign (0%)",
    "3: probably benign (0–2%) → short-interval follow-up 6 months",
    "4a: low suspicion (2–10%) → biopsy",
    "4b: moderate suspicion (10–50%) → biopsy",
    "4c: high suspicion (50–95%) → biopsy",
    "5: highly suggestive of malignancy (> 95%) → biopsy",
    "6: known biopsy-proven malignancy",
    "",
    "LI-RADS (ACR LI-RADS v2018) CATEGORIES:",
    "LR-NC: non-categorizable (inadequate technical quality)",
    "LR-1: definitely benign",
    "LR-2: probably benign",
    "LR-3: intermediate probability → return in 3-6 months",
    "LR-4: probably HCC → multidisciplinary discussion",
    "LR-5: definitely HCC (APHE + washout/capsule + threshold growth) → treat as HCC",
    "LR-M: probably malignant, not HCC-specific → biopsy or multidisciplinary",
    "LR-TIV: tumor in vein → treat as HCC with vascular invasion",
    "",
    "LI-RADS MAJOR FEATURES FOR HCC DIAGNOSIS:",
    "APHE (non-peripheral arterial phase hyperenhancement): enhancement greater than surrounding liver, non-peripheral/non-rim",
    "Washout: hypoenhancement in portal venous or delayed phase relative to liver",
    "Enhancing capsule: smooth peripheral rim of enhancement in portal venous or delayed phase",
    "Threshold growth: increase ≥ 50% in ≤ 6 months",
    "Size ≥ 10 mm: required for LR-5; < 10 mm cannot be LR-5",
    "",
    "LI-RADS DIAGNOSTIC TABLE (observation with APHE):",
    "< 10 mm + no additional features = LR-3 | +1 feature (washout OR capsule OR growth) = LR-4 | +≥2 features = LR-4",
    "10–19 mm + no additional features = LR-3 | +1 feature = LR-4 | +≥2 features = LR-5",
    "≥ 20 mm + no additional features = LR-4 | +1 feature = LR-5 | +≥2 features = LR-5",
    "",
    "LUNG-RADS v2022 (ACR Lung Cancer Screening) — also known as: Lung RADS, LungRADS, clasificación de nódulos pulmonares por screening LDCT:",
    "Lung-RADS 0: incomplete — prior chest CT not available → compare with prior or additional imaging",
    "Lung-RADS 1: negative — no lung nodules (< 1% malignancy) → continue annual LDCT screening",
    "Lung-RADS 2: benign appearance — solid < 6 mm, part-solid < 6 mm total, GGN < 30 mm (< 1%) → continue annual LDCT screening",
    "Lung-RADS 3: probably benign — solid 6–8 mm (baseline), part-solid ≥ 6 mm with solid < 6 mm, GGN ≥ 30 mm (1–2%) → 6-month follow-up LDCT",
    "Lung-RADS 4A: suspicious — solid 8–15 mm, new solid 4–8 mm, part-solid with solid 6–8 mm (5–15%) → 3-month follow-up LDCT or PET/CT",
    "Lung-RADS 4B: suspicious — solid ≥ 15 mm, new/growing solid ≥ 8 mm, part-solid with solid ≥ 8 mm (> 15%) → chest CT ± PET/CT, tissue sampling",
    "Lung-RADS 4X: category 3/4 with additional suspicious features (spiculation, lymphadenopathy, etc.) (> 15%) → tissue sampling recommended",
    "Lung-RADS S: clinically significant incidental finding unrelated to lung cancer → as indicated by finding",
    "",
    "O-RADS MRI 2022 (ACR Ovarian-Adnexal Reporting) — also known as: ORADS, O-RADS, clasificación de lesiones ováricas por RM:",
    "O-RADS 1: normal ovary (< 0.5% malignancy) → routine care",
    "O-RADS 2: almost certainly benign — simple cyst, endometrioma without solid tissue, dermoid (< 1%) → optional follow-up",
    "O-RADS 3: low risk — fibroma-like (T2 dark, low DWI), multilocular thin-walled, smooth wall + TIC type 1 (1–5%) → follow-up MRI 12 weeks",
    "O-RADS 4: intermediate risk — thick wall/septa ≥ 3mm, irregular wall, smooth + TIC type 2/3 (10–50%) → surgical evaluation",
    "O-RADS 5: high risk — irregular wall + high DWI + TIC type 3, peritoneal implants (> 50%) → surgical evaluation by gynecologic oncology",
    "",
    "CAROTID STENOSIS (NASCET) — DOPPLER US CRITERIA:",
    "Normal: PSV < 125 cm/s, EDV < 40 cm/s, ICA/CCA ratio < 2.0",
    "< 50% stenosis: PSV < 125, EDV < 40, ICA/CCA < 2.0",
    "50–69%: PSV 125–230, EDV 40–100, ICA/CCA 2.0–4.0",
    "≥ 70%: PSV > 230, EDV > 100, ICA/CCA > 4.0",
    "Near-occlusion (> 95%): variable low-velocity flow",
    "Occlusion: no flow detected",
    "",
    "PERIPHERAL ARTERY DISEASE (Fontaine / Rutherford):",
    "Fontaine I / Rutherford 0: asymptomatic",
    "Fontaine IIa / Rutherford 1: mild claudication",
    "Fontaine IIb / Rutherford 2-3: moderate-severe claudication",
    "Fontaine III / Rutherford 4: ischemic rest pain",
    "Fontaine IV / Rutherford 5: minor tissue loss",
    "Fontaine IV / Rutherford 6: major tissue loss / gangrene",
    "",
    "DVT/PE CLASSIFICATION:",
    "PE location: saddle (main PA bifurcation), central (main/lobar), lobar, segmental, subsegmental",
    "RV strain signs: RV/LV ratio > 1.0, septal bowing, IVC reflux",
    "",
    "ASPECTS (Alberta Stroke Program Early CT Score):",
    "Regions: C (caudate), L (lentiform), IC (internal capsule), I (insular ribbon), M1–M6 (MCA cortex)",
    "Score 10 = normal, 0 = complete MCA territory infarct",
    "≤ 5: large infarct core (poor outcome with thrombolysis)",
    "> 7: small infarct core (favorable for intervention)",
    "",
    "FAZEKAS SCALE (white matter disease):",
    "Grade 0: none or single punctate lesion",
    "Grade 1: multiple punctate lesions",
    "Grade 2: beginning confluent lesions (bridging)",
    "Grade 3: large confluent areas",
    "",
    "SPINAL CANAL STENOSIS (Schizas et al., Spine 2010):",
    "Grade A (A1–A4): no stenosis — CSF clearly visible around rootlets",
    "Grade B: moderate — rootlets occupy entire canal but can be individualized",
    "Grade C: severe — rootlets not individually visible, some CSF present",
    "Grade D: extreme — no CSF signal, complete compression",
    "",
    "FORAMINAL STENOSIS (Lee/Wildermuth):",
    "Grade 0: normal — perineural fat surrounds root",
    "Grade 1: mild — perineural fat obliteration, root size preserved",
    "Grade 2: moderate — root deformity/flattening, fat partially effaced",
    "Grade 3: severe — root collapsed/not visible",
    "",
    "DISC NOMENCLATURE (Fardon et al., Spine J 2014):",
    "Normal disc: no extension beyond vertebral body margins",
    "Bulge: circumferential symmetrical extension > 50% of disc circumference",
    "Protrusion: focal extension with base wider than apex in at least one plane",
    "Extrusion: extension with base narrower than apex, or migrated material",
    "Sequestration: extruded fragment with no continuity with parent disc",
    "",
    "PEDIATRIC HIP ULTRASOUND — GRAF CLASSIFICATION (DDH):",
    "Type Ia: α ≥ 60° — mature, normal",
    "Type Ib: α ≥ 60° — mature with blunt bony rim",
    "Type IIa: α 50–59° — physiologic immaturity (< 3 months), observe",
    "Type IIb: α 50–59° — ossification delay (> 3 months), treat",
    "Type IIc: α 43–49° — critical, cartilaginous roof deficient",
    "Type D: α 43–49° — decentering, unstable → Pavlik harness",
    "Type IIIa/b: α < 43° — dislocated, cartilaginous roof displaced → Pavlik harness or surgery",
    "Type IV: α < 43° — dislocated, labrum interposed → surgical reduction",
    "",
    "INTERSTITIAL LUNG DISEASE PATTERNS (ATS/ERS 2022):",
    "UIP (usual interstitial pneumonia):",
    "  Typical: subpleural basal predominant honeycombing ± traction bronchiectasis",
    "  Probable: subpleural basal predominant reticular pattern with traction bronchiectasis, no honeycombing",
    "  Indeterminate: subpleural but not basal predominant, or features of other patterns",
    "  Alternative diagnosis: features suggesting other diagnoses (mosaic attenuation, GGN predominance, centrilobular nodules)",
    "Hypersensitivity Pneumonitis (ATS/JRS 2020):",
    "  Typical: mid-lung predominance, mosaic attenuation/air trapping + fibrotic features",
    "  Compatible: fibrotic features without typical HP distribution",
    "  Indeterminate: features overlap with other fibrotic ILDs",
    "",
    "INCIDENTAL LIVER LESIONS (ACR Incidental Findings Committee 2017):",
    "Simple cyst: any size → no follow-up needed",
    "Typical hemangioma: < 3 cm → no follow-up | ≥ 3 cm → no follow-up if typical; MRI if atypical",
    "FNH-like (homogeneous enhancement, central scar): any size → no follow-up if typical; hepatobiliary MRI if uncertain",
    "Indeterminate hypodense lesion: < 1 cm → no follow-up if low risk | 1–1.5 cm → follow-up at 6 months if low risk, multiphase MRI if high risk | > 1.5 cm → multiphase MRI",
    "",
    "RENAL LESION CHARACTERIZATION (CT):",
    "Simple cyst criteria: water density (0–20 HU), no enhancement, thin wall, no septation",
    "Enhancement threshold: > 20 HU increase post-contrast = enhancing (suspicious)",
    "Homogeneously > 70 HU on unenhanced CT: hyperdense cyst (Bosniak II)",
    "",
    "RESISTIVE INDEX (Doppler) — RI = (PSV − EDV) / PSV:",
    "Renal artery: normal RI 0.50–0.70 | ≥0.70 suggests nephropathy/stenosis",
    "Hepatic artery: normal RI 0.55–0.80 | <0.50 (tardus-parvus) suggests proximal stenosis",
    "Splenic artery: normal RI 0.50–0.70 | comparable to renal in practice",
    "Internal carotid artery (ICA): normal RI 0.50–0.70 | low RI in low-resistance territory",
    "Ophthalmic artery: normal RI 0.65–0.75 | flow reversal suggests severe ICA stenosis",
    "Uterine artery (non-pregnant): normal RI 0.80–0.90 | decreases in pregnancy (0.50–0.60 in 3rd trimester)",
    "Umbilical artery (2nd-3rd trimester): normal RI 0.55–0.70 | absent/reversed diastole = fetal compromise",
    "Fetal MCA: normal RI 0.70–0.80 | ↓RI indicates fetal hemodynamic redistribution",
    "",
    "TRANSPLANT DOPPLER US — HEPATIC TRANSPLANT (ACR Appropriateness Criteria 2022; AIUM):",
    "Hepatic artery RI: normal 0.50–0.80 | >0.80 rejection/thrombosis; <0.50 tardus-parvus (stenosis)",
    "Hepatic artery PSV: normal 30–100 cm/s | <30 cm/s low flow; >200 cm/s stenosis",
    "Hepatic artery acceleration time (AT): normal < 0.08 s | ≥0.08 s (tardus-parvus) → hepatic artery stenosis",
    "Portal vein velocity: normal 20–40 cm/s | <20 cm/s stenosis/partial thrombosis",
    "Portal flow direction: normal hepatopetal | hepatofugal or absent = thrombosis/portal hypertension",
    "Hepatic vein waveform: normal triphasic/biphasic | monophasic = rejection/congestion",
    "",
    "TRANSPLANT DOPPLER US — RENAL TRANSPLANT (ACR Appropriateness Criteria 2022; AIUM):",
    "Transplant renal artery RI: normal 0.50–0.80 | >0.80 rejection/ATN; <0.50 proximal stenosis",
    "Renal artery PSV (anastomosis): normal < 200 cm/s | >200 cm/s or ratio >3:1 = stenosis",
    "Segmental artery RI: normal 0.50–0.70 | >0.80 or tardus-parvus → stenosis/rejection",
    "Renal vein flow: normal continuous antegrade | absent/reversed = venous thrombosis",
    "Acceleration time (AT): normal < 0.07 s | ≥0.07 s → renal artery stenosis",
    "",
    "CAD-RADS 2.0 — CORONARY ARTERY DISEASE REPORTING (Cury RC et al., Radiology 2022):",
    "CAD-RADS 0: 0% stenosis — no plaque or stenosis → no further workup",
    "CAD-RADS 1: 1–24% — minimal stenosis → preventive therapy",
    "CAD-RADS 2: 25–49% — mild stenosis → preventive therapy",
    "CAD-RADS 3: 50–69% — moderate stenosis → consider functional assessment",
    "CAD-RADS 4A: 70–99% — severe stenosis (1-2 vessels) → consider ICA / revascularization",
    "CAD-RADS 4B: LM ≥50% or 3-vessel ≥70% — severe (left main or 3-vessel) → consider ICA / revascularization",
    "CAD-RADS 5: 100% — total occlusion → consider ICA / revascularization",
    "Modifiers: /S (stent), /G (graft), /V (vulnerable plaque: positive remodeling, low attenuation, napkin-ring, spotty calcification), /I (non-diagnostic), /E (exception: anomaly, aneurysm, dissection)",
    "Plaque burden (new in 2.0): P1 (mild, 1-2 segments), P2 (mild, ≥3 segments), P3 (moderate, 25-49% per segment), P4 (extensive, ≥4 segments or ≥2 with P3)",
    "",
    "MYOCARDIAL ENHANCEMENT PATTERNS — CARDIAC MRI (Mahrholdt H et al., Eur Heart J 2005; Kim RJ et al., Circulation 1999):",
    "Late Gadolinium Enhancement (LGE) patterns:",
    "Ischemic (subendocardial → transmural): follows coronary territory → acute/chronic MI",
    "Mid-wall (mesocardial): interventricular septum → DCM, chronic myocarditis, sarcoidosis",
    "Epicardial: inferolateral wall → acute myocarditis, sarcoidosis",
    "Diffuse subendocardial: global circumferential → amyloidosis (+ difficulty nulling myocardium)",
    "RV insertion points: anterior & inferior RV-LV junctions → HCM, pulmonary hypertension",
    "Patchy/multifocal: variable location → sarcoidosis, myocarditis",
    "Mid-wall basal inferolateral: specific pattern → Anderson-Fabry disease",
    "",
    "AHA 17-SEGMENT MODEL — CORONARY TERRITORIES (Cerqueira MD et al., Circulation 2002):",
    "LAD territory: segments 1 (basal anterior), 2 (basal anteroseptal), 7 (mid anterior), 8 (mid anteroseptal), 13 (apical anterior), 14 (apical septal), 17 (apex)",
    "RCA territory: segments 3 (basal inferoseptal), 4 (basal inferior), 9 (mid inferoseptal), 10 (mid inferior), 15 (apical inferior)",
    "LCx territory: segments 5 (basal inferolateral), 6 (basal anterolateral), 11 (mid inferolateral), 12 (mid anterolateral), 16 (apical lateral)",
    "Basal ring: 6 segments (60° each) | Mid ring: 6 segments | Apical ring: 4 segments (90° each) | Apex: segment 17",
    "",
    "PANCREATIC CYSTIC LESION CHARACTERISTICS (ACR Incidental Findings 2017 / Fukuoka IAP 2017):",
    "Incidental cyst management by size:",
    "< 1.5 cm: no follow-up or MRI at 1 year if risk factors",
    "1.5–2.5 cm: MRI at 1 year, then every 2 years if stable (up to 5 years)",
    "> 2.5 cm: MRI at 6 months, then annually; refer to GI/surgery",
    "Worrisome features (solid component, Wirsung > 5mm, caliber change): surgical referral; consider EUS + FNA",
    "",
    "Cyst types — differential characteristics:",
    "SCN (serous cystadenoma): microcystic/honeycomb, central scar ± stellate calcification | any location (most common: head) | no duct communication | very low malignant potential (< 1%)",
    "MCN (mucinous cystic neoplasm): macrocystic, thick wall, peripheral calcification, no duct communication | body/tail | no duct communication | moderate malignant potential (15-20%)",
    "BD-IPMN (branch duct): cluster of cysts communicating with branch duct, normal Wirsung | head (uncinate) | yes (branch duct) | low-moderate (15-25%)",
    "MD-IPMN (main duct): Wirsung ≥ 5 mm segmental or diffuse ± mural nodules | any location | yes (main duct) | high (40-70%); surgery recommended",
    "SPN (solid pseudopapillary neoplasm): well-encapsulated solid-cystic mass, hemorrhagic component | body/tail | no | low (10-15%); young women",
    "",
    "Fukuoka / IAP 2017 criteria:",
    "Worrisome features: cyst ≥ 3 cm, thickened/enhancing wall, non-enhancing mural nodule, Wirsung 5-9 mm, abrupt caliber change, lymphadenopathy, elevated CA 19-9, growth ≥ 5 mm/2 years",
    "High-risk stigmata: enhancing mural nodule ≥ 5 mm, Wirsung ≥ 10 mm, obstructive jaundice with cystic lesion in pancreatic head",
    "",
    "TESTICULAR TORSION — ULTRASOUND DIAGNOSIS (ACR Appropriateness Criteria 2022 / Blaivas M et al., Acad Emerg Med 2001):",
    "Color Doppler absent/reduced flow: absence or marked reduction of flow in affected testis vs contralateral → cardinal finding; sensitivity 86-100%",
    "Whirlpool sign: twisted spermatic cord visible as spiral on ultrasound → pathognomonic of torsion",
    "Enlarged testis: diffuse enlargement, heterogeneous echogenicity (edema/hemorrhage) → edema from venous congestion",
    "Reactive hydrocele: fluid between layers of tunica vaginalis → frequent; nonspecific",
    "Scrotal wall thickening: increased cutaneous and subcutaneous thickness ipsilateral → reactive edema",
    "Enlarged epididymis: edematous and hypoechoic epididymis → associated venous congestion",
    "",
    "Testicular torsion timing & prognosis:",
    "< 6 hours: salvage rate > 90%",
    "6-12 hours: salvage rate ~50%",
    "> 24 hours: salvage rate < 10%",
    "SURGICAL EMERGENCY — do not delay for imaging if clinical suspicion is high",
    "",
    "BTS 2015 — INCIDENTAL PULMONARY NODULE GUIDELINES (Callister et al., Thorax 2015):",
    "SOLID NODULES:",
    "< 5 mm (< 80 mm³): no follow-up",
    "5-6 mm (80-300 mm³): CT at 1 year",
    "6-8 mm (300-500 mm³): CT at 3 and 12 months; consider PET if stable or growing",
    "> 8 mm (> 500 mm³): contrast-enhanced CT ± PET/CT ± biopsy",
    "SUBSOLID NODULES:",
    "GGN < 5 mm: no follow-up",
    "GGN ≥ 5 mm: CT at 3 months, then annual up to 4 years",
    "Part-solid (any size): CT at 3 months; if persistent, manage as suspicious",
    "",
    "INCIDENTAL THYROID NODULE (ACR 2015):",
    "Low sonographic risk: FNA if ≥ 2.5 cm; follow-up if 1.5-2.4 cm",
    "Moderate risk: FNA if ≥ 1.5 cm; follow-up if 1.0-1.4 cm",
    "High risk: FNA if ≥ 1.0 cm",
    "Suspicious features: microcalcifications, solid component, taller-than-wide, extrathyroidal extension",
    "Patient < 35 years: consider FNA at lower size thresholds",
    "",
    "MEDIASTINAL LYMPH NODE STATIONS (IASLC, Rusch et al., J Thorac Oncol 2009):",
    "Station 1: supraclavicular/low cervical — above clavicle, lower border of cricoid",
    "Station 2: upper paratracheal — between manubrium and trachea/BCT intersection",
    "Station 3a: prevascular — anterior to SVC and aorta | 3p: retrotracheal — posterior to trachea",
    "Station 4: lower paratracheal — 4R: between BCT and azygos; 4L: between BCT and carina",
    "Station 5: subaortic (AP window) — lateral to ligamentum arteriosum",
    "Station 6: para-aortic — anterior/lateral to ascending aorta",
    "Station 7: subcarinal — below carina, medial to both main bronchi",
    "Station 8: paraesophageal — adjacent to esophagus, below carina",
    "Station 9: pulmonary ligament — within inferior pulmonary ligament",
    "Station 10: hilar — adjacent to main bronchus and hilar vessels; 11-14: interlobar, lobar, segmental, subsegmental",
    "",
    "INCIDENTAL ADRENAL NODULES (ACR Incidental Findings Committee 2017):",
    "Homogeneous ≤ 10 HU, < 4 cm: benign adenoma — no follow-up",
    "Homogeneous > 10 HU, < 4 cm: CT washout or chemical shift MRI",
    "≥ 4 cm: consider biopsy/surgery; hormonal workup",
    "Heterogeneous, irregular, or growing: biopsy or resection; consider PET/CT",
    "",
    "GALLBLADDER POLYPS (Wiles et al., Radiology 2017 / ESG-ESGAR 2022):",
    "< 5 mm, no risk factors: no follow-up",
    "5-9 mm, no risk factors: US at 1 year, then every 2 years up to 5 years",
    "5-9 mm, with risk factors: US at 6 months, then annually up to 5 years",
    "≥ 10 mm: cholecystectomy",
    "Growth ≥ 2 mm on follow-up: surgical referral (cholecystectomy)",
    "Risk factors: age > 50, sessile polyp, PSC, Indian/Native American ethnicity, coexisting gallstones",
    "",
    "INCIDENTAL OVARIAN LESIONS (ACR 2020, Patel et al., JACR 2020):",
    "PREMENOPAUSAL:",
    "Simple cyst < 5 cm: physiologic — no follow-up",
    "Simple cyst 5-7 cm: US at 6-12 weeks",
    "Simple cyst > 7 cm: US or MRI",
    "Hemorrhagic cyst < 5 cm: US at 6-12 weeks",
    "Hemorrhagic cyst ≥ 5 cm: US or MRI at 6-12 weeks",
    "Complex lesion (any size): MRI or dedicated US; refer to gynecology",
    "POSTMENOPAUSAL:",
    "Simple cyst < 3 cm: no follow-up",
    "Simple cyst 3-7 cm: annual US",
    "Simple cyst > 7 cm: MRI or US + referral",
    "Complex lesion (any size): MRI or dedicated US; refer to gynecology",
    "",
    "ACUTE DIVERTICULITIS CLASSIFICATION (Hinchey/Modified):",
    "Stage 0: mild clinical — confined to colon wall",
    "Stage Ia: confined pericolic inflammation/phlegmon",
    "Stage Ib: confined pericolic abscess (< 4 cm)",
    "Stage II: pelvic, distant intra-abdominal, or retroperitoneal abscess",
    "Stage III: generalized purulent peritonitis",
    "Stage IV: generalized fecal peritonitis",
    "CT findings: uncomplicated = wall thickening + pericolic fat stranding | abscess = fluid collection with rim enhancement | perforation = free extraluminal air | fistula = tract to bladder/vagina | obstruction = stricture",
    "",
    "ACR BI-RADS BREAST DENSITY:",
    "A (almost entirely fatty): mammographic sensitivity ~85%",
    "B (scattered fibroglandular): sensitivity ~80%",
    "C (heterogeneously dense): sensitivity ~65%",
    "D (extremely dense): sensitivity ~50% — consider supplemental screening",
    "",
    "BREAST SCREENING BY RISK LEVEL (ACR):",
    "Average risk (no high-risk factors): annual mammography from age 40",
    "Intermediate risk (15-20% lifetime): annual mammography ± MRI per clinical judgment",
    "High risk (≥ 20% lifetime, BRCA, chest radiation ages 10-30): annual mammography + annual MRI from age 25-30",
    "",
    "BI-RADS US LEXICON:",
    "Shape: benign = oval/round; suspicious = irregular",
    "Orientation: benign = parallel (wider than tall); suspicious = not parallel (taller than wide)",
    "Margins: benign = circumscribed; suspicious = spiculated/angular/microlobulated",
    "Echogenicity: benign = anechoic/hyperechoic; suspicious = complex hypoechoic",
    "Posterior features: benign = no shadowing/posterior enhancement; suspicious = posterior acoustic shadowing",
    "",
    "BREAST IMPLANT COMPLICATIONS (ACR):",
    "Intact implant: routine follow-up; MRI at 5-6 years post-placement and every 2-3 years",
    "Intracapsular rupture: linguine sign, keyhole sign; silicone within capsule → elective surgery",
    "Extracapsular rupture: silicone outside capsule, may migrate → surgical explantation recommended",
    "Capsular contracture: Baker I-IV; Baker III-IV → consider capsulectomy/replacement",
    "BIA-ALCL: late seroma > 1 year → aspirate for cytology with CD30; refer to oncology",
    "",
    "CEREBRAL VASCULAR TERRITORIES:",
    "ACA: medial frontal lobe, cingulate, anterior corpus callosum",
    "MCA superior division: lateral frontal cortex, anterior parietal, insula",
    "MCA inferior division: lateral temporal cortex, posterior parietal, angular gyrus",
    "MCA lenticulostriate perforators: basal ganglia (putamen, globus pallidus, caudate), internal capsule",
    "PCA: occipital lobe, medial inferior temporal, thalamus (perforators)",
    "Basilar perforators: central pons, midbrain",
    "PICA: posteroinferior cerebellum, dorsolateral medulla (Wallenberg)",
    "AICA: anteroinferior cerebellum, lateral pons, inner ear",
    "SCA: superior cerebellum, superior cerebellar peduncles",
    "",
    "CEREBRAL ANEURYSM — MANAGEMENT BY SIZE (AHA/ASA 2015 / ISUIA 2003):",
    "< 3 mm: generally observation if asymptomatic; follow-up in 1-3 years",
    "3-6 mm anterior: imaging follow-up; treat if risk factors (smoking, HTN, family history)",
    "3-6 mm posterior: consider treatment; higher rupture risk than anterior",
    "7-12 mm: treatment generally recommended (endovascular or surgical)",
    "13-24 mm: high rupture risk; treatment recommended",
    "≥ 25 mm (giant): very high risk; urgent treatment required",
    "",
    "MODIFIED FISHER SCALE (SAH vasospasm risk):",
    "Grade 0: no SAH or IVH — low vasospasm risk",
    "Grade 1: focal or diffuse thin SAH (< 1 mm) without IVH — low risk",
    "Grade 2: focal or diffuse thin SAH with IVH — moderate risk",
    "Grade 3: thick cisternal clot (≥ 1 mm) without IVH — high risk",
    "Grade 4: thick cisternal clot with IVH — very high risk",
    "",
    "BRAIN TUMORS — WHO 2021 CNS GRADES:",
    "Grade 1: meningioma (grade I), pilocytic astrocytoma, schwannoma",
    "Grade 2: diffuse astrocytoma, oligodendroglioma, atypical meningioma",
    "Grade 3: anaplastic astrocytoma, anaplastic oligodendroglioma, anaplastic meningioma",
    "Grade 4: glioblastoma, DIPG, medulloblastoma, atypical teratoid/rhabdoid tumor",
    "",
    "CT BRAIN PERFUSION (CTP):",
    "Parameters: CBF (cerebral blood flow), CBV (cerebral blood volume), MTT (mean transit time), TTP (time to peak, bilaterally symmetric), Tmax (max time residue function)",
    "Ischemic core: ↓↓CBF + ↓↓CBV → irreversible infarct",
    "Ischemic penumbra: ↓CBF + preserved CBV → at-risk tissue, potentially salvageable",
    "Benign oligemia: mildly ↓CBF + normal CBV → mild hypoperfusion, no infarct risk",
    "DAWN trial (6-24h): clinical-imaging mismatch: NIHSS ≥10 + core <21-51 mL by age",
    "DEFUSE trial (6-16h): perfusion mismatch: penumbra/core ≥1.8, core <70 mL, Tmax>6s vol <180 mL",
    "",
    "COMPLEX INFARCT SYNDROMES:",
    "Wallenberg (PICA/lat. medulla): ipsi Horner + facial hypoesthesia / contra thermoalgesia",
    "Dejerine (medial medulla): ipsi tongue deviation + contra hemiparesis + contra proprioceptive loss",
    "Weber (ventral midbrain): ipsi CN III palsy + contra hemiparesis",
    "Claude (dorsal midbrain): ipsi CN III palsy + contra ataxia/tremor (no hemiparesis)",
    "Benedikt (midbrain tegmentum): ipsi CN III palsy + contra involuntary movements ± hemiparesis",
    "Millard-Gubler (ventral pons): ipsi CN VI and VII palsy + contra hemiparesis",
    "Foville (dorsal pons): ipsi conjugate gaze palsy + ipsi facial palsy + contra hemiparesis",
    "Locked-in (bilateral ventral pons): quadriplegia + anarthria; only vertical eye movements preserved",
    "Artery of Percheron: bilateral paramedian thalamic DWI ± V-sign midbrain FLAIR → decreased consciousness + vertical gaze palsy",
    "Top-of-basilar: bilateral thalami/midbrain/occipital/superior cerebellum DWI → coma + visual deficits + ophthalmoplegia",
    "Cortical watershed: parasagittal ACA/MCA or temporo-occipital MCA/PCA → systemic hypotension / carotid stenosis",
    "Deep watershed: corona radiata chain parallel to ventricle → microembolism + carotid stenosis",
    "Olivary hypertrophy: T2 hyperintense enlarged inferior olive (Guillain-Mollaret triangle) → appears ~1 month post-insult",
    "Wallerian degeneration: T2 hyperintense ipsilateral cerebral peduncle/pons → weeks-months post infarct",
    "",
    "DEMYELINATING DISEASES:",
    "MS: ovoid periventricular plaques, Dawson fingers, central vein sign, open ring enhancement; DIS: ≥1 T2 in ≥2 of 5 regions (periventricular, juxtacortical, infratentorial, spinal, optic nerve)",
    "McDonald 2024: DIT via simultaneous enhancing+non-enhancing or CSF OCBs; CVS (≥5 lesions with central vein) 98% specificity; PRL (paramagnetic rim) ~100% specificity",
    "NMOSD (Devic): LETM ≥3 segments (central cord), area postrema lesion, AQP4-IgG+; LETM + area postrema = pathognomonic",
    "MOGAD: fluffy cortical lesions, conus H-sign, bilateral anterior optic neuritis with perineural enhancement",
    "ADEM: large bilateral poorly defined WM lesions, thalamic/BG involvement, simultaneous enhancement, monophasic post-infectious",
    "PML: asymmetric subcortical WM involving U-fibers, no mass effect, no enhancement, DWI at advancing edge; immunocompromised (HIV, natalizumab)",
    "Osmotic demyelination: T2 trident sign in central pons sparing periphery; rapid Na+ correction",
    "Marchiafava-Bignami: T2/FLAIR in central corpus callosum (sandwich sign); chronic alcoholism",
    "Baló concentric sclerosis: alternating concentric T2 rings (bullseye); aggressive MS variant",
    "SUSAC: central callosal snowball lesions; triad = encephalopathy + branch retinal artery occlusion + sensorineural hearing loss",
    "",
    "NEURODEGENERATIVE DISEASES:",
    "Alzheimer: medial temporal/hippocampal atrophy; Scheltens MTA ≥1 (<75y), ≥2 (≥75y); dilated temporal horns",
    "FTD behavioral: bilateral frontal + anterior temporal atrophy with posterior sparing",
    "FTD semantic: temporal pole knife-blade atrophy, usually left-predominant → loss of word meaning",
    "FTD nonfluent: left perisylvian (posterior frontoinsular) atrophy → agrammatic speech",
    "Lewy body: preserved hippocampi (unlike AD) + visual hallucinations + parkinsonism",
    "Parkinson: loss of swallow tail sign (nigrosome-1) on SWI 3T; Se ~100%, Sp ~95%",
    "MSA-C: hot cross bun sign in pons (T2) + cerebellar/peduncular atrophy; Sp 97%",
    "MSA-P: lateral putaminal T2 hyperintense rim + putaminal atrophy; poor L-dopa response",
    "PSP: hummingbird sign (sagittal midbrain atrophy); morning glory sign (axial); midbrain/pons ratio <0.15; early falls",
    "CBD: asymmetric frontoparietal atrophy contralateral to clinical side; alien limb",
    "Huntington: caudate atrophy (box-car ventricles); bilateral; CAG ≥36",
    "ALS: bilateral corticospinal tract T2 hyperintensity (PLIC, corona radiata); motor band sign on SWI",
    "CJD: cortical ribboning on DWI + caudate/putamen DWI restriction; bilateral pulvinar = vCJD (Sp 98%); rapid dementia",
    "Normal pressure hydrocephalus: Evans index >0.3, DESH pattern (dilated Sylvian + tight convexity), callosal angle <90°; triad = gait + dementia + incontinence",
    "",
    "NECK ANATOMY — SPACES & LYMPH NODE STATIONS:",
    "Pharyngeal mucosal: mucosa, Waldeyer ring, constrictors → SCC, lymphoma, abscess",
    "Parapharyngeal: fat, V3 branches → displaced by adjacent masses; lipoma, sarcoma",
    "Masticator: masseter, pterygoids, mandible, V3 → odontogenic abscess, perineural V3",
    "Parotid: parotid gland, VII, retromandibular vein → pleomorphic adenoma, Warthin, mucoepidermoid",
    "Carotid: ICA, IJV, CN IX-XII, sympathetic chain → paraganglioma, schwannoma, metastatic LN",
    "Retropharyngeal: Rouvière nodes, fat → retropharyngeal abscess, metastatic LN",
    "Prevertebral: muscles, vertebral body → spondylodiscitis, metastasis, chordoma",
    "Posterior cervical: fat, XI, level V nodes → lymphadenopathy, lipoma, lymphoma",
    "Lymph node levels: Ia (submental), Ib (submandibular), IIa/b (upper jugular), III (middle jugular), IV (lower jugular), Va/b (posterior triangle), VI (central), VII (superior mediastinum)",
    "Pharynx: nasopharynx (torus tubarius, Rosenmüller fossa), oropharynx (tonsils, tongue base), hypopharynx (pyriform sinuses)",
    "Larynx: supraglottis (epiglottis, false cords), glottis (true vocal cords), subglottis (below cords → inferior cricoid)",
    "",
    "MRI SHOULDER ANATOMY:",
    "Rotator cuff: supraspinatus (greater tuberosity sup. facet, coronal T2 FS), infraspinatus (middle facet, axial/coronal T2 FS), subscapularis (lesser tuberosity, axial T2 FS), teres minor (inferior facet, coronal/sagittal T2 FS)",
    "Labrum: anterior + IGHL/MGHL, posterior, superior (SLAP) + biceps; best = axial T1 FS with MR arthrography",
    "",
    "ROTATOR CUFF CLASSIFICATIONS:",
    "Partial tears (Ellman): Grade 1 (minimal fraying), Grade 2 (up to 50% thickness), Grade 3 (> 50% without full disruption)",
    "Full-thickness by size: small (< 1 cm), medium (1-3 cm), large (3-5 cm), massive (> 5 cm)",
    "Retraction (Patte): Stage 1 (stump proximal to insertion), Stage 2 (at humeral head), Stage 3 (at/medial to glenoid)",
    "Fatty infiltration (Goutallier): 0 (normal), 1 (minimal streaks), 2 (fat < muscle), 3 (fat = muscle), 4 (fat > muscle)",
    "",
    "MRI KNEE ANATOMY:",
    "Menisci: medial (C-shaped), lateral (O-shaped); low T1/T2 signal",
    "Meniscal signal grades: I (globular intrameniscal, no tear), II (linear intrameniscal, no tear), III (signal reaching articular surface = tear)",
    "Ligaments: ACL (sagittal T2 FS/coronal), PCL (sagittal T2), MCL (coronal T2 FS), LCL (coronal T2 FS)",
    "Cartilage: coronal/sagittal PD FS — Outerbridge grades I-IV",
    "",
    "MRI ANKLE ANATOMY:",
    "Tendons: Achilles (posterior, no synovial sheath), tibialis posterior (posteromedial), FDL (posteromedial), FHL (posterior between talar tubercles), peroneus longus/brevis (posterolateral), tibialis anterior (anteromedial)",
    "Ligaments: ATFL, CFL, PTFL (lateral), deltoid (medial); best: axial/coronal T2 FS",
    "Medial mnemonic (ant→post): Tom, Dick ANd Harry = Tib. post., FDL, Artery/Nerve, FHL",
    "",
    "MRI THIGH & LEG — AXIAL ANATOMY:",
    "Thigh anterior: quadriceps + sartorius → femoral n. (L2-L4)",
    "Thigh medial: adductors + gracilis + pectineus → obturator n. (L2-L4)",
    "Thigh posterior: semimembranosus, semitendinosus, biceps femoris → sciatic n. (L4-S3)",
    "Leg anterior: tibialis ant., EHL, EDL → deep peroneal n.",
    "Leg lateral: peroneus longus/brevis → superficial peroneal n.",
    "Leg deep posterior: tibialis post., FDL, FHL → tibial n.",
    "Leg superficial posterior: gastrocnemius, soleus, plantaris → tibial n.",
    "",
    "BONE TUMORS DIAGNOSTIC CHEAT SHEET:",
    "By age: 0-10y benign = simple bone cyst, eosinophilic granuloma; malignant = Ewing, neuroblastoma mets",
    "10-30y benign = osteochondroma, enchondroma, GCT, ABC; malignant = osteosarcoma, Ewing",
    "30-40y benign = enchondroma, GCT, vertebral hemangioma; malignant = chondrosarcoma, bone lymphoma",
    "> 40y benign = hemangioma, enchondroma; malignant = metastasis, myeloma, chondrosarcoma",
    "By location: epiphysis = chondroblastoma, GCT; metaphysis = osteochondroma, osteosarcoma; diaphysis = Ewing, fibrous dysplasia",
    "Matrix: chondroid (arcs/rings) = enchondroma/chondrosarcoma; osteoid (dense, cloud-like) = osteosarcoma; ground-glass = fibrous dysplasia",
    "Periosteal reaction: solid/thick = benign/slow; lamellated (onion-skin) = Ewing/osteomyelitis; sunburst = osteosarcoma/metastasis",
    "",
    "VERTEBRAL FRACTURES CLASSIFICATIONS:",
    "Genant: G0 (normal), G1 (mild, 20-25% height loss), G2 (moderate, 25-40%), G3 (severe, >40% / vertebra plana)",
    "AO Spine: A0 (minor, spinous/transverse), A1 (compression one endplate), A2 (split fracture), A3 (incomplete burst), A4 (complete burst both endplates)",
    "AO Spine B: B1 (Chance fracture), B2 (PLC disruption), B3 (anterior hyperextension through disc)",
    "AO Spine C: translation/rotation injury — any A or B + displacement in any plane",
    "",
    "WHOLE AORTA CTA — MEASUREMENT LANDMARKS:",
    "Root (sinuses of Valsalva): max sinus-to-sinus (double oblique)",
    "STJ: junction between sinuses and tubular ascending",
    "Mid-ascending: at PA bifurcation level",
    "Proximal arch: origin of brachiocephalic trunk",
    "Mid-arch: between left CCA and left subclavian",
    "Isthmus: distal to left subclavian origin",
    "Descending: at left atrium/carina level",
    "Suprarenal/infrarenal: above/below renal arteries",
    "Key findings checklist: root/ascending (diameters, ectasia, BAV, dissection) | arch (variants, great vessel stenosis, coarctation) | descending (atheroma, ulcer, IMH, endograft) | abdominal (celiac/SMA/renal stenosis) | iliac (aneurysm, stenosis) | wall (calcification, thrombus, thickening, aortitis)",
    "",
    "PEDIATRIC CHEST X-RAY:",
    "Normal thymus: sail sign, wave sign (< 2 years); absent in neonato = consider DiGeorge",
    "RDS (HMD): diffuse ground-glass, air bronchograms, low volume (preterm)",
    "TTN: cisural fluid, mild cardiomegaly, hyperinflation, resolves 24-48h (term, C-section)",
    "MAS: hyperinflation, patchy atelectasis, pneumothorax risk (post-term)",
    "Bronchiolitis (< 2 years, RSV): hyperinflation, peribronchial thickening, subsegmental atelectasis",
    "Round pneumonia (< 8 years): round opacity simulating mass, lower lobes",
    "Foreign body (1-3 years): unilateral air trapping on expiration, obstructive emphysema",
    "Cardiothoracic ratio: < 0.60 neonates, < 0.55 > 1 year",
    "",
    "PEDIATRIC HYDRONEPHROSIS:",
    "SFU grading: 1 (mild pelvis dilation), 2 (pelvis + some calices), 3 (pelvis + all calices, normal parenchyma), 4 (severe + parenchymal thinning)",
    "Renal pelvis APD prenatal: 2nd trimester normal < 4 mm, mild 4-7, moderate 7-10, severe > 10 mm",
    "3rd trimester normal < 7 mm, mild 7-10, moderate 10-15, severe > 15 mm",
    "Neonatal/postnatal normal < 10 mm, mild 10-15, moderate 15-20, severe > 20 mm",
    "UTD classification: P1 (low risk, no caliceal dilation), P2 (intermediate, caliceal dilation), P3 (high risk, abnormal parenchyma)",
    "",
    "PEDIATRIC TUMORS BY AGE:",
    "< 1 year: neuroblastoma (suprarenal, crosses midline, calcifications 90%, encases vessels), sacrococcygeal teratoma (mixed solid-cystic)",
    "1-5 years: Wilms (intrarenal, pseudocapsule, renal vein/IVC thrombus), hepatoblastoma (solid heterogeneous, elevated AFP), rhabdomyosarcoma (head/neck/GU, invasive)",
    "5-10 years: lymphoma (anterior mediastinal mass, sandwich pattern), posterior fossa tumors (medulloblastoma = vermis, ependimoma = exits 4V foramina)",
    "> 10 years: osteosarcoma (metaphysis, sunburst, Codman triangle), Ewing (diaphysis, onion-skin periosteal), germ cell tumors (mediastinum/gonads/pineal)",
    "Key DDx: neuroblastoma vs Wilms: NB crosses midline + encases vessels; Wilms displaces vessels + pseudocapsule",
    "",
    "CRYPTORCHIDISM — ULTRASOUND (AUA/EAU Guidelines):",
    "Canalicular (72%): testis between internal and external inguinal ring",
    "Inguinal superficial (20%): superficial to external ring, ectopic",
    "Abdominal (8%): not visible on US; requires MRI or laparoscopy",
    "Prescrotal: upper scrotum, retractile testis",
    "Measurement: volume = L × W × AP × 0.52; atrophy if < 50% of contralateral",
    "Malignancy risk: undescended testis = 5-10× risk of testicular tumor; seminoma most common",
    "",
    "TRANSFONTANELLAR US — NEONATAL BRAIN (Papile et al., J Pediatr 1978):",
    "Germinal matrix hemorrhage (Papile): Grade I (subependymal only), Grade II (IVH < 50% ventricle, no dilation), Grade III (IVH > 50% + ventricular dilation, hydrocephalus 50-80%), Grade IV (intraparenchymal hemorrhagic infarct, severe sequelae)",
    "Periventricular leukomalacia (de Vries): Grade I (transient periventricular echogenicity < 7 days), Grade II (persistent > 7 days, small frontoparietal cysts), Grade III (extensive cysts fronto-parieto-occipital), Grade IV (diffuse subcortical cysts + porencephaly)",
    "Reference measurements: ventricular index (Levene) < 13 mm at term; frontal horn width < 3 mm; ventricle/hemisphere ratio < 0.35; 3rd ventricle < 3 mm",
  ].join("\n");
}
