import { DEFAULT_TEMPLATES } from "./templates";

export interface NormalityDefault {
  modality: string;
  section_label: string;
  phrase: string;
}

const SKIP_LABELS = new Set([
  "clinical indication", "clinical context", "indication",
  "radiotracer", "image quality", "comments",
  "recist 1.1 response assessment", "target lesions", "non-target lesions", "new lesions",
  "clinical data", "procedure details", "procedure", "outcome", "complications", "operators",
  "gestational age", "sex", "chronological age",
  "bone age estimation", "bone development assessment",
  "alpha angle", "beta angle",
  "bowel preparation and distension quality",
  "perfusion parameters",
]);

const NUMBERED_LABEL = /^\d+\.\s/;

function shouldSkip(label: string): boolean {
  const lower = label.toLowerCase();
  if (SKIP_LABELS.has(lower)) return true;
  if (NUMBERED_LABEL.test(label)) return true;
  return false;
}

export function extractSectionsFromTemplates(): { modality: string; label: string }[] {
  const seen = new Set<string>();
  const result: { modality: string; label: string }[] = [];

  for (const t of DEFAULT_TEMPLATES) {
    if (t.technique === "Procedures") continue;
    const re = /\*{2,3}([^*]+)\*{2,3}(?::?\s*\{[^}]+\})/g;
    let m;
    while ((m = re.exec(t.template)) !== null) {
      const label = m[1].trim();
      if (shouldSkip(label)) continue;
      const key = `${t.technique}|${label.toLowerCase()}`;
      if (seen.has(key)) continue;
      seen.add(key);
      result.push({ modality: t.technique, label });
    }
  }

  result.sort((a, b) => a.modality.localeCompare(b.modality) || a.label.localeCompare(b.label));
  return result;
}

const GENERIC_CT = "No significant abnormalities.";
const GENERIC_MRI = "No significant abnormalities.";
const GENERIC_US = "Normal appearance.";
const GENERIC_XRAY = "No significant abnormalities.";
const GENERIC_MAMMO = "No significant findings.";

const MODALITY_GENERIC: Record<string, string> = {
  CT: GENERIC_CT,
  MRI: GENERIC_MRI,
  Ultrasound: GENERIC_US,
  XRay: GENERIC_XRAY,
  Mammography: GENERIC_MAMMO,
};

const DEFAULTS: Record<string, Record<string, string>> = {
  CT: {
    "Liver": "Normal in size, morphology and density. No focal lesions.",
    "Spleen": "Normal in size and density. No focal lesions.",
    "Pancreas": "Normal in size, morphology and density. No pancreatic duct dilation.",
    "Gallbladder": "Normal. No gallstones or wall thickening.",
    "Bile ducts": "No intrahepatic or extrahepatic biliary dilation.",
    "Kidneys": "Normal in size and morphology bilaterally. No hydronephrosis or focal lesions.",
    "Kidneys and ureters": "Normal in size and morphology bilaterally. No hydronephrosis. Ureters not dilated.",
    "Adrenal glands": "Normal in size and morphology bilaterally.",
    "Bladder": "Normal distension and wall thickness. No intraluminal lesions.",
    "Portal vein and hepatic artery": "Patent portal vein and hepatic artery. Normal caliber.",
    "Peritoneum and retroperitoneum": "No free fluid or lymphadenopathy.",
    "Peritoneum, retroperitoneum": "No free fluid or lymphadenopathy.",
    "Stomach": "Normal gastric wall. No wall thickening.",
    "Small bowel and colon": "Normal caliber. No wall thickening or obstruction.",
    "Small bowel loops and colon": "Normal caliber. No wall thickening or obstruction.",
    "Other pelvic structures": "No significant pelvic abnormalities.",
    "Lung parenchyma": "No pulmonary nodules, consolidations or ground-glass opacities. Normal lung parenchyma.",
    "Mediastinal lymph nodes": "No pathologically enlarged mediastinal lymph nodes.",
    "Mediastinum": "No pathologically enlarged mediastinal lymph nodes. Normal mediastinal structures.",
    "Trachea and bronchi": "Normal caliber. No endoluminal lesions.",
    "Esophagus": "Normal caliber. No wall thickening.",
    "Coronary arteries": "No significant coronary calcifications.",
    "Aorta and pulmonary artery": "Normal caliber of the aorta and pulmonary artery. No aneurysm or dissection.",
    "Heart and pericardium": "Normal heart size. No pericardial effusion.",
    "Pleura": "No pleural effusion or thickening.",
    "Pleura and diaphragm": "No pleural effusion. Normal diaphragm position.",
    "Diaphragm": "Normal position and morphology.",
    "Supradiaphragmatic tissues and thyroid": "No significant supradiaphragmatic abnormalities. Thyroid within normal limits.",
    "Thoracic wall": "No thoracic wall abnormalities.",
    "Thoracic wall and bone structures": "No thoracic wall or bone abnormalities.",
    "Spine": "No acute vertebral fractures or significant degenerative changes.",
    "Bone structures": "No acute fractures or suspicious bone lesions.",
    "Bone structures and included portions of the thorax": "No acute fractures or suspicious bone lesions. No significant thoracic abnormalities.",
    "Bone density": "Normal bone density.",
    "Soft tissues": "No significant soft tissue abnormalities.",
    "Included portions of the abdomen": "No significant abnormalities in the included portions of the abdomen.",
    "Supratentorial brain parenchyma": "Normal supratentorial brain parenchyma. No mass lesions, hemorrhage or acute ischemic changes.",
    "Infratentorial brain parenchyma": "Normal infratentorial brain parenchyma. No mass lesions in the posterior fossa.",
    "Extra-axial spaces and midline": "No extra-axial collections. Midline structures in normal position.",
    "Extra-axial spaces": "No extra-axial collections.",
    "Skull and extracranial soft tissues": "No calvarial fractures. Extracranial soft tissues unremarkable.",
    "Included portions of the cervical spine and vascular structures": "No acute cervical spine abnormalities. Vascular structures unremarkable.",
    "Brain parenchyma": "Normal brain parenchyma. No mass lesions, hemorrhage or acute ischemic changes.",
    "Ventricular system": "Normal size and morphology of the ventricular system.",
    "Other extra-axial spaces": "No extra-axial collections.",
    "Sinuses": "Normal paranasal sinuses.",
    "Cervical soft tissues": "No significant cervical soft tissue abnormalities.",
    "Cervical vascular structures": "Normal caliber of cervical vascular structures. No significant stenosis.",
    "Cervical lymph nodes": "No pathologically enlarged cervical lymph nodes.",
    "Nasopharynx": "Normal nasopharyngeal mucosa.",
    "Oropharynx": "Normal oropharyngeal structures.",
    "Parotids": "Normal parotid glands bilaterally.",
    "Submandibular glands": "Normal submandibular glands bilaterally.",
    "Vocal cords": "Symmetric vocal cords.",
    "Piriform sinuses": "Normal piriform sinuses.",
    "Epiglottis": "Normal epiglottis.",
    "Trachea": "Normal tracheal caliber and morphology.",
    "Parapharyngeal space": "Normal parapharyngeal spaces.",
    "Vascular space": "No vascular abnormalities.",
    "Salivary glands": "Normal salivary glands.",
    "Willis polygon": "Normal circle of Willis. No aneurysms.",
    "Ascending aorta": "Normal caliber ascending aorta.",
    "Aortic arch": "Normal aortic arch and branch vessels.",
    "Descending aorta": "Normal caliber descending aorta.",
    "Thoracic aorta": "Normal caliber thoracic aorta. No aneurysm or dissection.",
    "Abdominal aorta": "Normal caliber abdominal aorta. No aneurysm.",
    "Iliac arteries": "Normal caliber iliac arteries. No significant stenosis.",
    "Renal arteries": "Normal caliber renal arteries bilaterally.",
    "Celiac trunk and mesenteric arteries": "Normal caliber celiac trunk and mesenteric arteries.",
    "Other thoracic structures": "No additional thoracic abnormalities.",
    "Other thoracic and abdominal structures": "No additional thoraco-abdominal abnormalities.",
    "Other intraabdominal structures": "No additional intraabdominal abnormalities.",
    "Intraabdominal solid organs": "Normal intraabdominal solid organs.",
    "Other mediastinal findings": "No additional mediastinal abnormalities.",
    "Gallbladder and bile ducts": "Normal gallbladder. No biliary dilation.",
    "Stomach and bowel": "Normal gastric and bowel wall. No obstruction.",
    "Abdominal aorta and iliac arteries": "Normal caliber abdominal aorta and iliac arteries.",
    "Bone structures and soft tissues": "No acute fractures or significant soft tissue abnormalities.",
    "Nasopharynx, oropharynx and larynx": "Normal pharyngeal and laryngeal structures.",
    "Vascular structures": "No vascular abnormalities.",
    "Femur": "No fracture or bone lesion.",
    "Tibia": "No fracture or bone lesion.",
    "Patella": "No fracture or bone lesion.",
    "Joint space": "Normal joint space. No effusion.",
    "Tibia and fibula": "No fracture.",
    "Talus": "No fracture or bone lesion.",
    "Calcaneus": "No fracture.",
    "Ankle joint": "Normal ankle joint. No effusion.",
    "Superficial and deep femoral arteries": "Normal caliber. No significant stenosis or occlusion.",
    "Popliteal artery": "Normal caliber. No significant stenosis.",
    "Tibialis and peroneal arteries": "Patent tibial and peroneal arteries.",
    "Distal arteries of the dorsal and plantar aspect of the foot": "Patent distal arteries.",
  },
  MRI: {
    "Liver": "Normal in size, morphology and signal intensity. No focal lesions.",
    "Liver and spleen": "Normal in size, morphology and signal intensity. No focal lesions.",
    "Spleen": "Normal in size and signal intensity.",
    "Pancreas": "Normal in size, morphology and signal intensity. No pancreatic duct dilation.",
    "Gallbladder": "Normal. No gallstones or wall thickening.",
    "Gallbladder and bile ducts": "Normal gallbladder. No biliary dilation.",
    "Bile ducts": "No intrahepatic or extrahepatic biliary dilation.",
    "Intrahepatic and extrahepatic biliary ducts": "No intrahepatic or extrahepatic biliary dilation. Normal common bile duct caliber.",
    "Kidneys": "Normal in size, morphology and signal intensity bilaterally. No hydronephrosis or focal lesions.",
    "Adrenal glands": "Normal in size and signal intensity bilaterally.",
    "Adrenal glands and kidneys": "Normal adrenal glands and kidneys bilaterally. No focal lesions.",
    "Bladder": "Normal distension and wall thickness.",
    "Portal vein and hepatic artery": "Patent portal vein and hepatic artery. Normal caliber.",
    "Peritoneum and retroperitoneum": "No free fluid or lymphadenopathy.",
    "Peritoneum retroperitoneum": "No free fluid or lymphadenopathy.",
    "Peritoneum, retroperitoneum": "No free fluid or lymphadenopathy.",
    "Peritoneum": "No free fluid.",
    "Stomach": "Normal gastric wall.",
    "Small bowel and colon": "Normal caliber. No wall thickening.",
    "Small bowel loops and colon": "Normal caliber. No wall thickening.",
    "Other pelvic structures": "No significant pelvic abnormalities.",
    "Other intraabdominal structures": "No additional intraabdominal abnormalities.",
    "Supratentorial brain parenchyma": "Normal supratentorial brain parenchyma. Normal signal intensity. No mass lesions, restricted diffusion or abnormal enhancement.",
    "Infratentorial brain parenchyma": "Normal infratentorial brain parenchyma. No mass lesions in the posterior fossa.",
    "Extra-axial spaces and midline": "No extra-axial collections. Midline structures in normal position.",
    "Extra-axial space": "No extra-axial collections.",
    "Skull and extracranial soft tissues": "No calvarial abnormalities. Extracranial soft tissues unremarkable.",
    "Included portions of the cervical spine and vascular structures": "No acute cervical spine abnormalities. Vascular structures unremarkable.",
    "Cervical spine": "Normal cervical alignment. No marrow signal abnormalities.",
    "Vertebral bodies": "Normal vertebral body height, alignment and marrow signal.",
    "Intervertebral spaces and discs": "Normal intervertebral disc height and signal intensity. No significant disc herniation.",
    "Intervertebral discs": "Normal disc height and signal intensity. No significant herniation.",
    "Ligaments": "Normal ligamentous structures.",
    "Spinal cord": "Normal spinal cord signal and morphology.",
    "Soft tissues": "No significant soft tissue abnormalities.",
    "Soft tissues and associated structures": "No significant soft tissue abnormalities.",
    "Bone structures": "No bone marrow signal abnormalities or fractures.",
    "Bone structures and periprostatic tissues": "No suspicious bone lesions. Normal periprostatic tissues.",
    "Meniscus": "Normal meniscal morphology and signal. No tears.",
    "Ligaments and tendons": "Normal ligamentous and tendinous structures. No tears.",
    "Ligaments and syndesmosis": "Normal ligaments and syndesmosis. No tears.",
    "Joints": "Normal joint surfaces. No effusion.",
    "Bones": "No fractures or bone marrow edema.",
    "Tendons": "Normal tendinous structures. No tears or tendinopathy.",
    "Tendons and muscles": "Normal tendons and muscles. No tears.",
    "Cartilage and articular surfaces": "Normal cartilage thickness and articular surfaces.",
    "Nerves": "Normal course and signal of visualized nerves.",
    "Supraspinatus tendon": "Normal supraspinatus tendon. No tear or tendinopathy.",
    "Infraspinatus tendon": "Normal infraspinatus tendon. No tear.",
    "Subscapularis tendon": "Normal subscapularis tendon. No tear.",
    "Teres minor tendon": "Normal teres minor tendon.",
    "Biceps tendon": "Normal long head of biceps tendon in the bicipital groove.",
    "Subacromial subdeltoid bursa": "No subacromial subdeltoid bursitis.",
    "Glenohumeral joint": "Normal glenohumeral joint. No effusion.",
    "Labrum": "Normal labral morphology and signal.",
    "Acromioclavicular joint": "Normal acromioclavicular joint.",
    "Humerus": "Normal humeral head. No bone marrow edema.",
    "Scapula": "Normal scapula.",
    "Other findings": "No additional findings.",
    "Carpal bones": "Normal carpal bones. No fractures or avascular necrosis.",
    "Distal radius and ulna": "Normal distal radius and ulna.",
    "Carpal tunnel": "Normal carpal tunnel contents. No median nerve compression.",
    "Temporomandibular joint": "Normal temporomandibular joint. Normal disc position.",
    "Masticatory muscles": "Normal masticatory muscles.",
    "Retrodiscal space": "Normal retrodiscal tissue.",
    "Mandible and temporal bone": "Normal mandible and temporal bone.",
    "Nasopharynx": "Normal nasopharyngeal mucosa.",
    "Oropharynx": "Normal oropharyngeal structures.",
    "Parotids": "Normal parotid glands bilaterally.",
    "Submandibular glands": "Normal submandibular glands bilaterally.",
    "Vocal cords": "Symmetric vocal cords.",
    "Piriform sinuses": "Normal piriform sinuses.",
    "Epiglottis": "Normal epiglottis.",
    "Trachea": "Normal tracheal caliber.",
    "Parapharyngeal space": "Normal parapharyngeal spaces.",
    "Vascular space": "No vascular abnormalities.",
    "Cervical lymph nodes": "No pathologically enlarged cervical lymph nodes.",
    "Vascular structures": "No vascular abnormalities.",
    "Lymph nodes": "No pathologically enlarged lymph nodes.",
    "Lymph nodes or adenopathy": "No pathologically enlarged lymph nodes.",
    "General prostate assessment": "Normal prostate size and morphology. No suspicious focal lesions.",
    "Peripheral zone": "Normal peripheral zone signal. No suspicious focal lesions (PI-RADS 1).",
    "Transition zone": "Normal transition zone. No suspicious focal lesions.",
    "Seminal vesicles": "Normal seminal vesicles bilaterally.",
    "Uterus": "Normal uterine size, morphology and signal.",
    "Endometrium": "Normal endometrial thickness and signal.",
    "Cervix": "Normal cervical morphology and signal.",
    "Ovaries": "Normal ovaries bilaterally. No adnexal masses.",
    "Fallopian tubes": "Fallopian tubes not dilated.",
    "Rectum and sigmoid": "Normal rectal and sigmoid wall.",
    "Rectum": "Normal rectal wall. No mural thickening.",
    "Mesorectum": "Normal mesorectal fat. No suspicious lymph nodes.",
    "Mesorectal fascia": "Intact mesorectal fascia.",
    "Perianal soft tissues": "Normal perianal soft tissues. No fistula tract or abscess.",
    "Sphincters": "Normal internal and external sphincters.",
    "Other perineal structures": "No significant perineal abnormalities.",
  },
  Ultrasound: {
    "Liver": "Normal in size, echogenicity and echotexture. No focal lesions.",
    "Spleen": "Normal in size and echogenicity.",
    "Pancreas": "Normal in size and echogenicity. Visualized portions unremarkable.",
    "Gallbladder": "Normal. No gallstones or wall thickening.",
    "Bile ducts": "No intrahepatic or extrahepatic biliary dilation.",
    "Kidneys": "Normal in size, morphology and echogenicity bilaterally. Normal corticomedullary differentiation. No hydronephrosis.",
    "Bladder": "Normal distension and wall thickness.",
    "Portal vein and hepatic artery": "Patent portal vein with hepatopetal flow. Normal caliber.",
    "Peritoneum and retroperitoneum": "No free fluid.",
    "Other pelvic structures": "No significant pelvic abnormalities.",
    "General thyroid assessment": "Normal thyroid gland in size and echogenicity. No nodules.",
    "Cervical lymph nodes": "No pathologically enlarged cervical lymph nodes.",
    "Other structures": "No additional abnormalities.",
    "Breast parenchyma": "Normal breast parenchyma. No suspicious masses.",
    "Ductal system": "No ductal dilation.",
    "Lymph nodes": "No pathologically enlarged lymph nodes.",
    "Skin and subcutaneous tissues": "Normal skin and subcutaneous tissues.",
    "Other findings": "No additional findings.",
    "Ventricular size": "Normal ventricular size.",
    "Cortical structure": "Normal cortical structure and sulcal pattern.",
    "Midline Structures": "Midline structures in normal position.",
    "Choroid plexus": "Normal choroid plexus.",
    "Femoral head": "Normal femoral head ossification center.",
    "Acetabular development": "Normal acetabular development.",
    "Joint stability": "Stable hip joint.",
    "Visible portion of the meniscus": "Normal echogenicity of the visualized meniscal portions.",
    "Ligaments and tendons": "Normal ligamentous and tendinous structures.",
    "Ligaments and joints": "Normal ligaments and joint surfaces.",
    "Joint space": "Normal joint space. No effusion.",
    "Bursae": "No bursitis.",
    "Soft tissues": "No significant soft tissue abnormalities.",
    "Bone structures": "No cortical irregularities.",
    "Tendons": "Normal tendinous structures. No tears or tendinopathy.",
    "Skin": "Normal skin.",
    "Subcutaneous tissues": "Normal subcutaneous tissues.",
    "Muscles": "Normal muscular echogenicity and morphology.",
    "Vascular structures": "Normal vascular structures.",
    "Common femoral vein": "Patent common femoral vein. Normal compressibility.",
    "Superficial femoral vein": "Patent superficial femoral vein. Normal compressibility.",
    "Popliteal vein": "Patent popliteal vein. Normal compressibility.",
    "Tibial and peroneal veins": "Patent tibial and peroneal veins.",
    "Soft tissues and superficial venous system": "No significant superficial venous abnormalities.",
    "Common femoral artery": "Normal common femoral artery. Triphasic waveform.",
    "Superficial femoral artery": "Normal superficial femoral artery. No significant stenosis.",
    "Popliteal artery": "Normal popliteal artery. No significant stenosis.",
    "Tibial and peroneal arteries": "Patent tibial and peroneal arteries.",
    "Soft tissues and superficial arterial system": "No significant superficial arterial abnormalities.",
  },
  XRay: {
    "Lung": "Clear lung fields. No consolidations, effusions or nodules.",
    "Mediastinum and hilum": "Normal mediastinal silhouette and hila.",
    "Pleura and diaphragm": "No pleural effusion. Normal diaphragm position.",
    "Heart size and contours": "Normal heart size. Cardiothoracic ratio within normal limits.",
    "Bone structures": "No acute fractures or suspicious bone lesions.",
    "Other findings": "No additional findings.",
    "Glenohumeral joint": "Normal glenohumeral joint space.",
    "Acromioclavicular joint": "Normal acromioclavicular joint.",
    "Humeral head": "Normal humeral head. No fracture.",
    "Scapula": "Normal scapula.",
    "Clavicle": "Normal clavicle. No fracture.",
    "Vertebral bodies": "Normal vertebral body height and alignment.",
    "Intervertebral spaces": "Preserved intervertebral disc spaces.",
    "Facet joints": "Normal facet joints.",
    "Spinous processes": "Normal spinous processes.",
    "Soft tissues": "No significant soft tissue abnormalities.",
    "Sacroiliac joints": "Normal sacroiliac joints.",
    "Femoral heads": "Normal femoral heads. No avascular necrosis.",
    "Acetabulum": "Normal acetabulum bilaterally.",
    "Pubic symphysis": "Normal pubic symphysis.",
    "Calvarium": "Normal calvarium. No fractures.",
    "Facial bones": "Normal facial bones.",
    "Sinuses": "Normal paranasal sinuses.",
    "Orbits": "Normal orbits.",
    "Mandible": "Normal mandible.",
    "Femur": "No fracture or bone lesion.",
    "Tibia": "No fracture or bone lesion.",
    "Patella": "No fracture.",
    "Joint space": "Normal joint space.",
    "Tibia and fibula": "No fracture.",
    "Talus": "No fracture.",
    "Ankle joint": "Normal ankle joint.",
    "Humerus": "No fracture.",
    "Radius and ulna": "No fracture.",
    "Elbow joint": "Normal elbow joint. No effusion.",
    "Metacarpals": "Normal metacarpals.",
    "Phalanges": "Normal phalanges.",
    "Carpal bones": "Normal carpal bones.",
    "Joints": "Normal joint spaces.",
    "Wrist joint": "Normal wrist joint.",
    "Tarsal bones": "Normal tarsal bones.",
    "Metatarsals": "Normal metatarsals.",
    "Bone density": "Normal bone density.",
    "Bowel gas pattern": "Normal bowel gas pattern. No signs of obstruction.",
    "Organ outlines": "Normal organ outlines.",
    "Ribs": "No rib fractures.",
    "Clavicles": "Normal clavicles.",
    "Sternum": "Normal sternum.",
  },
  Mammography: {
    "Overall composition of the breasts": "Breast composition: ACR density classification [A-D]. No suspicious masses, calcifications or architectural distortion.",
    "Right breast": "No suspicious masses, calcifications or architectural distortion in the right breast.",
    "Left breast": "No suspicious masses, calcifications or architectural distortion in the left breast.",
  },
};

export function getDefaultPhrase(modality: string, sectionLabel: string): string {
  return DEFAULTS[modality]?.[sectionLabel] ?? MODALITY_GENERIC[modality] ?? "No significant abnormalities.";
}

export function getAllDefaults(): NormalityDefault[] {
  const sections = extractSectionsFromTemplates();
  return sections.map(({ modality, label }) => ({
    modality,
    section_label: label,
    phrase: getDefaultPhrase(modality, label),
  }));
}

export function getDefaultsForModality(modality: string): NormalityDefault[] {
  return getAllDefaults().filter((d) => d.modality === modality);
}
