import { DEFAULT_TEMPLATES } from "./templates";

export interface NormalityDefault {
  modality: string;
  section_label: string;
  phrase: string;
}

const SKIP_LABELS = new Set([
  "clinical indication", "clinical context", "indication",
  "radiotracer", "image quality", "comments",
  "recist 1.1 response assessment", "target lesions", "non-target lesions", "new lesions",
  "clinical data", "procedure details", "procedure", "outcome", "complications", "operators",
  "gestational age", "sex", "chronological age",
  "bone age estimation", "bone development assessment",
  "alpha angle", "beta angle",
  "bowel preparation and distension quality",
  "perfusion parameters",
]);

const NUMBERED_LABEL = /^\d+\.\s/;

function shouldSkip(label: string): boolean {
  const lower = label.toLowerCase();
  if (SKIP_LABELS.has(lower)) return true;
  if (NUMBERED_LABEL.test(label)) return true;
  return false;
}

export function extractSectionsFromTemplates(): { modality: string; label: string }[] {
  const seen = new Set<string>();
  const result: { modality: string; label: string }[] = [];

  for (const t of DEFAULT_TEMPLATES) {
    if (t.technique === "Procedures") continue;
    const re = /\*{2,3}([^*]+)\*{2,3}(?::?\s*\{[^}]+\})/g;
    let m;
    while ((m = re.exec(t.template)) !== null) {
      const label = m[1].trim();
      if (shouldSkip(label)) continue;
      const key = `${t.technique}|${label.toLowerCase()}`;
      if (seen.has(key)) continue;
      seen.add(key);
      result.push({ modality: t.technique, label });
    }
  }

  result.sort((a, b) => a.modality.localeCompare(b.modality) || a.label.localeCompare(b.label));
  return result;
}

const MODALITY_GENERIC: Record<string, Record<string, string>> = {
  en: { CT: "No significant abnormalities.", MRI: "No significant abnormalities.", Ultrasound: "Normal appearance.", XRay: "No significant abnormalities.", Mammography: "No significant findings." },
  es: { CT: "Sin alteraciones significativas.", MRI: "Sin alteraciones significativas.", Ultrasound: "Aspecto normal.", XRay: "Sin alteraciones significativas.", Mammography: "Sin hallazgos significativos." },
};

const DEFAULTS: Record<string, Record<string, string>> = {
  CT: {
    "Liver": "Normal in size, morphology and density. No focal lesions.",
    "Spleen": "Normal in size and density. No focal lesions.",
    "Pancreas": "Normal in size, morphology and density. No pancreatic duct dilation.",
    "Gallbladder": "Normal. No gallstones or wall thickening.",
    "Bile ducts": "No intrahepatic or extrahepatic biliary dilation.",
    "Kidneys": "Normal in size and morphology bilaterally. No hydronephrosis or focal lesions.",
    "Kidneys and ureters": "Normal in size and morphology bilaterally. No hydronephrosis. Ureters not dilated.",
    "Adrenal glands": "Normal in size and morphology bilaterally.",
    "Bladder": "Normal distension and wall thickness. No intraluminal lesions.",
    "Portal vein and hepatic artery": "Patent portal vein and hepatic artery. Normal caliber.",
    "Peritoneum and retroperitoneum": "No free fluid or lymphadenopathy.",
    "Peritoneum, retroperitoneum": "No free fluid or lymphadenopathy.",
    "Stomach": "Normal gastric wall. No wall thickening.",
    "Small bowel and colon": "Normal caliber. No wall thickening or obstruction.",
    "Small bowel loops and colon": "Normal caliber. No wall thickening or obstruction.",
    "Other pelvic structures": "No significant pelvic abnormalities.",
    "Lung parenchyma": "No pulmonary nodules, consolidations or ground-glass opacities. Normal lung parenchyma.",
    "Mediastinal lymph nodes": "No pathologically enlarged mediastinal lymph nodes.",
    "Mediastinum": "No pathologically enlarged mediastinal lymph nodes. Normal mediastinal structures.",
    "Trachea and bronchi": "Normal caliber. No endoluminal lesions.",
    "Esophagus": "Normal caliber. No wall thickening.",
    "Coronary arteries": "No significant coronary calcifications.",
    "Aorta and pulmonary artery": "Normal caliber of the aorta and pulmonary artery. No aneurysm or dissection.",
    "Heart and pericardium": "Normal heart size. No pericardial effusion.",
    "Pleura": "No pleural effusion or thickening.",
    "Pleura and diaphragm": "No pleural effusion. Normal diaphragm position.",
    "Diaphragm": "Normal position and morphology.",
    "Supradiaphragmatic tissues and thyroid": "No significant supradiaphragmatic abnormalities. Thyroid within normal limits.",
    "Thoracic wall": "No thoracic wall abnormalities.",
    "Thoracic wall and bone structures": "No thoracic wall or bone abnormalities.",
    "Spine": "No acute vertebral fractures or significant degenerative changes.",
    "Bone structures": "No acute fractures or suspicious bone lesions.",
    "Bone structures and included portions of the thorax": "No acute fractures or suspicious bone lesions. No significant thoracic abnormalities.",
    "Bone density": "Normal bone density.",
    "Soft tissues": "No significant soft tissue abnormalities.",
    "Included portions of the abdomen": "No significant abnormalities in the included portions of the abdomen.",
    "Supratentorial brain parenchyma": "Normal supratentorial brain parenchyma. No mass lesions, hemorrhage or acute ischemic changes.",
    "Infratentorial brain parenchyma": "Normal infratentorial brain parenchyma. No mass lesions in the posterior fossa.",
    "Extra-axial spaces and midline": "No extra-axial collections. Midline structures in normal position.",
    "Extra-axial spaces": "No extra-axial collections.",
    "Skull and extracranial soft tissues": "No calvarial fractures. Extracranial soft tissues unremarkable.",
    "Included portions of the cervical spine and vascular structures": "No acute cervical spine abnormalities. Vascular structures unremarkable.",
    "Brain parenchyma": "Normal brain parenchyma. No mass lesions, hemorrhage or acute ischemic changes.",
    "Ventricular system": "Normal size and morphology of the ventricular system.",
    "Other extra-axial spaces": "No extra-axial collections.",
    "Sinuses": "Normal paranasal sinuses.",
    "Cervical soft tissues": "No significant cervical soft tissue abnormalities.",
    "Cervical vascular structures": "Normal caliber of cervical vascular structures. No significant stenosis.",
    "Cervical lymph nodes": "No pathologically enlarged cervical lymph nodes.",
    "Nasopharynx": "Normal nasopharyngeal mucosa.",
    "Oropharynx": "Normal oropharyngeal structures.",
    "Parotids": "Normal parotid glands bilaterally.",
    "Submandibular glands": "Normal submandibular glands bilaterally.",
    "Vocal cords": "Symmetric vocal cords.",
    "Piriform sinuses": "Normal piriform sinuses.",
    "Epiglottis": "Normal epiglottis.",
    "Trachea": "Normal tracheal caliber and morphology.",
    "Parapharyngeal space": "Normal parapharyngeal spaces.",
    "Vascular space": "No vascular abnormalities.",
    "Salivary glands": "Normal salivary glands.",
    "Willis polygon": "Normal circle of Willis. No aneurysms.",
    "Ascending aorta": "Normal caliber ascending aorta.",
    "Aortic arch": "Normal aortic arch and branch vessels.",
    "Aortic arch and branches": "Normal aortic arch. Patent branch vessels without significant stenosis.",
    "Aortic arch and supra-aortic trunks": "Normal aortic arch. Patent supra-aortic trunks without significant stenosis.",
    "Descending aorta": "Normal caliber descending aorta.",
    "Descending thoracic aorta": "Normal caliber descending thoracic aorta. No aneurysm or dissection.",
    "Thoracic aorta": "Normal caliber thoracic aorta. No aneurysm or dissection.",
    "Abdominal aorta": "Normal caliber abdominal aorta. No aneurysm.",
    "Iliac arteries": "Normal caliber iliac arteries. No significant stenosis.",
    "Renal arteries": "Normal caliber renal arteries bilaterally.",
    "Celiac trunk and mesenteric arteries": "Normal caliber celiac trunk and mesenteric arteries.",
    "Other thoracic structures": "No additional thoracic abnormalities.",
    "Other thoracic and abdominal structures": "No additional thoraco-abdominal abnormalities.",
    "Other intraabdominal structures": "No additional intraabdominal abnormalities.",
    "Intraabdominal solid organs": "Normal intraabdominal solid organs.",
    "Other mediastinal findings": "No additional mediastinal abnormalities.",
    "Gallbladder and bile ducts": "Normal gallbladder. No biliary dilation.",
    "Stomach and bowel": "Normal gastric and bowel wall. No obstruction.",
    "Abdominal aorta and iliac arteries": "Normal caliber abdominal aorta and iliac arteries.",
    "Bone structures and soft tissues": "No acute fractures or significant soft tissue abnormalities.",
    "Nasopharynx, oropharynx and larynx": "Normal pharyngeal and laryngeal structures.",
    "Vascular structures": "No vascular abnormalities.",
    "Femur": "No fracture or bone lesion.",
    "Tibia": "No fracture or bone lesion.",
    "Patella": "No fracture or bone lesion.",
    "Joint space": "Normal joint space. No effusion.",
    "Tibia and fibula": "No fracture.",
    "Talus": "No fracture or bone lesion.",
    "Calcaneus": "No fracture.",
    "Ankle joint": "Normal ankle joint. No effusion.",
    "Superficial and deep femoral arteries": "Normal caliber. No significant stenosis or occlusion.",
    "Popliteal artery": "Normal caliber. No significant stenosis.",
    "Tibialis and peroneal arteries": "Patent tibial and peroneal arteries.",
    "Distal arteries of the dorsal and plantar aspect of the foot": "Patent distal arteries.",
  },
  MRI: {
    "Liver": "Normal in size, morphology and signal intensity. No focal lesions.",
    "Liver and spleen": "Normal in size, morphology and signal intensity. No focal lesions.",
    "Spleen": "Normal in size and signal intensity.",
    "Pancreas": "Normal in size, morphology and signal intensity. No pancreatic duct dilation.",
    "Gallbladder": "Normal. No gallstones or wall thickening.",
    "Gallbladder and bile ducts": "Normal gallbladder. No biliary dilation.",
    "Bile ducts": "No intrahepatic or extrahepatic biliary dilation.",
    "Intrahepatic and extrahepatic biliary ducts": "No intrahepatic or extrahepatic biliary dilation. Normal common bile duct caliber.",
    "Kidneys": "Normal in size, morphology and signal intensity bilaterally. No hydronephrosis or focal lesions.",
    "Adrenal glands": "Normal in size and signal intensity bilaterally.",
    "Adrenal glands and kidneys": "Normal adrenal glands and kidneys bilaterally. No focal lesions.",
    "Bladder": "Normal distension and wall thickness.",
    "Portal vein and hepatic artery": "Patent portal vein and hepatic artery. Normal caliber.",
    "Peritoneum and retroperitoneum": "No free fluid or lymphadenopathy.",
    "Peritoneum retroperitoneum": "No free fluid or lymphadenopathy.",
    "Peritoneum, retroperitoneum": "No free fluid or lymphadenopathy.",
    "Peritoneum": "No free fluid.",
    "Stomach": "Normal gastric wall.",
    "Small bowel and colon": "Normal caliber. No wall thickening.",
    "Small bowel loops and colon": "Normal caliber. No wall thickening.",
    "Other pelvic structures": "No significant pelvic abnormalities.",
    "Other intraabdominal structures": "No additional intraabdominal abnormalities.",
    "Supratentorial brain parenchyma": "Normal supratentorial brain parenchyma. Normal signal intensity. No mass lesions, restricted diffusion or abnormal enhancement.",
    "Infratentorial brain parenchyma": "Normal infratentorial brain parenchyma. No mass lesions in the posterior fossa.",
    "Extra-axial spaces and midline": "No extra-axial collections. Midline structures in normal position.",
    "Extra-axial space": "No extra-axial collections.",
    "Skull and extracranial soft tissues": "No calvarial abnormalities. Extracranial soft tissues unremarkable.",
    "Included portions of the cervical spine and vascular structures": "No acute cervical spine abnormalities. Vascular structures unremarkable.",
    "Cervical spine": "Normal cervical alignment. No marrow signal abnormalities.",
    "Vertebral bodies": "Normal vertebral body height, alignment and marrow signal.",
    "Intervertebral spaces and discs": "Normal intervertebral disc height and signal intensity. No significant disc herniation.",
    "Intervertebral discs": "Normal disc height and signal intensity. No significant herniation.",
    "Ligaments": "Normal ligamentous structures.",
    "Spinal cord": "Normal spinal cord signal and morphology.",
    "Soft tissues": "No significant soft tissue abnormalities.",
    "Soft tissues and associated structures": "No significant soft tissue abnormalities.",
    "Bone structures": "No bone marrow signal abnormalities or fractures.",
    "Bone structures and periprostatic tissues": "No suspicious bone lesions. Normal periprostatic tissues.",
    "Meniscus": "Normal meniscal morphology and signal. No tears.",
    "Ligaments and tendons": "Normal ligamentous and tendinous structures. No tears.",
    "Ligaments and syndesmosis": "Normal ligaments and syndesmosis. No tears.",
    "Joints": "Normal joint surfaces. No effusion.",
    "Bones": "No fractures or bone marrow edema.",
    "Tendons": "Normal tendinous structures. No tears or tendinopathy.",
    "Tendons and muscles": "Normal tendons and muscles. No tears.",
    "Cartilage and articular surfaces": "Normal cartilage thickness and articular surfaces.",
    "Nerves": "Normal course and signal of visualized nerves.",
    "Supraspinatus tendon": "Normal supraspinatus tendon. No tear or tendinopathy.",
    "Infraspinatus tendon": "Normal infraspinatus tendon. No tear.",
    "Subscapularis tendon": "Normal subscapularis tendon. No tear.",
    "Teres minor tendon": "Normal teres minor tendon.",
    "Biceps tendon": "Normal long head of biceps tendon in the bicipital groove.",
    "Subacromial subdeltoid bursa": "No subacromial subdeltoid bursitis.",
    "Glenohumeral joint": "Normal glenohumeral joint. No effusion.",
    "Labrum": "Normal labral morphology and signal.",
    "Acromioclavicular joint": "Normal acromioclavicular joint.",
    "Humerus": "Normal humeral head. No bone marrow edema.",
    "Scapula": "Normal scapula.",
    "Other findings": "No additional findings.",
    "Carpal bones": "Normal carpal bones. No fractures or avascular necrosis.",
    "Distal radius and ulna": "Normal distal radius and ulna.",
    "Carpal tunnel": "Normal carpal tunnel contents. No median nerve compression.",
    "Temporomandibular joint": "Normal temporomandibular joint. Normal disc position.",
    "Masticatory muscles": "Normal masticatory muscles.",
    "Retrodiscal space": "Normal retrodiscal tissue.",
    "Mandible and temporal bone": "Normal mandible and temporal bone.",
    "Nasopharynx": "Normal nasopharyngeal mucosa.",
    "Oropharynx": "Normal oropharyngeal structures.",
    "Parotids": "Normal parotid glands bilaterally.",
    "Submandibular glands": "Normal submandibular glands bilaterally.",
    "Vocal cords": "Symmetric vocal cords.",
    "Piriform sinuses": "Normal piriform sinuses.",
    "Epiglottis": "Normal epiglottis.",
    "Trachea": "Normal tracheal caliber.",
    "Parapharyngeal space": "Normal parapharyngeal spaces.",
    "Vascular space": "No vascular abnormalities.",
    "Cervical lymph nodes": "No pathologically enlarged cervical lymph nodes.",
    "Vascular structures": "No vascular abnormalities.",
    "Lymph nodes": "No pathologically enlarged lymph nodes.",
    "Lymph nodes or adenopathy": "No pathologically enlarged lymph nodes.",
    "General prostate assessment": "Normal prostate size and morphology. No suspicious focal lesions.",
    "Peripheral zone": "Normal peripheral zone signal. No suspicious focal lesions (PI-RADS 1).",
    "Transition zone": "Normal transition zone. No suspicious focal lesions.",
    "Seminal vesicles": "Normal seminal vesicles bilaterally.",
    "Uterus": "Normal uterine size, morphology and signal.",
    "Endometrium": "Normal endometrial thickness and signal.",
    "Cervix": "Normal cervical morphology and signal.",
    "Ovaries": "Normal ovaries bilaterally. No adnexal masses.",
    "Fallopian tubes": "Fallopian tubes not dilated.",
    "Rectum and sigmoid": "Normal rectal and sigmoid wall.",
    "Rectum": "Normal rectal wall. No mural thickening.",
    "Mesorectum": "Normal mesorectal fat. No suspicious lymph nodes.",
    "Mesorectal fascia": "Intact mesorectal fascia.",
    "Perianal soft tissues": "Normal perianal soft tissues. No fistula tract or abscess.",
    "Sphincters": "Normal internal and external sphincters.",
    "Other perineal structures": "No significant perineal abnormalities.",
  },
  Ultrasound: {
    "Liver": "Normal in size, echogenicity and echotexture. No focal lesions.",
    "Spleen": "Normal in size and echogenicity.",
    "Pancreas": "Normal in size and echogenicity. Visualized portions unremarkable.",
    "Gallbladder": "Normal. No gallstones or wall thickening.",
    "Bile ducts": "No intrahepatic or extrahepatic biliary dilation.",
    "Kidneys": "Normal in size, morphology and echogenicity bilaterally. Normal corticomedullary differentiation. No hydronephrosis.",
    "Bladder": "Normal distension and wall thickness.",
    "Portal vein and hepatic artery": "Patent portal vein with hepatopetal flow. Normal caliber.",
    "Peritoneum and retroperitoneum": "No free fluid.",
    "Other pelvic structures": "No significant pelvic abnormalities.",
    "General thyroid assessment": "Normal thyroid gland in size and echogenicity. No nodules.",
    "Cervical lymph nodes": "No pathologically enlarged cervical lymph nodes.",
    "Other structures": "No additional abnormalities.",
    "Breast parenchyma": "Normal breast parenchyma. No suspicious masses.",
    "Ductal system": "No ductal dilation.",
    "Lymph nodes": "No pathologically enlarged lymph nodes.",
    "Skin and subcutaneous tissues": "Normal skin and subcutaneous tissues.",
    "Other findings": "No additional findings.",
    "Ventricular size": "Normal ventricular size.",
    "Cortical structure": "Normal cortical structure and sulcal pattern.",
    "Midline Structures": "Midline structures in normal position.",
    "Choroid plexus": "Normal choroid plexus.",
    "Femoral head": "Normal femoral head ossification center.",
    "Acetabular development": "Normal acetabular development.",
    "Joint stability": "Stable hip joint.",
    "Visible portion of the meniscus": "Normal echogenicity of the visualized meniscal portions.",
    "Ligaments and tendons": "Normal ligamentous and tendinous structures.",
    "Ligaments and joints": "Normal ligaments and joint surfaces.",
    "Joint space": "Normal joint space. No effusion.",
    "Bursae": "No bursitis.",
    "Soft tissues": "No significant soft tissue abnormalities.",
    "Bone structures": "No cortical irregularities.",
    "Tendons": "Normal tendinous structures. No tears or tendinopathy.",
    "Skin": "Normal skin.",
    "Subcutaneous tissues": "Normal subcutaneous tissues.",
    "Muscles": "Normal muscular echogenicity and morphology.",
    "Vascular structures": "Normal vascular structures.",
    "Common femoral vein": "Patent common femoral vein. Normal compressibility.",
    "Superficial femoral vein": "Patent superficial femoral vein. Normal compressibility.",
    "Popliteal vein": "Patent popliteal vein. Normal compressibility.",
    "Tibial and peroneal veins": "Patent tibial and peroneal veins.",
    "Soft tissues and superficial venous system": "No significant superficial venous abnormalities.",
    "Common femoral artery": "Normal common femoral artery. Triphasic waveform.",
    "Superficial femoral artery": "Normal superficial femoral artery. No significant stenosis.",
    "Popliteal artery": "Normal popliteal artery. No significant stenosis.",
    "Tibial and peroneal arteries": "Patent tibial and peroneal arteries.",
    "Soft tissues and superficial arterial system": "No significant superficial arterial abnormalities.",
  },
  XRay: {
    "Lung": "Clear lung fields. No consolidations, effusions or nodules.",
    "Mediastinum and hilum": "Normal mediastinal silhouette and hila.",
    "Pleura and diaphragm": "No pleural effusion. Normal diaphragm position.",
    "Heart size and contours": "Normal heart size. Cardiothoracic ratio within normal limits.",
    "Bone structures": "No acute fractures or suspicious bone lesions.",
    "Other findings": "No additional findings.",
    "Glenohumeral joint": "Normal glenohumeral joint space.",
    "Acromioclavicular joint": "Normal acromioclavicular joint.",
    "Humeral head": "Normal humeral head. No fracture.",
    "Scapula": "Normal scapula.",
    "Clavicle": "Normal clavicle. No fracture.",
    "Vertebral bodies": "Normal vertebral body height and alignment.",
    "Intervertebral spaces": "Preserved intervertebral disc spaces.",
    "Facet joints": "Normal facet joints.",
    "Spinous processes": "Normal spinous processes.",
    "Soft tissues": "No significant soft tissue abnormalities.",
    "Sacroiliac joints": "Normal sacroiliac joints.",
    "Femoral heads": "Normal femoral heads. No avascular necrosis.",
    "Acetabulum": "Normal acetabulum bilaterally.",
    "Pubic symphysis": "Normal pubic symphysis.",
    "Calvarium": "Normal calvarium. No fractures.",
    "Facial bones": "Normal facial bones.",
    "Sinuses": "Normal paranasal sinuses.",
    "Orbits": "Normal orbits.",
    "Mandible": "Normal mandible.",
    "Femur": "No fracture or bone lesion.",
    "Tibia": "No fracture or bone lesion.",
    "Patella": "No fracture.",
    "Joint space": "Normal joint space.",
    "Tibia and fibula": "No fracture.",
    "Talus": "No fracture.",
    "Ankle joint": "Normal ankle joint.",
    "Humerus": "No fracture.",
    "Radius and ulna": "No fracture.",
    "Elbow joint": "Normal elbow joint. No effusion.",
    "Metacarpals": "Normal metacarpals.",
    "Phalanges": "Normal phalanges.",
    "Carpal bones": "Normal carpal bones.",
    "Joints": "Normal joint spaces.",
    "Wrist joint": "Normal wrist joint.",
    "Tarsal bones": "Normal tarsal bones.",
    "Metatarsals": "Normal metatarsals.",
    "Bone density": "Normal bone density.",
    "Bowel gas pattern": "Normal bowel gas pattern. No signs of obstruction.",
    "Organ outlines": "Normal organ outlines.",
    "Ribs": "No rib fractures.",
    "Clavicles": "Normal clavicles.",
    "Sternum": "Normal sternum.",
  },
  Mammography: {
    "Overall composition of the breasts": "Breast composition: ACR density classification [A-D]. No suspicious masses, calcifications or architectural distortion.",
    "Right breast": "No suspicious masses, calcifications or architectural distortion in the right breast.",
    "Left breast": "No suspicious masses, calcifications or architectural distortion in the left breast.",
  },
};

const DEFAULTS_ES: Record<string, Record<string, string>> = {
  CT: {
    "Liver": "Tamaño, morfología y densidad normales. Sin lesiones focales.",
    "Spleen": "Tamaño y densidad normales. Sin lesiones focales.",
    "Pancreas": "Tamaño, morfología y densidad normales. Sin dilatación del conducto pancreático.",
    "Gallbladder": "Normal. Sin colelitiasis ni engrosamiento parietal.",
    "Bile ducts": "Sin dilatación de la vía biliar intra ni extrahepática.",
    "Kidneys": "Tamaño y morfología normales bilateralmente. Sin hidronefrosis ni lesiones focales.",
    "Kidneys and ureters": "Tamaño y morfología normales bilateralmente. Sin hidronefrosis. Uréteres no dilatados.",
    "Adrenal glands": "Tamaño y morfología normales bilateralmente.",
    "Bladder": "Distensión y grosor parietal normales. Sin lesiones intraluminales.",
    "Portal vein and hepatic artery": "Vena porta y arteria hepática permeables. Calibre normal.",
    "Peritoneum and retroperitoneum": "Sin líquido libre ni adenopatías.",
    "Peritoneum, retroperitoneum": "Sin líquido libre ni adenopatías.",
    "Stomach": "Pared gástrica normal. Sin engrosamiento parietal.",
    "Small bowel and colon": "Calibre normal. Sin engrosamiento parietal ni signos de obstrucción.",
    "Small bowel loops and colon": "Calibre normal. Sin engrosamiento parietal ni signos de obstrucción.",
    "Other pelvic structures": "Sin alteraciones pélvicas significativas.",
    "Lung parenchyma": "Sin nódulos pulmonares, consolidaciones ni opacidades en vidrio deslustrado. Parénquima pulmonar normal.",
    "Mediastinal lymph nodes": "Sin adenopatías mediastínicas de tamaño patológico.",
    "Mediastinum": "Sin adenopatías mediastínicas de tamaño patológico. Estructuras mediastínicas normales.",
    "Trachea and bronchi": "Calibre normal. Sin lesiones endoluminales.",
    "Esophagus": "Calibre normal. Sin engrosamiento parietal.",
    "Coronary arteries": "Sin calcificaciones coronarias significativas.",
    "Aorta and pulmonary artery": "Calibre normal de la aorta y la arteria pulmonar. Sin aneurisma ni disección.",
    "Heart and pericardium": "Tamaño cardíaco normal. Sin derrame pericárdico.",
    "Pleura": "Sin derrame pleural ni engrosamiento.",
    "Pleura and diaphragm": "Sin derrame pleural. Posición diafragmática normal.",
    "Diaphragm": "Posición y morfología normales.",
    "Supradiaphragmatic tissues and thyroid": "Sin alteraciones supradiafragmáticas significativas. Tiroides dentro de límites normales.",
    "Thoracic wall": "Sin alteraciones de la pared torácica.",
    "Thoracic wall and bone structures": "Sin alteraciones de la pared torácica ni óseas.",
    "Spine": "Sin fracturas vertebrales agudas ni cambios degenerativos significativos.",
    "Bone structures": "Sin fracturas agudas ni lesiones óseas sospechosas.",
    "Bone structures and included portions of the thorax": "Sin fracturas agudas ni lesiones óseas sospechosas. Sin alteraciones torácicas significativas.",
    "Bone density": "Densidad ósea normal.",
    "Soft tissues": "Sin alteraciones significativas de partes blandas.",
    "Included portions of the abdomen": "Sin alteraciones significativas en las porciones incluidas del abdomen.",
    "Supratentorial brain parenchyma": "Parénquima cerebral supratentorial normal. Sin lesiones ocupantes de espacio, hemorragia ni cambios isquémicos agudos.",
    "Infratentorial brain parenchyma": "Parénquima cerebral infratentorial normal. Sin lesiones ocupantes de espacio en fosa posterior.",
    "Extra-axial spaces and midline": "Sin colecciones extra-axiales. Estructuras de la línea media en posición normal.",
    "Extra-axial spaces": "Sin colecciones extra-axiales.",
    "Skull and extracranial soft tissues": "Sin fracturas de la calota. Partes blandas extracraneales sin alteraciones.",
    "Included portions of the cervical spine and vascular structures": "Sin alteraciones agudas de la columna cervical. Estructuras vasculares sin alteraciones.",
    "Brain parenchyma": "Parénquima cerebral normal. Sin lesiones ocupantes de espacio, hemorragia ni cambios isquémicos agudos.",
    "Ventricular system": "Sistema ventricular de tamaño y morfología normales.",
    "Other extra-axial spaces": "Sin colecciones extra-axiales.",
    "Sinuses": "Senos paranasales normales.",
    "Cervical soft tissues": "Sin alteraciones significativas de partes blandas cervicales.",
    "Cervical vascular structures": "Calibre normal de las estructuras vasculares cervicales. Sin estenosis significativa.",
    "Cervical lymph nodes": "Sin adenopatías cervicales de tamaño patológico.",
    "Nasopharynx": "Mucosa nasofaríngea normal.",
    "Oropharynx": "Estructuras orofaríngeas normales.",
    "Parotids": "Glándulas parótidas normales bilateralmente.",
    "Submandibular glands": "Glándulas submandibulares normales bilateralmente.",
    "Vocal cords": "Cuerdas vocales simétricas.",
    "Piriform sinuses": "Senos piriformes normales.",
    "Epiglottis": "Epiglotis normal.",
    "Trachea": "Calibre y morfología traqueales normales.",
    "Parapharyngeal space": "Espacios parafaríngeos normales.",
    "Vascular space": "Sin alteraciones vasculares.",
    "Salivary glands": "Glándulas salivales normales.",
    "Willis polygon": "Polígono de Willis normal. Sin aneurismas.",
    "Ascending aorta": "Aorta ascendente de calibre normal.",
    "Aortic arch": "Arco aórtico y troncos supraaórticos normales.",
    "Aortic arch and branches": "Arco aórtico normal. Ramas permeables sin estenosis significativa.",
    "Aortic arch and supra-aortic trunks": "Arco aórtico normal. Troncos supraaórticos permeables sin estenosis significativa.",
    "Descending aorta": "Aorta descendente de calibre normal.",
    "Descending thoracic aorta": "Aorta torácica descendente de calibre normal. Sin aneurisma ni disección.",
    "Thoracic aorta": "Aorta torácica de calibre normal. Sin aneurisma ni disección.",
    "Abdominal aorta": "Aorta abdominal de calibre normal. Sin aneurisma.",
    "Iliac arteries": "Arterias ilíacas de calibre normal. Sin estenosis significativa.",
    "Renal arteries": "Arterias renales de calibre normal bilateralmente.",
    "Celiac trunk and mesenteric arteries": "Tronco celíaco y arterias mesentéricas de calibre normal.",
    "Other thoracic structures": "Sin alteraciones torácicas adicionales.",
    "Other thoracic and abdominal structures": "Sin alteraciones toracoabdominales adicionales.",
    "Other intraabdominal structures": "Sin alteraciones intraabdominales adicionales.",
    "Intraabdominal solid organs": "Órganos sólidos intraabdominales normales.",
    "Other mediastinal findings": "Sin hallazgos mediastínicos adicionales.",
    "Gallbladder and bile ducts": "Vesícula biliar normal. Sin dilatación de la vía biliar.",
    "Stomach and bowel": "Pared gástrica e intestinal normales. Sin obstrucción.",
    "Abdominal aorta and iliac arteries": "Aorta abdominal y arterias ilíacas de calibre normal.",
    "Bone structures and soft tissues": "Sin fracturas agudas ni alteraciones significativas de partes blandas.",
    "Nasopharynx, oropharynx and larynx": "Estructuras faríngeas y laríngeas normales.",
    "Vascular structures": "Sin alteraciones vasculares.",
    "Femur": "Sin fractura ni lesión ósea.",
    "Tibia": "Sin fractura ni lesión ósea.",
    "Patella": "Sin fractura ni lesión ósea.",
    "Joint space": "Espacio articular normal. Sin derrame.",
    "Tibia and fibula": "Sin fractura.",
    "Talus": "Sin fractura ni lesión ósea.",
    "Calcaneus": "Sin fractura.",
    "Ankle joint": "Articulación del tobillo normal. Sin derrame.",
    "Superficial and deep femoral arteries": "Calibre normal. Sin estenosis ni oclusión significativas.",
    "Popliteal artery": "Calibre normal. Sin estenosis significativa.",
    "Tibialis and peroneal arteries": "Arterias tibiales y peroneas permeables.",
    "Distal arteries of the dorsal and plantar aspect of the foot": "Arterias distales permeables.",
  },
  MRI: {
    "Liver": "Tamaño, morfología e intensidad de señal normales. Sin lesiones focales.",
    "Liver and spleen": "Tamaño, morfología e intensidad de señal normales. Sin lesiones focales.",
    "Spleen": "Tamaño e intensidad de señal normales.",
    "Pancreas": "Tamaño, morfología e intensidad de señal normales. Sin dilatación del conducto pancreático.",
    "Gallbladder": "Normal. Sin colelitiasis ni engrosamiento parietal.",
    "Gallbladder and bile ducts": "Vesícula biliar normal. Sin dilatación de la vía biliar.",
    "Bile ducts": "Sin dilatación de la vía biliar intra ni extrahepática.",
    "Intrahepatic and extrahepatic biliary ducts": "Sin dilatación de la vía biliar intra ni extrahepática. Calibre normal del colédoco.",
    "Kidneys": "Tamaño, morfología e intensidad de señal normales bilateralmente. Sin hidronefrosis ni lesiones focales.",
    "Adrenal glands": "Tamaño e intensidad de señal normales bilateralmente.",
    "Adrenal glands and kidneys": "Glándulas suprarrenales y riñones normales bilateralmente. Sin lesiones focales.",
    "Bladder": "Distensión y grosor parietal normales.",
    "Portal vein and hepatic artery": "Vena porta y arteria hepática permeables. Calibre normal.",
    "Peritoneum and retroperitoneum": "Sin líquido libre ni adenopatías.",
    "Peritoneum retroperitoneum": "Sin líquido libre ni adenopatías.",
    "Peritoneum, retroperitoneum": "Sin líquido libre ni adenopatías.",
    "Peritoneum": "Sin líquido libre.",
    "Stomach": "Pared gástrica normal.",
    "Small bowel and colon": "Calibre normal. Sin engrosamiento parietal.",
    "Small bowel loops and colon": "Calibre normal. Sin engrosamiento parietal.",
    "Other pelvic structures": "Sin alteraciones pélvicas significativas.",
    "Other intraabdominal structures": "Sin alteraciones intraabdominales adicionales.",
    "Supratentorial brain parenchyma": "Parénquima cerebral supratentorial normal. Intensidad de señal normal. Sin lesiones ocupantes de espacio, restricción en difusión ni realce patológico.",
    "Infratentorial brain parenchyma": "Parénquima cerebral infratentorial normal. Sin lesiones ocupantes de espacio en fosa posterior.",
    "Extra-axial spaces and midline": "Sin colecciones extra-axiales. Estructuras de la línea media en posición normal.",
    "Extra-axial space": "Sin colecciones extra-axiales.",
    "Skull and extracranial soft tissues": "Sin alteraciones de la calota. Partes blandas extracraneales sin hallazgos.",
    "Included portions of the cervical spine and vascular structures": "Sin alteraciones agudas de la columna cervical. Estructuras vasculares sin alteraciones.",
    "Cervical spine": "Alineación cervical normal. Sin alteraciones de señal medular.",
    "Vertebral bodies": "Altura, alineación y señal medular normales de los cuerpos vertebrales.",
    "Intervertebral spaces and discs": "Altura e intensidad de señal discales normales. Sin herniación discal significativa.",
    "Intervertebral discs": "Altura e intensidad de señal normales. Sin herniación significativa.",
    "Ligaments": "Estructuras ligamentosas normales.",
    "Spinal cord": "Señal y morfología normales de la médula espinal.",
    "Soft tissues": "Sin alteraciones significativas de partes blandas.",
    "Soft tissues and associated structures": "Sin alteraciones significativas de partes blandas.",
    "Bone structures": "Sin alteraciones de señal medular ósea ni fracturas.",
    "Bone structures and periprostatic tissues": "Sin lesiones óseas sospechosas. Tejidos periprostáticos normales.",
    "Meniscus": "Morfología y señal meniscales normales. Sin roturas.",
    "Ligaments and tendons": "Estructuras ligamentosas y tendinosas normales. Sin roturas.",
    "Ligaments and syndesmosis": "Ligamentos y sindesmosis normales. Sin roturas.",
    "Joints": "Superficies articulares normales. Sin derrame.",
    "Bones": "Sin fracturas ni edema de médula ósea.",
    "Tendons": "Estructuras tendinosas normales. Sin roturas ni tendinopatía.",
    "Tendons and muscles": "Tendones y músculos normales. Sin roturas.",
    "Cartilage and articular surfaces": "Grosor cartilaginoso y superficies articulares normales.",
    "Nerves": "Trayecto y señal normales de los nervios visualizados.",
    "Supraspinatus tendon": "Tendón del supraespinoso normal. Sin rotura ni tendinopatía.",
    "Infraspinatus tendon": "Tendón del infraespinoso normal. Sin rotura.",
    "Subscapularis tendon": "Tendón del subescapular normal. Sin rotura.",
    "Teres minor tendon": "Tendón del redondo menor normal.",
    "Biceps tendon": "Tendón de la porción larga del bíceps normal en la corredera bicipital.",
    "Subacromial subdeltoid bursa": "Sin bursitis subacromial-subdeltoidea.",
    "Glenohumeral joint": "Articulación glenohumeral normal. Sin derrame.",
    "Labrum": "Morfología y señal del labrum normales.",
    "Acromioclavicular joint": "Articulación acromioclavicular normal.",
    "Humerus": "Cabeza humeral normal. Sin edema de médula ósea.",
    "Scapula": "Escápula normal.",
    "Other findings": "Sin hallazgos adicionales.",
    "Carpal bones": "Huesos del carpo normales. Sin fracturas ni necrosis avascular.",
    "Distal radius and ulna": "Radio y cúbito distales normales.",
    "Carpal tunnel": "Contenido del túnel carpiano normal. Sin compresión del nervio mediano.",
    "Temporomandibular joint": "Articulación temporomandibular normal. Posición discal normal.",
    "Masticatory muscles": "Musculatura masticatoria normal.",
    "Retrodiscal space": "Tejido retrodiscal normal.",
    "Mandible and temporal bone": "Mandíbula y hueso temporal normales.",
    "Nasopharynx": "Mucosa nasofaríngea normal.",
    "Oropharynx": "Estructuras orofaríngeas normales.",
    "Parotids": "Glándulas parótidas normales bilateralmente.",
    "Submandibular glands": "Glándulas submandibulares normales bilateralmente.",
    "Vocal cords": "Cuerdas vocales simétricas.",
    "Piriform sinuses": "Senos piriformes normales.",
    "Epiglottis": "Epiglotis normal.",
    "Trachea": "Calibre traqueal normal.",
    "Parapharyngeal space": "Espacios parafaríngeos normales.",
    "Vascular space": "Sin alteraciones vasculares.",
    "Cervical lymph nodes": "Sin adenopatías cervicales de tamaño patológico.",
    "Vascular structures": "Sin alteraciones vasculares.",
    "Lymph nodes": "Sin adenopatías de tamaño patológico.",
    "Lymph nodes or adenopathy": "Sin adenopatías de tamaño patológico.",
    "General prostate assessment": "Tamaño y morfología prostáticos normales. Sin lesiones focales sospechosas.",
    "Peripheral zone": "Señal normal de la zona periférica. Sin lesiones focales sospechosas (PI-RADS 1).",
    "Transition zone": "Zona de transición normal. Sin lesiones focales sospechosas.",
    "Seminal vesicles": "Vesículas seminales normales bilateralmente.",
    "Uterus": "Tamaño, morfología y señal uterinos normales.",
    "Endometrium": "Grosor y señal endometriales normales.",
    "Cervix": "Morfología y señal cervicales normales.",
    "Ovaries": "Ovarios normales bilateralmente. Sin masas anexiales.",
    "Fallopian tubes": "Trompas de Falopio no dilatadas.",
    "Rectum and sigmoid": "Pared rectal y sigmoidea normales.",
    "Rectum": "Pared rectal normal. Sin engrosamiento mural.",
    "Mesorectum": "Grasa mesorrectal normal. Sin ganglios sospechosos.",
    "Mesorectal fascia": "Fascia mesorrectal intacta.",
    "Perianal soft tissues": "Partes blandas perianales normales. Sin trayecto fistuloso ni absceso.",
    "Sphincters": "Esfínteres interno y externo normales.",
    "Other perineal structures": "Sin alteraciones perineales significativas.",
  },
  Ultrasound: {
    "Liver": "Tamaño, ecogenicidad y ecoestructura normales. Sin lesiones focales.",
    "Spleen": "Tamaño y ecogenicidad normales.",
    "Pancreas": "Tamaño y ecogenicidad normales. Porciones visualizadas sin alteraciones.",
    "Gallbladder": "Normal. Sin colelitiasis ni engrosamiento parietal.",
    "Bile ducts": "Sin dilatación de la vía biliar intra ni extrahepática.",
    "Kidneys": "Tamaño, morfología y ecogenicidad normales bilateralmente. Diferenciación corticomedular conservada. Sin hidronefrosis.",
    "Bladder": "Distensión y grosor parietal normales.",
    "Portal vein and hepatic artery": "Vena porta permeable con flujo hepatópeto. Calibre normal.",
    "Peritoneum and retroperitoneum": "Sin líquido libre.",
    "Other pelvic structures": "Sin alteraciones pélvicas significativas.",
    "General thyroid assessment": "Glándula tiroides de tamaño y ecogenicidad normales. Sin nódulos.",
    "Cervical lymph nodes": "Sin adenopatías cervicales de tamaño patológico.",
    "Other structures": "Sin alteraciones adicionales.",
    "Breast parenchyma": "Parénquima mamario normal. Sin masas sospechosas.",
    "Ductal system": "Sin dilatación ductal.",
    "Lymph nodes": "Sin adenopatías de tamaño patológico.",
    "Skin and subcutaneous tissues": "Piel y tejido subcutáneo normales.",
    "Other findings": "Sin hallazgos adicionales.",
    "Ventricular size": "Tamaño ventricular normal.",
    "Cortical structure": "Estructura cortical y patrón de surcos normales.",
    "Midline Structures": "Estructuras de la línea media en posición normal.",
    "Choroid plexus": "Plexos coroideos normales.",
    "Femoral head": "Núcleo de osificación de la cabeza femoral normal.",
    "Acetabular development": "Desarrollo acetabular normal.",
    "Joint stability": "Articulación de cadera estable.",
    "Visible portion of the meniscus": "Ecogenicidad normal de las porciones meniscales visualizadas.",
    "Ligaments and tendons": "Estructuras ligamentosas y tendinosas normales.",
    "Ligaments and joints": "Ligamentos y superficies articulares normales.",
    "Joint space": "Espacio articular normal. Sin derrame.",
    "Bursae": "Sin bursitis.",
    "Soft tissues": "Sin alteraciones significativas de partes blandas.",
    "Bone structures": "Sin irregularidades corticales.",
    "Tendons": "Estructuras tendinosas normales. Sin roturas ni tendinopatía.",
    "Skin": "Piel normal.",
    "Subcutaneous tissues": "Tejido subcutáneo normal.",
    "Muscles": "Ecogenicidad y morfología musculares normales.",
    "Vascular structures": "Estructuras vasculares normales.",
    "Common femoral vein": "Vena femoral común permeable. Compresibilidad normal.",
    "Superficial femoral vein": "Vena femoral superficial permeable. Compresibilidad normal.",
    "Popliteal vein": "Vena poplítea permeable. Compresibilidad normal.",
    "Tibial and peroneal veins": "Venas tibiales y peroneas permeables.",
    "Soft tissues and superficial venous system": "Sin alteraciones venosas superficiales significativas.",
    "Common femoral artery": "Arteria femoral común normal. Onda trifásica.",
    "Superficial femoral artery": "Arteria femoral superficial normal. Sin estenosis significativa.",
    "Popliteal artery": "Arteria poplítea normal. Sin estenosis significativa.",
    "Tibial and peroneal arteries": "Arterias tibiales y peroneas permeables.",
    "Soft tissues and superficial arterial system": "Sin alteraciones arteriales superficiales significativas.",
  },
  XRay: {
    "Lung": "Campos pulmonares transparentes. Sin consolidaciones, derrames ni nódulos.",
    "Mediastinum and hilum": "Silueta mediastínica e hilios normales.",
    "Pleura and diaphragm": "Sin derrame pleural. Posición diafragmática normal.",
    "Heart size and contours": "Tamaño cardíaco normal. Índice cardiotorácico dentro de límites normales.",
    "Bone structures": "Sin fracturas agudas ni lesiones óseas sospechosas.",
    "Other findings": "Sin hallazgos adicionales.",
    "Glenohumeral joint": "Espacio articular glenohumeral normal.",
    "Acromioclavicular joint": "Articulación acromioclavicular normal.",
    "Humeral head": "Cabeza humeral normal. Sin fractura.",
    "Scapula": "Escápula normal.",
    "Clavicle": "Clavícula normal. Sin fractura.",
    "Vertebral bodies": "Altura y alineación normales de los cuerpos vertebrales.",
    "Intervertebral spaces": "Espacios discales intervertebrales conservados.",
    "Facet joints": "Articulaciones facetarias normales.",
    "Spinous processes": "Procesos espinosos normales.",
    "Soft tissues": "Sin alteraciones significativas de partes blandas.",
    "Sacroiliac joints": "Articulaciones sacroilíacas normales.",
    "Femoral heads": "Cabezas femorales normales. Sin necrosis avascular.",
    "Acetabulum": "Acetábulo normal bilateralmente.",
    "Pubic symphysis": "Sínfisis púbica normal.",
    "Calvarium": "Calota craneal normal. Sin fracturas.",
    "Facial bones": "Huesos faciales normales.",
    "Sinuses": "Senos paranasales normales.",
    "Orbits": "Órbitas normales.",
    "Mandible": "Mandíbula normal.",
    "Femur": "Sin fractura ni lesión ósea.",
    "Tibia": "Sin fractura ni lesión ósea.",
    "Patella": "Sin fractura.",
    "Joint space": "Espacio articular normal.",
    "Tibia and fibula": "Sin fractura.",
    "Talus": "Sin fractura.",
    "Ankle joint": "Articulación del tobillo normal.",
    "Humerus": "Sin fractura.",
    "Radius and ulna": "Sin fractura.",
    "Elbow joint": "Articulación del codo normal. Sin derrame.",
    "Metacarpals": "Metacarpianos normales.",
    "Phalanges": "Falanges normales.",
    "Carpal bones": "Huesos del carpo normales.",
    "Joints": "Espacios articulares normales.",
    "Wrist joint": "Articulación de la muñeca normal.",
    "Tarsal bones": "Huesos del tarso normales.",
    "Metatarsals": "Metatarsianos normales.",
    "Bone density": "Densidad ósea normal.",
    "Bowel gas pattern": "Patrón de gas intestinal normal. Sin signos de obstrucción.",
    "Organ outlines": "Contornos de órganos normales.",
    "Ribs": "Sin fracturas costales.",
    "Clavicles": "Clavículas normales.",
    "Sternum": "Esternón normal.",
  },
  Mammography: {
    "Overall composition of the breasts": "Composición mamaria: clasificación de densidad ACR [A-D]. Sin masas, calcificaciones ni distorsión arquitectural sospechosas.",
    "Right breast": "Sin masas, calcificaciones ni distorsión arquitectural sospechosas en la mama derecha.",
    "Left breast": "Sin masas, calcificaciones ni distorsión arquitectural sospechosas en la mama izquierda.",
  },
};

export type NormalityLang = "en" | "es";

export function getDefaultPhrase(modality: string, sectionLabel: string, lang: NormalityLang = "en"): string {
  if (lang === "es") {
    return DEFAULTS_ES[modality]?.[sectionLabel]
      ?? MODALITY_GENERIC.es[modality]
      ?? "Sin alteraciones significativas.";
  }
  return DEFAULTS[modality]?.[sectionLabel]
    ?? MODALITY_GENERIC.en[modality]
    ?? "No significant abnormalities.";
}

export function getAllDefaults(lang: NormalityLang = "en"): NormalityDefault[] {
  const sections = extractSectionsFromTemplates();
  return sections.map(({ modality, label }) => ({
    modality,
    section_label: label,
    phrase: getDefaultPhrase(modality, label, lang),
  }));
}

export function getDefaultsForModality(modality: string, lang: NormalityLang = "en"): NormalityDefault[] {
  return getAllDefaults(lang).filter((d) => d.modality === modality);
}
