// Deepgram keyterm boosters for medical radiology speech recognition.
// Used with the `keyterm` parameter (no intensity needed, unlike `keywords`).

export const RADIOLOGY_KEYTERMS_ES: string[] = [
  // ── Anatomía general ──
  "nódulo", "nódulos", "lóbulo", "lóbulos", "lóbulo hepático",
  "parénquima", "parenquimatoso", "parenquimatosa",
  "mediastino", "mediastínico", "mediastinal",
  "retroperitoneal", "peritoneal", "retroperitoneo",
  "hilio", "hilar", "hiliares", "hilios",
  "pleura", "pleural", "pleurales",
  "pericardio", "pericárdico", "pericárdica",
  "peritoneo", "epiplón", "mesenterio", "mesentérico",
  // ── Anatomía torácica ──
  "ápex", "apical", "lóbulo superior", "lóbulo medio", "lóbulo inferior",
  "língula", "lingular", "segmento", "segmentario",
  "bronquio", "bronquial", "bronquios", "bronquiolo",
  "tráquea", "traqueal", "carina", "subcarinal",
  "paratraqueal", "prevascular", "pretraqueal",
  "aortopulmonar", "ventana aortopulmonar",
  "costodiafragmático", "costofrénico", "costal",
  "supraclavicular", "infraclavicular", "axilar",
  "diafragma", "diafragmático", "hemidiafragma",
  "cisura", "cisura mayor", "cisura menor",
  // ── Anatomía abdominal ──
  "hígado", "hepático", "hepática", "lóbulo caudado",
  "vesícula biliar", "colédoco", "vía biliar", "conducto hepático",
  "páncreas", "pancreático", "pancreática", "wirsung",
  "bazo", "esplénico", "esplénica",
  "riñón", "renal", "renales", "corteza renal", "pelvis renal",
  "uréter", "ureteral", "uréteres",
  "vejiga", "vesical",
  "aorta", "aórtico", "aórtica",
  "vena cava", "cava inferior", "cava superior",
  "porta", "vena porta", "portal",
  "suprarrenal", "glándula suprarrenal", "adrenal",
  "duodeno", "duodenal", "yeyuno", "íleon", "ileal",
  "ciego", "apéndice", "cecal",
  "colon", "colónico", "recto", "rectal", "sigmoides",
  // ── Anatomía musculoesquelética ──
  "vértebra", "vertebral", "vertebrales",
  "cervical", "torácica", "lumbar", "sacra", "sacro",
  "disco intervertebral", "discal", "hernia discal",
  "espondilosis", "espondilolistesis", "espondilólisis",
  "artrosis", "artropatía", "osteoartritis",
  "menisco", "ligamento", "ligamentario",
  "tendón", "tendinoso", "tendinitis", "tendinosis",
  "cortical", "medular", "esponjoso", "trabecular",
  "epífisis", "metáfisis", "diáfisis",
  "fémur", "femoral", "tibia", "tibial", "peroné", "peroneal",
  "húmero", "humeral", "radio", "cúbito", "cubital",
  "escápula", "escapular", "clavícula", "clavicular",
  "acetábulo", "acetabular", "rótula", "rotuliano",
  "calcáneo", "astrágalo", "tarso", "metatarso",
  // ── Anatomía neurológica ──
  "cerebro", "cerebral", "cerebeloso", "cerebelosa",
  "tálamo", "talámico", "hipotálamo",
  "hipófisis", "hipofisario", "silla turca",
  "ventrículo", "ventricular", "ventrículos laterales",
  "sustancia blanca", "sustancia gris",
  "ganglios basales", "núcleo caudado", "putamen",
  "cuerpo calloso", "fosa posterior",
  "meninges", "meníngeo", "dural", "duramadre",
  "subaracnoideo", "epidural", "subdural",
  // ── Anatomía mamaria ──
  "mama", "mamario", "mamaria", "mamografía",
  "axila", "axilar", "ganglio axilar",
  "conducto galactóforo", "tejido fibroglandular",
  "birads", "bi-rads",
  // ── Patología general ──
  "adenopatía", "adenopatías", "linfadenopatía",
  "derrame pleural", "derrame pericárdico",
  "neumotórax", "hemotórax", "hidroneumotórax",
  "atelectasia", "atelectasias", "atelectásico", "atelectásica",
  "consolidación", "consolidativa", "consolidativo",
  "cavitación", "cavitada", "cavitado",
  "empiema", "absceso", "colección",
  "embolia", "tromboembolismo", "trombo", "trombosis",
  "hepatomegalia", "esplenomegalia", "cardiomegalia",
  "hidronefrosis", "ureterohidronefrosis",
  "bronquiectasias", "bronquiectasia",
  "loculado", "loculada", "loculación",
  "opacidad", "opacidades",
  "fibrosis", "fibrótico", "fibrótica",
  "calcificación", "calcificaciones", "calcificado", "calcificada",
  "necrosis", "necrótico", "necrótica",
  "edema", "edematoso", "edematosa",
  "hemorragia", "hemorrágico", "hemorrágica", "hematoma",
  "isquemia", "isquémico", "isquémica",
  "infarto", "infartado",
  "estenosis", "estenosante", "estenótico",
  "dilatación", "dilatado", "dilatada", "ectasia",
  "aneurisma", "aneurismático",
  "hernia", "herniación", "herniado",
  "metástasis", "metastásico", "metastásica",
  "neoplasia", "neoplásico", "neoplásica",
  "masa", "lesión", "lesiones", "tumoración",
  "quiste", "quístico", "quística", "quistes",
  "pólipo", "pólipos", "polipoide",
  "litiasis", "colelitiasis", "nefrolitiasis", "urolitiasis",
  "cálculo", "cálculos", "lito",
  "esteatosis", "esteatósico", "esteatósica",
  "cirrosis", "cirrótico", "cirrótica",
  "ascitis", "líquido libre",
  "diverticulosis", "divertículo", "diverticulitis",
  "pancreatitis", "colecistitis", "apendicitis",
  "neumonía", "neumonitis", "neumopatía",
  "enfisema", "enfisematoso", "enfisematosa",
  "ateromatosis", "aterosclerosis", "ateromatosa",
  "tromboflebitis", "flebitis",
  "fístula", "fistuloso", "fistulosa",
  "perforación", "perforado", "perforada",
  "obstrucción", "obstructivo", "obstructiva",
  "invaginación", "intususcepción", "vólvulo",
  // ── Descriptores de imagen ──
  "hipoecoico", "hiperecoico", "anecoico", "ecogénico",
  "hipointenso", "hiperintenso", "isointenso",
  "hipodenso", "hiperdenso", "isodenso",
  "homogéneo", "heterogéneo", "heterogénea",
  "difuso", "difusa", "focal", "multifocal",
  "infiltrativo", "infiltrativa",
  "espiculado", "espiculada", "lobulado", "lobulada",
  "mal definido", "bien definido", "circunscrito",
  "irregular", "regular", "oval", "redondeado",
  "sésil", "pediculado", "pediculada",
  "captante", "realce", "realce heterogéneo",
  "restricción", "restricción a la difusión",
  // ── Medidas y cuantificación ──
  "milímetros", "centímetros", "milímetro", "centímetro",
  "unidades hounsfield", "hounsfield",
  "diámetro", "transverso", "anteroposterior", "craneocaudal",
  "longitudinal", "axial", "coronal", "sagital",
  // ── Modalidades y técnicas ──
  "tomografía", "resonancia magnética", "ecografía", "ultrasonido",
  "radiografía", "fluoroscopia", "mamografía", "densitometría",
  "angiotomografía", "angiorresonancia", "angiografía",
  "contraste", "medio de contraste", "gadolinio",
  "difusión", "perfusión", "espectroscopia",
  "secuencia", "ponderación", "T1", "T2", "FLAIR", "STIR",
  // ── Normalidad ──
  "normal", "sin alteraciones", "sin hallazgos", "sin evidencia",
  "conservado", "conservada", "dentro de límites normales",
  "homogéneo", "calibre normal", "morfología normal",
  "sin dilatación", "permeable", "permeables",
];

export const RADIOLOGY_KEYTERMS_PT: string[] = [
  // ── Anatomia geral ──
  "nódulo", "nódulos", "lóbulo", "lóbulos", "lóbulo hepático",
  "parênquima", "parenquimatoso", "parenquimatosa",
  "mediastino", "mediastinal",
  "retroperitoneal", "peritoneal", "retroperitônio",
  "hilo", "hilar", "hilares",
  "pleura", "pleural", "pleurais",
  "pericárdio", "pericárdico", "pericárdica",
  "peritônio", "mesentério", "mesentérico",
  // ── Anatomia torácica ──
  "ápice", "apical", "lobo superior", "lobo médio", "lobo inferior",
  "língula", "lingular", "segmento", "segmentar",
  "brônquio", "brônquios", "bronquíolo",
  "traqueia", "traqueal", "carina", "subcarinal",
  "paratraqueal", "pré-vascular", "pré-traqueal",
  "aortopulmonar", "janela aortopulmonar",
  "costodiafragmático", "costofrênico", "costal",
  "supraclavicular", "infraclavicular", "axilar",
  "diafragma", "diafragmático", "hemidiafragma",
  "cissura", "cissura maior", "cissura menor",
  // ── Anatomia abdominal ──
  "fígado", "hepático", "hepática", "lobo caudado",
  "vesícula biliar", "colédoco", "via biliar", "ducto hepático",
  "pâncreas", "pancreático", "pancreática", "wirsung",
  "baço", "esplênico", "esplênica",
  "rim", "renal", "renais", "córtex renal", "pelve renal",
  "ureter", "ureteral", "ureteres",
  "bexiga", "vesical",
  "aorta", "aórtico", "aórtica",
  "veia cava", "cava inferior", "cava superior",
  "porta", "veia porta", "portal",
  "suprarrenal", "glândula suprarrenal", "adrenal",
  "duodeno", "duodenal", "jejuno", "íleo", "ileal",
  "ceco", "apêndice", "cecal",
  "cólon", "colônico", "reto", "retal", "sigmoide",
  // ── Anatomia musculoesquelética ──
  "vértebra", "vertebral", "vertebrais",
  "cervical", "torácica", "lombar", "sacral", "sacro",
  "disco intervertebral", "discal", "hérnia discal",
  "espondilose", "espondilolistese", "espondilólise",
  "artrose", "artropatia", "osteoartrite",
  "menisco", "ligamento", "ligamentar",
  "tendão", "tendinoso", "tendinite", "tendinose",
  "cortical", "medular", "esponjoso", "trabecular",
  "epífise", "metáfise", "diáfise",
  "fêmur", "femoral", "tíbia", "tibial", "fíbula", "fibular",
  "úmero", "umeral", "rádio", "ulna", "ulnar",
  "escápula", "escapular", "clavícula", "clavicular",
  "acetábulo", "acetabular", "patela", "patelar",
  "calcâneo", "tálus", "tarso", "metatarso",
  // ── Anatomia neurológica ──
  "cérebro", "cerebral", "cerebelar",
  "tálamo", "talâmico", "hipotálamo",
  "hipófise", "hipofisário", "sela túrcica",
  "ventrículo", "ventricular", "ventrículos laterais",
  "substância branca", "substância cinzenta",
  "gânglios da base", "núcleo caudado", "putâmen",
  "corpo caloso", "fossa posterior",
  "meninges", "meníngeo", "dural", "dura-máter",
  "subaracnóideo", "epidural", "subdural",
  // ── Anatomia mamária ──
  "mama", "mamário", "mamária", "mamografia",
  "axila", "axilar", "linfonodo axilar",
  "ducto galactóforo", "tecido fibroglandular",
  "birads", "bi-rads",
  // ── Patologia geral ──
  "adenopatia", "adenopatias", "linfonodomegalia",
  "derrame pleural", "derrame pericárdico",
  "pneumotórax", "hemotórax", "hidropneumotórax",
  "atelectasia", "atelectasias", "atelectásico", "atelectásica",
  "consolidação", "consolidativa", "consolidativo",
  "cavitação", "cavitada", "cavitado",
  "empiema", "abscesso", "coleção",
  "embolia", "tromboembolismo", "trombo", "trombose",
  "hepatomegalia", "esplenomegalia", "cardiomegalia",
  "hidronefrose", "ureterohidronefrose",
  "bronquiectasias", "bronquiectasia",
  "loculado", "loculada", "loculação",
  "opacidade", "opacidades",
  "fibrose", "fibrótico", "fibrótica",
  "calcificação", "calcificações", "calcificado", "calcificada",
  "necrose", "necrótico", "necrótica",
  "edema", "edematoso", "edematosa",
  "hemorragia", "hemorrágico", "hemorrágica", "hematoma",
  "isquemia", "isquêmico", "isquêmica",
  "infarto", "infartado",
  "estenose", "estenosante", "estenótico",
  "dilatação", "dilatado", "dilatada", "ectasia",
  "aneurisma", "aneurismático",
  "hérnia", "herniação", "herniado",
  "metástase", "metastático", "metastática",
  "neoplasia", "neoplásico", "neoplásica",
  "massa", "lesão", "lesões", "tumoração",
  "cisto", "cístico", "cística", "cistos",
  "pólipo", "pólipos", "polipoide",
  "litíase", "colelitíase", "nefrolitíase", "urolitíase",
  "cálculo", "cálculos",
  "esteatose", "esteatósico", "esteatósica",
  "cirrose", "cirrótico", "cirrótica",
  "ascite", "líquido livre",
  "diverticulose", "divertículo", "diverticulite",
  "pancreatite", "colecistite", "apendicite",
  "pneumonia", "pneumonite", "pneumopatia",
  "enfisema", "enfisematoso", "enfisematosa",
  "ateromatose", "aterosclerose", "ateromatosa",
  "tromboflebite", "flebite",
  "fístula", "fistuloso", "fistulosa",
  "perfuração", "perfurado", "perfurada",
  "obstrução", "obstrutivo", "obstrutiva",
  "invaginação", "intussuscepção", "volvo",
  // ── Descritores de imagem ──
  "hipoecoico", "hiperecoico", "anecoico", "ecogênico",
  "hipointenso", "hiperintenso", "isointenso",
  "hipodenso", "hiperdenso", "isodenso",
  "homogêneo", "heterogêneo", "heterogênea",
  "difuso", "difusa", "focal", "multifocal",
  "infiltrativo", "infiltrativa",
  "espiculado", "espiculada", "lobulado", "lobulada",
  "mal definido", "bem definido", "circunscrito",
  "irregular", "regular", "oval", "arredondado",
  "séssil", "pediculado", "pediculada",
  "captante", "realce", "realce heterogêneo",
  "restrição", "restrição à difusão",
  // ── Medidas e quantificação ──
  "milímetros", "centímetros", "milímetro", "centímetro",
  "unidades hounsfield", "hounsfield",
  "diâmetro", "transverso", "anteroposterior", "craniocaudal",
  "longitudinal", "axial", "coronal", "sagital",
  // ── Modalidades e técnicas ──
  "tomografia", "ressonância magnética", "ecografia", "ultrassonografia",
  "radiografia", "fluoroscopia", "mamografia", "densitometria",
  "angiotomografia", "angiorressonância", "angiografia",
  "contraste", "meio de contraste", "gadolínio",
  "difusão", "perfusão", "espectroscopia",
  "sequência", "ponderação", "T1", "T2", "FLAIR", "STIR",
  // ── Normalidade ──
  "normal", "sem alterações", "sem achados", "sem evidência",
  "preservado", "preservada", "dentro dos limites normais",
  "homogêneo", "calibre normal", "morfologia normal",
  "sem dilatação", "permeável", "permeáveis",
];

export const RADIOLOGY_KEYTERMS_EN: string[] = [
  // ── General anatomy ──
  "nodule", "nodules", "lobe", "lobes", "hepatic lobe",
  "parenchyma", "parenchymal",
  "mediastinum", "mediastinal",
  "retroperitoneal", "peritoneal", "retroperitoneum",
  "hilum", "hilar", "hila",
  "pleura", "pleural",
  "pericardium", "pericardial",
  "peritoneum", "omentum", "mesentery", "mesenteric",
  // ── Thoracic anatomy ──
  "apex", "apical", "upper lobe", "middle lobe", "lower lobe",
  "lingula", "lingular", "segment", "segmental",
  "bronchus", "bronchial", "bronchi", "bronchiole",
  "trachea", "tracheal", "carina", "subcarinal",
  "paratracheal", "prevascular", "pretracheal",
  "aortopulmonary", "aortopulmonary window",
  "costophrenic", "costal",
  "supraclavicular", "infraclavicular", "axillary",
  "diaphragm", "diaphragmatic", "hemidiaphragm",
  "fissure", "major fissure", "minor fissure",
  // ── Abdominal anatomy ──
  "liver", "hepatic", "caudate lobe",
  "gallbladder", "common bile duct", "biliary", "hepatic duct",
  "pancreas", "pancreatic", "wirsung",
  "spleen", "splenic",
  "kidney", "renal", "renal cortex", "renal pelvis",
  "ureter", "ureteral", "ureters",
  "bladder", "vesical",
  "aorta", "aortic",
  "vena cava", "inferior vena cava", "superior vena cava",
  "portal vein", "portal",
  "adrenal", "adrenal gland",
  "duodenum", "duodenal", "jejunum", "ileum", "ileal",
  "cecum", "appendix", "cecal",
  "colon", "colonic", "rectum", "rectal", "sigmoid",
  // ── Musculoskeletal anatomy ──
  "vertebra", "vertebral", "vertebrae",
  "cervical", "thoracic", "lumbar", "sacral", "sacrum",
  "intervertebral disc", "discal", "disc herniation",
  "spondylosis", "spondylolisthesis", "spondylolysis",
  "osteoarthritis", "arthropathy",
  "meniscus", "ligament", "ligamentous",
  "tendon", "tendinous", "tendinitis", "tendinosis",
  "cortical", "medullary", "cancellous", "trabecular",
  "epiphysis", "metaphysis", "diaphysis",
  "femur", "femoral", "tibia", "tibial", "fibula", "fibular",
  "humerus", "humeral", "radius", "ulna", "ulnar",
  "scapula", "scapular", "clavicle", "clavicular",
  "acetabulum", "acetabular", "patella", "patellar",
  "calcaneus", "talus", "tarsus", "metatarsal",
  // ── Neurological anatomy ──
  "cerebrum", "cerebral", "cerebellar",
  "thalamus", "thalamic", "hypothalamus",
  "pituitary", "sella turcica",
  "ventricle", "ventricular", "lateral ventricles",
  "white matter", "gray matter",
  "basal ganglia", "caudate nucleus", "putamen",
  "corpus callosum", "posterior fossa",
  "meninges", "meningeal", "dural", "dura mater",
  "subarachnoid", "epidural", "subdural",
  // ── Breast anatomy ──
  "breast", "mammary", "mammography",
  "axilla", "axillary", "axillary lymph node",
  "galactophorous duct", "fibroglandular tissue",
  "birads", "bi-rads",
  // ── General pathology ──
  "adenopathy", "lymphadenopathy",
  "pleural effusion", "pericardial effusion",
  "pneumothorax", "hemothorax", "hydropneumothorax",
  "atelectasis", "atelectatic",
  "consolidation", "consolidative",
  "cavitation", "cavitary",
  "empyema", "abscess", "collection",
  "embolism", "thromboembolism", "thrombus", "thrombosis",
  "hepatomegaly", "splenomegaly", "cardiomegaly",
  "hydronephrosis", "ureterhydronephrosis",
  "bronchiectasis",
  "loculated", "loculation",
  "opacity", "opacities",
  "fibrosis", "fibrotic",
  "calcification", "calcifications", "calcified",
  "necrosis", "necrotic",
  "edema", "edematous",
  "hemorrhage", "hemorrhagic", "hematoma",
  "ischemia", "ischemic",
  "infarction", "infarcted",
  "stenosis", "stenotic",
  "dilation", "dilated", "ectasia",
  "aneurysm", "aneurysmal",
  "hernia", "herniation", "herniated",
  "metastasis", "metastatic",
  "neoplasm", "neoplastic",
  "mass", "lesion", "lesions",
  "cyst", "cystic", "cysts",
  "polyp", "polyps", "polypoid",
  "lithiasis", "cholelithiasis", "nephrolithiasis", "urolithiasis",
  "calculus", "calculi",
  "steatosis", "steatotic",
  "cirrhosis", "cirrhotic",
  "ascites", "free fluid",
  "diverticulosis", "diverticulum", "diverticulitis",
  "pancreatitis", "cholecystitis", "appendicitis",
  "pneumonia", "pneumonitis",
  "emphysema", "emphysematous",
  "atherosclerosis", "atheromatous",
  "thrombophlebitis", "phlebitis",
  "fistula", "fistulous",
  "perforation", "perforated",
  "obstruction", "obstructive",
  "intussusception", "volvulus",
  // ── Image descriptors ──
  "hypoechoic", "hyperechoic", "anechoic", "echogenic",
  "hypointense", "hyperintense", "isointense",
  "hypodense", "hyperdense", "isodense",
  "homogeneous", "heterogeneous",
  "diffuse", "focal", "multifocal",
  "infiltrative",
  "spiculated", "lobulated",
  "ill-defined", "well-defined", "circumscribed",
  "irregular", "regular", "oval", "rounded",
  "sessile", "pedunculated",
  "enhancing", "enhancement", "heterogeneous enhancement",
  "restriction", "diffusion restriction",
  // ── Measurements ──
  "millimeters", "centimeters",
  "hounsfield units", "hounsfield",
  "diameter", "transverse", "anteroposterior", "craniocaudal",
  "longitudinal", "axial", "coronal", "sagittal",
  // ── Modalities ──
  "tomography", "magnetic resonance", "ultrasound", "sonography",
  "radiograph", "fluoroscopy", "mammography", "densitometry",
  "CT angiography", "MR angiography", "angiography",
  "contrast", "contrast medium", "gadolinium",
  "diffusion", "perfusion", "spectroscopy",
  "sequence", "weighting", "T1", "T2", "FLAIR", "STIR",
  // ── Normality ──
  "normal", "unremarkable", "no abnormality", "no evidence",
  "preserved", "within normal limits",
  "homogeneous", "normal caliber", "normal morphology",
  "no dilation", "patent",
];

export function getRadiologyKeyterms(language: string): string[] {
  if (language.startsWith("es")) return RADIOLOGY_KEYTERMS_ES;
  if (language.startsWith("en")) return RADIOLOGY_KEYTERMS_EN;
  if (language.startsWith("pt")) return RADIOLOGY_KEYTERMS_PT;
  return [];
}

export function resolveDeepgramLanguage(language: string): string {
  if (language === "es" || language === "es-419") return "es-419";
  if (language === "pt" || language === "pt-BR") return "pt-BR";
  return language;
}
