import type { ManualRecommendation } from "./types";

export const DEFAULT_RECOMMENDATIONS: ManualRecommendation[] = [
  // ═══════════════════════════════════════════
  // THORAX — Fleischner 2017
  // ═══════════════════════════════════════════
  {
    id: "fleisch_solid_lt6_low",
    category: "Thorax",
    modality: "CT",
    title: { es: "Sólido <6mm bajo riesgo", en: "Solid <6mm low risk", pt: "Sólido <6mm baixo risco" },
    text: {
      es: "Nódulo pulmonar sólido <6 mm en paciente de bajo riesgo. No requiere seguimiento según criterios Fleischner 2017.",
      en: "Solid pulmonary nodule <6 mm in low-risk patient. No routine follow-up required per Fleischner 2017 guidelines.",
      pt: "Nódulo pulmonar sólido <6 mm em paciente de baixo risco. Não requer seguimento segundo critérios Fleischner 2017.",
    },
    tags: ["nódulo", "nodule", "sólido", "solid", "pulmonar", "bajo riesgo", "low risk"],
    source: "Fleischner 2017 (MacMahon et al., Radiology 2017)",
    scope: "system",
  },
  {
    id: "fleisch_solid_lt6_high",
    category: "Thorax",
    modality: "CT",
    title: { es: "Sólido <6mm alto riesgo", en: "Solid <6mm high risk", pt: "Sólido <6mm alto risco" },
    text: {
      es: "Nódulo pulmonar sólido <6 mm en paciente de alto riesgo. Se recomienda TC de control opcional a los 12 meses (Fleischner 2017).",
      en: "Solid pulmonary nodule <6 mm in high-risk patient. Optional follow-up CT at 12 months recommended (Fleischner 2017).",
      pt: "Nódulo pulmonar sólido <6 mm em paciente de alto risco. TC de controle opcional em 12 meses recomendado (Fleischner 2017).",
    },
    tags: ["nódulo", "nodule", "sólido", "solid", "pulmonar", "alto riesgo", "high risk"],
    source: "Fleischner 2017",
    scope: "system",
  },
  {
    id: "fleisch_solid_6to8_low",
    category: "Thorax",
    modality: "CT",
    title: { es: "Sólido 6-8mm bajo riesgo", en: "Solid 6-8mm low risk", pt: "Sólido 6-8mm baixo risco" },
    text: {
      es: "Nódulo pulmonar sólido de 6-8 mm en paciente de bajo riesgo. Se recomienda TC de control en 6-12 meses; considerar TC adicional a los 18-24 meses (Fleischner 2017).",
      en: "Solid pulmonary nodule 6-8 mm in low-risk patient. Follow-up CT at 6-12 months recommended; consider CT at 18-24 months (Fleischner 2017).",
      pt: "Nódulo pulmonar sólido de 6-8 mm em paciente de baixo risco. TC de controle em 6-12 meses recomendado; considerar TC adicional em 18-24 meses (Fleischner 2017).",
    },
    tags: ["nódulo", "nodule", "sólido", "solid", "pulmonar", "6 mm", "7 mm", "8 mm"],
    source: "Fleischner 2017",
    scope: "system",
  },
  {
    id: "fleisch_solid_6to8_high",
    category: "Thorax",
    modality: "CT",
    title: { es: "Sólido 6-8mm alto riesgo", en: "Solid 6-8mm high risk", pt: "Sólido 6-8mm alto risco" },
    text: {
      es: "Nódulo pulmonar sólido de 6-8 mm en paciente de alto riesgo. Se recomienda TC de control en 6-12 meses, y TC adicional a los 18-24 meses (Fleischner 2017).",
      en: "Solid pulmonary nodule 6-8 mm in high-risk patient. Follow-up CT at 6-12 months, then CT at 18-24 months recommended (Fleischner 2017).",
      pt: "Nódulo pulmonar sólido de 6-8 mm em paciente de alto risco. TC de controle em 6-12 meses, depois TC em 18-24 meses recomendado (Fleischner 2017).",
    },
    tags: ["nódulo", "nodule", "sólido", "solid", "pulmonar", "alto riesgo", "high risk"],
    source: "Fleischner 2017",
    scope: "system",
  },
  {
    id: "fleisch_solid_gt8",
    category: "Thorax",
    modality: "CT",
    title: { es: "Sólido >8mm", en: "Solid >8mm", pt: "Sólido >8mm" },
    text: {
      es: "Nódulo pulmonar sólido >8 mm. Considerar TC de control a los 3 meses, PET/TC o toma de muestra tisular (Fleischner 2017).",
      en: "Solid pulmonary nodule >8 mm. Consider CT at 3 months, PET/CT, or tissue sampling (Fleischner 2017).",
      pt: "Nódulo pulmonar sólido >8 mm. Considerar TC em 3 meses, PET/TC ou biópsia (Fleischner 2017).",
    },
    tags: ["nódulo", "nodule", "sólido", "solid", "pulmonar", "PET", "biopsia"],
    source: "Fleischner 2017",
    scope: "system",
  },
  {
    id: "fleisch_ggn_lt6",
    category: "Thorax",
    modality: "CT",
    title: { es: "Vidrio deslustrado <6mm", en: "GGN <6mm", pt: "Vidro fosco <6mm" },
    text: {
      es: "Nódulo pulmonar en vidrio deslustrado <6 mm. No requiere seguimiento de rutina (Fleischner 2017).",
      en: "Ground-glass nodule <6 mm. No routine follow-up required (Fleischner 2017).",
      pt: "Nódulo em vidro fosco <6 mm. Não requer seguimento de rotina (Fleischner 2017).",
    },
    tags: ["vidrio", "deslustrado", "ground-glass", "GGN", "subsólido", "subsolid"],
    source: "Fleischner 2017",
    scope: "system",
  },
  {
    id: "fleisch_ggn_ge6",
    category: "Thorax",
    modality: "CT",
    title: { es: "Vidrio deslustrado ≥6mm", en: "GGN ≥6mm", pt: "Vidro fosco ≥6mm" },
    text: {
      es: "Nódulo pulmonar en vidrio deslustrado ≥6 mm. Se recomienda TC de control en 6-12 meses para confirmar persistencia, luego TC cada 2 años hasta completar 5 años (Fleischner 2017).",
      en: "Ground-glass nodule ≥6 mm. Follow-up CT at 6-12 months to confirm persistence, then CT every 2 years for 5 years (Fleischner 2017).",
      pt: "Nódulo em vidro fosco ≥6 mm. TC de controle em 6-12 meses para confirmar persistência, depois TC a cada 2 anos por 5 anos (Fleischner 2017).",
    },
    tags: ["vidrio", "deslustrado", "ground-glass", "GGN", "subsólido", "subsolid"],
    source: "Fleischner 2017",
    scope: "system",
  },
  {
    id: "fleisch_partsolid_lt6",
    category: "Thorax",
    modality: "CT",
    title: { es: "Parcialmente sólido <6mm", en: "Part-solid <6mm", pt: "Parcialmente sólido <6mm" },
    text: {
      es: "Nódulo pulmonar parcialmente sólido <6 mm. No requiere seguimiento de rutina (Fleischner 2017).",
      en: "Part-solid pulmonary nodule <6 mm. No routine follow-up required (Fleischner 2017).",
      pt: "Nódulo parcialmente sólido <6 mm. Não requer seguimento de rotina (Fleischner 2017).",
    },
    tags: ["parcialmente", "part-solid", "subsólido", "subsolid", "mixto"],
    source: "Fleischner 2017",
    scope: "system",
  },
  {
    id: "fleisch_partsolid_ge6",
    category: "Thorax",
    modality: "CT",
    title: { es: "Parcialmente sólido ≥6mm", en: "Part-solid ≥6mm", pt: "Parcialmente sólido ≥6mm" },
    text: {
      es: "Nódulo pulmonar parcialmente sólido ≥6 mm. Se recomienda TC de control en 3-6 meses para confirmar persistencia; si persiste con componente sólido <6 mm, TC anual durante 5 años (Fleischner 2017).",
      en: "Part-solid pulmonary nodule ≥6 mm. Follow-up CT at 3-6 months; if persistent with solid component <6 mm, annual CT for 5 years (Fleischner 2017).",
      pt: "Nódulo parcialmente sólido ≥6 mm. TC de controle em 3-6 meses; se persistente com componente sólido <6 mm, TC anual por 5 anos (Fleischner 2017).",
    },
    tags: ["parcialmente", "part-solid", "subsólido", "subsolid", "mixto", "componente sólido"],
    source: "Fleischner 2017",
    scope: "system",
  },

  // ═══════════════════════════════════════════
  // THORAX — BTS 2015
  // ═══════════════════════════════════════════
  {
    id: "bts_lt5mm",
    category: "Thorax",
    modality: "CT",
    title: { es: "BTS <5mm / <80mm³", en: "BTS <5mm / <80mm³", pt: "BTS <5mm / <80mm³" },
    text: {
      es: "Nódulo pulmonar <5 mm (<80 mm³). No requiere seguimiento según guías BTS 2015.",
      en: "Pulmonary nodule <5 mm (<80 mm³). No follow-up required per BTS 2015 guidelines.",
      pt: "Nódulo pulmonar <5 mm (<80 mm³). Não requer seguimento segundo diretrizes BTS 2015.",
    },
    tags: ["nódulo", "nodule", "BTS", "volumetría", "volumetry"],
    source: "BTS 2015 (Callister et al., Thorax 2015)",
    scope: "system",
  },
  {
    id: "bts_5to6mm",
    category: "Thorax",
    modality: "CT",
    title: { es: "BTS 5-6mm / 80-300mm³", en: "BTS 5-6mm / 80-300mm³", pt: "BTS 5-6mm / 80-300mm³" },
    text: {
      es: "Nódulo pulmonar 5-6 mm (80-300 mm³). Se recomienda TC de control con volumetría a los 3 meses; si estable, alta (BTS 2015).",
      en: "Pulmonary nodule 5-6 mm (80-300 mm³). Follow-up CT with volumetry at 3 months; if stable, discharge (BTS 2015).",
      pt: "Nódulo pulmonar 5-6 mm (80-300 mm³). TC de controle com volumetria em 3 meses; se estável, alta (BTS 2015).",
    },
    tags: ["nódulo", "nodule", "BTS", "volumetría", "volumetry"],
    source: "BTS 2015",
    scope: "system",
  },
  {
    id: "bts_gt6mm",
    category: "Thorax",
    modality: "CT",
    title: { es: "BTS >6mm / >300mm³", en: "BTS >6mm / >300mm³", pt: "BTS >6mm / >300mm³" },
    text: {
      es: "Nódulo pulmonar >6 mm (>300 mm³). Se recomienda TC con volumetría a los 3 meses. Si VDT <400 días: considerar biopsia/resección; VDT 400-600 días: TC al año y a los 2 años; VDT >600 días: alta (BTS 2015).",
      en: "Pulmonary nodule >6 mm (>300 mm³). Follow-up CT with volumetry at 3 months. If VDT <400 days: consider biopsy/resection; VDT 400-600 days: CT at 1 and 2 years; VDT >600 days: discharge (BTS 2015).",
      pt: "Nódulo pulmonar >6 mm (>300 mm³). TC com volumetria em 3 meses. Se TDV <400 dias: considerar biópsia/ressecção; TDV 400-600 dias: TC em 1 e 2 anos; TDV >600 dias: alta (BTS 2015).",
    },
    tags: ["nódulo", "nodule", "BTS", "volumetría", "VDT", "duplicación", "doubling"],
    source: "BTS 2015",
    scope: "system",
  },

  // ═══════════════════════════════════════════
  // THORAX — Other
  // ═══════════════════════════════════════════
  {
    id: "thyroid_incidental_ct",
    category: "Thorax",
    modality: "CT",
    title: { es: "Nódulo tiroideo incidental", en: "Incidental thyroid nodule", pt: "Nódulo tireoidiano incidental" },
    text: {
      es: "Nódulo tiroideo incidental >1 cm identificado en TC. Se recomienda valoración ecográfica para caracterización (ACR 2015).",
      en: "Incidental thyroid nodule >1 cm identified on CT. Ultrasound evaluation recommended for characterization (ACR 2015).",
      pt: "Nódulo tireoidiano incidental >1 cm identificado em TC. Avaliação ecográfica recomendada para caracterização (ACR 2015).",
    },
    tags: ["tiroides", "thyroid", "nódulo", "incidental", "incidentaloma"],
    source: "ACR Incidental Thyroid Findings 2015",
    scope: "system",
  },

  // ═══════════════════════════════════════════
  // ABDOMEN
  // ═══════════════════════════════════════════
  {
    id: "liver_simple_cyst",
    category: "Abdomen and pelvis",
    modality: "all",
    title: { es: "Quiste hepático simple", en: "Simple hepatic cyst", pt: "Cisto hepático simples" },
    text: {
      es: "Quiste hepático simple. No requiere seguimiento según criterios ACR (hallazgo benigno sin significancia clínica).",
      en: "Simple hepatic cyst. No follow-up required per ACR criteria (benign finding without clinical significance).",
      pt: "Cisto hepático simples. Não requer seguimento segundo critérios ACR (achado benigno sem significância clínica).",
    },
    tags: ["quiste", "cyst", "hepático", "hepatic", "hígado", "liver", "simple"],
    source: "ACR Incidental Findings 2017",
    scope: "system",
  },
  {
    id: "liver_hemangioma",
    category: "Abdomen and pelvis",
    modality: "all",
    title: { es: "Hemangioma hepático típico", en: "Typical hepatic hemangioma", pt: "Hemangioma hepático típico" },
    text: {
      es: "Hemangioma hepático de aspecto típico. No requiere seguimiento (hallazgo benigno).",
      en: "Typical hepatic hemangioma. No follow-up required (benign finding).",
      pt: "Hemangioma hepático de aspecto típico. Não requer seguimento (achado benigno).",
    },
    tags: ["hemangioma", "hepático", "hepatic", "hígado", "liver", "benigno", "benign"],
    source: "ACR Incidental Findings 2017",
    scope: "system",
  },
  {
    id: "liver_indeterminate",
    category: "Abdomen and pelvis",
    modality: "CT",
    title: { es: "Lesión hepática indeterminada", en: "Indeterminate liver lesion", pt: "Lesão hepática indeterminada" },
    text: {
      es: "Lesión hepática de caracterización indeterminada en TC. Se recomienda RM hepática con contraste hepatoespecífico para mejor caracterización.",
      en: "Indeterminate liver lesion on CT. Hepatobiliary MRI with hepatocyte-specific contrast recommended for further characterization.",
      pt: "Lesão hepática de caracterização indeterminada em TC. RM hepática com contraste hepatoespecífico recomendada para melhor caracterização.",
    },
    tags: ["hepático", "hepatic", "hígado", "liver", "lesión", "lesion", "indeterminada", "indeterminate", "RM", "MRI"],
    source: "ACR Incidental Findings 2017",
    scope: "system",
  },
  {
    id: "lirads_3",
    category: "Abdomen and pelvis",
    modality: "CT",
    title: { es: "LI-RADS 3: seguimiento", en: "LI-RADS 3: follow-up", pt: "LI-RADS 3: seguimento" },
    text: {
      es: "Observación hepática LI-RADS 3. Se recomienda repetir estudio con contraste o modalidad alternativa en 3-6 meses (ACR LI-RADS v2018).",
      en: "LI-RADS 3 hepatic observation. Repeat or alternative contrast-enhanced imaging in 3-6 months recommended (ACR LI-RADS v2018).",
      pt: "Observação hepática LI-RADS 3. Repetir estudo contrastado ou modalidade alternativa em 3-6 meses recomendado (ACR LI-RADS v2018).",
    },
    tags: ["LI-RADS", "hepático", "hepatic", "hepatocarcinoma", "HCC", "cirrosis", "cirrhosis"],
    source: "ACR LI-RADS v2018",
    scope: "system",
  },
  {
    id: "renal_bosniak_iif",
    category: "Abdomen and pelvis",
    modality: "CT",
    title: { es: "Bosniak IIF: seguimiento", en: "Bosniak IIF: follow-up", pt: "Bosniak IIF: seguimento" },
    text: {
      es: "Lesión renal quística Bosniak IIF. Se recomienda seguimiento con imagen a los 6 y 12 meses para confirmar estabilidad (Bosniak 2019).",
      en: "Bosniak IIF cystic renal lesion. Follow-up imaging at 6 and 12 months to confirm stability recommended (Bosniak 2019).",
      pt: "Lesão renal cística Bosniak IIF. Seguimento por imagem em 6 e 12 meses para confirmar estabilidade recomendado (Bosniak 2019).",
    },
    tags: ["Bosniak", "renal", "quiste", "cyst", "quístico", "cystic", "riñón", "kidney"],
    source: "Bosniak Classification v2019 (Silverman et al., Radiology 2019)",
    scope: "system",
  },
  {
    id: "renal_bosniak_iii",
    category: "Abdomen and pelvis",
    modality: "CT",
    title: { es: "Bosniak III: cirugía", en: "Bosniak III: surgery", pt: "Bosniak III: cirurgia" },
    text: {
      es: "Lesión renal quística Bosniak III. Se recomienda valoración quirúrgica o vigilancia activa según contexto clínico (Bosniak 2019).",
      en: "Bosniak III cystic renal lesion. Surgical evaluation or active surveillance recommended depending on clinical context (Bosniak 2019).",
      pt: "Lesão renal cística Bosniak III. Avaliação cirúrgica ou vigilância ativa recomendada conforme contexto clínico (Bosniak 2019).",
    },
    tags: ["Bosniak", "renal", "quiste", "cyst", "riñón", "kidney", "cirugía", "surgery"],
    source: "Bosniak Classification v2019",
    scope: "system",
  },
  {
    id: "adrenal_lt1cm",
    category: "Abdomen and pelvis",
    modality: "CT",
    title: { es: "Adrenal <1cm", en: "Adrenal <1cm", pt: "Adrenal <1cm" },
    text: {
      es: "Lesión adrenal <1 cm. Probablemente benigna; no requiere seguimiento en ausencia de antecedente neoplásico (ACR 2017).",
      en: "Adrenal lesion <1 cm. Likely benign; no follow-up required in the absence of known malignancy (ACR 2017).",
      pt: "Lesão adrenal <1 cm. Provavelmente benigna; não requer seguimento na ausência de antecedente neoplásico (ACR 2017).",
    },
    tags: ["adrenal", "suprarrenal", "incidentaloma", "adenoma"],
    source: "ACR Incidental Adrenal Findings 2017",
    scope: "system",
  },
  {
    id: "adrenal_1to4cm",
    category: "Abdomen and pelvis",
    modality: "CT",
    title: { es: "Adrenal 1-4cm: caracterizar", en: "Adrenal 1-4cm: characterize", pt: "Adrenal 1-4cm: caracterizar" },
    text: {
      es: "Lesión adrenal de 1-4 cm. Se recomienda TC con protocolo de lavado adrenal o RM con secuencia de desplazamiento químico para caracterización (ACR 2017).",
      en: "Adrenal lesion 1-4 cm. Adrenal washout CT or chemical shift MRI recommended for characterization (ACR 2017).",
      pt: "Lesão adrenal de 1-4 cm. TC com protocolo de lavado adrenal ou RM com sequência de deslocamento químico para caracterização (ACR 2017).",
    },
    tags: ["adrenal", "suprarrenal", "incidentaloma", "lavado", "washout", "adenoma"],
    source: "ACR Incidental Adrenal Findings 2017",
    scope: "system",
  },
  {
    id: "adrenal_gt4cm",
    category: "Abdomen and pelvis",
    modality: "CT",
    title: { es: "Adrenal >4cm: cirugía", en: "Adrenal >4cm: surgery", pt: "Adrenal >4cm: cirurgia" },
    text: {
      es: "Lesión adrenal >4 cm. Se recomienda valoración quirúrgica y estudio bioquímico funcional (ACR 2017).",
      en: "Adrenal lesion >4 cm. Surgical evaluation and functional biochemical workup recommended (ACR 2017).",
      pt: "Lesão adrenal >4 cm. Avaliação cirúrgica e estudo bioquímico funcional recomendados (ACR 2017).",
    },
    tags: ["adrenal", "suprarrenal", "incidentaloma", "cirugía", "surgery", "masa"],
    source: "ACR Incidental Adrenal Findings 2017",
    scope: "system",
  },
  {
    id: "pancreas_cyst_lt15",
    category: "Abdomen and pelvis",
    modality: "all",
    title: { es: "Quiste pancreático <1.5cm", en: "Pancreatic cyst <1.5cm", pt: "Cisto pancreático <1.5cm" },
    text: {
      es: "Lesión quística pancreática <1.5 cm sin características preocupantes. Se recomienda RM de control en 2 años (ACR/AGA 2015).",
      en: "Pancreatic cystic lesion <1.5 cm without worrisome features. Follow-up MRI in 2 years recommended (ACR/AGA 2015).",
      pt: "Lesão cística pancreática <1.5 cm sem características preocupantes. RM de controle em 2 anos recomendada (ACR/AGA 2015).",
    },
    tags: ["páncreas", "pancreas", "quiste", "cyst", "IPMN", "mucinoso"],
    source: "ACR Incidental Findings 2017 / AGA Guidelines 2015",
    scope: "system",
  },
  {
    id: "pancreas_cyst_ge3",
    category: "Abdomen and pelvis",
    modality: "all",
    title: { es: "Quiste pancreático ≥3cm", en: "Pancreatic cyst ≥3cm", pt: "Cisto pancreático ≥3cm" },
    text: {
      es: "Lesión quística pancreática ≥3 cm o con características preocupantes. Se recomienda valoración con ecoendoscopia (EUS) y posible punción (ACR/AGA 2015).",
      en: "Pancreatic cystic lesion ≥3 cm or with worrisome features. Endoscopic ultrasound (EUS) with possible aspiration recommended (ACR/AGA 2015).",
      pt: "Lesão cística pancreática ≥3 cm ou com características preocupantes. Ecoendoscopia (EUS) com possível punção recomendada (ACR/AGA 2015).",
    },
    tags: ["páncreas", "pancreas", "quiste", "cyst", "IPMN", "preocupante", "worrisome", "EUS"],
    source: "ACR/AGA 2015",
    scope: "system",
  },
  {
    id: "ovarian_premenop_lt5",
    category: "Abdomen and pelvis",
    modality: "Ultrasound",
    title: { es: "Quiste ovárico simple <5cm", en: "Simple ovarian cyst <5cm", pt: "Cisto ovariano simples <5cm" },
    text: {
      es: "Quiste ovárico simple <5 cm en paciente premenopáusica. Probablemente funcional. Se recomienda ecografía de control en 8-12 semanas (ACR/SRU 2019).",
      en: "Simple ovarian cyst <5 cm in premenopausal patient. Likely functional. Follow-up ultrasound at 8-12 weeks recommended (ACR/SRU 2019).",
      pt: "Cisto ovariano simples <5 cm em paciente pré-menopausa. Provavelmente funcional. Ecografia de controle em 8-12 semanas recomendada (ACR/SRU 2019).",
    },
    tags: ["ovario", "ovarian", "quiste", "cyst", "funcional", "functional", "premenopáusica"],
    source: "ACR/SRU Incidental Ovarian Findings 2019",
    scope: "system",
  },
  {
    id: "gb_polyp_lt6",
    category: "Abdomen and pelvis",
    modality: "Ultrasound",
    title: { es: "Pólipo vesicular <6mm", en: "GB polyp <6mm", pt: "Pólipo vesicular <6mm" },
    text: {
      es: "Pólipo de vesícula biliar <6 mm. No requiere seguimiento en ausencia de factores de riesgo (guías ESGAR 2017).",
      en: "Gallbladder polyp <6 mm. No follow-up required in the absence of risk factors (ESGAR 2017 guidelines).",
      pt: "Pólipo de vesícula biliar <6 mm. Não requer seguimento na ausência de fatores de risco (diretrizes ESGAR 2017).",
    },
    tags: ["pólipo", "polyp", "vesícula", "gallbladder", "biliar"],
    source: "ESGAR/EAES Guidelines 2017",
    scope: "system",
  },
  {
    id: "gb_polyp_6to9",
    category: "Abdomen and pelvis",
    modality: "Ultrasound",
    title: { es: "Pólipo vesicular 6-9mm", en: "GB polyp 6-9mm", pt: "Pólipo vesicular 6-9mm" },
    text: {
      es: "Pólipo de vesícula biliar de 6-9 mm. Se recomienda ecografía de control en 6 meses, luego anual durante 2 años (ESGAR 2017).",
      en: "Gallbladder polyp 6-9 mm. Follow-up ultrasound at 6 months, then annually for 2 years recommended (ESGAR 2017).",
      pt: "Pólipo de vesícula biliar de 6-9 mm. Ecografia de controle em 6 meses, depois anual por 2 anos recomendada (ESGAR 2017).",
    },
    tags: ["pólipo", "polyp", "vesícula", "gallbladder", "biliar"],
    source: "ESGAR/EAES Guidelines 2017",
    scope: "system",
  },
  {
    id: "gb_polyp_ge10",
    category: "Abdomen and pelvis",
    modality: "Ultrasound",
    title: { es: "Pólipo vesicular ≥10mm", en: "GB polyp ≥10mm", pt: "Pólipo vesicular ≥10mm" },
    text: {
      es: "Pólipo de vesícula biliar ≥10 mm. Se recomienda valoración quirúrgica (colecistectomía) dado el riesgo de malignidad (ESGAR 2017).",
      en: "Gallbladder polyp ≥10 mm. Surgical evaluation (cholecystectomy) recommended given malignancy risk (ESGAR 2017).",
      pt: "Pólipo de vesícula biliar ≥10 mm. Avaliação cirúrgica (colecistectomia) recomendada dado o risco de malignidade (ESGAR 2017).",
    },
    tags: ["pólipo", "polyp", "vesícula", "gallbladder", "biliar", "colecistectomía"],
    source: "ESGAR/EAES Guidelines 2017",
    scope: "system",
  },

  // ═══════════════════════════════════════════
  // NEURO
  // ═══════════════════════════════════════════
  {
    id: "meningioma_lt2",
    category: "Head and neck",
    modality: "MRI",
    title: { es: "Meningioma incidental <2cm", en: "Incidental meningioma <2cm", pt: "Meningioma incidental <2cm" },
    text: {
      es: "Meningioma incidental <2 cm. Se recomienda RM de control al año; si estable, considerar RM cada 2-3 años (EANO 2016).",
      en: "Incidental meningioma <2 cm. Follow-up MRI at 1 year recommended; if stable, consider MRI every 2-3 years (EANO 2016).",
      pt: "Meningioma incidental <2 cm. RM de controle em 1 ano recomendada; se estável, considerar RM a cada 2-3 anos (EANO 2016).",
    },
    tags: ["meningioma", "incidental", "extra-axial", "dural"],
    source: "EANO Guidelines 2016",
    scope: "system",
  },
  {
    id: "aneurysm_lt5mm",
    category: "Head and neck",
    modality: "all",
    title: { es: "Aneurisma cerebral <5mm", en: "Cerebral aneurysm <5mm", pt: "Aneurisma cerebral <5mm" },
    text: {
      es: "Aneurisma intracraneal <5 mm. Se recomienda seguimiento con angio-RM o angio-TC según guías AHA/ASA. Valoración individualizada del riesgo.",
      en: "Intracranial aneurysm <5 mm. Follow-up with MRA or CTA per AHA/ASA guidelines. Individualized risk assessment recommended.",
      pt: "Aneurisma intracraniano <5 mm. Seguimento com angio-RM ou angio-TC conforme diretrizes AHA/ASA. Avaliação individualizada do risco recomendada.",
    },
    tags: ["aneurisma", "aneurysm", "intracraneal", "intracranial", "cerebral", "ACI", "ACM", "MCA"],
    source: "AHA/ASA Guidelines 2015",
    scope: "system",
  },

  // ═══════════════════════════════════════════
  // VASCULAR
  // ═══════════════════════════════════════════
  {
    id: "aaa_3to4",
    category: "Abdomen and pelvis",
    modality: "all",
    title: { es: "AAA 3-4cm: eco anual", en: "AAA 3-4cm: annual US", pt: "AAA 3-4cm: eco anual" },
    text: {
      es: "Aneurisma de aorta abdominal de 3-4 cm. Se recomienda ecografía de control anual (SVS 2018).",
      en: "Abdominal aortic aneurysm 3-4 cm. Annual follow-up ultrasound recommended (SVS 2018).",
      pt: "Aneurisma de aorta abdominal de 3-4 cm. Ecografia de controle anual recomendada (SVS 2018).",
    },
    tags: ["aneurisma", "aneurysm", "aorta", "abdominal", "AAA"],
    source: "SVS Practice Guidelines 2018",
    scope: "system",
  },
  {
    id: "aaa_4to55",
    category: "Abdomen and pelvis",
    modality: "all",
    title: { es: "AAA 4-5.5cm: eco 6 meses", en: "AAA 4-5.5cm: US 6 months", pt: "AAA 4-5.5cm: eco 6 meses" },
    text: {
      es: "Aneurisma de aorta abdominal de 4-5.5 cm. Se recomienda ecografía o TC de control cada 6 meses (SVS 2018).",
      en: "Abdominal aortic aneurysm 4-5.5 cm. Follow-up ultrasound or CT every 6 months recommended (SVS 2018).",
      pt: "Aneurisma de aorta abdominal de 4-5.5 cm. Ecografia ou TC de controle a cada 6 meses recomendada (SVS 2018).",
    },
    tags: ["aneurisma", "aneurysm", "aorta", "abdominal", "AAA"],
    source: "SVS Practice Guidelines 2018",
    scope: "system",
  },
  {
    id: "aaa_gt55",
    category: "Abdomen and pelvis",
    modality: "all",
    title: { es: "AAA >5.5cm: cirugía", en: "AAA >5.5cm: surgery", pt: "AAA >5.5cm: cirurgia" },
    text: {
      es: "Aneurisma de aorta abdominal >5.5 cm. Se recomienda valoración quirúrgica urgente (reparación abierta o endovascular) (SVS 2018).",
      en: "Abdominal aortic aneurysm >5.5 cm. Urgent surgical evaluation (open or endovascular repair) recommended (SVS 2018).",
      pt: "Aneurisma de aorta abdominal >5.5 cm. Avaliação cirúrgica urgente (reparo aberto ou endovascular) recomendada (SVS 2018).",
    },
    tags: ["aneurisma", "aneurysm", "aorta", "abdominal", "AAA", "cirugía", "surgery"],
    source: "SVS Practice Guidelines 2018",
    scope: "system",
  },

  // ═══════════════════════════════════════════
  // MSK
  // ═══════════════════════════════════════════
  {
    id: "bone_lesion_benign",
    category: "Upper limbs",
    modality: "XRay",
    title: { es: "Lesión ósea probablemente benigna", en: "Likely benign bone lesion", pt: "Lesão óssea provavelmente benigna" },
    text: {
      es: "Lesión ósea de aspecto probablemente benigno. Se recomienda radiografía de control en 6 meses para confirmar estabilidad.",
      en: "Likely benign bone lesion. Follow-up radiograph at 6 months to confirm stability recommended.",
      pt: "Lesão óssea de aspecto provavelmente benigno. Radiografia de controle em 6 meses para confirmar estabilidade recomendada.",
    },
    tags: ["lesión ósea", "bone lesion", "óseo", "bone", "benigno", "benign", "fibroma", "encondroma"],
    source: "ACR Appropriateness Criteria",
    scope: "system",
  },
  {
    id: "compression_fx_atypical",
    category: "Spine",
    modality: "all",
    title: { es: "Fractura vertebral atípica: RM", en: "Atypical vertebral fracture: MRI", pt: "Fratura vertebral atípica: RM" },
    text: {
      es: "Fractura por compresión vertebral con rasgos atípicos. Se recomienda RM de columna para descartar origen patológico/tumoral.",
      en: "Vertebral compression fracture with atypical features. Spine MRI recommended to exclude pathologic/neoplastic etiology.",
      pt: "Fratura por compressão vertebral com características atípicas. RM de coluna recomendada para excluir etiologia patológica/tumoral.",
    },
    tags: ["fractura", "fracture", "compresión", "compression", "vertebral", "patológica", "pathologic", "tumor"],
    source: "ACR Appropriateness Criteria",
    scope: "system",
  },
];
