import type { OutputLanguage } from "./types";

const ES: Record<string, string> = {
  "Lung parenchyma": "Parénquima pulmonar",
  "Mediastinum and hila": "Mediastino e hilios",
  "Cardiac silhouette": "Silueta cardíaca",
  "Pleura and diaphragm": "Pleura y diafragma",
  "Bone structures": "Estructuras óseas",
  "Soft tissues": "Partes blandas",
  "Bowel gas pattern": "Patrón de gas intestinal",
  "Solid organ outlines": "Contornos de órganos sólidos",
  "Peritoneal fat planes": "Planos grasos peritoneales",
  "Other findings": "Otros hallazgos",
  "Supratentorial brain parenchyma": "Parénquima cerebral supratentorial",
  "Infratentorial brain parenchyma": "Parénquima cerebral infratentorial",
  "Ventricular system and midline": "Sistema ventricular y línea media",
  "Extra-axial spaces": "Espacios extra-axiales",
  "Skull and extracranial soft tissues": "Cráneo y partes blandas extracraneales",
  "Paranasal sinuses and mastoid cells": "Senos paranasales y celdillas mastoideas",
  "Included cervical structures": "Estructuras cervicales incluidas",
  "Parotids": "Parótidas",
  "Submandibular glands": "Glándulas submandibulares",
  "Nasopharynx": "Nasofaringe",
  "Oropharynx": "Orofaringe",
  "Vocal cords": "Cuerdas vocales",
  "Piriform sinuses": "Senos piriformes",
  "Epiglottis": "Epiglotis",
  "Trachea and cervical esophagus": "Tráquea y esófago cervical",
  "Thyroid gland": "Glándula tiroides",
  "Parapharyngeal and retropharyngeal spaces": "Espacios parafaríngeo y retrofaríngeo",
  "Cervical vascular structures": "Estructuras vasculares cervicales",
  "Cervical lymph nodes": "Ganglios linfáticos cervicales",
  "Salivary glands": "Glándulas salivales",
  "Cervical spine": "Columna cervical",
  "Mediastinal lymph nodes": "Ganglios linfáticos mediastínicos",
  "Mediastinum": "Mediastino",
  "Trachea and bronchi": "Tráquea y bronquios",
  "Trachea": "Tráquea",
  "Esophagus": "Esófago",
  "Coronary arteries": "Arterias coronarias",
  "Aorta and pulmonary arteries": "Aorta y arterias pulmonares",
  "Aorta and pulmonary artery": "Aorta y arteria pulmonar",
  "Aorta and great vessels": "Aorta y grandes vasos",
  "Heart and pericardium": "Corazón y pericardio",
  "Pleura": "Pleura",
  "Diaphragm": "Diafragma",
  "Thoracic wall": "Pared torácica",
  "Thoracic wall and bone structures": "Pared torácica y estructuras óseas",
  "Thyroid and supradiaphragmatic tissues": "Tiroides y tejidos supradiafragmáticos",
  "Supradiaphragmatic tissues and thyroid": "Tiroides y tejidos supradiafragmáticos",
  "Included portions of the abdomen": "Porciones incluidas del abdomen",
  "Included portions of the thorax": "Porciones incluidas del tórax",
  "Liver": "Hígado",
  "Liver parenchyma": "Parénquima hepático",
  "Liver and spleen": "Hígado y bazo",
  "Hepatic focal lesions": "Lesiones focales hepáticas",
  "Portal vein and hepatic artery": "Vena porta y arteria hepática",
  "Portal vein and hepatic veins": "Vena porta y venas hepáticas",
  "Portal vein": "Vena porta",
  "Hepatic artery": "Arteria hepática",
  "Gallbladder": "Vesícula biliar",
  "Gallbladder and bile ducts": "Vesícula biliar y vías biliares",
  "Bile ducts": "Vías biliares",
  "Intrahepatic and extrahepatic biliary ducts": "Vías biliares intrahepáticas y extrahepáticas",
  "Spleen": "Bazo",
  "Pancreas": "Páncreas",
  "Pancreatic duct": "Conducto pancreático",
  "Peripancreatic fat and vessels": "Grasa peripancreática y vasos",
  "Adrenal glands": "Glándulas suprarrenales",
  "Adrenal glands and kidneys": "Glándulas suprarrenales y riñones",
  "Kidneys and ureters": "Riñones y uréteres",
  "Kidneys": "Riñones",
  "Right kidney": "Riñón derecho",
  "Left kidney": "Riñón izquierdo",
  "Bladder": "Vejiga",
  "Peritoneum and retroperitoneum": "Peritoneo y retroperitoneo",
  "Peritoneum, retroperitoneum": "Peritoneo y retroperitoneo",
  "Peritoneum retroperitoneum": "Peritoneo y retroperitoneo",
  "Peritoneum": "Peritoneo",
  "Stomach": "Estómago",
  "Stomach and bowel": "Estómago e intestino",
  "Small bowel and colon": "Intestino delgado y colon",
  "Small bowel loops and colon": "Asas de intestino delgado y colon",
  "Other pelvic structures": "Otras estructuras pélvicas",
  "Pelvic structures": "Estructuras pélvicas",
  "Pelvic organs": "Órganos pélvicos",
  "Pelvic lymph nodes": "Ganglios linfáticos pélvicos",
  "Abdominal aorta and iliac arteries": "Aorta abdominal y arterias ilíacas",
  "Abdominal aorta": "Aorta abdominal",
  "Iliac arteries": "Arterias ilíacas",
  "Intraabdominal organs": "Órganos intraabdominales",
  "Intraabdominal solid organs": "Órganos sólidos intraabdominales",
  "Other intraabdominal structures": "Otras estructuras intraabdominales",
  "Other thoracic structures": "Otras estructuras torácicas",
  "Other thoracic and abdominal structures": "Otras estructuras torácicas y abdominales",
  "Other mediastinal findings": "Otros hallazgos mediastínicos",
  "Bone structures and soft tissues": "Estructuras óseas y partes blandas",
  "Bone structures and included portions of the thorax": "Estructuras óseas y porciones incluidas del tórax",
  "Spine": "Columna vertebral",
  "Bone density": "Densidad ósea",
  "Vertebral bodies": "Cuerpos vertebrales",
  "Intervertebral spaces and discs": "Espacios y discos intervertebrales",
  "Intervertebral discs": "Discos intervertebrales",
  "Spinal cord": "Médula espinal",
  "Neural foramina": "Forámenes neurales",
  "Ligaments": "Ligamentos",
  "Craniocervical junction": "Unión craneocervical",
  "Conus medullaris and cauda equina": "Cono medular y cola de caballo",
  "Uterus": "Útero",
  "Endometrium": "Endometrio",
  "Cervix": "Cérvix",
  "Ovaries": "Ovarios",
  "Fallopian tubes": "Trompas de Falopio",
  "Vagina": "Vagina",
  "Rectum and sigmoid": "Recto y sigma",
  "Rectum": "Recto",
  "Mesorectum": "Mesorrecto",
  "Mesorectal fascia": "Fascia mesorrectal",
  "Perianal soft tissues": "Partes blandas perianales",
  "Sphincters": "Esfínteres",
  "Other perineal structures": "Otras estructuras perineales",
  "General prostate assessment": "Valoración general de la próstata",
  "Peripheral zone": "Zona periférica",
  "Transition zone": "Zona de transición",
  "Seminal vesicles": "Vesículas seminales",
  "Bone structures and periprostatic tissues": "Estructuras óseas y tejidos periprostáticos",
  "Lymph nodes": "Ganglios linfáticos",
  "Lymph nodes or adenopathy": "Ganglios linfáticos o adenopatías",
  "Vascular structures": "Estructuras vasculares",
  "Soft tissues and associated structures": "Partes blandas y estructuras asociadas",
  "Supraspinatus tendon": "Tendón del supraespinoso",
  "Infraspinatus tendon": "Tendón del infraespinoso",
  "Subscapularis tendon": "Tendón del subescapular",
  "Teres minor tendon": "Tendón del redondo menor",
  "Biceps tendon": "Tendón del bíceps",
  "Subacromial subdeltoid bursa": "Bursa subacromial-subdeltoidea",
  "Subacromial-subdeltoid bursa": "Bursa subacromial-subdeltoidea",
  "Glenohumeral joint": "Articulación glenohumeral",
  "Labrum": "Labrum",
  "Acromioclavicular joint": "Articulación acromioclavicular",
  "Humerus": "Húmero",
  "Scapula": "Escápula",
  "Meniscus": "Menisco",
  "Medial meniscus": "Menisco medial",
  "Lateral meniscus": "Menisco lateral",
  "Anterior cruciate ligament": "Ligamento cruzado anterior",
  "Posterior cruciate ligament": "Ligamento cruzado posterior",
  "Medial collateral ligament": "Ligamento colateral medial",
  "Lateral collateral ligament": "Ligamento colateral lateral",
  "Patellar tendon and quadriceps tendon": "Tendón rotuliano y tendón cuadricipital",
  "Articular cartilage": "Cartílago articular",
  "Cartilage and articular surfaces": "Cartílago y superficies articulares",
  "Joint effusion and synovium": "Derrame articular y sinovial",
  "Soft tissues and popliteal fossa": "Partes blandas y fosa poplítea",
  "Ligaments and tendons": "Ligamentos y tendones",
  "Ligaments and syndesmosis": "Ligamentos y sindesmosis",
  "Ligaments and joints": "Ligamentos y articulaciones",
  "Joints": "Articulaciones",
  "Joint space": "Espacio articular",
  "Bones": "Huesos",
  "Tendons": "Tendones",
  "Tendons and muscles": "Tendones y músculos",
  "Nerves": "Nervios",
  "Bursae": "Bursas",
  "Achilles tendon": "Tendón de Aquiles",
  "Peroneal tendons": "Tendones peroneos",
  "Posterior tibial tendon": "Tendón tibial posterior",
  "Anterior tendons": "Tendones anteriores",
  "Lateral ligament complex": "Complejo ligamentario lateral",
  "Medial (deltoid) ligament": "Ligamento medial (deltoideo)",
  "Syndesmosis": "Sindesmosis",
  "Tibiotalar and subtalar joints": "Articulaciones tibioastragalina y subastragalina",
  "Plantar fascia": "Fascia plantar",
  "Bone marrow signal": "Señal de médula ósea",
  "Femur": "Fémur",
  "Tibia": "Tibia",
  "Tibia and fibula": "Tibia y peroné",
  "Patella": "Rótula",
  "Talus": "Astrágalo",
  "Calcaneus": "Calcáneo",
  "Ankle joint": "Articulación del tobillo",
  "Carpal bones": "Huesos del carpo",
  "Distal radius and ulna": "Radio y cúbito distales",
  "Carpal tunnel": "Túnel carpiano",
  "Temporomandibular joint": "Articulación temporomandibular",
  "Masticatory muscles": "Músculos masticatorios",
  "Retrodiscal space": "Espacio retrodiscal",
  "Mandible and temporal bone": "Mandíbula y hueso temporal",
  "Willis polygon": "Polígono de Willis",
  "Ascending aorta": "Aorta ascendente",
  "Aortic arch": "Arco aórtico",
  "Descending aorta": "Aorta descendente",
  "Thoracic aorta": "Aorta torácica",
  "Renal arteries": "Arterias renales",
  "Celiac trunk and mesenteric arteries": "Tronco celíaco y arterias mesentéricas",
  "Aorta": "Aorta",
  "Free fluid": "Líquido libre",
  "Breast composition": "Composición mamaria",
  "Overall composition of the breasts": "Composición general de las mamas",
  "Right breast": "Mama derecha",
  "Left breast": "Mama izquierda",
  "Axillary lymph nodes": "Ganglios linfáticos axilares",
  "Skin and nipple": "Piel y pezón",
  "Right breast parenchyma": "Parénquima mamario derecho",
  "Left breast parenchyma": "Parénquima mamario izquierdo",
  "Focal lesions": "Lesiones focales",
  "Ductal system": "Sistema ductal",
  "Skin and subcutaneous tissues": "Piel y tejido subcutáneo",
  "Muscles and fasciae": "Músculos y fascias",
  "Muscles": "Músculos",
  "Skin": "Piel",
  "Subcutaneous tissues": "Tejido subcutáneo",
  "General thyroid assessment": "Valoración general del tiroides",
  "Right thyroid lobe": "Lóbulo tiroideo derecho",
  "Left thyroid lobe": "Lóbulo tiroideo izquierdo",
  "Isthmus": "Istmo",
  "Thyroid nodules": "Nódulos tiroideos",
  "Other structures": "Otras estructuras",
  "Ventricular size": "Tamaño ventricular",
  "Cortical structure": "Estructura cortical",
  "Midline Structures": "Estructuras de línea media",
  "Choroid plexus": "Plexo coroideo",
  "Femoral head": "Cabeza femoral",
  "Acetabular development": "Desarrollo acetabular",
  "Joint stability": "Estabilidad articular",
  "Visible portion of the meniscus": "Porción visible del menisco",
  "Superficial and deep femoral arteries": "Arterias femorales superficial y profunda",
  "Popliteal artery": "Arteria poplítea",
  "Tibialis and peroneal arteries": "Arterias tibiales y peroneas",
  "Distal arteries of the dorsal and plantar aspect of the foot": "Arterias distales del dorso y planta del pie",
  "Common femoral vein": "Vena femoral común",
  "Superficial femoral vein": "Vena femoral superficial",
  "Popliteal vein": "Vena poplítea",
  "Tibial and peroneal veins": "Venas tibiales y peroneas",
  "Soft tissues and superficial venous system": "Partes blandas y sistema venoso superficial",
  "Common femoral artery": "Arteria femoral común",
  "Superficial femoral artery": "Arteria femoral superficial",
  "Tibial and peroneal arteries": "Arterias tibiales y peroneas",
  "Soft tissues and superficial arterial system": "Partes blandas y sistema arterial superficial",
  "Nasopharynx, oropharynx and larynx": "Nasofaringe, orofaringe y laringe",
  "Parapharyngeal space": "Espacio parafaríngeo",
  "Vascular space": "Espacio vascular",
  "LV volumes and ejection fraction": "Volúmenes y fracción de eyección del VI",
  "RV volumes and ejection fraction": "Volúmenes y fracción de eyección del VD",
  "LV myocardial mass": "Masa miocárdica del VI",
  "Wall motion abnormalities": "Anomalías de la contractilidad segmentaria",
  "T2-weighted signal": "Señal en T2",
  "T1 and T2 mapping": "Mapas T1 y T2",
  "ECV": "VEC",
  "LGE presence and distribution": "Presencia y distribución de RTG",
  "LGE location and burden": "Localización y carga de RTG",
  "Valves": "Válvulas",
  "Pericardium": "Pericardio",
  "Pleural spaces": "Espacios pleurales",
  "Intracranial vascular structures": "Estructuras vasculares intracraneales",
  "Included cervical spine": "Columna cervical incluida",
  "Included portions of the cervical spine and vascular structures": "Porciones incluidas de la columna cervical y estructuras vasculares",
  "Sacroiliac joints": "Articulaciones sacroilíacas",
  "Right sacroiliac joint": "Articulación sacroilíaca derecha",
  "Left sacroiliac joint": "Articulación sacroilíaca izquierda",
  "Sacral bone marrow": "Médula ósea sacra",
  "Iliac bone marrow": "Médula ósea ilíaca",
  "Periarticular soft tissues": "Partes blandas periarticulares",
  "Lumbar spine": "Columna lumbar",
  "Sacrum": "Sacro",
  "Brain parenchyma": "Parénquima cerebral",
  "Ventricular system": "Sistema ventricular",
  "Other extra-axial spaces": "Otros espacios extra-axiales",
  "Sinuses": "Senos paranasales",
  "Cervical soft tissues": "Partes blandas cervicales",
  "Lung": "Pulmón",
  "Mediastinum and hilum": "Mediastino e hilio",
  "Heart size and contours": "Tamaño y contornos cardíacos",
  "Clavicle": "Clavícula",
  "Clavicles": "Clavículas",
  "Sternum": "Esternón",
  "Ribs": "Costillas",
  "Humeral head": "Cabeza humeral",
  "Femoral heads": "Cabezas femorales",
  "Acetabulum": "Acetábulo",
  "Pubic symphysis": "Sínfisis púbica",
  "Intervertebral spaces": "Espacios intervertebrales",
  "Facet joints": "Articulaciones facetarias",
  "Spinous processes": "Procesos espinosos",
  "Metacarpals": "Metacarpianos",
  "Wrist joint": "Articulación de la muñeca",
  "Tarsal bones": "Huesos del tarso",
  "Metatarsals": "Metatarsianos",
  "Elbow joint": "Articulación del codo",
  "Radius and ulna": "Radio y cúbito",
  "Organ outlines": "Contornos de órganos",
  "Calvarium": "Calota craneal",
  "Facial bones": "Huesos faciales",
  "Mandible": "Mandíbula",
  "Orbits": "Órbitas",
  "Extra-axial spaces and midline": "Espacios extra-axiales y línea media",
};

export function translateSectionLabel(name: string, lang: OutputLanguage): string {
  if (lang === "es") return ES[name] ?? name;
  return name;
}

export function translateTemplate(template: string, lang: OutputLanguage): string {
  if (lang === "en" || !template) return template;
  const dict = lang === "es" ? ES : null;
  if (!dict) return template;

  return template.replace(
    /(\*{2,3})([^*]+)\1/g,
    (match, stars: string, label: string) => {
      const trimmed = label.trim();
      const translated = dict[trimmed];
      if (!translated) return match;
      return `${stars}${translated}${stars}`;
    },
  );
}

const NORMALITY_PHRASE_ES: [RegExp, string][] = [
  [/\bNormal in size,? morphology and density\b/gi, "De tamaño, morfología y densidad normales"],
  [/\bNormal in size,? morphology and signal intensity\b/gi, "De tamaño, morfología e intensidad de señal normales"],
  [/\bNormal in size,? morphology and echogenicity\b/gi, "De tamaño, morfología y ecogenicidad normales"],
  [/\bNormal in size and density\b/gi, "De tamaño y densidad normales"],
  [/\bNormal in size and signal intensity\b/gi, "De tamaño e intensidad de señal normales"],
  [/\bNormal in size and morphology bilaterally\b/gi, "De tamaño y morfología normales bilateralmente"],
  [/\bNormal in size and morphology\b/gi, "De tamaño y morfología normales"],
  [/\bNormal in size,? echogenicity and echotexture\b/gi, "De tamaño, ecogenicidad y ecotextura normales"],
  [/\bNormal in size and echogenicity\b/gi, "De tamaño y ecogenicidad normales"],
  [/\bNormal in size, morphology and signal intensity bilaterally\b/gi, "De tamaño, morfología e intensidad de señal normales bilateralmente"],
  [/\bNormal in size and signal intensity bilaterally\b/gi, "De tamaño e intensidad de señal normales bilateralmente"],
  [/\bNormal distension and wall thickness\b/gi, "Distensión y grosor parietal normales"],
  [/\bNormal position and morphology\b/gi, "De posición y morfología normales"],
  [/\bNormal caliber and morphology\b/gi, "De calibre y morfología normales"],
  [/\bNormal heart size\b/gi, "Corazón de tamaño normal"],
  [/\bNormal bone density\b/gi, "Densidad ósea normal"],
  [/\bNormal gastric wall\b/gi, "Pared gástrica normal"],
  [/\bNormal caliber\b/gi, "De calibre normal"],
  [/\bNormal appearance\b/gi, "Aspecto normal"],
  [/\bNo significant abnormalities\b/gi, "Sin alteraciones significativas"],
  [/\bNo significant findings\b/gi, "Sin hallazgos significativos"],
  [/\bNo focal lesions\b/gi, "Sin lesiones focales"],
  [/\bNo gallstones or wall thickening\b/gi, "Sin litiasis ni engrosamiento parietal"],
  [/\bNo intrahepatic or extrahepatic biliary dilation\b/gi, "Sin dilatación biliar intrahepática ni extrahepática"],
  [/\bNo hydronephrosis or focal lesions\b/gi, "Sin hidronefrosis ni lesiones focales"],
  [/\bNo hydronephrosis\b/gi, "Sin hidronefrosis"],
  [/\bNo intraluminal lesions\b/gi, "Sin lesiones intraluminales"],
  [/\bNo free fluid or lymphadenopathy\b/gi, "Sin líquido libre ni adenopatías"],
  [/\bNo free fluid\b/gi, "Sin líquido libre"],
  [/\bNo wall thickening or obstruction\b/gi, "Sin engrosamiento parietal ni obstrucción"],
  [/\bNo wall thickening\b/gi, "Sin engrosamiento parietal"],
  [/\bNo pulmonary nodules,? consolidations or ground-glass opacities\b/gi, "Sin nódulos pulmonares, consolidaciones ni opacidades en vidrio deslustrado"],
  [/\bNo pathologically enlarged mediastinal lymph nodes\b/gi, "Sin adenopatías mediastínicas de tamaño patológico"],
  [/\bNo pathologically enlarged cervical lymph nodes\b/gi, "Sin adenopatías cervicales de tamaño patológico"],
  [/\bNo pathologically enlarged lymph nodes\b/gi, "Sin adenopatías de tamaño patológico"],
  [/\bNo endoluminal lesions\b/gi, "Sin lesiones endoluminales"],
  [/\bNo significant coronary calcifications\b/gi, "Sin calcificaciones coronarias significativas"],
  [/\bNo aneurysm or dissection\b/gi, "Sin aneurisma ni disección"],
  [/\bNo aneurysm\b/gi, "Sin aneurisma"],
  [/\bNo pericardial effusion\b/gi, "Sin derrame pericárdico"],
  [/\bNo pleural effusion or thickening\b/gi, "Sin derrame pleural ni engrosamiento"],
  [/\bNo pleural effusion\b/gi, "Sin derrame pleural"],
  [/\bNo thoracic wall abnormalities\b/gi, "Sin alteraciones de la pared torácica"],
  [/\bNo acute vertebral fractures or significant degenerative changes\b/gi, "Sin fracturas vertebrales agudas ni cambios degenerativos significativos"],
  [/\bNo acute fractures or suspicious bone lesions\b/gi, "Sin fracturas agudas ni lesiones óseas sospechosas"],
  [/\bNo acute fractures\b/gi, "Sin fracturas agudas"],
  [/\bNo extra-axial collections\b/gi, "Sin colecciones extra-axiales"],
  [/\bNo mass lesions,? hemorrhage or acute ischemic changes\b/gi, "Sin lesiones ocupantes de espacio, hemorragia ni cambios isquémicos agudos"],
  [/\bNo mass lesions in the posterior fossa\b/gi, "Sin lesiones ocupantes de espacio en fosa posterior"],
  [/\bNo mass lesions\b/gi, "Sin lesiones ocupantes de espacio"],
  [/\bNo significant stenosis\b/gi, "Sin estenosis significativa"],
  [/\bNo significant soft tissue abnormalities\b/gi, "Sin alteraciones significativas de partes blandas"],
  [/\bNo significant pelvic abnormalities\b/gi, "Sin alteraciones pélvicas significativas"],
  [/\bNo significant supradiaphragmatic abnormalities\b/gi, "Sin alteraciones supradiafragmáticas significativas"],
  [/\bNo additional findings\b/gi, "Sin hallazgos adicionales"],
  [/\bNo additional (?:thoracic |mediastinal |intraabdominal |thoraco-abdominal )?abnormalities\b/gi, "Sin alteraciones adicionales"],
  [/\bNo fracture or bone lesion\b/gi, "Sin fractura ni lesión ósea"],
  [/\bNo fracture\b/gi, "Sin fractura"],
  [/\bNo effusion\b/gi, "Sin derrame"],
  [/\bNo vascular abnormalities\b/gi, "Sin alteraciones vasculares"],
  [/\bNo bone marrow signal abnormalities or fractures\b/gi, "Sin alteraciones de señal de médula ósea ni fracturas"],
  [/\bNo bone marrow edema\b/gi, "Sin edema de médula ósea"],
  [/\bNo tears or tendinopathy\b/gi, "Sin roturas ni tendinopatía"],
  [/\bNo tears\b/gi, "Sin roturas"],
  [/\bNo consolidations,? effusions or nodules\b/gi, "Sin consolidaciones, derrames ni nódulos"],
  [/\bNo cortical irregularities\b/gi, "Sin irregularidades corticales"],
  [/\bNo rib fractures\b/gi, "Sin fracturas costales"],
  [/\bNo signs of obstruction\b/gi, "Sin signos de obstrucción"],
  [/\bNo bursitis\b/gi, "Sin bursitis"],
  [/\bNo gallstones\b/gi, "Sin litiasis"],
  [/\bNo biliary dilation\b/gi, "Sin dilatación biliar"],
  [/\bNo obstruction\b/gi, "Sin obstrucción"],
  [/\bPatent portal vein and hepatic artery\b/gi, "Vena porta y arteria hepática permeables"],
  [/\bPatent portal vein with hepatopetal flow\b/gi, "Vena porta permeable con flujo hepatópeto"],
  [/\bPatent (?:tibial and peroneal|distal) arteries\b/gi, "Arterias permeables"],
  [/\bNormal lung parenchyma\b/gi, "Parénquima pulmonar normal"],
  [/\bNormal mediastinal structures\b/gi, "Estructuras mediastínicas normales"],
  [/\bNormal paranasal sinuses\b/gi, "Senos paranasales normales"],
  [/\bNormal epiglottis\b/gi, "Epiglotis normal"],
  [/\bNormal tracheal caliber\b/gi, "Tráquea de calibre normal"],
  [/\bNormal salivary glands\b/gi, "Glándulas salivales normales"],
  [/\bNormal parotid glands bilaterally\b/gi, "Glándulas parótidas normales bilateralmente"],
  [/\bNormal submandibular glands bilaterally\b/gi, "Glándulas submandibulares normales bilateralmente"],
  [/\bSymmetric vocal cords\b/gi, "Cuerdas vocales simétricas"],
  [/\bNormal circle of Willis\b/gi, "Polígono de Willis normal"],
  [/\bNo aneurysms\b/gi, "Sin aneurismas"],
  [/\bNormal piriform sinuses\b/gi, "Senos piriformes normales"],
  [/\bNormal parapharyngeal spaces\b/gi, "Espacios parafaríngeos normales"],
  [/\bNormal nasopharyngeal mucosa\b/gi, "Mucosa nasofaríngea normal"],
  [/\bNormal oropharyngeal structures\b/gi, "Estructuras orofaríngeas normales"],
  [/\bNormal brain parenchyma\b/gi, "Parénquima cerebral normal"],
  [/\bNormal supratentorial brain parenchyma\b/gi, "Parénquima cerebral supratentorial normal"],
  [/\bNormal infratentorial brain parenchyma\b/gi, "Parénquima cerebral infratentorial normal"],
  [/\bNormal size and morphology of the ventricular system\b/gi, "Sistema ventricular de tamaño y morfología normales"],
  [/\bMidline structures in normal position\b/gi, "Estructuras de línea media en posición normal"],
  [/\bNormal diaphragm position\b/gi, "Diafragma en posición normal"],
  [/\bThyroid within normal limits\b/gi, "Tiroides dentro de límites normales"],
  [/\bExtracranial soft tissues unremarkable\b/gi, "Partes blandas extracraneales sin hallazgos"],
  [/\bVascular structures unremarkable\b/gi, "Estructuras vasculares sin hallazgos"],
  [/\bUreters not dilated\b/gi, "Uréteres no dilatados"],
  [/\bClear lung fields\b/gi, "Campos pulmonares libres"],
  [/\bNormal mediastinal silhouette and hila\b/gi, "Silueta mediastínica e hilios normales"],
  [/\bNormal joint space\b/gi, "Espacio articular normal"],
  [/\bNormal joint spaces\b/gi, "Espacios articulares normales"],
  [/\bNo pancreatic duct dilation\b/gi, "Sin dilatación del conducto pancreático"],
  [/\bNormal compressibility\b/gi, "Compresibilidad normal"],
  [/\bTriphasic waveform\b/gi, "Onda trifásica"],
  [/\bNormal corticomedullary differentiation\b/gi, "Diferenciación corticomedular normal"],
  [/\bVisualized portions unremarkable\b/gi, "Porciones visualizadas sin hallazgos"],
  [/\bNormal signal intensity\b/gi, "Intensidad de señal normal"],
  [/\bNo restricted diffusion or abnormal enhancement\b/gi, "Sin restricción de la difusión ni realce anómalo"],
  [/\bNo calvarial (?:fractures|abnormalities)\b/gi, "Sin alteraciones calvariales"],
  [/\bNo acute cervical spine abnormalities\b/gi, "Sin alteraciones agudas de la columna cervical"],
  [/\bNormal cervical alignment\b/gi, "Alineación cervical normal"],
  [/\bNo marrow signal abnormalities\b/gi, "Sin alteraciones de señal medular"],
  [/\bNormal vertebral body height,? alignment and marrow signal\b/gi, "Cuerpos vertebrales de altura, alineación y señal medular normales"],
  [/\bNormal intervertebral disc height and signal intensity\b/gi, "Discos intervertebrales de altura e intensidad de señal normales"],
  [/\bNo significant disc herniation\b/gi, "Sin herniación discal significativa"],
  [/\bNormal ligamentous structures\b/gi, "Estructuras ligamentarias normales"],
  [/\bNormal spinal cord signal and morphology\b/gi, "Médula espinal de señal y morfología normales"],
  [/\bNormal meniscal morphology and signal\b/gi, "Morfología y señal meniscal normales"],
  [/\bNormal ligamentous and tendinous structures\b/gi, "Estructuras ligamentarias y tendinosas normales"],
  [/\bNormal cartilage thickness and articular surfaces\b/gi, "Cartílago de grosor normal y superficies articulares normales"],
  [/\bNormal course and signal of visualized nerves\b/gi, "Trayecto y señal normales de los nervios visualizados"],
  [/\bNormal tendinous structures\b/gi, "Estructuras tendinosas normales"],
  [/\bNormal ankle joint\b/gi, "Articulación del tobillo normal"],
  [/\bNormal glenohumeral joint\b/gi, "Articulación glenohumeral normal"],
  [/\bNormal elbow joint\b/gi, "Articulación del codo normal"],
  [/\bNormal wrist joint\b/gi, "Articulación de la muñeca normal"],
  [/\bNormal acromioclavicular joint\b/gi, "Articulación acromioclavicular normal"],
  [/\bNormal temporomandibular joint\b/gi, "Articulación temporomandibular normal"],
];

export function enforceOutputLanguage(text: string, lang: OutputLanguage): string {
  if (lang === "en" || !text) return text;
  if (lang !== "es") return text;

  let result = text;
  for (const [pattern, replacement] of NORMALITY_PHRASE_ES) {
    result = result.replace(pattern, replacement);
  }
  return result;
}
