import type { OutputLanguage } from "./types";

const ES: Record<string, string> = {
  "Lung parenchyma": "Parénquima pulmonar",
  "Mediastinum and hila": "Mediastino e hilios",
  "Cardiac silhouette": "Silueta cardíaca",
  "Pleura and diaphragm": "Pleura y diafragma",
  "Bone structures": "Estructuras óseas",
  "Soft tissues": "Partes blandas",
  "Bowel gas pattern": "Patrón de gas intestinal",
  "Solid organ outlines": "Contornos de órganos sólidos",
  "Peritoneal fat planes": "Planos grasos peritoneales",
  "Other findings": "Otros hallazgos",
  "Supratentorial brain parenchyma": "Parénquima cerebral supratentorial",
  "Infratentorial brain parenchyma": "Parénquima cerebral infratentorial",
  "Ventricular system and midline": "Sistema ventricular y línea media",
  "Extra-axial spaces": "Espacios extra-axiales",
  "Skull and extracranial soft tissues": "Cráneo y partes blandas extracraneales",
  "Paranasal sinuses and mastoid cells": "Senos paranasales y celdillas mastoideas",
  "Included cervical structures": "Estructuras cervicales incluidas",
  "Parotids": "Parótidas",
  "Submandibular glands": "Glándulas submandibulares",
  "Nasopharynx": "Nasofaringe",
  "Oropharynx": "Orofaringe",
  "Vocal cords": "Cuerdas vocales",
  "Piriform sinuses": "Senos piriformes",
  "Epiglottis": "Epiglotis",
  "Trachea and cervical esophagus": "Tráquea y esófago cervical",
  "Thyroid gland": "Glándula tiroides",
  "Parapharyngeal and retropharyngeal spaces": "Espacios parafaríngeo y retrofaríngeo",
  "Cervical vascular structures": "Estructuras vasculares cervicales",
  "Cervical lymph nodes": "Ganglios linfáticos cervicales",
  "Salivary glands": "Glándulas salivales",
  "Cervical spine": "Columna cervical",
  "Mediastinal lymph nodes": "Ganglios linfáticos mediastínicos",
  "Mediastinum": "Mediastino",
  "Trachea and bronchi": "Tráquea y bronquios",
  "Trachea": "Tráquea",
  "Esophagus": "Esófago",
  "Coronary arteries": "Arterias coronarias",
  "Aorta and pulmonary arteries": "Aorta y arterias pulmonares",
  "Aorta and pulmonary artery": "Aorta y arteria pulmonar",
  "Aorta and great vessels": "Aorta y grandes vasos",
  "Heart and pericardium": "Corazón y pericardio",
  "Pleura": "Pleura",
  "Diaphragm": "Diafragma",
  "Thoracic wall": "Pared torácica",
  "Thoracic wall and bone structures": "Pared torácica y estructuras óseas",
  "Thyroid and supradiaphragmatic tissues": "Tiroides y tejidos supradiafragmáticos",
  "Supradiaphragmatic tissues and thyroid": "Tiroides y tejidos supradiafragmáticos",
  "Included portions of the abdomen": "Porciones incluidas del abdomen",
  "Included portions of the thorax": "Porciones incluidas del tórax",
  "Liver": "Hígado",
  "Liver parenchyma": "Parénquima hepático",
  "Liver and spleen": "Hígado y bazo",
  "Hepatic focal lesions": "Lesiones focales hepáticas",
  "Portal vein and hepatic artery": "Vena porta y arteria hepática",
  "Portal vein and hepatic veins": "Vena porta y venas hepáticas",
  "Portal vein": "Vena porta",
  "Hepatic artery": "Arteria hepática",
  "Gallbladder": "Vesícula biliar",
  "Gallbladder and bile ducts": "Vesícula biliar y vías biliares",
  "Bile ducts": "Vías biliares",
  "Intrahepatic and extrahepatic biliary ducts": "Vías biliares intrahepáticas y extrahepáticas",
  "Spleen": "Bazo",
  "Pancreas": "Páncreas",
  "Pancreatic duct": "Conducto pancreático",
  "Peripancreatic fat and vessels": "Grasa peripancreática y vasos",
  "Adrenal glands": "Glándulas suprarrenales",
  "Adrenal glands and kidneys": "Glándulas suprarrenales y riñones",
  "Kidneys and ureters": "Riñones y uréteres",
  "Kidneys": "Riñones",
  "Right kidney": "Riñón derecho",
  "Left kidney": "Riñón izquierdo",
  "Bladder": "Vejiga",
  "Peritoneum and retroperitoneum": "Peritoneo y retroperitoneo",
  "Peritoneum, retroperitoneum": "Peritoneo y retroperitoneo",
  "Peritoneum retroperitoneum": "Peritoneo y retroperitoneo",
  "Peritoneum": "Peritoneo",
  "Stomach": "Estómago",
  "Stomach and bowel": "Estómago e intestino",
  "Small bowel and colon": "Intestino delgado y colon",
  "Small bowel loops and colon": "Asas de intestino delgado y colon",
  "Other pelvic structures": "Otras estructuras pélvicas",
  "Pelvic structures": "Estructuras pélvicas",
  "Pelvic organs": "Órganos pélvicos",
  "Pelvic lymph nodes": "Ganglios linfáticos pélvicos",
  "Abdominal aorta and iliac arteries": "Aorta abdominal y arterias ilíacas",
  "Abdominal aorta": "Aorta abdominal",
  "Iliac arteries": "Arterias ilíacas",
  "Intraabdominal organs": "Órganos intraabdominales",
  "Intraabdominal solid organs": "Órganos sólidos intraabdominales",
  "Other intraabdominal structures": "Otras estructuras intraabdominales",
  "Other thoracic structures": "Otras estructuras torácicas",
  "Other thoracic and abdominal structures": "Otras estructuras torácicas y abdominales",
  "Other mediastinal findings": "Otros hallazgos mediastínicos",
  "Bone structures and soft tissues": "Estructuras óseas y partes blandas",
  "Bone structures and included portions of the thorax": "Estructuras óseas y porciones incluidas del tórax",
  "Spine": "Columna vertebral",
  "Bone density": "Densidad ósea",
  "Vertebral bodies": "Cuerpos vertebrales",
  "Intervertebral spaces and discs": "Espacios y discos intervertebrales",
  "Intervertebral discs": "Discos intervertebrales",
  "Spinal cord": "Médula espinal",
  "Neural foramina": "Forámenes neurales",
  "Ligaments": "Ligamentos",
  "Craniocervical junction": "Unión craneocervical",
  "Conus medullaris and cauda equina": "Cono medular y cola de caballo",
  "Uterus": "Útero",
  "Endometrium": "Endometrio",
  "Cervix": "Cérvix",
  "Ovaries": "Ovarios",
  "Fallopian tubes": "Trompas de Falopio",
  "Vagina": "Vagina",
  "Rectum and sigmoid": "Recto y sigma",
  "Rectum": "Recto",
  "Mesorectum": "Mesorrecto",
  "Mesorectal fascia": "Fascia mesorrectal",
  "Perianal soft tissues": "Partes blandas perianales",
  "Sphincters": "Esfínteres",
  "Other perineal structures": "Otras estructuras perineales",
  "General prostate assessment": "Valoración general de la próstata",
  "Peripheral zone": "Zona periférica",
  "Transition zone": "Zona de transición",
  "Seminal vesicles": "Vesículas seminales",
  "Bone structures and periprostatic tissues": "Estructuras óseas y tejidos periprostáticos",
  "Lymph nodes": "Ganglios linfáticos",
  "Lymph nodes or adenopathy": "Ganglios linfáticos o adenopatías",
  "Vascular structures": "Estructuras vasculares",
  "Soft tissues and associated structures": "Partes blandas y estructuras asociadas",
  "Supraspinatus tendon": "Tendón del supraespinoso",
  "Infraspinatus tendon": "Tendón del infraespinoso",
  "Subscapularis tendon": "Tendón del subescapular",
  "Teres minor tendon": "Tendón del redondo menor",
  "Biceps tendon": "Tendón del bíceps",
  "Subacromial subdeltoid bursa": "Bursa subacromial-subdeltoidea",
  "Subacromial-subdeltoid bursa": "Bursa subacromial-subdeltoidea",
  "Glenohumeral joint": "Articulación glenohumeral",
  "Labrum": "Labrum",
  "Acromioclavicular joint": "Articulación acromioclavicular",
  "Humerus": "Húmero",
  "Scapula": "Escápula",
  "Meniscus": "Menisco",
  "Medial meniscus": "Menisco medial",
  "Lateral meniscus": "Menisco lateral",
  "Anterior cruciate ligament": "Ligamento cruzado anterior",
  "Posterior cruciate ligament": "Ligamento cruzado posterior",
  "Medial collateral ligament": "Ligamento colateral medial",
  "Lateral collateral ligament": "Ligamento colateral lateral",
  "Patellar tendon and quadriceps tendon": "Tendón rotuliano y tendón cuadricipital",
  "Articular cartilage": "Cartílago articular",
  "Cartilage and articular surfaces": "Cartílago y superficies articulares",
  "Joint effusion and synovium": "Derrame articular y sinovial",
  "Soft tissues and popliteal fossa": "Partes blandas y fosa poplítea",
  "Ligaments and tendons": "Ligamentos y tendones",
  "Ligaments and syndesmosis": "Ligamentos y sindesmosis",
  "Ligaments and joints": "Ligamentos y articulaciones",
  "Joints": "Articulaciones",
  "Joint space": "Espacio articular",
  "Bones": "Huesos",
  "Tendons": "Tendones",
  "Tendons and muscles": "Tendones y músculos",
  "Nerves": "Nervios",
  "Bursae": "Bursas",
  "Achilles tendon": "Tendón de Aquiles",
  "Peroneal tendons": "Tendones peroneos",
  "Posterior tibial tendon": "Tendón tibial posterior",
  "Anterior tendons": "Tendones anteriores",
  "Lateral ligament complex": "Complejo ligamentario lateral",
  "Medial (deltoid) ligament": "Ligamento medial (deltoideo)",
  "Syndesmosis": "Sindesmosis",
  "Tibiotalar and subtalar joints": "Articulaciones tibioastragalina y subastragalina",
  "Plantar fascia": "Fascia plantar",
  "Bone marrow signal": "Señal de médula ósea",
  "Femur": "Fémur",
  "Tibia": "Tibia",
  "Tibia and fibula": "Tibia y peroné",
  "Patella": "Rótula",
  "Talus": "Astrágalo",
  "Calcaneus": "Calcáneo",
  "Ankle joint": "Articulación del tobillo",
  "Carpal bones": "Huesos del carpo",
  "Distal radius and ulna": "Radio y cúbito distales",
  "Carpal tunnel": "Túnel carpiano",
  "Temporomandibular joint": "Articulación temporomandibular",
  "Masticatory muscles": "Músculos masticatorios",
  "Retrodiscal space": "Espacio retrodiscal",
  "Mandible and temporal bone": "Mandíbula y hueso temporal",
  "Willis polygon": "Polígono de Willis",
  "Ascending aorta": "Aorta ascendente",
  "Aortic arch": "Arco aórtico",
  "Aortic arch and branches": "Arco aórtico y ramas",
  "Aortic arch and supra-aortic trunks": "Arco aórtico y troncos supraaórticos",
  "Descending aorta": "Aorta descendente",
  "Descending thoracic aorta": "Aorta torácica descendente",
  "Thoracic aorta": "Aorta torácica",
  "Renal arteries": "Arterias renales",
  "Celiac trunk and mesenteric arteries": "Tronco celíaco y arterias mesentéricas",
  "Aorta": "Aorta",
  "Free fluid": "Líquido libre",
  "Breast composition": "Composición mamaria",
  "Overall composition of the breasts": "Composición general de las mamas",
  "Right breast": "Mama derecha",
  "Left breast": "Mama izquierda",
  "Axillary lymph nodes": "Ganglios linfáticos axilares",
  "Skin and nipple": "Piel y pezón",
  "Right breast parenchyma": "Parénquima mamario derecho",
  "Left breast parenchyma": "Parénquima mamario izquierdo",
  "Focal lesions": "Lesiones focales",
  "Ductal system": "Sistema ductal",
  "Skin and subcutaneous tissues": "Piel y tejido subcutáneo",
  "Muscles and fasciae": "Músculos y fascias",
  "Muscles": "Músculos",
  "Skin": "Piel",
  "Subcutaneous tissues": "Tejido subcutáneo",
  "General thyroid assessment": "Valoración general del tiroides",
  "Right thyroid lobe": "Lóbulo tiroideo derecho",
  "Left thyroid lobe": "Lóbulo tiroideo izquierdo",
  "Isthmus": "Istmo",
  "Thyroid nodules": "Nódulos tiroideos",
  "Other structures": "Otras estructuras",
  "Ventricular size": "Tamaño ventricular",
  "Cortical structure": "Estructura cortical",
  "Midline Structures": "Estructuras de línea media",
  "Choroid plexus": "Plexo coroideo",
  "Femoral head": "Cabeza femoral",
  "Acetabular development": "Desarrollo acetabular",
  "Joint stability": "Estabilidad articular",
  "Visible portion of the meniscus": "Porción visible del menisco",
  "Superficial and deep femoral arteries": "Arterias femorales superficial y profunda",
  "Popliteal artery": "Arteria poplítea",
  "Tibialis and peroneal arteries": "Arterias tibiales y peroneas",
  "Distal arteries of the dorsal and plantar aspect of the foot": "Arterias distales del dorso y planta del pie",
  "Common femoral vein": "Vena femoral común",
  "Superficial femoral vein": "Vena femoral superficial",
  "Popliteal vein": "Vena poplítea",
  "Tibial and peroneal veins": "Venas tibiales y peroneas",
  "Soft tissues and superficial venous system": "Partes blandas y sistema venoso superficial",
  "Common femoral artery": "Arteria femoral común",
  "Superficial femoral artery": "Arteria femoral superficial",
  "Tibial and peroneal arteries": "Arterias tibiales y peroneas",
  "Soft tissues and superficial arterial system": "Partes blandas y sistema arterial superficial",
  "Nasopharynx, oropharynx and larynx": "Nasofaringe, orofaringe y laringe",
  "Parapharyngeal space": "Espacio parafaríngeo",
  "Vascular space": "Espacio vascular",
  "LV volumes and ejection fraction": "Volúmenes y fracción de eyección del VI",
  "RV volumes and ejection fraction": "Volúmenes y fracción de eyección del VD",
  "LV myocardial mass": "Masa miocárdica del VI",
  "Wall motion abnormalities": "Anomalías de la contractilidad segmentaria",
  "T2-weighted signal": "Señal en T2",
  "T1 and T2 mapping": "Mapas T1 y T2",
  "ECV": "VEC",
  "LGE presence and distribution": "Presencia y distribución de RTG",
  "LGE location and burden": "Localización y carga de RTG",
  "Valves": "Válvulas",
  "Pericardium": "Pericardio",
  "Pleural spaces": "Espacios pleurales",
  "Intracranial vascular structures": "Estructuras vasculares intracraneales",
  "Included cervical spine": "Columna cervical incluida",
  "Included portions of the cervical spine and vascular structures": "Porciones incluidas de la columna cervical y estructuras vasculares",
  "Sacroiliac joints": "Articulaciones sacroilíacas",
  "Right sacroiliac joint": "Articulación sacroilíaca derecha",
  "Left sacroiliac joint": "Articulación sacroilíaca izquierda",
  "Sacral bone marrow": "Médula ósea sacra",
  "Iliac bone marrow": "Médula ósea ilíaca",
  "Periarticular soft tissues": "Partes blandas periarticulares",
  "Lumbar spine": "Columna lumbar",
  "Sacrum": "Sacro",
  "Brain parenchyma": "Parénquima cerebral",
  "Ventricular system": "Sistema ventricular",
  "Other extra-axial spaces": "Otros espacios extra-axiales",
  "Sinuses": "Senos paranasales",
  "Cervical soft tissues": "Partes blandas cervicales",
  "Lung": "Pulmón",
  "Mediastinum and hilum": "Mediastino e hilio",
  "Heart size and contours": "Tamaño y contornos cardíacos",
  "Clavicle": "Clavícula",
  "Clavicles": "Clavículas",
  "Sternum": "Esternón",
  "Ribs": "Costillas",
  "Humeral head": "Cabeza humeral",
  "Femoral heads": "Cabezas femorales",
  "Acetabulum": "Acetábulo",
  "Pubic symphysis": "Sínfisis púbica",
  "Intervertebral spaces": "Espacios intervertebrales",
  "Facet joints": "Articulaciones facetarias",
  "Spinous processes": "Procesos espinosos",
  "Metacarpals": "Metacarpianos",
  "Wrist joint": "Articulación de la muñeca",
  "Tarsal bones": "Huesos del tarso",
  "Metatarsals": "Metatarsianos",
  "Elbow joint": "Articulación del codo",
  "Radius and ulna": "Radio y cúbito",
  "Organ outlines": "Contornos de órganos",
  "Calvarium": "Calota craneal",
  "Facial bones": "Huesos faciales",
  "Mandible": "Mandíbula",
  "Orbits": "Órbitas",
  "Extra-axial spaces and midline": "Espacios extra-axiales y línea media",
  // ── Merged from the UI sections dictionary (catalog coverage) ──
  "Access route": "Vía de acceso",
  "Access site": "Sitio de acceso",
  "Access site and needle": "Punto de acceso y aguja",
  "Access type": "Tipo de acceso",
  "Access vein": "Vena de acceso",
  "Accessory veins": "Venas accesorias",
  "Acetabulum and labrum": "Acetábulo y labrum",
  "Achilles tendon proximal": "Tendón de Aquiles proximal",
  "Acromion and coracoid": "Acromion y coracoides",
  "Adductor muscles": "Músculos aductores",
  "Adenoid tissue": "Tejido adenoideo",
  "Adjacent lung parenchyma": "Parénquima pulmonar adyacente",
  "Adnexa": "Anejos",
  "Air-fluid levels": "Niveles hidroaéreos",
  "Alignment": "Alineación",
  "Alignment and curvature": "Alineación y curvatura",
  "Alignment and listhesis": "Alineación y listesis",
  "Amniotic fluid": "Líquido amniótico",
  "Ampulla of Vater": "Ampolla de Vater",
  "Anatomical femoral axis": "Eje anatómico femoral",
  "Anatomical tibial axis": "Eje anatómico tibial",
  "Aneurysm or pseudoaneurysm": "Aneurisma o pseudoaneurisma",
  "Ankle joints": "Articulaciones del tobillo",
  "Ankle-brachial index": "Índice tobillo-brazo",
  "Anterior cerebral arteries": "Arterias cerebrales anteriores",
  "Anterior compartment": "Compartimento anterior",
  "Anterior cranial fossa": "Fosa craneal anterior",
  "Anterior mediastinum": "Mediastino anterior",
  "Anterior nasal spine": "Espina nasal anterior",
  "Aorta at renal level": "Aorta a nivel renal",
  "Aortic root": "Raíz aórtica",
  "Aortic valve": "Válvula aórtica",
  "Aortic wall": "Pared aórtica",
  "Aortic wall and lumen": "Pared y luz aórtica",
  "Appendicolith": "Apendicolito",
  "Appendix diameter": "Diámetro del apéndice",
  "Appendix visualization": "Visualización del apéndice",
  "Approach": "Abordaje",
  "Architectural distortion": "Distorsión arquitectural",
  "Arterial anastomosis": "Anastomosis arterial",
  "Arterial phase enhancement": "Realce en fase arterial",
  "Articular surfaces": "Superficies articulares",
  "Ascites": "Ascitis",
  "Aspirated material": "Material aspirado",
  "Aspirated volume and appearance": "Volumen aspirado y aspecto",
  "Axillae": "Axilas",
  "B-lines": "Líneas B",
  "Background parenchymal enhancement": "Realce parenquimatoso de fondo",
  "Baker cyst": "Quiste de Baker",
  "Balloon or stent type and size": "Tipo y tamaño del balón o stent",
  "Basilar artery": "Arteria basilar",
  "Biceps and triceps muscles": "Músculos bíceps y tríceps",
  "Biceps tendon insertion": "Inserción del tendón del bíceps",
  "Biceps tendon long head": "Tendón del bíceps porción larga",
  "Bladder and pelvic organs": "Vejiga y órganos pélvicos",
  "Bladder morphology": "Morfología vesical",
  "Bladder wall": "Pared vesical",
  "Bohler angle": "Ángulo de Böhler",
  "Bone height and width": "Altura y anchura ósea",
  "Bowel wall enhancement": "Realce de la pared intestinal",
  "Bowel wall signal and enhancement": "Señal y realce de la pared intestinal",
  "Brachial neurovascular bundle": "Paquete neurovascular braquial",
  "Brainstem": "Tronco del encéfalo",
  "Branch vessels": "Vasos ramas",
  "Breast composition and BPE": "Composición mamaria y BPE",
  "Breast parenchyma": "Parénquima mamario",
  "Calcaneal body": "Cuerpo del calcáneo",
  "Calcifications": "Calcificaciones",
  "Calcium score": "Score de calcio",
  "Cannulated duct": "Conducto canulado",
  "Capsular integrity": "Integridad capsular",
  "Cardiac activity": "Actividad cardíaca",
  "Cardiac chambers": "Cámaras cardíacas",
  "Carpal alignment": "Alineación carpiana",
  "Catheter position": "Posición del catéter",
  "Catheter tip position": "Posición de la punta del catéter",
  "Catheter type": "Tipo de catéter",
  "Catheter type and size": "Tipo y calibre del catéter",
  "Cauda equina": "Cola de caballo",
  "Cavernous sinuses": "Senos cavernosos",
  "CBF maps": "Mapas de CBF",
  "CBV maps": "Mapas de CBV",
  "Cement distribution": "Distribución del cemento",
  "Cement leakage": "Fuga de cemento",
  "Cement type and volume": "Tipo y volumen de cemento",
  "Central veins": "Venas centrales",
  "Central zone": "Zona central",
  "Cerebellopontine angles": "Ángulos pontocerebelosos",
  "Cerebral parenchyma": "Parénquima cerebral",
  "Cervical muscles": "Musculatura cervical",
  "Cervical soft tissues and lymph nodes": "Partes blandas cervicales y ganglios",
  "Cervical soft tissues and salivary glands": "Partes blandas cervicales y glándulas salivales",
  "Chest wall": "Pared torácica",
  "Chest wall mass or lesion": "Masa o lesión de pared torácica",
  "Chest wall soft tissues": "Partes blandas de la pared torácica",
  "Cholangiogram findings": "Hallazgos de la colangiografía",
  "Circle of Willis": "Polígono de Willis",
  "Clavicular shaft": "Diáfisis clavicular",
  "Cobb angles": "Ángulos de Cobb",
  "Coccyx": "Cóccix",
  "Cochlea": "Cóclea",
  "Collateral circulation": "Circulación colateral",
  "Collateral ligaments": "Ligamentos colaterales",
  "Collecting systems": "Sistemas colectores",
  "Collection location and size": "Localización y tamaño de la colección",
  "Common and superficial femoral arteries left": "Arterias femoral común y superficial izquierdas",
  "Common and superficial femoral arteries right": "Arterias femoral común y superficial derechas",
  "Common bile duct": "Colédoco",
  "Common carotid arteries": "Arterias carótidas comunes",
  "Common extensor tendon": "Tendón extensor común",
  "Common flexor tendon": "Tendón flexor común",
  "Common hepatic duct": "Conducto hepático común",
  "Common iliac arteries": "Arterias ilíacas comunes",
  "Complications": "Complicaciones",
  "Condyles": "Cóndilos",
  "Consolidation": "Consolidación",
  "Contrast extravasation": "Extravasación de contraste",
  "Contrast spread": "Distribución del contraste",
  "Contrast type and volume": "Tipo y volumen de contraste",
  "Conus medullaris": "Cono medular",
  "Coracoid process": "Apófisis coracoides",
  "Cord expansion or atrophy": "Expansión o atrofia medular",
  "Coronary dominance": "Dominancia coronaria",
  "Coronoid and olecranon": "Coronoides y olécranon",
  "Coronoid processes": "Apófisis coronoides",
  "Cortex and medullary canal": "Cortical y canal medular",
  "Cortical thickness": "Grosor cortical",
  "Costal cartilage": "Cartílago costal",
  "Costovertebral joints": "Articulaciones costovertebrales",
  "Crown-rump length and gestational age": "Longitud cráneo-nalga y edad gestacional",
  "Crucial angle of Gissane": "Ángulo crucial de Gissane",
  "CSF spaces": "Espacios de LCR",
  "Cul-de-sac": "Fondo de saco de Douglas",
  "Deep posterior compartment": "Compartimento posterior profundo",
  "Deep veins": "Venas profundas",
  "Degree of hydronephrosis": "Grado de hidronefrosis",
  "Delayed phase": "Fase tardía",
  "Deltoid muscle": "Músculo deltoides",
  "Dental structures": "Estructuras dentales",
  "Diaphragm and free air": "Diafragma y neumoperitoneo",
  "Diffusion restriction and ADC": "Restricción a la difusión y ADC",
  "Distal arteries of the foot left": "Arterias distales del pie izquierdo",
  "Distal arteries of the foot right": "Arterias distales del pie derecho",
  "Distal femur": "Fémur distal",
  "Distal fibula": "Peroné distal",
  "Distal humerus": "Húmero distal",
  "Distal metacarpals": "Metacarpianos distales",
  "Distal metatarsals": "Metatarsianos distales",
  "Distal radius": "Radio distal",
  "Distal tibia": "Tibia distal",
  "Distal tibia and fibula": "Tibia y peroné distales",
  "Distal ulna": "Cúbito distal",
  "Distribution pattern": "Patrón de distribución",
  "Divisions and cords": "Divisiones y cordones",
  "Doppler findings": "Hallazgos Doppler",
  "Dorsal ganglia": "Ganglios dorsales",
  "Ductal dilatation": "Dilatación ductal",
  "Ductal morphology": "Morfología ductal",
  "Duodenum": "Duodeno",
  "Dynamic contrast enhancement": "Realce dinámico con contraste",
  "Early ischemic signs (ASPECTS)": "Signos isquémicos precoces (ASPECTS)",
  "Elbow joint and cartilage": "Articulación del codo y cartílago",
  "Elbow joint effusion": "Derrame articular del codo",
  "Elbow joint space": "Espacio articular del codo",
  "Embolic agent and dose": "Agente embólico y dosis",
  "Embryo/fetus": "Embrión/feto",
  "Enhancement kinetics": "Cinética de realce",
  "Enhancement pattern": "Patrón de realce",
  "Enhancing lesions": "Lesiones con realce",
  "Epididymis": "Epidídimo",
  "Epidural space confirmation": "Confirmación del espacio epidural",
  "Estimated fetal weight and percentile": "Peso fetal estimado y percentil",
  "Ethmoid cells": "Celdillas etmoidales",
  "Excretory phase": "Fase excretora",
  "Extensor compartment": "Compartimento extensor",
  "Extensor tendons": "Tendones extensores",
  "External auditory canals": "Conductos auditivos externos",
  "Extramural vascular invasion": "Invasión vascular extramural",
  "Extraocular muscles": "Músculos extraoculares",
  "Extravasation": "Extravasación",
  "Extrinsic ligaments": "Ligamentos extrínsecos",
  "Facet joints L5-S1": "Articulaciones facetarias L5-S1",
  "Facial nerve canal": "Canal del nervio facial",
  "Facial nerves": "Nervios faciales",
  "Fasciae": "Fascias",
  "Fat pads": "Almohadillas grasas",
  "Feeding arteries": "Arterias nutricias",
  "Femoral head and neck": "Cabeza y cuello femoral",
  "Femoral head coverage": "Cobertura de cabeza femoral",
  "Femoral heads and acetabula": "Cabezas femorales y acetábulos",
  "Femoral neck": "Cuello femoral",
  "Femoral nerve": "Nervio femoral",
  "Femoral region": "Región femoral",
  "Femoral shaft": "Diáfisis femoral",
  "Fetal abdomen": "Abdomen fetal",
  "Fetal biometry": "Biometría fetal",
  "Fetal face": "Cara fetal",
  "Fetal head and brain": "Cabeza y cerebro fetal",
  "Fetal limbs": "Extremidades fetales",
  "Fetal spine": "Columna fetal",
  "Fetal thorax and heart": "Tórax y corazón fetal",
  "Fibular head": "Cabeza del peroné",
  "Fibular shaft": "Diáfisis peronea",
  "Filling defects": "Defectos de repleción",
  "Findings": "Hallazgos",
  "Fistulae and abscesses": "Fístulas y abscesos",
  "Flexor compartment": "Compartimento flexor",
  "Flexor tendons": "Tendones flexores",
  "Foramen magnum": "Foramen magno",
  "Fracture type": "Tipo de fractura",
  "Free intraperitoneal air": "Neumoperitoneo",
  "Frontal sinuses": "Senos frontales",
  "Gastrocnemius muscles": "Músculos gastrocnemios",
  "Germinal matrix": "Matriz germinal",
  "Gestational sac": "Saco gestacional",
  "Gland parenchyma": "Parénquima glandular",
  "Glenoid": "Glenoides",
  "Global coronal alignment": "Alineación coronal global",
  "Global sagittal alignment": "Alineación sagital global",
  "Globes": "Globos oculares",
  "Great saphenous veins": "Venas safenas internas",
  "Great vessels": "Grandes vasos",
  "Greater and lesser trochanter": "Trocánter mayor y menor",
  "Ground-glass opacities": "Opacidades en vidrio deslustrado",
  "Guidance modality": "Modalidad de guía",
  "Hamstring muscles": "Músculos isquiotibiales",
  "Heart chambers": "Cámaras cardíacas",
  "Hemorrhagic exclusion": "Exclusión hemorrágica",
  "Hepatic artery anatomy": "Anatomía de la arteria hepática",
  "Hepatic veins": "Venas hepáticas",
  "Hernia content": "Contenido herniario",
  "Hernia sac": "Saco herniario",
  "Hilum preservation": "Preservación hiliar",
  "Hip joint": "Articulación de la cadera",
  "Hip joint and cartilage": "Articulación de cadera y cartílago",
  "Hip joint effusion": "Derrame articular de cadera",
  "Hip joint space": "Espacio articular de cadera",
  "Hip joints": "Articulaciones de la cadera",
  "Honeycombing": "Panalización",
  "Humeral shaft": "Diáfisis humeral",
  "Hydrocele": "Hidrocele",
  "Hyperdense vessel sign": "Signo del vaso hiperdenso",
  "Ileum": "Íleon",
  "Iliac bones": "Huesos ilíacos",
  "Iliac vessels": "Vasos ilíacos",
  "Included intracranial structures": "Estructuras intracraneales incluidas",
  "Infrarenal aorta": "Aorta infrarrenal",
  "Injected substance and volume": "Sustancia y volumen inyectados",
  "Inner ears and cochlea": "Oídos internos y cóclea",
  "Intermetatarsal spaces": "Espacios intermetatarsianos",
  "Internal and external iliac arteries": "Arterias ilíacas interna y externa",
  "Internal auditory canals": "Conductos auditivos internos",
  "Internal carotid arteries": "Arterias carótidas internas",
  "Interosseous membrane": "Membrana interósea",
  "Interphalangeal joints": "Articulaciones interfalángicas",
  "Intervertebral disc spaces": "Espacios discales intervertebrales",
  "Intervertebral discs cervical": "Discos intervertebrales cervicales",
  "Intervertebral discs cervicothoracic": "Discos intervertebrales cervicotorácicos",
  "Intervertebral discs lumbar": "Discos intervertebrales lumbares",
  "Intervertebral discs thoracic": "Discos intervertebrales torácicos",
  "Intraconal and extraconal spaces": "Espacios intraconal y extraconal",
  "Intracranial arteries": "Arterias intracraneales",
  "Intraglandular ducts": "Conductos intraglandulares",
  "Intrahepatic bile ducts": "Vías biliares intrahepáticas",
  "Intrinsic ligaments": "Ligamentos intrínsecos",
  "Ischemic core volume": "Volumen del core isquémico",
  "Jejunum": "Yeyuno",
  "Joint": "Articulación",
  "Joint distension": "Distensión articular",
  "Joint effusion": "Derrame articular",
  "Joints and alignment": "Articulaciones y alineación",
  "Jugular veins": "Venas yugulares",
  "Kidneys and adrenal glands": "Riñones y glándulas suprarrenales",
  "Knee joint space": "Espacio articular de rodilla",
  "Knee joints": "Articulaciones de la rodilla",
  "L1-L2 vertebral bodies": "Cuerpos vertebrales L1-L2",
  "L5 vertebral body": "Cuerpo vertebral L5",
  "L5-S1 disc space": "Espacio discal L5-S1",
  "Labrum or ligaments": "Labrum o ligamentos",
  "Lacrimal glands": "Glándulas lagrimales",
  "Larynx": "Laringe",
  "Lateral collateral ligament complex": "Complejo ligamentario colateral lateral",
  "Lateral compartment": "Compartimento lateral",
  "Lateral pelvic lymph nodes": "Ganglios pélvicos laterales",
  "Lateral ventricles": "Ventrículos laterales",
  "Left anterior descending artery": "Arteria descendente anterior",
  "Left anterior zones": "Zonas anteriores izquierdas",
  "Left axillary lymph nodes": "Ganglios linfáticos axilares izquierdos",
  "Left axillary vein": "Vena axilar izquierda",
  "Left basilic and cephalic veins": "Venas basílica y cefálica izquierdas",
  "Left brachial veins": "Venas braquiales izquierdas",
  "Left breast enhancement": "Realce de mama izquierda",
  "Left circumflex artery": "Arteria circunfleja",
  "Left common carotid artery": "Arteria carótida común izquierda",
  "Left common femoral artery": "Arteria femoral común izquierda",
  "Left common femoral vein": "Vena femoral común izquierda",
  "Left condyle": "Cóndilo izquierdo",
  "Left external carotid artery": "Arteria carótida externa izquierda",
  "Left fallopian tube": "Trompa de Falopio izquierda",
  "Left hip alpha angle": "Ángulo alfa cadera izquierda",
  "Left hip beta angle": "Ángulo beta cadera izquierda",
  "Left hip Graf classification": "Clasificación de Graf cadera izquierda",
  "Left inguinal canal": "Canal inguinal izquierdo",
  "Left internal carotid artery": "Arteria carótida interna izquierda",
  "Left intrarenal resistive indices": "Índices de resistencia intrarrenales izquierdos",
  "Left kidney morphology": "Morfología renal izquierda",
  "Left lateral zones": "Zonas laterales izquierdas",
  "Left main coronary artery": "Tronco coronario izquierdo",
  "Left ovary": "Ovario izquierdo",
  "Left parotid gland": "Glándula parótida izquierda",
  "Left pleural space": "Espacio pleural izquierdo",
  "Left popliteal artery": "Arteria poplítea izquierda",
  "Left popliteal vein": "Vena poplítea izquierda",
  "Left posterior zones": "Zonas posteriores izquierdas",
  "Left renal artery Doppler": "Doppler arteria renal izquierda",
  "Left ribs": "Costillas izquierdas",
  "Left sternoclavicular joint": "Articulación esternoclavicular izquierda",
  "Left subclavian vein": "Vena subclavia izquierda",
  "Left submandibular gland": "Glándula submandibular izquierda",
  "Left superficial femoral artery": "Arteria femoral superficial izquierda",
  "Left superficial femoral vein": "Vena femoral superficial izquierda",
  "Left testis": "Testículo izquierdo",
  "Left tibial and peroneal arteries": "Arterias tibiales y peroneas izquierdas",
  "Left tibial and peroneal veins": "Venas tibiales y peroneas izquierdas",
  "Left TMJ disc position closed mouth": "Posición del disco ATM izquierda boca cerrada",
  "Left TMJ disc position open mouth": "Posición del disco ATM izquierda boca abierta",
  "Left ureter": "Uréter izquierdo",
  "Left vertebral artery": "Arteria vertebral izquierda",
  "Leg length discrepancy": "Dismetría de miembros inferiores",
  "Level and cause of obstruction": "Nivel y causa de la obstrucción",
  "LI-RADS category": "Categoría LI-RADS",
  "Lumbar and sacral spine": "Columna lumbar y sacra",
  "Lumbosacral plexus": "Plexo lumbosacro",
  "Lung apices": "Vértices pulmonares",
  "Lung sliding": "Deslizamiento pleural",
  "Lymph node morphology": "Morfología ganglionar",
  "Main duct": "Conducto principal",
  "Main portal vein": "Vena porta principal",
  "Mandibular alveolar ridge": "Reborde alveolar mandibular",
  "Mandibular body": "Cuerpo mandibular",
  "Mandibular canal": "Canal mandibular",
  "Manubrium": "Manubrio",
  "Masses": "Masas",
  "Mastoid air cells": "Celdillas mastoideas",
  "Maxillary alveolar ridge": "Reborde alveolar maxilar",
  "Maxillary bones": "Huesos maxilares",
  "Maxillary sinuses": "Senos maxilares",
  "Mechanical axis": "Eje mecánico",
  "Medial clavicles": "Extremos mediales de las clavículas",
  "Median nerve": "Nervio mediano",
  "Mediastinum and great vessels": "Mediastino y grandes vasos",
  "Mesenteric arteries": "Arterias mesentéricas",
  "Mesenteric fat and vessels": "Grasa y vasos mesentéricos",
  "Mesenteric lymph nodes": "Ganglios linfáticos mesentéricos",
  "Mesorectal lymph nodes": "Ganglios mesorrectales",
  "Metacarpophalangeal joints": "Articulaciones metacarpofalángicas",
  "Metatarsals and phalanges": "Metatarsianos y falanges",
  "Metatarsophalangeal joints": "Articulaciones metatarsofalángicas",
  "Middle cerebral arteries": "Arterias cerebrales medias",
  "Middle cranial fossa": "Fosa craneal media",
  "Middle ears": "Oídos medios",
  "Middle ears and ossicles": "Oídos medios y cadena osicular",
  "Middle mediastinum": "Mediastino medio",
  "Midline structures": "Estructuras de línea media",
  "Mismatch ratio": "Ratio de mismatch",
  "Mosaic attenuation": "Atenuación en mosaico",
  "MTT and Tmax maps": "Mapas de MTT y Tmax",
  "Muscle tears or collections": "Roturas musculares o colecciones",
  "Nasal bones": "Huesos nasales",
  "Nasal cavity and septum": "Cavidad nasal y tabique",
  "Nasal septum": "Tabique nasal",
  "Nasopharyngeal airway": "Vía aérea nasofaríngea",
  "Nasopharynx and oropharynx": "Nasofaringe y orofaringe",
  "Needle gauge": "Calibre de la aguja",
  "Needle placement": "Colocación de la aguja",
  "Needle type and gauge": "Tipo y calibre de aguja",
  "Nephrostogram findings": "Hallazgos del nefrostograma",
  "Nerve roots C5-T1": "Raíces nerviosas C5-T1",
  "Nerve roots L1-S3": "Raíces nerviosas L1-S3",
  "Neural foramina cervical": "Forámenes neurales cervicales",
  "Neural foramina lumbar": "Forámenes neurales lumbares",
  "Neural foramina thoracic": "Forámenes neurales torácicos",
  "Neurovascular bundles": "Paquetes neurovasculares",
  "Neurovascular structures": "Estructuras neurovasculares",
  "Nodule TI-RADS category": "Categoría TI-RADS del nódulo",
  "Nodules": "Nódulos",
  "Non-enhancing lesions": "Lesiones sin realce",
  "Non-target embolization": "Embolización no diana",
  "Number of gestations": "Número de gestaciones",
  "Number of lumens": "Número de luces",
  "Number of passes": "Número de pases",
  "Optic chiasm": "Quiasma óptico",
  "Optic nerves": "Nervios ópticos",
  "Optic nerves and chiasm": "Nervios ópticos y quiasma",
  "Orbital fat": "Grasa orbitaria",
  "Orbital walls": "Paredes orbitarias",
  "Ostiomeatal complexes": "Complejos ostiomeatales",
  "Pancreas and bowel": "Páncreas e intestino",
  "Paranasal sinuses": "Senos paranasales",
  "Paravertebral soft tissues": "Partes blandas paravertebrales",
  "Patellar tendon": "Tendón rotuliano",
  "Pedicles and posterior elements": "Pedículos y elementos posteriores",
  "Pelvic bones and hips": "Huesos pélvicos y caderas",
  "Pelvic parameters": "Parámetros pélvicos",
  "Pelvic ring": "Anillo pélvico",
  "Pelvic ring and hips": "Anillo pélvico y caderas",
  "Penumbra volume": "Volumen de penumbra",
  "Periappendiceal fat": "Grasa periapendicular",
  "Periarticular tendons": "Tendones periarticulares",
  "Peripheral zone T2 signal": "Señal T2 de zona periférica",
  "Peritoneal spill": "Paso peritoneal",
  "Peritoneum and mesenteric fat": "Peritoneo y grasa mesentérica",
  "Periventricular white matter": "Sustancia blanca periventricular",
  "Petrous bones": "Peñascos",
  "Phalanges": "Falanges",
  "PI-RADS assessment": "Evaluación PI-RADS",
  "Piriformis muscles": "Músculos piriformes",
  "Pituitary gland": "Glándula hipófisis",
  "Pituitary stalk": "Tallo hipofisario",
  "Plantar plates": "Placas plantares",
  "Plantaris tendon": "Tendón plantar delgado",
  "Pleural effusion": "Derrame pleural",
  "Pleural effusion characteristics": "Características del derrame pleural",
  "Pleural effusion location and size": "Localización y cuantía del derrame pleural",
  "Pleural thickening": "Engrosamiento pleural",
  "Pneumothorax check": "Control de neumotórax",
  "Popliteal artery left": "Arteria poplítea izquierda",
  "Popliteal artery right": "Arteria poplítea derecha",
  "Portal venous phase": "Fase portal",
  "Post-procedure check": "Control postprocedimiento",
  "Post-procedure pneumothorax": "Neumotórax postprocedimiento",
  "Post-procedure pneumothorax check": "Control de neumotórax postprocedimiento",
  "Post-procedure position": "Posición postprocedimiento",
  "Post-void residual": "Residuo posmiccional",
  "Posterior cerebral arteries": "Arterias cerebrales posteriores",
  "Posterior cranial fossa": "Fosa craneal posterior",
  "Posterior elements": "Elementos posteriores",
  "Posterior fossa": "Fosa posterior",
  "Posterior mediastinum": "Mediastino posterior",
  "Posterior pharyngeal wall": "Pared faríngea posterior",
  "Posterior tuberosity": "Tuberosidad posterior",
  "Presacral soft tissues": "Partes blandas presacras",
  "Presacral space": "Espacio presacro",
  "Prevertebral soft tissues": "Partes blandas prevertebrales",
  "Prostate": "Próstata",
  "Prostate (if applicable)": "Próstata (si procede)",
  "Prostate size and morphology": "Tamaño y morfología prostática",
  "Prostate size and volume": "Tamaño y volumen prostáticos",
  "Proximal femur": "Fémur proximal",
  "Proximal humerus": "Húmero proximal",
  "Proximal radius": "Radio proximal",
  "Proximal radius and ulna": "Radio y cúbito proximales",
  "Proximal tibia": "Tibia proximal",
  "Proximal tibia and fibula": "Tibia y peroné proximales",
  "Proximal ulna": "Cúbito proximal",
  "Psoas and iliacus muscles": "Músculos psoas e ilíaco",
  "Pulleys": "Poleas",
  "Pulmonary arteries": "Arterias pulmonares",
  "Quadriceps muscles": "Músculos cuádriceps",
  "Quadriceps tendon": "Tendón cuadricipital",
  "Radial shaft": "Diáfisis radial",
  "Radiocarpal joint": "Articulación radiocarpiana",
  "Rami and angles": "Ramas y ángulos mandibulares",
  "Rectal tumor location and morphology": "Localización y morfología del tumor rectal",
  "Reducibility with Valsalva": "Reductibilidad con Valsalva",
  "Relationship to adjacent structures": "Relación con estructuras adyacentes",
  "Renal arteries and veins": "Arterias y venas renales",
  "Renal enhancement pattern": "Patrón de realce renal",
  "Renal masses": "Masas renales",
  "Residual stenosis post": "Estenosis residual post",
  "Reticular pattern": "Patrón reticular",
  "Retroperitoneum": "Retroperitoneo",
  "Ribs and sternum": "Costillas y esternón",
  "Right and left portal branches": "Ramas portales derecha e izquierda",
  "Right anterior zones": "Zonas anteriores derechas",
  "Right axillary lymph nodes": "Ganglios linfáticos axilares derechos",
  "Right axillary vein": "Vena axilar derecha",
  "Right basilic and cephalic veins": "Venas basílica y cefálica derechas",
  "Right brachial veins": "Venas braquiales derechas",
  "Right breast enhancement": "Realce de mama derecha",
  "Right common carotid artery": "Arteria carótida común derecha",
  "Right common femoral artery": "Arteria femoral común derecha",
  "Right common femoral vein": "Vena femoral común derecha",
  "Right condyle": "Cóndilo derecho",
  "Right coronary artery": "Arteria coronaria derecha",
  "Right external carotid artery": "Arteria carótida externa derecha",
  "Right fallopian tube": "Trompa de Falopio derecha",
  "Right hip alpha angle": "Ángulo alfa cadera derecha",
  "Right hip beta angle": "Ángulo beta cadera derecha",
  "Right hip Graf classification": "Clasificación de Graf cadera derecha",
  "Right inguinal canal": "Canal inguinal derecho",
  "Right internal carotid artery": "Arteria carótida interna derecha",
  "Right intrarenal resistive indices": "Índices de resistencia intrarrenales derechos",
  "Right kidney morphology": "Morfología renal derecha",
  "Right lateral zones": "Zonas laterales derechas",
  "Right ovary": "Ovario derecho",
  "Right parotid gland": "Glándula parótida derecha",
  "Right pleural space": "Espacio pleural derecho",
  "Right popliteal artery": "Arteria poplítea derecha",
  "Right popliteal vein": "Vena poplítea derecha",
  "Right posterior zones": "Zonas posteriores derechas",
  "Right renal artery Doppler": "Doppler arteria renal derecha",
  "Right ribs": "Costillas derechas",
  "Right sternoclavicular joint": "Articulación esternoclavicular derecha",
  "Right subclavian vein": "Vena subclavia derecha",
  "Right submandibular gland": "Glándula submandibular derecha",
  "Right superficial femoral artery": "Arteria femoral superficial derecha",
  "Right superficial femoral vein": "Vena femoral superficial derecha",
  "Right testis": "Testículo derecho",
  "Right tibial and peroneal arteries": "Arterias tibiales y peroneas derechas",
  "Right tibial and peroneal veins": "Venas tibiales y peroneas derechas",
  "Right TMJ disc position closed mouth": "Posición del disco ATM derecha boca cerrada",
  "Right TMJ disc position open mouth": "Posición del disco ATM derecha boca abierta",
  "Right ureter": "Uréter derecho",
  "Right vertebral artery": "Arteria vertebral derecha",
  "Risser sign": "Signo de Risser",
  "Run-off post-procedure": "Run-off postprocedimiento",
  "S1 vertebral body": "Cuerpo vertebral S1",
  "Sacral canal": "Canal sacro",
  "Sacral foramina": "Forámenes sacros",
  "Sacral nerve roots": "Raíces nerviosas sacras",
  "Sacral segments": "Segmentos sacros",
  "Sacrococcygeal alignment": "Alineación sacrococcígea",
  "Sacrum and coccyx": "Sacro y cóccix",
  "Salivary ducts": "Conductos salivales",
  "Scalene muscles": "Músculos escalenos",
  "Scapulae and clavicles": "Escápulas y clavículas",
  "Scapular body": "Cuerpo escapular",
  "Sciatic nerve": "Nervio ciático",
  "Sclerosant or embolic agent": "Agente esclerosante o embólico",
  "Scrotal wall": "Pared escrotal",
  "Sella turcica": "Silla turca",
  "Site and extent of occlusion": "Localización y extensión de la oclusión",
  "Skull and facial bones": "Cráneo y huesos faciales",
  "Skull and paranasal sinuses": "Cráneo y senos paranasales",
  "Skull base": "Base del cráneo",
  "Skull base foramina": "Forámenes de la base del cráneo",
  "Small saphenous veins": "Venas safenas externas",
  "Soft palate": "Paladar blando",
  "Soft tissues and subcutaneous emphysema": "Partes blandas y enfisema subcutáneo",
  "Soleus muscle": "Músculo sóleo",
  "Solid abdominal organs": "Órganos sólidos abdominales",
  "Specimen adequacy": "Adecuación de la muestra",
  "Spermatic cord": "Cordón espermático",
  "Spermatic cords": "Cordones espermáticos",
  "Sphenoid sinus": "Seno esfenoidal",
  "Sphenoid sinuses": "Senos esfenoidales",
  "Spinal canal": "Canal raquídeo",
  "Spinal cord cervical": "Médula espinal cervical",
  "Spinal cord signal cervical": "Señal de médula espinal cervical",
  "Spinal cord signal thoracic": "Señal de médula espinal torácica",
  "Spinal cord thoracic": "Médula espinal torácica",
  "Spine of scapula": "Espina de la escápula",
  "Spleen and splenic vein": "Bazo y vena esplénica",
  "Stasis endpoint": "Punto de estasis",
  "Stenosis": "Estenosis",
  "Stenosis degree pre": "Grado de estenosis pre",
  "Sternal alignment": "Alineación esternal",
  "Sternal body": "Cuerpo esternal",
  "Sternoclavicular joint": "Articulación esternoclavicular",
  "Sternoclavicular joints": "Articulaciones esternoclaviculares",
  "Strictures": "Estenosis",
  "Subclavian vessels": "Vasos subclavios",
  "Sublingual glands": "Glándulas sublinguales",
  "Subtalar joint": "Articulación subastragalina",
  "Superficial posterior compartment": "Compartimento posterior superficial",
  "Suprapatellar bursa": "Bursa suprarrotuliana",
  "Suprarenal aorta": "Aorta suprarrenal",
  "Suprasellar cistern": "Cisterna supraselar",
  "Synovium": "Sinovial",
  "T staging (rectal wall invasion)": "Estadificación T (invasión de pared rectal)",
  "T11-T12 vertebral bodies": "Cuerpos vertebrales T11-T12",
  "Target bile duct": "Conducto biliar objetivo",
  "Target facet joints": "Articulaciones facetarias objetivo",
  "Target joint": "Articulación objetivo",
  "Target kidney and calyx": "Riñón y cáliz objetivo",
  "Target lesion": "Lesión diana",
  "Target lesion location and size": "Localización y tamaño de la lesión diana",
  "Target level": "Nivel objetivo",
  "Target nodule": "Nódulo objetivo",
  "Target structure": "Estructura diana",
  "Target vein": "Vena objetivo",
  "Target vertebral level": "Nivel vertebral objetivo",
  "Target vessel": "Vaso diana",
  "Tegmen tympani": "Tegmen timpánico",
  "Temporomandibular joints": "Articulaciones temporomandibulares",
  "Terminal ileum": "Íleon terminal",
  "TFCC": "CFCT",
  "Third ventricle": "Tercer ventrículo",
  "Thoracic spine": "Columna torácica",
  "Tibial and peroneal arteries left": "Arterias tibiales y peroneas izquierdas",
  "Tibial and peroneal arteries right": "Arterias tibiales y peroneas derechas",
  "Tibial plateau": "Meseta tibial",
  "Tibial shaft": "Diáfisis tibial",
  "Tibiotalar joint": "Articulación tibioastragalina",
  "Traction bronchiectasis": "Bronquiectasias de tracción",
  "Transition zone T2 signal": "Señal T2 de zona transicional",
  "Triceps tendon": "Tendón del tríceps",
  "Trunks": "Troncos",
  "Ulnar nerve": "Nervio cubital",
  "Ulnar shaft": "Diáfisis cubital",
  "Umbilical cord": "Cordón umbilical",
  "Uncovertebral joints": "Articulaciones uncovertebrales",
  "Ureters": "Uréteres",
  "Urethra (if included)": "Uretra (si se incluye)",
  "Uterine cavity": "Cavidad uterina",
  "Uterus and adnexa": "Útero y anejos",
  "Venous occlusion confirmation": "Confirmación de oclusión venosa",
  "Venous outflow": "Drenaje venoso",
  "Vertebral arteries": "Arterias vertebrales",
  "Vertebral bodies C1-C7": "Cuerpos vertebrales C1-C7",
  "Vertebral bodies C1-T4": "Cuerpos vertebrales C1-T4",
  "Vertebral bodies cervical": "Cuerpos vertebrales cervicales",
  "Vertebral bodies L1-L5": "Cuerpos vertebrales L1-L5",
  "Vertebral bodies L1-S1": "Cuerpos vertebrales L1-S1",
  "Vertebral bodies lumbar": "Cuerpos vertebrales lumbares",
  "Vertebral bodies T1-T12": "Cuerpos vertebrales T1-T12",
  "Vertebral bodies thoracic": "Cuerpos vertebrales torácicos",
  "Vertebral body morphology": "Morfología del cuerpo vertebral",
  "Vesicoureteral reflux": "Reflujo vesicoureteral",
  "Vestibular and cochlear nerves": "Nervios vestibular y coclear",
  "Vestibule and semicircular canals": "Vestíbulo y conductos semicirculares",
  "Volume injected": "Volumen inyectado",
  "Wall thickness": "Grosor parietal",
  "Xiphoid process": "Apéndice xifoides",
  "Yolk sac": "Saco vitelino",
  "Zygomatic arches": "Arcos cigomáticos",
  // ── Manual additions (labels absent from the UI dictionary) ──
  "Additional findings": "Hallazgos adicionales",
  "Adjacent joints": "Articulaciones adyacentes",
  "Adjacent structures": "Estructuras adyacentes",
  "Aortic arch diameter and morphology": "Diámetro y morfología del arco aórtico",
  "Aortic root and ascending aorta": "Raíz aórtica y aorta ascendente",
  "Aortic root diameter": "Diámetro de la raíz aórtica",
  "Ascending aorta diameter and morphology": "Diámetro y morfología de la aorta ascendente",
  "Celiac trunk": "Tronco celíaco",
  "Descending thoracic aorta diameter and morphology": "Diámetro y morfología de la aorta torácica descendente",
  "External iliac arteries": "Arterias ilíacas externas",
  "Gastrointestinal tract": "Tracto gastrointestinal",
  "Inferior mesenteric artery": "Arteria mesentérica inferior",
  "Infrarenal aorta diameter and morphology": "Diámetro y morfología de la aorta infrarrenal",
  "Intercostal arteries": "Arterias intercostales",
  "Internal iliac arteries": "Arterias ilíacas internas",
  "Intramural hematoma or dissection flap": "Hematoma intramural o flap de disección",
  "Liver and gallbladder": "Hígado y vesícula biliar",
  "Mesenteric and retroperitoneal structures": "Estructuras mesentéricas y retroperitoneales",
  "Pars interarticularis": "Pars interarticular",
  "Periaortic findings": "Hallazgos periaórticos",
  "Periaortic soft tissues and lymph nodes": "Partes blandas y ganglios periaórticos",
  "Pleura and pericardium": "Pleura y pericardio",
  "Radius": "Radio",
  "Renal pelvis and ureters": "Pelvis renal y uréteres",
  "Superior mesenteric artery": "Arteria mesentérica superior",
  "Supra-aortic trunks": "Troncos supraaórticos",
  "Ulcerated plaques": "Placas ulceradas",
  "Ulna": "Cúbito",
  "Acromion": "Acromion",
  "Cardiac morphology and function": "Morfología y función cardíaca",
  "Clivus": "Clivus",
  "Colon": "Colon",
  "Late gadolinium enhancement (LGE)": "Realce tardío de gadolinio (RTG)",
  "Left lower limb": "Miembro inferior izquierdo",
  "Right lower limb": "Miembro inferior derecho",
  "Placenta": "Placenta",
  "Run-off": "Run-off distal",
  "Tissue characterization": "Caracterización tisular",
  "Upper abdomen": "Abdomen superior",
  "Urinary bladder": "Vejiga urinaria",
  "Visceral branches": "Ramas viscerales",
  "Wall thickening or calcification": "Engrosamiento o calcificación parietal",
};

const PT: Record<string, string> = {
  "Lung parenchyma": "Parênquima pulmonar",
  "Mediastinum and hila": "Mediastino e hilos",
  "Cardiac silhouette": "Silhueta cardíaca",
  "Pleura and diaphragm": "Pleura e diafragma",
  "Bone structures": "Estruturas ósseas",
  "Soft tissues": "Partes moles",
  "Bowel gas pattern": "Padrão de gás intestinal",
  "Solid organ outlines": "Contornos de órgãos sólidos",
  "Peritoneal fat planes": "Planos gordurosos peritoneais",
  "Other findings": "Outros achados",
  "Supratentorial brain parenchyma": "Parênquima cerebral supratentorial",
  "Infratentorial brain parenchyma": "Parênquima cerebral infratentorial",
  "Ventricular system and midline": "Sistema ventricular e linha média",
  "Extra-axial spaces": "Espaços extra-axiais",
  "Skull and extracranial soft tissues": "Crânio e partes moles extracranianas",
  "Paranasal sinuses and mastoid cells": "Seios paranasais e células mastoideas",
  "Included cervical structures": "Estruturas cervicais incluídas",
  "Parotids": "Parótidas",
  "Submandibular glands": "Glândulas submandibulares",
  "Nasopharynx": "Nasofaringe",
  "Oropharynx": "Orofaringe",
  "Vocal cords": "Cordas vocais",
  "Piriform sinuses": "Seios piriformes",
  "Epiglottis": "Epiglote",
  "Trachea and cervical esophagus": "Traqueia e esôfago cervical",
  "Thyroid gland": "Glândula tireoide",
  "Parapharyngeal and retropharyngeal spaces": "Espaços parafaríngeo e retrofaríngeo",
  "Cervical vascular structures": "Estruturas vasculares cervicais",
  "Cervical lymph nodes": "Linfonodos cervicais",
  "Salivary glands": "Glândulas salivares",
  "Cervical spine": "Coluna cervical",
  "Mediastinal lymph nodes": "Linfonodos mediastinais",
  "Mediastinum": "Mediastino",
  "Trachea and bronchi": "Traqueia e brônquios",
  "Trachea": "Traqueia",
  "Esophagus": "Esôfago",
  "Coronary arteries": "Artérias coronárias",
  "Aorta and pulmonary arteries": "Aorta e artérias pulmonares",
  "Aorta and pulmonary artery": "Aorta e artéria pulmonar",
  "Aorta and great vessels": "Aorta e grandes vasos",
  "Heart and pericardium": "Coração e pericárdio",
  "Pleura": "Pleura",
  "Diaphragm": "Diafragma",
  "Thoracic wall": "Parede torácica",
  "Thoracic wall and bone structures": "Parede torácica e estruturas ósseas",
  "Thyroid and supradiaphragmatic tissues": "Tireoide e tecidos supradiafragmáticos",
  "Supradiaphragmatic tissues and thyroid": "Tireoide e tecidos supradiafragmáticos",
  "Included portions of the abdomen": "Porções incluídas do abdome",
  "Included portions of the thorax": "Porções incluídas do tórax",
  "Liver": "Fígado",
  "Liver parenchyma": "Parênquima hepático",
  "Liver and spleen": "Fígado e baço",
  "Hepatic focal lesions": "Lesões focais hepáticas",
  "Portal vein and hepatic artery": "Veia porta e artéria hepática",
  "Portal vein and hepatic veins": "Veia porta e veias hepáticas",
  "Portal vein": "Veia porta",
  "Hepatic artery": "Artéria hepática",
  "Gallbladder": "Vesícula biliar",
  "Gallbladder and bile ducts": "Vesícula biliar e vias biliares",
  "Bile ducts": "Vias biliares",
  "Intrahepatic and extrahepatic biliary ducts": "Vias biliares intra e extra-hepáticas",
  "Spleen": "Baço",
  "Pancreas": "Pâncreas",
  "Pancreatic duct": "Ducto pancreático",
  "Peripancreatic fat and vessels": "Gordura peripancreática e vasos",
  "Adrenal glands": "Glândulas adrenais",
  "Adrenal glands and kidneys": "Glândulas adrenais e rins",
  "Kidneys and ureters": "Rins e ureteres",
  "Kidneys": "Rins",
  "Right kidney": "Rim direito",
  "Left kidney": "Rim esquerdo",
  "Bladder": "Bexiga",
  "Peritoneum and retroperitoneum": "Peritônio e retroperitônio",
  "Peritoneum, retroperitoneum": "Peritônio e retroperitônio",
  "Peritoneum retroperitoneum": "Peritônio e retroperitônio",
  "Peritoneum": "Peritônio",
  "Stomach": "Estômago",
  "Stomach and bowel": "Estômago e intestino",
  "Small bowel and colon": "Intestino delgado e cólon",
  "Small bowel loops and colon": "Alças de intestino delgado e cólon",
  "Other pelvic structures": "Outras estruturas pélvicas",
  "Pelvic structures": "Estruturas pélvicas",
  "Pelvic organs": "Órgãos pélvicos",
  "Pelvic lymph nodes": "Linfonodos pélvicos",
  "Abdominal aorta and iliac arteries": "Aorta abdominal e artérias ilíacas",
  "Abdominal aorta": "Aorta abdominal",
  "Iliac arteries": "Artérias ilíacas",
  "Intraabdominal organs": "Órgãos intra-abdominais",
  "Intraabdominal solid organs": "Órgãos sólidos intra-abdominais",
  "Other intraabdominal structures": "Outras estruturas intra-abdominais",
  "Other thoracic structures": "Outras estruturas torácicas",
  "Other thoracic and abdominal structures": "Outras estruturas torácicas e abdominais",
  "Other mediastinal findings": "Outros achados mediastinais",
  "Bone structures and soft tissues": "Estruturas ósseas e partes moles",
  "Bone structures and included portions of the thorax": "Estruturas ósseas e porções incluídas do tórax",
  "Spine": "Coluna vertebral",
  "Bone density": "Densidade óssea",
  "Vertebral bodies": "Corpos vertebrais",
  "Intervertebral spaces and discs": "Espaços e discos intervertebrais",
  "Intervertebral discs": "Discos intervertebrais",
  "Spinal cord": "Medula espinhal",
  "Neural foramina": "Forames neurais",
  "Ligaments": "Ligamentos",
  "Craniocervical junction": "Junção craniocervical",
  "Conus medullaris and cauda equina": "Cone medular e cauda equina",
  "Uterus": "Útero",
  "Endometrium": "Endométrio",
  "Cervix": "Colo uterino",
  "Ovaries": "Ovários",
  "Fallopian tubes": "Trompas de Falópio",
  "Vagina": "Vagina",
  "Rectum and sigmoid": "Reto e sigmoide",
  "Rectum": "Reto",
  "Mesorectum": "Mesorreto",
  "Mesorectal fascia": "Fáscia mesorretal",
  "Perianal soft tissues": "Partes moles perianais",
  "Sphincters": "Esfíncteres",
  "Other perineal structures": "Outras estruturas perineais",
  "General prostate assessment": "Avaliação geral da próstata",
  "Peripheral zone": "Zona periférica",
  "Transition zone": "Zona de transição",
  "Seminal vesicles": "Vesículas seminais",
  "Bone structures and periprostatic tissues": "Estruturas ósseas e tecidos periprostáticos",
  "Lymph nodes": "Linfonodos",
  "Lymph nodes or adenopathy": "Linfonodos ou adenopatias",
  "Vascular structures": "Estruturas vasculares",
  "Soft tissues and associated structures": "Partes moles e estruturas associadas",
  "Supraspinatus tendon": "Tendão do supraespinhal",
  "Infraspinatus tendon": "Tendão do infraespinhal",
  "Subscapularis tendon": "Tendão do subescapular",
  "Teres minor tendon": "Tendão do redondo menor",
  "Biceps tendon": "Tendão do bíceps",
  "Subacromial subdeltoid bursa": "Bursa subacromial-subdeltoidea",
  "Subacromial-subdeltoid bursa": "Bursa subacromial-subdeltoidea",
  "Glenohumeral joint": "Articulação glenoumeral",
  "Labrum": "Labrum",
  "Acromioclavicular joint": "Articulação acromioclavicular",
  "Humerus": "Úmero",
  "Scapula": "Escápula",
  "Meniscus": "Menisco",
  "Medial meniscus": "Menisco medial",
  "Lateral meniscus": "Menisco lateral",
  "Anterior cruciate ligament": "Ligamento cruzado anterior",
  "Posterior cruciate ligament": "Ligamento cruzado posterior",
  "Medial collateral ligament": "Ligamento colateral medial",
  "Lateral collateral ligament": "Ligamento colateral lateral",
  "Patellar tendon and quadriceps tendon": "Tendão patelar e tendão do quadríceps",
  "Articular cartilage": "Cartilagem articular",
  "Cartilage and articular surfaces": "Cartilagem e superfícies articulares",
  "Joint effusion and synovium": "Derrame articular e sinóvia",
  "Soft tissues and popliteal fossa": "Partes moles e fossa poplítea",
  "Ligaments and tendons": "Ligamentos e tendões",
  "Ligaments and syndesmosis": "Ligamentos e sindesmose",
  "Ligaments and joints": "Ligamentos e articulações",
  "Joints": "Articulações",
  "Joint space": "Espaço articular",
  "Bones": "Ossos",
  "Tendons": "Tendões",
  "Tendons and muscles": "Tendões e músculos",
  "Nerves": "Nervos",
  "Bursae": "Bursas",
  "Achilles tendon": "Tendão de Aquiles",
  "Peroneal tendons": "Tendões fibulares",
  "Posterior tibial tendon": "Tendão tibial posterior",
  "Anterior tendons": "Tendões anteriores",
  "Lateral ligament complex": "Complexo ligamentar lateral",
  "Medial (deltoid) ligament": "Ligamento medial (deltoideo)",
  "Syndesmosis": "Sindesmose",
  "Tibiotalar and subtalar joints": "Articulações tibiotalar e subtalar",
  "Plantar fascia": "Fáscia plantar",
  "Bone marrow signal": "Sinal da medula óssea",
  "Femur": "Fêmur",
  "Tibia": "Tíbia",
  "Tibia and fibula": "Tíbia e fíbula",
  "Patella": "Patela",
  "Talus": "Tálus",
  "Calcaneus": "Calcâneo",
  "Ankle joint": "Articulação do tornozelo",
  "Carpal bones": "Ossos do carpo",
  "Distal radius and ulna": "Rádio e ulna distais",
  "Carpal tunnel": "Túnel do carpo",
  "Temporomandibular joint": "Articulação temporomandibular",
  "Masticatory muscles": "Músculos mastigatórios",
  "Retrodiscal space": "Espaço retrodiscal",
  "Mandible and temporal bone": "Mandíbula e osso temporal",
  "Willis polygon": "Polígono de Willis",
  "Ascending aorta": "Aorta ascendente",
  "Aortic arch": "Arco aórtico",
  "Descending aorta": "Aorta descendente",
  "Thoracic aorta": "Aorta torácica",
  "Renal arteries": "Artérias renais",
  "Celiac trunk and mesenteric arteries": "Tronco celíaco e artérias mesentéricas",
  "Aorta": "Aorta",
  "Free fluid": "Líquido livre",
  "Breast composition": "Composição mamária",
  "Overall composition of the breasts": "Composição geral das mamas",
  "Right breast": "Mama direita",
  "Left breast": "Mama esquerda",
  "Axillary lymph nodes": "Linfonodos axilares",
  "Skin and nipple": "Pele e mamilo",
  "Right breast parenchyma": "Parênquima mamário direito",
  "Left breast parenchyma": "Parênquima mamário esquerdo",
  "Focal lesions": "Lesões focais",
  "Ductal system": "Sistema ductal",
  "Skin and subcutaneous tissues": "Pele e tecido subcutâneo",
  "Muscles and fasciae": "Músculos e fáscias",
  "Muscles": "Músculos",
  "Skin": "Pele",
  "Subcutaneous tissues": "Tecido subcutâneo",
  "General thyroid assessment": "Avaliação geral da tireoide",
  "Right thyroid lobe": "Lobo tireoidiano direito",
  "Left thyroid lobe": "Lobo tireoidiano esquerdo",
  "Isthmus": "Istmo",
  "Thyroid nodules": "Nódulos tireoidianos",
  "Other structures": "Outras estruturas",
  "Ventricular size": "Tamanho ventricular",
  "Cortical structure": "Estrutura cortical",
  "Midline Structures": "Estruturas de linha média",
  "Choroid plexus": "Plexo coroide",
  "Femoral head": "Cabeça femoral",
  "Acetabular development": "Desenvolvimento acetabular",
  "Joint stability": "Estabilidade articular",
  "Visible portion of the meniscus": "Porção visível do menisco",
  "Superficial and deep femoral arteries": "Artérias femorais superficial e profunda",
  "Popliteal artery": "Artéria poplítea",
  "Tibialis and peroneal arteries": "Artérias tibiais e fibulares",
  "Distal arteries of the dorsal and plantar aspect of the foot": "Artérias distais do dorso e planta do pé",
  "Common femoral vein": "Veia femoral comum",
  "Superficial femoral vein": "Veia femoral superficial",
  "Popliteal vein": "Veia poplítea",
  "Tibial and peroneal veins": "Veias tibiais e fibulares",
  "Soft tissues and superficial venous system": "Partes moles e sistema venoso superficial",
  "Common femoral artery": "Artéria femoral comum",
  "Superficial femoral artery": "Artéria femoral superficial",
  "Tibial and peroneal arteries": "Artérias tibiais e fibulares",
  "Soft tissues and superficial arterial system": "Partes moles e sistema arterial superficial",
  "Nasopharynx, oropharynx and larynx": "Nasofaringe, orofaringe e laringe",
  "Parapharyngeal space": "Espaço parafaríngeo",
  "Vascular space": "Espaço vascular",
  "LV volumes and ejection fraction": "Volumes e fração de ejeção do VE",
  "RV volumes and ejection fraction": "Volumes e fração de ejeção do VD",
  "LV myocardial mass": "Massa miocárdica do VE",
  "Wall motion abnormalities": "Anomalias da contratilidade segmentar",
  "T2-weighted signal": "Sinal em T2",
  "T1 and T2 mapping": "Mapas T1 e T2",
  "ECV": "VEC",
  "LGE presence and distribution": "Presença e distribuição de RTG",
  "LGE location and burden": "Localização e carga de RTG",
  "Valves": "Válvulas",
  "Pericardium": "Pericárdio",
  "Pleural spaces": "Espaços pleurais",
  "Intracranial vascular structures": "Estruturas vasculares intracranianas",
  "Included cervical spine": "Coluna cervical incluída",
  "Included portions of the cervical spine and vascular structures": "Porções incluídas da coluna cervical e estruturas vasculares",
  "Sacroiliac joints": "Articulações sacroilíacas",
  "Right sacroiliac joint": "Articulação sacroilíaca direita",
  "Left sacroiliac joint": "Articulação sacroilíaca esquerda",
  "Sacral bone marrow": "Medula óssea sacral",
  "Iliac bone marrow": "Medula óssea ilíaca",
  "Periarticular soft tissues": "Partes moles periarticulares",
  "Lumbar spine": "Coluna lombar",
  "Sacrum": "Sacro",
  "Brain parenchyma": "Parênquima cerebral",
  "Ventricular system": "Sistema ventricular",
  "Other extra-axial spaces": "Outros espaços extra-axiais",
  "Sinuses": "Seios paranasais",
  "Cervical soft tissues": "Partes moles cervicais",
  "Lung": "Pulmão",
  "Mediastinum and hilum": "Mediastino e hilo",
  "Heart size and contours": "Tamanho e contornos cardíacos",
  "Clavicle": "Clavícula",
  "Clavicles": "Clavículas",
  "Sternum": "Esterno",
  "Ribs": "Costelas",
  "Humeral head": "Cabeça umeral",
  "Femoral heads": "Cabeças femorais",
  "Acetabulum": "Acetábulo",
  "Pubic symphysis": "Sínfise púbica",
  "Intervertebral spaces": "Espaços intervertebrais",
  "Facet joints": "Articulações facetárias",
  "Spinous processes": "Processos espinhosos",
  "Metacarpals": "Metacarpos",
  "Wrist joint": "Articulação do punho",
  "Tarsal bones": "Ossos do tarso",
  "Metatarsals": "Metatarsos",
  "Elbow joint": "Articulação do cotovelo",
  "Radius and ulna": "Rádio e ulna",
  "Organ outlines": "Contornos de órgãos",
  "Calvarium": "Calota craniana",
  "Facial bones": "Ossos da face",
  "Mandible": "Mandíbula",
  "Orbits": "Órbitas",
  "Extra-axial spaces and midline": "Espaços extra-axiais e linha média",
  "Hip joint": "Articulação do quadril",
  "Acetabular labrum": "Labrum acetabular",
  "Proximal femur": "Fêmur proximal",
  "Muscles and tendons": "Músculos e tendões",
  "Brachial plexus roots": "Raízes do plexo braquial",
  "Brachial plexus trunks": "Troncos do plexo braquial",
  "Brachial plexus cords": "Cordões do plexo braquial",
  // ── Merged from the UI sections dictionary (catalog coverage) ──
  "Access site": "Local de acesso",
  "Acetabulum and labrum": "Acetábulo e labrum",
  "Acromion and coracoid": "Acrômio e coracoide",
  "Adnexa": "Anexos",
  "Alignment": "Alinhamento",
  "Alignment and curvature": "Alinhamento e curvatura",
  "Amniotic fluid": "Líquido amniótico",
  "Ankle-brachial index": "Índice tornozelo-braquial",
  "Anterior cerebral arteries": "Artérias cerebrais anteriores",
  "Aorta at renal level": "Aorta ao nível renal",
  "Aortic arch and branches": "Arco aórtico e ramos",
  "Aortic wall and lumen": "Parede e lúmen aórtico",
  "Ascites": "Ascite",
  "Aspirated material": "Material aspirado",
  "Baker cyst": "Cisto de Baker",
  "Basilar artery": "Artéria basilar",
  "Biceps tendon insertion": "Inserção do tendão do bíceps",
  "Biceps tendon long head": "Tendão do bíceps porção longa",
  "Bladder and pelvic organs": "Bexiga e órgãos pélvicos",
  "Bladder morphology": "Morfologia vesical",
  "Bladder wall": "Parede vesical",
  "Breast composition and BPE": "Composição mamária e BPE",
  "Cardiac activity": "Atividade cardíaca",
  "Catheter type and size": "Tipo e calibre do cateter",
  "CBF maps": "Mapas de CBF",
  "CBV maps": "Mapas de CBV",
  "Cervical soft tissues and lymph nodes": "Partes moles cervicais e linfonodos",
  "Chest wall": "Parede torácica",
  "Circle of Willis": "Polígono de Willis",
  "Collateral circulation": "Circulação colateral",
  "Collection location and size": "Localização e tamanho da coleção",
  "Common carotid arteries": "Artérias carótidas comuns",
  "Common extensor tendon": "Tendão extensor comum",
  "Common flexor tendon": "Tendão flexor comum",
  "Common iliac arteries": "Artérias ilíacas comuns",
  "Complications": "Complicações",
  "Cortex and medullary canal": "Cortical e canal medular",
  "Costovertebral joints": "Articulações costovertebrais",
  "Crown-rump length and gestational age": "Comprimento cabeça-nádega e idade gestacional",
  "Cul-de-sac": "Fundo de saco de Douglas",
  "Dental structures": "Estruturas dentárias",
  "Descending thoracic aorta": "Aorta torácica descendente",
  "Diffusion restriction and ADC": "Restrição à difusão e ADC",
  "Distal femur": "Fêmur distal",
  "Distal humerus": "Úmero distal",
  "Distal tibia and fibula": "Tíbia e fíbula distais",
  "Divisions and cords": "Divisões e cordões",
  "Doppler findings": "Achados Doppler",
  "Dynamic contrast enhancement": "Realce dinâmico com contraste",
  "Early ischemic signs (ASPECTS)": "Sinais isquêmicos precoces (ASPECTS)",
  "Elbow joint and cartilage": "Articulação do cotovelo e cartilagem",
  "Elbow joint space": "Espaço articular do cotovelo",
  "Embryo/fetus": "Embrião/feto",
  "Enhancement kinetics": "Cinética de realce",
  "Epididymis": "Epidídimo",
  "Estimated fetal weight and percentile": "Peso fetal estimado e percentil",
  "Ethmoid cells": "Células etmoidais",
  "External auditory canals": "Condutos auditivos externos",
  "Extramural vascular invasion": "Invasão vascular extramural",
  "Extrinsic ligaments": "Ligamentos extrínsecos",
  "Facial nerve canal": "Canal do nervo facial",
  "Fat pads": "Coxins gordurosos",
  "Femoral head and neck": "Cabeça e colo femoral",
  "Femoral head coverage": "Cobertura da cabeça femoral",
  "Femoral heads and acetabula": "Cabeças femorais e acetábulos",
  "Femoral shaft": "Diáfise femoral",
  "Fetal abdomen": "Abdome fetal",
  "Fetal biometry": "Biometria fetal",
  "Fetal face": "Face fetal",
  "Fetal head and brain": "Cabeça e cérebro fetal",
  "Fetal limbs": "Membros fetais",
  "Fetal spine": "Coluna fetal",
  "Fetal thorax and heart": "Tórax e coração fetal",
  "Fibular shaft": "Diáfise fibular",
  "Findings": "Achados",
  "Frontal sinuses": "Seios frontais",
  "Gestational sac": "Saco gestacional",
  "Great saphenous veins": "Veias safenas magnas",
  "Greater and lesser trochanter": "Trocanter maior e menor",
  "Guidance modality": "Modalidade de guia",
  "Hemorrhagic exclusion": "Exclusão hemorrágica",
  "Hepatic veins": "Veias hepáticas",
  "Hip joint and cartilage": "Articulação do quadril e cartilagem",
  "Hip joint space": "Espaço articular do quadril",
  "Hip joints": "Articulações do quadril",
  "Humeral shaft": "Diáfise umeral",
  "Hydrocele": "Hidrocele",
  "Hyperdense vessel sign": "Sinal do vaso hiperdenso",
  "Iliac bones": "Ossos ilíacos",
  "Iliac vessels": "Vasos ilíacos",
  "Infrarenal aorta": "Aorta infrarrenal",
  "Inner ears and cochlea": "Orelhas internas e cóclea",
  "Internal and external iliac arteries": "Artérias ilíacas interna e externa",
  "Internal auditory canals": "Condutos auditivos internos",
  "Internal carotid arteries": "Artérias carótidas internas",
  "Intervertebral disc spaces": "Espaços discais intervertebrais",
  "Intervertebral discs cervicothoracic": "Discos intervertebrais cervicotorácicos",
  "Intracranial arteries": "Artérias intracranianas",
  "Intrinsic ligaments": "Ligamentos intrínsecos",
  "Ischemic core volume": "Volume do core isquêmico",
  "Joint": "Articulação",
  "Joint effusion": "Derrame articular",
  "Joints and alignment": "Articulações e alinhamento",
  "Jugular veins": "Veias jugulares",
  "Kidneys and adrenal glands": "Rins e glândulas suprarrenais",
  "Knee joint space": "Espaço articular do joelho",
  "Lateral collateral ligament complex": "Complexo ligamentar colateral lateral",
  "Lateral pelvic lymph nodes": "Linfonodos pélvicos laterais",
  "Left axillary vein": "Veia axilar esquerda",
  "Left basilic and cephalic veins": "Veias basílica e cefálica esquerdas",
  "Left brachial veins": "Veias braquiais esquerdas",
  "Left common carotid artery": "Artéria carótida comum esquerda",
  "Left common femoral artery": "Artéria femoral comum esquerda",
  "Left common femoral vein": "Veia femoral comum esquerda",
  "Left condyle": "Côndilo esquerdo",
  "Left external carotid artery": "Artéria carótida externa esquerda",
  "Left fallopian tube": "Tuba uterina esquerda",
  "Left hip alpha angle": "Ângulo alfa quadril esquerdo",
  "Left hip beta angle": "Ângulo beta quadril esquerdo",
  "Left hip Graf classification": "Classificação de Graf quadril esquerdo",
  "Left internal carotid artery": "Artéria carótida interna esquerda",
  "Left intrarenal resistive indices": "Índices de resistência intrarrenais esquerdos",
  "Left kidney morphology": "Morfologia renal esquerda",
  "Left ovary": "Ovário esquerdo",
  "Left popliteal artery": "Artéria poplítea esquerda",
  "Left popliteal vein": "Veia poplítea esquerda",
  "Left renal artery Doppler": "Doppler da artéria renal esquerda",
  "Left subclavian vein": "Veia subclávia esquerda",
  "Left superficial femoral artery": "Artéria femoral superficial esquerda",
  "Left superficial femoral vein": "Veia femoral superficial esquerda",
  "Left testis": "Testículo esquerdo",
  "Left tibial and peroneal arteries": "Artérias tibiais e fibulares esquerdas",
  "Left tibial and peroneal veins": "Veias tibiais e fibulares esquerdas",
  "Left TMJ disc position closed mouth": "Posição do disco ATM esquerda boca fechada",
  "Left TMJ disc position open mouth": "Posição do disco ATM esquerda boca aberta",
  "Left vertebral artery": "Artéria vertebral esquerda",
  "Lumbar and sacral spine": "Coluna lombar e sacral",
  "Lung apices": "Ápices pulmonares",
  "Main portal vein": "Veia porta principal",
  "Mastoid air cells": "Células mastoideas",
  "Maxillary bones": "Ossos maxilares",
  "Maxillary sinuses": "Seios maxilares",
  "Mediastinum and great vessels": "Mediastino e grandes vasos",
  "Mesenteric arteries": "Artérias mesentéricas",
  "Mesorectal lymph nodes": "Linfonodos messorretais",
  "Middle cerebral arteries": "Artérias cerebrais médias",
  "Middle ears and ossicles": "Orelhas médias e cadeia ossicular",
  "Mismatch ratio": "Razão de mismatch",
  "MTT and Tmax maps": "Mapas de MTT e Tmax",
  "Nasal bones": "Ossos nasais",
  "Nasal cavity and septum": "Cavidade nasal e septo",
  "Nasal septum": "Septo nasal",
  "Needle type and gauge": "Tipo e calibre da agulha",
  "Nerve roots C5-T1": "Raízes nervosas C5-T1",
  "Neurovascular bundles": "Feixes neurovasculares",
  "Neurovascular structures": "Estruturas neurovasculares",
  "Number of gestations": "Número de gestações",
  "Number of passes": "Número de passagens",
  "Ostiomeatal complexes": "Complexos ostiomeatais",
  "Pancreas and bowel": "Pâncreas e intestino",
  "Paranasal sinuses": "Seios paranasais",
  "Paravertebral soft tissues": "Partes moles paravertebrais",
  "Patellar tendon": "Tendão patelar",
  "Pedicles and posterior elements": "Pedículos e elementos posteriores",
  "Pelvic bones and hips": "Ossos pélvicos e quadris",
  "Pelvic ring and hips": "Anel pélvico e quadris",
  "Penumbra volume": "Volume de penumbra",
  "Peripheral zone T2 signal": "Sinal T2 da zona periférica",
  "Peritoneal spill": "Passagem peritoneal",
  "Peritoneum and mesenteric fat": "Peritônio e gordura mesentérica",
  "Phalanges": "Falanges",
  "PI-RADS assessment": "Avaliação PI-RADS",
  "Post-procedure check": "Controle pós-procedimento",
  "Post-procedure position": "Posição pós-procedimento",
  "Post-void residual": "Resíduo pós-miccional",
  "Posterior cerebral arteries": "Artérias cerebrais posteriores",
  "Prevertebral soft tissues": "Partes moles pré-vertebrais",
  "Prostate": "Próstata",
  "Prostate (if applicable)": "Próstata (se aplicável)",
  "Prostate size and morphology": "Tamanho e morfologia prostática",
  "Proximal humerus": "Úmero proximal",
  "Proximal radius": "Rádio proximal",
  "Proximal radius and ulna": "Rádio e ulna proximais",
  "Proximal tibia and fibula": "Tíbia e fíbula proximais",
  "Proximal ulna": "Ulna proximal",
  "Quadriceps tendon": "Tendão do quadríceps",
  "Radial shaft": "Diáfise radial",
  "Rectal tumor location and morphology": "Localização e morfologia do tumor retal",
  "Right and left portal branches": "Ramos portais direito e esquerdo",
  "Right axillary vein": "Veia axilar direita",
  "Right basilic and cephalic veins": "Veias basílica e cefálica direitas",
  "Right brachial veins": "Veias braquiais direitas",
  "Right common carotid artery": "Artéria carótida comum direita",
  "Right common femoral artery": "Artéria femoral comum direita",
  "Right common femoral vein": "Veia femoral comum direita",
  "Right condyle": "Côndilo direito",
  "Right external carotid artery": "Artéria carótida externa direita",
  "Right fallopian tube": "Tuba uterina direita",
  "Right hip alpha angle": "Ângulo alfa quadril direito",
  "Right hip beta angle": "Ângulo beta quadril direito",
  "Right hip Graf classification": "Classificação de Graf quadril direito",
  "Right internal carotid artery": "Artéria carótida interna direita",
  "Right intrarenal resistive indices": "Índices de resistência intrarrenais direitos",
  "Right kidney morphology": "Morfologia renal direita",
  "Right ovary": "Ovário direito",
  "Right popliteal artery": "Artéria poplítea direita",
  "Right popliteal vein": "Veia poplítea direita",
  "Right renal artery Doppler": "Doppler da artéria renal direita",
  "Right subclavian vein": "Veia subclávia direita",
  "Right superficial femoral artery": "Artéria femoral superficial direita",
  "Right superficial femoral vein": "Veia femoral superficial direita",
  "Right testis": "Testículo direito",
  "Right tibial and peroneal arteries": "Artérias tibiais e fibulares direitas",
  "Right tibial and peroneal veins": "Veias tibiais e fibulares direitas",
  "Right TMJ disc position closed mouth": "Posição do disco ATM direita boca fechada",
  "Right TMJ disc position open mouth": "Posição do disco ATM direita boca aberta",
  "Right vertebral artery": "Artéria vertebral direita",
  "Sacrum and coccyx": "Sacro e cóccix",
  "Scalene muscles": "Músculos escalenos",
  "Scrotal wall": "Parede escrotal",
  "Site and extent of occlusion": "Localização e extensão da oclusão",
  "Skull and facial bones": "Crânio e ossos da face",
  "Skull base": "Base do crânio",
  "Small saphenous veins": "Veias safenas parvas",
  "Soft tissues and subcutaneous emphysema": "Partes moles e enfisema subcutâneo",
  "Specimen adequacy": "Adequação da amostra",
  "Spermatic cords": "Cordões espermáticos",
  "Sphenoid sinus": "Seio esfenoidal",
  "Sphenoid sinuses": "Seios esfenoidais",
  "Spinal canal": "Canal raquidiano",
  "Spleen and splenic vein": "Baço e veia esplênica",
  "Subclavian vessels": "Vasos subclávios",
  "Suprapatellar bursa": "Bursa suprapatelar",
  "Suprarenal aorta": "Aorta suprarrenal",
  "T staging (rectal wall invasion)": "Estadiamento T (invasão da parede retal)",
  "Target lesion": "Lesão-alvo",
  "Target structure": "Estrutura-alvo",
  "Target vessel": "Vaso-alvo",
  "Tegmen tympani": "Tégmen timpânico",
  "Temporomandibular joints": "Articulações temporomandibulares",
  "TFCC": "CFCT",
  "Thoracic spine": "Coluna torácica",
  "Tibial shaft": "Diáfise tibial",
  "Tibiotalar joint": "Articulação tibiotalar",
  "Transition zone T2 signal": "Sinal T2 da zona de transição",
  "Trunks": "Troncos",
  "Ulnar shaft": "Diáfise ulnar",
  "Umbilical cord": "Cordão umbilical",
  "Urethra (if included)": "Uretra (se incluída)",
  "Uterine cavity": "Cavidade uterina",
  "Uterus and adnexa": "Útero e anexos",
  "Vertebral arteries": "Artérias vertebrais",
  "Vertebral bodies C1-C7": "Corpos vertebrais C1-C7",
  "Vertebral bodies C1-T4": "Corpos vertebrais C1-T4",
  "Vertebral bodies L1-L5": "Corpos vertebrais L1-L5",
  "Vertebral bodies L1-S1": "Corpos vertebrais L1-S1",
  "Vertebral bodies T1-T12": "Corpos vertebrais T1-T12",
  "Vesicoureteral reflux": "Refluxo vesicoureteral",
  "Yolk sac": "Saco vitelínico",
  "Zygomatic arches": "Arcos zigomáticos",
};

export function translateSectionLabel(name: string, lang: OutputLanguage): string {
  if (lang === "es") return ES[name] ?? name;
  if (lang === "pt") return PT[name] ?? name;
  return name;
}

/** True if `name` has an explicit entry in the translation dictionary for `lang`. */
export function hasSectionTranslation(name: string, lang: OutputLanguage): boolean {
  if (lang === "es") return name in ES;
  if (lang === "pt") return name in PT;
  return true;
}

function getDictForLang(lang: OutputLanguage): Record<string, string> | null {
  if (lang === "es") return ES;
  if (lang === "pt") return PT;
  return null;
}

export function translateTemplate(template: string, lang: OutputLanguage): string {
  if (lang === "en" || !template) return template;
  const dict = getDictForLang(lang);
  if (!dict) return template;

  return template.replace(
    /(\*{2,3})([^*]+)\1/g,
    (match, stars: string, label: string) => {
      const trimmed = label.trim();
      const translated = dict[trimmed];
      if (!translated) return match;
      return `${stars}${translated}${stars}`;
    },
  );
}

export function translateLabelInLine(line: string, lang: OutputLanguage): string {
  const dict = getDictForLang(lang);
  if (!dict) return line;
  const m = line.match(/^([^:]+):\s/);
  if (!m) return line;
  const label = m[1].trim();
  const translated = dict[label];
  if (!translated) return line;
  return translated + ": " + line.slice(m[0].length);
}

const NORMALITY_PHRASE_ES: [RegExp, string][] = [
  [/\bNormal in size,? morphology and density\b/gi, "De tamaño, morfología y densidad normales"],
  [/\bNormal in size,? morphology and signal intensity\b/gi, "De tamaño, morfología e intensidad de señal normales"],
  [/\bNormal in size,? morphology and echogenicity\b/gi, "De tamaño, morfología y ecogenicidad normales"],
  [/\bNormal in size and density\b/gi, "De tamaño y densidad normales"],
  [/\bNormal in size and signal intensity\b/gi, "De tamaño e intensidad de señal normales"],
  [/\bNormal in size and morphology bilaterally\b/gi, "De tamaño y morfología normales bilateralmente"],
  [/\bNormal in size and morphology\b/gi, "De tamaño y morfología normales"],
  [/\bNormal in size,? echogenicity and echotexture\b/gi, "De tamaño, ecogenicidad y ecotextura normales"],
  [/\bNormal in size and echogenicity\b/gi, "De tamaño y ecogenicidad normales"],
  [/\bNormal in size, morphology and signal intensity bilaterally\b/gi, "De tamaño, morfología e intensidad de señal normales bilateralmente"],
  [/\bNormal in size and signal intensity bilaterally\b/gi, "De tamaño e intensidad de señal normales bilateralmente"],
  [/\bNormal distension and wall thickness\b/gi, "Distensión y grosor parietal normales"],
  [/\bNormal position and morphology\b/gi, "De posición y morfología normales"],
  [/\bNormal caliber and morphology\b/gi, "De calibre y morfología normales"],
  [/\bNormal heart size\b/gi, "Corazón de tamaño normal"],
  [/\bNormal bone density\b/gi, "Densidad ósea normal"],
  [/\bNormal gastric wall\b/gi, "Pared gástrica normal"],
  [/\bNormal caliber\b/gi, "De calibre normal"],
  [/\bNormal appearance\b/gi, "Aspecto normal"],
  [/\bNo significant abnormalities\b/gi, "Sin alteraciones significativas"],
  [/\bNo significant findings\b/gi, "Sin hallazgos significativos"],
  [/\bNo focal lesions\b/gi, "Sin lesiones focales"],
  [/\bNo gallstones or wall thickening\b/gi, "Sin litiasis ni engrosamiento parietal"],
  [/\bNo intrahepatic or extrahepatic biliary dilation\b/gi, "Sin dilatación biliar intrahepática ni extrahepática"],
  [/\bNo hydronephrosis or focal lesions\b/gi, "Sin hidronefrosis ni lesiones focales"],
  [/\bNo hydronephrosis\b/gi, "Sin hidronefrosis"],
  [/\bNo intraluminal lesions\b/gi, "Sin lesiones intraluminales"],
  [/\bNo free fluid or lymphadenopathy\b/gi, "Sin líquido libre ni adenopatías"],
  [/\bNo free fluid\b/gi, "Sin líquido libre"],
  [/\bNo wall thickening or obstruction\b/gi, "Sin engrosamiento parietal ni obstrucción"],
  [/\bNo wall thickening\b/gi, "Sin engrosamiento parietal"],
  [/\bNo pulmonary nodules,? consolidations or ground-glass opacities\b/gi, "Sin nódulos pulmonares, consolidaciones ni opacidades en vidrio deslustrado"],
  [/\bNo pathologically enlarged mediastinal lymph nodes\b/gi, "Sin adenopatías mediastínicas de tamaño patológico"],
  [/\bNo pathologically enlarged cervical lymph nodes\b/gi, "Sin adenopatías cervicales de tamaño patológico"],
  [/\bNo pathologically enlarged lymph nodes\b/gi, "Sin adenopatías de tamaño patológico"],
  [/\bNo endoluminal lesions\b/gi, "Sin lesiones endoluminales"],
  [/\bNo significant coronary calcifications\b/gi, "Sin calcificaciones coronarias significativas"],
  [/\bNo aneurysm or dissection\b/gi, "Sin aneurisma ni disección"],
  [/\bNo aneurysm\b/gi, "Sin aneurisma"],
  [/\bNo pericardial effusion\b/gi, "Sin derrame pericárdico"],
  [/\bNo pleural effusion or thickening\b/gi, "Sin derrame pleural ni engrosamiento"],
  [/\bNo pleural effusion\b/gi, "Sin derrame pleural"],
  [/\bNo thoracic wall abnormalities\b/gi, "Sin alteraciones de la pared torácica"],
  [/\bNo acute vertebral fractures or significant degenerative changes\b/gi, "Sin fracturas vertebrales agudas ni cambios degenerativos significativos"],
  [/\bNo acute fractures or suspicious bone lesions\b/gi, "Sin fracturas agudas ni lesiones óseas sospechosas"],
  [/\bNo acute fractures\b/gi, "Sin fracturas agudas"],
  [/\bNo extra-axial collections\b/gi, "Sin colecciones extra-axiales"],
  [/\bNo mass lesions,? hemorrhage or acute ischemic changes\b/gi, "Sin lesiones ocupantes de espacio, hemorragia ni cambios isquémicos agudos"],
  [/\bNo mass lesions in the posterior fossa\b/gi, "Sin lesiones ocupantes de espacio en fosa posterior"],
  [/\bNo mass lesions\b/gi, "Sin lesiones ocupantes de espacio"],
  [/\bNo significant stenosis\b/gi, "Sin estenosis significativa"],
  [/\bNo significant soft tissue abnormalities\b/gi, "Sin alteraciones significativas de partes blandas"],
  [/\bNo significant pelvic abnormalities\b/gi, "Sin alteraciones pélvicas significativas"],
  [/\bNo significant supradiaphragmatic abnormalities\b/gi, "Sin alteraciones supradiafragmáticas significativas"],
  [/\bNo additional findings\b/gi, "Sin hallazgos adicionales"],
  [/\bNo additional (?:thoracic |mediastinal |intraabdominal |thoraco-abdominal )?abnormalities\b/gi, "Sin alteraciones adicionales"],
  [/\bNo fracture or bone lesion\b/gi, "Sin fractura ni lesión ósea"],
  [/\bNo fracture\b/gi, "Sin fractura"],
  [/\bNo effusion\b/gi, "Sin derrame"],
  [/\bNo vascular abnormalities\b/gi, "Sin alteraciones vasculares"],
  [/\bNo bone marrow signal abnormalities or fractures\b/gi, "Sin alteraciones de señal de médula ósea ni fracturas"],
  [/\bNo bone marrow edema\b/gi, "Sin edema de médula ósea"],
  [/\bNo tears or tendinopathy\b/gi, "Sin roturas ni tendinopatía"],
  [/\bNo tears\b/gi, "Sin roturas"],
  [/\bNo consolidations,? effusions or nodules\b/gi, "Sin consolidaciones, derrames ni nódulos"],
  [/\bNo cortical irregularities\b/gi, "Sin irregularidades corticales"],
  [/\bNo rib fractures\b/gi, "Sin fracturas costales"],
  [/\bNo signs of obstruction\b/gi, "Sin signos de obstrucción"],
  [/\bNo bursitis\b/gi, "Sin bursitis"],
  [/\bNo gallstones\b/gi, "Sin litiasis"],
  [/\bNo biliary dilation\b/gi, "Sin dilatación biliar"],
  [/\bNo obstruction\b/gi, "Sin obstrucción"],
  [/\bPatent portal vein and hepatic artery\b/gi, "Vena porta y arteria hepática permeables"],
  [/\bPatent portal vein with hepatopetal flow\b/gi, "Vena porta permeable con flujo hepatópeto"],
  [/\bPatent (?:tibial and peroneal|distal) arteries\b/gi, "Arterias permeables"],
  [/\bNormal lung parenchyma\b/gi, "Parénquima pulmonar normal"],
  [/\bNormal mediastinal structures\b/gi, "Estructuras mediastínicas normales"],
  [/\bNormal paranasal sinuses\b/gi, "Senos paranasales normales"],
  [/\bNormal epiglottis\b/gi, "Epiglotis normal"],
  [/\bNormal tracheal caliber\b/gi, "Tráquea de calibre normal"],
  [/\bNormal salivary glands\b/gi, "Glándulas salivales normales"],
  [/\bNormal parotid glands bilaterally\b/gi, "Glándulas parótidas normales bilateralmente"],
  [/\bNormal submandibular glands bilaterally\b/gi, "Glándulas submandibulares normales bilateralmente"],
  [/\bSymmetric vocal cords\b/gi, "Cuerdas vocales simétricas"],
  [/\bNormal circle of Willis\b/gi, "Polígono de Willis normal"],
  [/\bNo aneurysms\b/gi, "Sin aneurismas"],
  [/\bNormal piriform sinuses\b/gi, "Senos piriformes normales"],
  [/\bNormal parapharyngeal spaces\b/gi, "Espacios parafaríngeos normales"],
  [/\bNormal nasopharyngeal mucosa\b/gi, "Mucosa nasofaríngea normal"],
  [/\bNormal oropharyngeal structures\b/gi, "Estructuras orofaríngeas normales"],
  [/\bNormal brain parenchyma\b/gi, "Parénquima cerebral normal"],
  [/\bNormal supratentorial brain parenchyma\b/gi, "Parénquima cerebral supratentorial normal"],
  [/\bNormal infratentorial brain parenchyma\b/gi, "Parénquima cerebral infratentorial normal"],
  [/\bNormal size and morphology of the ventricular system\b/gi, "Sistema ventricular de tamaño y morfología normales"],
  [/\bMidline structures in normal position\b/gi, "Estructuras de línea media en posición normal"],
  [/\bNormal diaphragm position\b/gi, "Diafragma en posición normal"],
  [/\bThyroid within normal limits\b/gi, "Tiroides dentro de límites normales"],
  [/\bExtracranial soft tissues unremarkable\b/gi, "Partes blandas extracraneales sin hallazgos"],
  [/\bVascular structures unremarkable\b/gi, "Estructuras vasculares sin hallazgos"],
  [/\bUreters not dilated\b/gi, "Uréteres no dilatados"],
  [/\bClear lung fields\b/gi, "Campos pulmonares libres"],
  [/\bNormal mediastinal silhouette and hila\b/gi, "Silueta mediastínica e hilios normales"],
  [/\bNormal joint space\b/gi, "Espacio articular normal"],
  [/\bNormal joint spaces\b/gi, "Espacios articulares normales"],
  [/\bNo pancreatic duct dilation\b/gi, "Sin dilatación del conducto pancreático"],
  [/\bNormal compressibility\b/gi, "Compresibilidad normal"],
  [/\bTriphasic waveform\b/gi, "Onda trifásica"],
  [/\bNormal corticomedullary differentiation\b/gi, "Diferenciación corticomedular normal"],
  [/\bVisualized portions unremarkable\b/gi, "Porciones visualizadas sin hallazgos"],
  [/\bNormal signal intensity\b/gi, "Intensidad de señal normal"],
  [/\bNo restricted diffusion or abnormal enhancement\b/gi, "Sin restricción de la difusión ni realce anómalo"],
  [/\bNo calvarial (?:fractures|abnormalities)\b/gi, "Sin alteraciones calvariales"],
  [/\bNo acute cervical spine abnormalities\b/gi, "Sin alteraciones agudas de la columna cervical"],
  [/\bNormal cervical alignment\b/gi, "Alineación cervical normal"],
  [/\bNo marrow signal abnormalities\b/gi, "Sin alteraciones de señal medular"],
  [/\bNormal vertebral body height,? alignment and marrow signal\b/gi, "Cuerpos vertebrales de altura, alineación y señal medular normales"],
  [/\bNormal intervertebral disc height and signal intensity\b/gi, "Discos intervertebrales de altura e intensidad de señal normales"],
  [/\bNo significant disc herniation\b/gi, "Sin herniación discal significativa"],
  [/\bNormal ligamentous structures\b/gi, "Estructuras ligamentarias normales"],
  [/\bNormal spinal cord signal and morphology\b/gi, "Médula espinal de señal y morfología normales"],
  [/\bNormal meniscal morphology and signal\b/gi, "Morfología y señal meniscal normales"],
  [/\bNormal ligamentous and tendinous structures\b/gi, "Estructuras ligamentarias y tendinosas normales"],
  [/\bNormal cartilage thickness and articular surfaces\b/gi, "Cartílago de grosor normal y superficies articulares normales"],
  [/\bNormal course and signal of visualized nerves\b/gi, "Trayecto y señal normales de los nervios visualizados"],
  [/\bNormal tendinous structures\b/gi, "Estructuras tendinosas normales"],
  [/\bNormal ankle joint\b/gi, "Articulación del tobillo normal"],
  [/\bNormal glenohumeral joint\b/gi, "Articulación glenohumeral normal"],
  [/\bNormal elbow joint\b/gi, "Articulación del codo normal"],
  [/\bNormal wrist joint\b/gi, "Articulación de la muñeca normal"],
  [/\bNormal acromioclavicular joint\b/gi, "Articulación acromioclavicular normal"],
  [/\bNormal temporomandibular joint\b/gi, "Articulación temporomandibular normal"],
];

const NORMALITY_PHRASE_PT: [RegExp, string][] = [
  [/\bNormal in size,? morphology and density\b/gi, "De tamanho, morfologia e densidade normais"],
  [/\bNormal in size,? morphology and signal intensity\b/gi, "De tamanho, morfologia e intensidade de sinal normais"],
  [/\bNormal in size,? morphology and echogenicity\b/gi, "De tamanho, morfologia e ecogenicidade normais"],
  [/\bNormal in size and density\b/gi, "De tamanho e densidade normais"],
  [/\bNormal in size and signal intensity\b/gi, "De tamanho e intensidade de sinal normais"],
  [/\bNormal in size and morphology bilaterally\b/gi, "De tamanho e morfologia normais bilateralmente"],
  [/\bNormal in size and morphology\b/gi, "De tamanho e morfologia normais"],
  [/\bNormal in size,? echogenicity and echotexture\b/gi, "De tamanho, ecogenicidade e ecotextura normais"],
  [/\bNormal in size and echogenicity\b/gi, "De tamanho e ecogenicidade normais"],
  [/\bNormal distension and wall thickness\b/gi, "Distensão e espessura parietal normais"],
  [/\bNormal position and morphology\b/gi, "De posição e morfologia normais"],
  [/\bNormal caliber and morphology\b/gi, "De calibre e morfologia normais"],
  [/\bNormal heart size\b/gi, "Coração de tamanho normal"],
  [/\bNormal bone density\b/gi, "Densidade óssea normal"],
  [/\bNormal caliber\b/gi, "De calibre normal"],
  [/\bNormal appearance\b/gi, "Aspecto normal"],
  [/\bNo significant abnormalities\b/gi, "Sem alterações significativas"],
  [/\bNo significant findings\b/gi, "Sem achados significativos"],
  [/\bNo focal lesions\b/gi, "Sem lesões focais"],
  [/\bNo gallstones or wall thickening\b/gi, "Sem litíase nem espessamento parietal"],
  [/\bNo intrahepatic or extrahepatic biliary dilation\b/gi, "Sem dilatação biliar intra ou extra-hepática"],
  [/\bNo hydronephrosis or focal lesions\b/gi, "Sem hidronefrose nem lesões focais"],
  [/\bNo hydronephrosis\b/gi, "Sem hidronefrose"],
  [/\bNo free fluid or lymphadenopathy\b/gi, "Sem líquido livre nem linfonodomegalias"],
  [/\bNo free fluid\b/gi, "Sem líquido livre"],
  [/\bNo wall thickening\b/gi, "Sem espessamento parietal"],
  [/\bNo pulmonary nodules,? consolidations or ground-glass opacities\b/gi, "Sem nódulos pulmonares, consolidações nem opacidades em vidro fosco"],
  [/\bNo pathologically enlarged mediastinal lymph nodes\b/gi, "Sem linfonodos mediastinais de tamanho patológico"],
  [/\bNo pathologically enlarged lymph nodes\b/gi, "Sem linfonodos de tamanho patológico"],
  [/\bNo acute fractures\b/gi, "Sem fraturas agudas"],
  [/\bNo extra-axial collections\b/gi, "Sem coleções extra-axiais"],
  [/\bNo mass lesions\b/gi, "Sem lesões expansivas"],
  [/\bNo pleural effusion\b/gi, "Sem derrame pleural"],
  [/\bNo pericardial effusion\b/gi, "Sem derrame pericárdico"],
  [/\bNo aneurysm\b/gi, "Sem aneurisma"],
  [/\bNo effusion\b/gi, "Sem derrame"],
  [/\bNo fracture\b/gi, "Sem fratura"],
  [/\bNo gallstones\b/gi, "Sem litíase"],
  [/\bNo biliary dilation\b/gi, "Sem dilatação biliar"],
  [/\bNo obstruction\b/gi, "Sem obstrução"],
  [/\bPatent portal vein and hepatic artery\b/gi, "Veia porta e artéria hepática permeáveis"],
  [/\bNormal lung parenchyma\b/gi, "Parênquima pulmonar normal"],
  [/\bNormal paranasal sinuses\b/gi, "Seios paranasais normais"],
  [/\bNormal circle of Willis\b/gi, "Polígono de Willis normal"],
  [/\bNormal brain parenchyma\b/gi, "Parênquima cerebral normal"],
  [/\bNormal signal intensity\b/gi, "Intensidade de sinal normal"],
  [/\bClear lung fields\b/gi, "Campos pulmonares livres"],
  [/\bNormal joint space\b/gi, "Espaço articular normal"],
  [/\bNormal joint spaces\b/gi, "Espaços articulares normais"],
  [/\bNormal compressibility\b/gi, "Compressibilidade normal"],
  [/\bNormal corticomedullary differentiation\b/gi, "Diferenciação corticomedular normal"],
];

export function enforcePeriodSeparation(text: string): string {
  if (!text) return text;
  return text.replace(/^([^:\n]+:\s*)(.+)$/gm, (_match, prefix: string, desc: string) => {
    let fixed = desc.replace(/;\s*/g, ". ");
    fixed = fixed.replace(/,\s+(?=[A-ZÁÉÍÓÚÑÀÈÌÒÙÂÊÎÔÛÃÕÇ])/g, ". ");
    if (fixed !== desc) {
      fixed = fixed.replace(/\.\s*\./g, ".");
    }
    return prefix + fixed;
  });
}

export function mergeDuplicateSections(text: string): string {
  if (!text) return text;
  const lines = text.split("\n");
  const seen = new Map<string, number>();
  const result: string[] = [];

  for (const line of lines) {
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) { result.push(line); continue; }

    const label = line.slice(0, colonIdx).trim().toLowerCase();
    const content = line.slice(colonIdx + 1).trim();

    if (seen.has(label)) {
      const idx = seen.get(label)!;
      const existing = result[idx];
      const existingColonIdx = existing.indexOf(":");
      const existingContent = existing.slice(existingColonIdx + 1).trim();
      const prefix = existing.slice(0, existingColonIdx + 1);
      const merged = existingContent.endsWith(".")
        ? `${existingContent} ${content}`
        : `${existingContent}. ${content}`;
      result[idx] = `${prefix} ${merged}`;
    } else {
      seen.set(label, result.length);
      result.push(line);
    }
  }

  return result.join("\n");
}

// ---------------------------------------------------------------------------
// Safety net: fill or strip unfilled template placeholders
// ---------------------------------------------------------------------------
// Template fields are injected as "**Label**: {label lowercased}". If the model
// leaves a placeholder unfilled it must NEVER reach the report as a raw
// "{trachea and bronchi}" token. This replaces a whole-line placeholder value
// with the section's normality phrase (matched by the English placeholder
// token), falling back to a generic normal statement, and strips any stray
// leftover token.
const GENERIC_NORMAL: Record<OutputLanguage, string> = {
  es: "Sin alteraciones significativas.",
  en: "No significant abnormality.",
  pt: "Sem alterações significativas.",
};

export function fillTemplatePlaceholders(
  text: string,
  normalByToken: Map<string, string>,
  lang: OutputLanguage,
): string {
  if (!text || text.indexOf("{") === -1) return text;
  const fallback = GENERIC_NORMAL[lang] || GENERIC_NORMAL.en;

  // "Label: {token}"  (the whole value is a bare placeholder)
  let result = text.replace(
    /^([^\n:]+):[ \t]*\{([^{}\n]+)\}[ \t]*$/gm,
    (_m, label: string, token: string) => {
      const phrase = normalByToken.get(token.trim().toLowerCase());
      return `${label}: ${phrase || fallback}`;
    },
  );

  // Any remaining stray placeholder token anywhere → remove it.
  result = result.replace(/\{[^{}\n]+\}/g, "").replace(/[ \t]+$/gm, "");

  return result;
}

export function enforceOutputLanguage(text: string, lang: OutputLanguage): string {
  if (lang === "en" || !text) return text;

  const dict = getDictForLang(lang);
  const phrases = lang === "es" ? NORMALITY_PHRASE_ES : lang === "pt" ? NORMALITY_PHRASE_PT : null;

  let result = text;

  if (dict) {
    result = result.replace(/^([^\n:]+):\s/gm, (match, label: string) => {
      const trimmed = label.trim();
      const translated = dict[trimmed];
      if (translated) return translated + ": ";
      return match;
    });
  }

  if (phrases) {
    for (const [pattern, replacement] of phrases) {
      result = result.replace(pattern, replacement);
    }
  }

  result = enforcePeriodSeparation(result);

  return result;
}
