import { Template } from "./types";

const F = "****FINDINGS****\n";
const C = "\n****CONCLUSION****\n{conclusion}";
function t(id: number, title: string, technique: string, section: string, fields: string): Template {
  return { id, title, template: F + fields + C, technique, section };
}
function sec(label: string): string { return `***${label}***: {${label.toLowerCase()}}`; }
function fld(label: string): string { return `**${label}**: {${label.toLowerCase()}}`; }

export const DEFAULT_TEMPLATES: Template[] = [
  // ═══════════════════════════════════════════
  //  RADIOGRAFÍAS (XRay)
  // ═══════════════════════════════════════════
  t(1, "Radiografía de tórax", "XRay", "Thorax", [
    fld("Lung parenchyma"),
    fld("Mediastinum and hila"),
    fld("Cardiac silhouette"),
    fld("Pleura and diaphragm"),
    fld("Bone structures"),
    fld("Soft tissues"),
  ].join("\n")),

  t(2, "Radiografía de abdomen", "XRay", "Abdomen and pelvis", [
    fld("Bowel gas pattern"),
    fld("Solid organ outlines"),
    fld("Peritoneal fat planes"),
    fld("Soft tissues"),
    fld("Bone structures"),
    fld("Other findings"),
  ].join("\n")),

  t(3, "Radiografía de tobillo", "XRay", "Lower limbs", [
    fld("Distal tibia and fibula"),
    fld("Talus"),
    fld("Calcaneus"),
    fld("Ankle joint"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(4, "Radiografía de pie", "XRay", "Lower limbs", [
    fld("Tarsal bones"),
    fld("Metatarsals"),
    fld("Phalanges"),
    fld("Joints and alignment"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(5, "Radiografía de cráneo", "XRay", "Head and neck", [
    fld("Calvarium"),
    fld("Skull base"),
    fld("Facial bones"),
    fld("Paranasal sinuses"),
    fld("Orbits"),
    fld("Mandible"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(6, "Radiografía de columna cervical", "XRay", "Spine", [
    fld("Vertebral bodies C1-C7"),
    fld("Intervertebral disc spaces"),
    fld("Facet joints"),
    fld("Spinous processes"),
    fld("Alignment and curvature"),
    fld("Prevertebral soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(7, "Radiografía de columna torácica", "XRay", "Spine", [
    fld("Vertebral bodies T1-T12"),
    fld("Intervertebral disc spaces"),
    fld("Pedicles and posterior elements"),
    fld("Alignment and curvature"),
    fld("Costovertebral joints"),
    fld("Paravertebral soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(8, "Radiografía de columna lumbar", "XRay", "Spine", [
    fld("Vertebral bodies L1-L5"),
    fld("Intervertebral disc spaces"),
    fld("Facet joints"),
    fld("Sacroiliac joints"),
    fld("Alignment and curvature"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(9, "Radiografía de pelvis", "XRay", "Abdomen and pelvis", [
    fld("Femoral heads and acetabula"),
    fld("Hip joints"),
    fld("Sacroiliac joints"),
    fld("Pubic symphysis"),
    fld("Iliac bones"),
    fld("Sacrum and coccyx"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  TOMOGRAFÍAS (CT)
  // ═══════════════════════════════════════════
  t(10, "TC de cráneo", "CT", "Head and neck", [
    fld("Supratentorial brain parenchyma"),
    fld("Infratentorial brain parenchyma"),
    fld("Ventricular system and midline"),
    fld("Extra-axial spaces"),
    fld("Skull and extracranial soft tissues"),
    fld("Paranasal sinuses and mastoid cells"),
    fld("Orbits"),
    fld("Included cervical structures"),
  ].join("\n")),

  t(11, "TC de cuello", "CT", "Head and neck", [
    sec("Salivary glands") + "\n" + fld("Parotids") + "\n" + fld("Submandibular glands"),
    fld("Nasopharynx"),
    fld("Oropharynx"),
    sec("Larynx") + "\n" + fld("Vocal cords") + "\n" + fld("Piriform sinuses") + "\n" + fld("Epiglottis"),
    fld("Trachea and cervical esophagus"),
    fld("Thyroid gland"),
    fld("Parapharyngeal and retropharyngeal spaces"),
    fld("Cervical vascular structures"),
    fld("Cervical lymph nodes"),
    fld("Bone structures"),
  ].join("\n")),

  t(12, "TC de cabeza y cuello", "CT", "Head and neck", [
    fld("Supratentorial brain parenchyma"),
    fld("Infratentorial brain parenchyma"),
    fld("Ventricular system and midline"),
    fld("Extra-axial spaces"),
    fld("Skull and paranasal sinuses"),
    fld("Orbits"),
    fld("Salivary glands"),
    fld("Nasopharynx and oropharynx"),
    fld("Larynx"),
    fld("Thyroid gland"),
    fld("Cervical vascular structures"),
    fld("Cervical lymph nodes"),
    fld("Cervical spine"),
  ].join("\n")),

  t(13, "TC de cuello y tórax", "CT", "Thorax", [
    fld("Cervical soft tissues and salivary glands"),
    fld("Thyroid gland"),
    fld("Cervical vascular structures"),
    fld("Cervical lymph nodes"),
    fld("Lung parenchyma"),
    fld("Mediastinal lymph nodes"),
    fld("Trachea and bronchi"),
    fld("Esophagus"),
    fld("Aorta and great vessels"),
    fld("Heart and pericardium"),
    fld("Pleura and diaphragm"),
    fld("Bone structures"),
  ].join("\n")),

  t(14, "TC de tórax", "CT", "Thorax", [
    fld("Lung parenchyma"),
    fld("Mediastinal lymph nodes"),
    fld("Trachea and bronchi"),
    fld("Esophagus"),
    fld("Aorta and pulmonary arteries"),
    fld("Heart and pericardium"),
    fld("Pleura"),
    fld("Diaphragm"),
    fld("Thoracic wall"),
    fld("Thyroid and supradiaphragmatic tissues"),
    fld("Bone structures"),
    fld("Included portions of the abdomen"),
  ].join("\n")),

  t(15, "TC de tórax y abdomen", "CT", "Thorax", [
    fld("Lung parenchyma"),
    fld("Mediastinal lymph nodes"),
    fld("Trachea and bronchi"),
    fld("Esophagus"),
    fld("Aorta and pulmonary arteries"),
    fld("Heart and pericardium"),
    fld("Pleura and diaphragm"),
    fld("Liver"),
    fld("Gallbladder and bile ducts"),
    fld("Spleen"),
    fld("Pancreas"),
    fld("Adrenal glands"),
    fld("Kidneys and ureters"),
    fld("Bladder"),
    fld("Peritoneum and retroperitoneum"),
    fld("Stomach and bowel"),
    fld("Bone structures"),
  ].join("\n")),

  t(16, "TC de abdomen", "CT", "Abdomen and pelvis", [
    fld("Liver"),
    fld("Portal vein and hepatic artery"),
    fld("Gallbladder and bile ducts"),
    fld("Spleen"),
    fld("Pancreas"),
    fld("Adrenal glands"),
    fld("Kidneys and ureters"),
    fld("Bladder"),
    fld("Peritoneum and retroperitoneum"),
    fld("Stomach and bowel"),
    fld("Pelvic structures"),
    fld("Abdominal aorta and iliac arteries"),
    fld("Bone structures"),
    fld("Included portions of the thorax"),
  ].join("\n")),

  t(17, "TC de tórax, abdomen y pelvis", "CT", "Thorax", [
    fld("Lung parenchyma"),
    fld("Mediastinal lymph nodes"),
    fld("Trachea and bronchi"),
    fld("Esophagus"),
    fld("Aorta and pulmonary arteries"),
    fld("Heart and pericardium"),
    fld("Pleura and diaphragm"),
    fld("Liver"),
    fld("Gallbladder and bile ducts"),
    fld("Spleen"),
    fld("Pancreas"),
    fld("Adrenal glands"),
    fld("Kidneys and ureters"),
    fld("Bladder"),
    fld("Peritoneum and retroperitoneum"),
    fld("Stomach and bowel"),
    fld("Pelvic organs"),
    fld("Abdominal aorta and iliac arteries"),
    fld("Bone structures"),
  ].join("\n")),

  t(18, "AngioTC de miembros inferiores", "CT", "Lower limbs", [
    fld("Abdominal aorta and iliac arteries"),
    fld("Intraabdominal organs"),
    "**Left lower limb**:\n" + [
      "   " + fld("Common and superficial femoral arteries left"),
      "   " + fld("Popliteal artery left"),
      "   " + fld("Tibial and peroneal arteries left"),
      "   " + fld("Distal arteries of the foot left"),
    ].join("\n"),
    "**Right lower limb**:\n" + [
      "   " + fld("Common and superficial femoral arteries right"),
      "   " + fld("Popliteal artery right"),
      "   " + fld("Tibial and peroneal arteries right"),
      "   " + fld("Distal arteries of the foot right"),
    ].join("\n"),
    fld("Bone structures and soft tissues"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  RESONANCIAS (MRI)
  // ═══════════════════════════════════════════
  t(19, "RM de abdomen", "MRI", "Abdomen and pelvis", [
    fld("Liver"),
    fld("Portal vein and hepatic artery"),
    fld("Gallbladder and bile ducts"),
    fld("Spleen"),
    fld("Pancreas"),
    fld("Adrenal glands"),
    fld("Kidneys"),
    fld("Bladder"),
    fld("Peritoneum and retroperitoneum"),
    fld("Stomach and bowel"),
    fld("Pelvic structures"),
    fld("Bone structures"),
  ].join("\n")),

  t(20, "RM de hígado", "MRI", "Abdomen and pelvis", [
    fld("Liver parenchyma"),
    fld("Hepatic focal lesions"),
    fld("Portal vein and hepatic veins"),
    fld("Hepatic artery"),
    fld("Gallbladder and bile ducts"),
    fld("Spleen"),
    fld("Pancreas"),
    fld("Adrenal glands and kidneys"),
    fld("Other intraabdominal structures"),
    fld("Bone structures"),
  ].join("\n")),

  t(21, "RM de páncreas", "MRI", "Abdomen and pelvis", [
    fld("Pancreas"),
    fld("Pancreatic duct"),
    fld("Gallbladder and bile ducts"),
    fld("Liver"),
    fld("Spleen"),
    fld("Adrenal glands and kidneys"),
    fld("Peripancreatic fat and vessels"),
    fld("Peritoneum and retroperitoneum"),
    fld("Other intraabdominal structures"),
  ].join("\n")),

  t(22, "RM de pelvis femenina", "MRI", "Abdomen and pelvis", [
    fld("Uterus"),
    fld("Endometrium"),
    fld("Cervix"),
    fld("Ovaries"),
    fld("Fallopian tubes"),
    fld("Vagina"),
    fld("Bladder"),
    fld("Rectum and sigmoid"),
    fld("Peritoneum and retroperitoneum"),
    fld("Pelvic lymph nodes"),
    fld("Bone structures"),
  ].join("\n")),

  t(23, "RM cardíaca", "MRI", "Thorax", [
    "**Cardiac morphology and function**:\n" + [
      "   " + fld("LV volumes and ejection fraction"),
      "   " + fld("RV volumes and ejection fraction"),
      "   " + fld("LV myocardial mass"),
      "   " + fld("Wall motion abnormalities"),
    ].join("\n"),
    "**Tissue characterization**:\n" + [
      "   " + fld("T2-weighted signal"),
      "   " + fld("T1 and T2 mapping"),
      "   " + fld("ECV"),
    ].join("\n"),
    "**Late gadolinium enhancement (LGE)**:\n" + [
      "   " + fld("LGE presence and distribution"),
      "   " + fld("LGE location and burden"),
    ].join("\n"),
    fld("Valves"),
    fld("Pericardium"),
    fld("Pleural spaces"),
    fld("Other findings"),
  ].join("\n")),

  t(24, "RM cerebral", "MRI", "Head and neck", [
    fld("Supratentorial brain parenchyma"),
    fld("Infratentorial brain parenchyma"),
    fld("Ventricular system and midline"),
    fld("Extra-axial spaces"),
    fld("Skull and extracranial soft tissues"),
    fld("Orbits"),
    fld("Paranasal sinuses and mastoid cells"),
    fld("Intracranial vascular structures"),
    fld("Included cervical spine"),
  ].join("\n")),

  t(25, "RM de cuello", "MRI", "Head and neck", [
    sec("Salivary glands") + "\n" + fld("Parotids") + "\n" + fld("Submandibular glands"),
    fld("Nasopharynx"),
    fld("Oropharynx"),
    sec("Larynx") + "\n" + fld("Vocal cords") + "\n" + fld("Piriform sinuses") + "\n" + fld("Epiglottis"),
    fld("Trachea"),
    fld("Thyroid gland"),
    fld("Parapharyngeal and retropharyngeal spaces"),
    fld("Cervical vascular structures"),
    fld("Cervical lymph nodes"),
    fld("Bone structures"),
  ].join("\n")),

  t(26, "RM de rodilla", "MRI", "Lower limbs", [
    fld("Medial meniscus"),
    fld("Lateral meniscus"),
    fld("Anterior cruciate ligament"),
    fld("Posterior cruciate ligament"),
    fld("Medial collateral ligament"),
    fld("Lateral collateral ligament"),
    fld("Patellar tendon and quadriceps tendon"),
    fld("Articular cartilage"),
    fld("Joint effusion and synovium"),
    fld("Bone structures"),
    fld("Soft tissues and popliteal fossa"),
  ].join("\n")),

  t(27, "RM de pie", "MRI", "Lower limbs", [
    fld("Tarsal bones"),
    fld("Metatarsals and phalanges"),
    fld("Joints and alignment"),
    fld("Tendons"),
    fld("Ligaments"),
    fld("Plantar fascia"),
    fld("Soft tissues"),
    fld("Bone marrow signal"),
  ].join("\n")),

  t(28, "RM de tobillo", "MRI", "Lower limbs", [
    fld("Achilles tendon"),
    fld("Peroneal tendons"),
    fld("Posterior tibial tendon"),
    fld("Anterior tendons"),
    fld("Lateral ligament complex"),
    fld("Medial (deltoid) ligament"),
    fld("Syndesmosis"),
    fld("Tibiotalar and subtalar joints"),
    fld("Bone structures"),
    fld("Soft tissues"),
  ].join("\n")),

  t(29, "RM de hombro", "MRI", "Upper limbs", [
    fld("Supraspinatus tendon"),
    fld("Infraspinatus tendon"),
    fld("Subscapularis tendon"),
    fld("Teres minor tendon"),
    fld("Biceps tendon"),
    fld("Subacromial-subdeltoid bursa"),
    fld("Glenohumeral joint"),
    fld("Labrum"),
    fld("Acromioclavicular joint"),
    fld("Bone structures"),
    fld("Soft tissues"),
  ].join("\n")),

  t(30, "RM de columna cervical", "MRI", "Spine", [
    fld("Vertebral bodies C1-C7"),
    fld("Intervertebral discs"),
    fld("Spinal cord"),
    fld("Neural foramina"),
    fld("Facet joints"),
    fld("Ligaments"),
    fld("Paravertebral soft tissues"),
    fld("Craniocervical junction"),
  ].join("\n")),

  t(31, "RM de columna torácica", "MRI", "Spine", [
    fld("Vertebral bodies T1-T12"),
    fld("Intervertebral discs"),
    fld("Spinal cord"),
    fld("Neural foramina"),
    fld("Facet joints"),
    fld("Ligaments"),
    fld("Paravertebral soft tissues"),
  ].join("\n")),

  t(32, "RM de columna lumbar", "MRI", "Spine", [
    fld("Vertebral bodies L1-L5"),
    fld("Intervertebral discs"),
    fld("Conus medullaris and cauda equina"),
    fld("Neural foramina"),
    fld("Facet joints"),
    fld("Ligaments"),
    fld("Paravertebral soft tissues"),
    fld("Sacrum"),
  ].join("\n")),

  t(33, "RM de articulaciones sacroilíacas", "MRI", "Spine", [
    fld("Right sacroiliac joint"),
    fld("Left sacroiliac joint"),
    fld("Sacral bone marrow"),
    fld("Iliac bone marrow"),
    fld("Periarticular soft tissues"),
    fld("Lumbar spine"),
    fld("Other findings"),
  ].join("\n")),

  t(34, "RM de columna completa", "MRI", "Spine", [
    "**Cervical spine**:\n" + [
      "   " + fld("Vertebral bodies cervical"),
      "   " + fld("Intervertebral discs cervical"),
      "   " + fld("Spinal cord cervical"),
      "   " + fld("Neural foramina cervical"),
    ].join("\n"),
    "**Thoracic spine**:\n" + [
      "   " + fld("Vertebral bodies thoracic"),
      "   " + fld("Intervertebral discs thoracic"),
      "   " + fld("Spinal cord thoracic"),
      "   " + fld("Neural foramina thoracic"),
    ].join("\n"),
    "**Lumbar spine**:\n" + [
      "   " + fld("Vertebral bodies lumbar"),
      "   " + fld("Intervertebral discs lumbar"),
      "   " + fld("Conus medullaris and cauda equina"),
      "   " + fld("Neural foramina lumbar"),
    ].join("\n"),
    fld("Ligaments"),
    fld("Paravertebral soft tissues"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  MAMOGRAFÍA
  // ═══════════════════════════════════════════
  t(35, "Mamografía", "Mammography", "Thorax", [
    fld("Breast composition"),
    fld("Right breast"),
    fld("Left breast"),
    fld("Axillary lymph nodes"),
    fld("Skin and nipple"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  ECOGRAFÍAS (Ultrasound)
  // ═══════════════════════════════════════════
  t(36, "Ecografía de abdomen", "Ultrasound", "Abdomen and pelvis", [
    fld("Liver"),
    fld("Portal vein"),
    fld("Gallbladder and bile ducts"),
    fld("Spleen"),
    fld("Pancreas"),
    fld("Right kidney"),
    fld("Left kidney"),
    fld("Bladder"),
    fld("Aorta"),
    fld("Free fluid"),
    fld("Other findings"),
  ].join("\n")),

  t(37, "Ecografía de cuello", "Ultrasound", "Head and neck", [
    fld("Thyroid gland"),
    fld("Salivary glands"),
    fld("Cervical lymph nodes"),
    fld("Cervical vascular structures"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(38, "Ecografía de tiroides", "Ultrasound", "Head and neck", [
    fld("Right thyroid lobe"),
    fld("Left thyroid lobe"),
    fld("Isthmus"),
    fld("Thyroid nodules"),
    fld("Cervical lymph nodes"),
    fld("Other findings"),
  ].join("\n")),

  t(39, "Ecografía de mama", "Ultrasound", "Thorax", [
    fld("Right breast parenchyma"),
    fld("Left breast parenchyma"),
    fld("Focal lesions"),
    fld("Ductal system"),
    fld("Axillary lymph nodes"),
    fld("Skin and subcutaneous tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(40, "Ecografía de partes blandas", "Ultrasound", "Upper limbs", [
    fld("Skin and subcutaneous tissues"),
    fld("Muscles and fasciae"),
    fld("Tendons"),
    fld("Vascular structures"),
    fld("Nerves"),
    fld("Other findings"),
  ].join("\n")),

  t(41, "Doppler de cuello", "Ultrasound", "Head and neck", [
    fld("Right common carotid artery"),
    fld("Right internal carotid artery"),
    fld("Right external carotid artery"),
    fld("Right vertebral artery"),
    fld("Left common carotid artery"),
    fld("Left internal carotid artery"),
    fld("Left external carotid artery"),
    fld("Left vertebral artery"),
    fld("Jugular veins"),
    fld("Other findings"),
  ].join("\n")),

  t(42, "Doppler venoso de miembros inferiores", "Ultrasound", "Lower limbs", [
    fld("Right common femoral vein"),
    fld("Right superficial femoral vein"),
    fld("Right popliteal vein"),
    fld("Right tibial and peroneal veins"),
    fld("Left common femoral vein"),
    fld("Left superficial femoral vein"),
    fld("Left popliteal vein"),
    fld("Left tibial and peroneal veins"),
    fld("Great saphenous veins"),
    fld("Small saphenous veins"),
    fld("Other findings"),
  ].join("\n")),

  t(43, "Doppler arterial de miembros inferiores", "Ultrasound", "Lower limbs", [
    fld("Right common femoral artery"),
    fld("Right superficial femoral artery"),
    fld("Right popliteal artery"),
    fld("Right tibial and peroneal arteries"),
    fld("Left common femoral artery"),
    fld("Left superficial femoral artery"),
    fld("Left popliteal artery"),
    fld("Left tibial and peroneal arteries"),
    fld("Ankle-brachial index"),
    fld("Other findings"),
  ].join("\n")),

  t(44, "Doppler venoso de miembros superiores", "Ultrasound", "Upper limbs", [
    fld("Right subclavian vein"),
    fld("Right axillary vein"),
    fld("Right brachial veins"),
    fld("Right basilic and cephalic veins"),
    fld("Left subclavian vein"),
    fld("Left axillary vein"),
    fld("Left brachial veins"),
    fld("Left basilic and cephalic veins"),
    fld("Other findings"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  RADIOGRAFÍAS (XRay) — nuevas
  // ═══════════════════════════════════════════
  t(45, "Radiografía de rodilla", "XRay", "Lower limbs", [
    fld("Distal femur"),
    fld("Proximal tibia and fibula"),
    fld("Patella"),
    fld("Knee joint space"),
    fld("Alignment"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(46, "Radiografía de cadera", "XRay", "Lower limbs", [
    fld("Femoral head and neck"),
    fld("Acetabulum"),
    fld("Hip joint space"),
    fld("Greater and lesser trochanter"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(47, "Radiografía de hombro", "XRay", "Upper limbs", [
    fld("Humeral head"),
    fld("Glenohumeral joint"),
    fld("Acromioclavicular joint"),
    fld("Acromion and coracoid"),
    fld("Scapula"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(48, "Radiografía de muñeca y mano", "XRay", "Upper limbs", [
    fld("Distal radius and ulna"),
    fld("Carpal bones"),
    fld("Metacarpals"),
    fld("Phalanges"),
    fld("Joints and alignment"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(49, "Radiografía de codo", "XRay", "Upper limbs", [
    fld("Distal humerus"),
    fld("Proximal radius"),
    fld("Proximal ulna"),
    fld("Elbow joint space"),
    fld("Fat pads"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(50, "Radiografía de fémur", "XRay", "Lower limbs", [
    fld("Proximal femur"),
    fld("Femoral shaft"),
    fld("Distal femur"),
    fld("Cortex and medullary canal"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(51, "Radiografía de tibia y peroné", "XRay", "Lower limbs", [
    fld("Proximal tibia and fibula"),
    fld("Tibial shaft"),
    fld("Fibular shaft"),
    fld("Distal tibia and fibula"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(52, "Radiografía de húmero", "XRay", "Upper limbs", [
    fld("Proximal humerus"),
    fld("Humeral shaft"),
    fld("Distal humerus"),
    fld("Cortex and medullary canal"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(53, "Radiografía de antebrazo", "XRay", "Upper limbs", [
    fld("Proximal radius and ulna"),
    fld("Radial shaft"),
    fld("Ulnar shaft"),
    fld("Distal radius and ulna"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(54, "Radiografía de senos paranasales", "XRay", "Head and neck", [
    fld("Maxillary sinuses"),
    fld("Frontal sinuses"),
    fld("Ethmoid cells"),
    fld("Sphenoid sinus"),
    fld("Nasal septum"),
    fld("Other findings"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  TOMOGRAFÍAS (CT) — nuevas
  // ═══════════════════════════════════════════
  t(55, "TC politraumatismo", "CT", "Thorax", [
    fld("Supratentorial brain parenchyma"),
    fld("Infratentorial brain parenchyma"),
    fld("Ventricular system and midline"),
    fld("Skull and facial bones"),
    fld("Cervical spine"),
    fld("Lung parenchyma"),
    fld("Mediastinum and great vessels"),
    fld("Heart and pericardium"),
    fld("Pleura and diaphragm"),
    fld("Thoracic spine"),
    fld("Liver and spleen"),
    fld("Kidneys and adrenal glands"),
    fld("Pancreas and bowel"),
    fld("Peritoneum and retroperitoneum"),
    fld("Bladder and pelvic organs"),
    fld("Pelvic ring and hips"),
    fld("Lumbar and sacral spine"),
    fld("Vascular structures"),
    fld("Soft tissues and subcutaneous emphysema"),
  ].join("\n")),

  t(56, "TC código ictus", "CT", "Head and neck", [
    "**TC craneal sin contraste**:\n" + [
      "   " + fld("Supratentorial brain parenchyma"),
      "   " + fld("Infratentorial brain parenchyma"),
      "   " + fld("Ventricular system and midline"),
      "   " + fld("Early ischemic signs (ASPECTS)"),
      "   " + fld("Hyperdense vessel sign"),
      "   " + fld("Hemorrhagic exclusion"),
    ].join("\n"),
    "**AngioTC de troncos supraaórticos e intracraneal**:\n" + [
      "   " + fld("Aortic arch"),
      "   " + fld("Common carotid arteries"),
      "   " + fld("Internal carotid arteries"),
      "   " + fld("Vertebral arteries"),
      "   " + fld("Basilar artery"),
      "   " + fld("Circle of Willis"),
      "   " + fld("Middle cerebral arteries"),
      "   " + fld("Anterior cerebral arteries"),
      "   " + fld("Posterior cerebral arteries"),
      "   " + fld("Site and extent of occlusion"),
      "   " + fld("Collateral circulation"),
    ].join("\n"),
    "**TC de perfusión cerebral**:\n" + [
      "   " + fld("CBV maps"),
      "   " + fld("CBF maps"),
      "   " + fld("MTT and Tmax maps"),
      "   " + fld("Ischemic core volume"),
      "   " + fld("Penumbra volume"),
      "   " + fld("Mismatch ratio"),
    ].join("\n"),
  ].join("\n")),

  t(57, "TC de cuello, tórax, abdomen y pelvis", "CT", "Thorax", [
    fld("Cervical soft tissues"),
    fld("Thyroid gland"),
    fld("Cervical lymph nodes"),
    fld("Lung parenchyma"),
    fld("Mediastinal lymph nodes"),
    fld("Trachea and bronchi"),
    fld("Aorta and great vessels"),
    fld("Heart and pericardium"),
    fld("Pleura and diaphragm"),
    fld("Liver"),
    fld("Gallbladder and bile ducts"),
    fld("Spleen"),
    fld("Pancreas"),
    fld("Adrenal glands"),
    fld("Kidneys and ureters"),
    fld("Peritoneum and retroperitoneum"),
    fld("Stomach and bowel"),
    fld("Bladder"),
    fld("Pelvic organs"),
    fld("Abdominal aorta and iliac arteries"),
    fld("Bone structures"),
  ].join("\n")),

  t(58, "TC de cabeza, cuello, tórax, abdomen y pelvis", "CT", "Thorax", [
    fld("Supratentorial brain parenchyma"),
    fld("Infratentorial brain parenchyma"),
    fld("Ventricular system and midline"),
    fld("Skull and paranasal sinuses"),
    fld("Cervical soft tissues and lymph nodes"),
    fld("Lung parenchyma"),
    fld("Mediastinum and great vessels"),
    fld("Heart and pericardium"),
    fld("Pleura and diaphragm"),
    fld("Liver"),
    fld("Gallbladder and bile ducts"),
    fld("Spleen"),
    fld("Pancreas"),
    fld("Adrenal glands"),
    fld("Kidneys and ureters"),
    fld("Peritoneum and retroperitoneum"),
    fld("Stomach and bowel"),
    fld("Pelvic organs"),
    fld("Abdominal aorta and iliac arteries"),
    fld("Bone structures"),
  ].join("\n")),

  t(59, "TC de pelvis", "CT", "Abdomen and pelvis", [
    fld("Bladder"),
    fld("Pelvic organs"),
    fld("Pelvic lymph nodes"),
    fld("Rectum and sigmoid"),
    fld("Peritoneum and mesenteric fat"),
    fld("Iliac vessels"),
    fld("Pelvic bones and hips"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(60, "AngioTC de troncos supraaórticos", "CT", "Head and neck", [
    fld("Aortic arch"),
    fld("Right common carotid artery"),
    fld("Right internal carotid artery"),
    fld("Right external carotid artery"),
    fld("Right vertebral artery"),
    fld("Left common carotid artery"),
    fld("Left internal carotid artery"),
    fld("Left external carotid artery"),
    fld("Left vertebral artery"),
    fld("Intracranial arteries"),
    fld("Bone structures"),
    fld("Other findings"),
  ].join("\n")),

  t(61, "AngioTC de aorta torácica", "CT", "Thorax", [
    fld("Ascending aorta"),
    fld("Aortic arch and branches"),
    fld("Descending thoracic aorta"),
    fld("Aortic wall and lumen"),
    fld("Pulmonary arteries"),
    fld("Heart and pericardium"),
    fld("Lung parenchyma"),
    fld("Pleura"),
    fld("Bone structures"),
    fld("Other findings"),
  ].join("\n")),

  t(62, "AngioTC de aorta abdominal", "CT", "Abdomen and pelvis", [
    fld("Suprarenal aorta"),
    fld("Infrarenal aorta"),
    fld("Renal arteries"),
    fld("Mesenteric arteries"),
    fld("Common iliac arteries"),
    fld("Internal and external iliac arteries"),
    fld("Aortic wall and lumen"),
    fld("Intraabdominal organs"),
    fld("Bone structures"),
    fld("Other findings"),
  ].join("\n")),

  t(63, "AngioTC pulmonar", "CT", "Thorax", [
    fld("Main pulmonary arteries"),
    fld("Lobar pulmonary arteries"),
    fld("Segmental and subsegmental arteries"),
    fld("Right ventricle and interventricular septum"),
    fld("Lung parenchyma"),
    fld("Pleura"),
    fld("Mediastinum"),
    fld("Bone structures"),
    fld("Other findings"),
  ].join("\n")),

  t(64, "TC de senos paranasales", "CT", "Head and neck", [
    fld("Maxillary sinuses"),
    fld("Frontal sinuses"),
    fld("Ethmoid cells"),
    fld("Sphenoid sinuses"),
    fld("Nasal cavity and septum"),
    fld("Ostiomeatal complexes"),
    fld("Orbits"),
    fld("Mastoid air cells"),
    fld("Other findings"),
  ].join("\n")),

  t(65, "TC de peñascos y oídos", "CT", "Head and neck", [
    fld("External auditory canals"),
    fld("Middle ears and ossicles"),
    fld("Inner ears and cochlea"),
    fld("Mastoid air cells"),
    fld("Tegmen tympani"),
    fld("Facial nerve canal"),
    fld("Internal auditory canals"),
    fld("Other findings"),
  ].join("\n")),

  t(66, "TC de abdomen y pelvis", "CT", "Abdomen and pelvis", [
    fld("Liver"),
    fld("Portal vein and hepatic artery"),
    fld("Gallbladder and bile ducts"),
    fld("Spleen"),
    fld("Pancreas"),
    fld("Adrenal glands"),
    fld("Kidneys and ureters"),
    fld("Bladder"),
    fld("Peritoneum and retroperitoneum"),
    fld("Stomach and bowel"),
    fld("Pelvic organs"),
    fld("Pelvic lymph nodes"),
    fld("Abdominal aorta and iliac arteries"),
    fld("Bone structures"),
    fld("Included portions of the thorax"),
  ].join("\n")),

  t(67, "TC columna lumbar", "CT", "Spine", [
    fld("Vertebral bodies L1-L5"),
    fld("Intervertebral discs"),
    fld("Facet joints"),
    fld("Spinal canal"),
    fld("Neural foramina"),
    fld("Sacrum and coccyx"),
    fld("Paravertebral soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(68, "TC maxilofacial", "CT", "Head and neck", [
    fld("Orbits"),
    fld("Nasal bones"),
    fld("Maxillary bones"),
    fld("Zygomatic arches"),
    fld("Mandible"),
    fld("Temporomandibular joints"),
    fld("Paranasal sinuses"),
    fld("Dental structures"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  RESONANCIAS (MRI) — nuevas
  // ═══════════════════════════════════════════
  t(69, "RM de pelvis masculina", "MRI", "Abdomen and pelvis", [
    fld("Prostate"),
    fld("Seminal vesicles"),
    fld("Bladder"),
    fld("Rectum and sigmoid"),
    fld("Peritoneum and retroperitoneum"),
    fld("Pelvic lymph nodes"),
    fld("Bone structures"),
    fld("Other findings"),
  ].join("\n")),

  t(70, "RM de próstata multiparamétrica", "MRI", "Abdomen and pelvis", [
    fld("Prostate size and morphology"),
    fld("Peripheral zone T2 signal"),
    fld("Transition zone T2 signal"),
    fld("Diffusion restriction and ADC"),
    fld("Dynamic contrast enhancement"),
    fld("PI-RADS assessment"),
    fld("Seminal vesicles"),
    fld("Neurovascular bundles"),
    fld("Pelvic lymph nodes"),
    fld("Bone structures"),
  ].join("\n")),

  t(71, "RM de mama", "MRI", "Thorax", [
    fld("Breast composition and BPE"),
    fld("Right breast parenchyma"),
    fld("Left breast parenchyma"),
    fld("Enhancement kinetics"),
    fld("Focal lesions"),
    fld("Axillary lymph nodes"),
    fld("Chest wall"),
    fld("Skin and nipple"),
    fld("Other findings"),
  ].join("\n")),

  t(72, "RM de cadera", "MRI", "Lower limbs", [
    fld("Femoral head and neck"),
    fld("Acetabulum and labrum"),
    fld("Hip joint and cartilage"),
    fld("Tendons and muscles"),
    fld("Bursae"),
    fld("Bone marrow signal"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(73, "RM de muñeca", "MRI", "Upper limbs", [
    fld("Distal radius and ulna"),
    fld("Carpal bones"),
    fld("TFCC"),
    fld("Intrinsic ligaments"),
    fld("Extrinsic ligaments"),
    fld("Tendons"),
    fld("Bone marrow signal"),
    fld("Soft tissues"),
  ].join("\n")),

  t(74, "RM de codo", "MRI", "Upper limbs", [
    fld("Distal humerus"),
    fld("Proximal radius and ulna"),
    fld("Elbow joint and cartilage"),
    fld("Medial collateral ligament"),
    fld("Lateral collateral ligament complex"),
    fld("Common extensor tendon"),
    fld("Common flexor tendon"),
    fld("Biceps tendon insertion"),
    fld("Bone marrow signal"),
    fld("Soft tissues"),
  ].join("\n")),

  t(75, "RM de recto", "MRI", "Abdomen and pelvis", [
    fld("Rectal tumor location and morphology"),
    fld("T staging (rectal wall invasion)"),
    fld("Mesorectal fascia"),
    fld("Extramural vascular invasion"),
    fld("Mesorectal lymph nodes"),
    fld("Lateral pelvic lymph nodes"),
    fld("Pelvic organs"),
    fld("Bone structures"),
    fld("Other findings"),
  ].join("\n")),

  t(76, "RM de plexo braquial", "MRI", "Upper limbs", [
    fld("Nerve roots C5-T1"),
    fld("Trunks"),
    fld("Divisions and cords"),
    fld("Scalene muscles"),
    fld("Subclavian vessels"),
    fld("Cervical spine"),
    fld("Lung apices"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(77, "RM de ATM", "MRI", "Head and neck", [
    fld("Right TMJ disc position closed mouth"),
    fld("Right TMJ disc position open mouth"),
    fld("Right condyle"),
    fld("Left TMJ disc position closed mouth"),
    fld("Left TMJ disc position open mouth"),
    fld("Left condyle"),
    fld("Joint effusion"),
    fld("Bone marrow signal"),
    fld("Other findings"),
  ].join("\n")),

  t(78, "RM de columna cervicotorácica", "MRI", "Spine", [
    fld("Vertebral bodies C1-T4"),
    fld("Intervertebral discs cervical"),
    fld("Intervertebral discs cervicothoracic"),
    fld("Spinal cord"),
    fld("Neural foramina"),
    fld("Facet joints"),
    fld("Craniocervical junction"),
    fld("Paravertebral soft tissues"),
  ].join("\n")),

  t(79, "RM de columna lumbosacra", "MRI", "Spine", [
    fld("Vertebral bodies L1-S1"),
    fld("Intervertebral discs"),
    fld("Conus medullaris and cauda equina"),
    fld("Neural foramina"),
    fld("Facet joints"),
    fld("Sacroiliac joints"),
    fld("Paravertebral soft tissues"),
    fld("Sacrum and coccyx"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  ECOGRAFÍAS (Ultrasound) — nuevas
  // ═══════════════════════════════════════════
  t(80, "Ecografía de pelvis femenina", "Ultrasound", "Abdomen and pelvis", [
    fld("Uterus"),
    fld("Endometrium"),
    fld("Cervix"),
    fld("Right ovary"),
    fld("Left ovary"),
    fld("Adnexa"),
    fld("Cul-de-sac"),
    fld("Bladder"),
    fld("Other findings"),
  ].join("\n")),

  t(81, "Ecografía obstétrica primer trimestre", "Ultrasound", "Abdomen and pelvis", [
    fld("Gestational sac"),
    fld("Yolk sac"),
    fld("Embryo/fetus"),
    fld("Crown-rump length and gestational age"),
    fld("Cardiac activity"),
    fld("Number of gestations"),
    fld("Uterus and adnexa"),
    fld("Other findings"),
  ].join("\n")),

  t(82, "Ecografía obstétrica segundo-tercer trimestre", "Ultrasound", "Abdomen and pelvis", [
    fld("Fetal biometry"),
    fld("Estimated fetal weight and percentile"),
    fld("Fetal head and brain"),
    fld("Fetal face"),
    fld("Fetal thorax and heart"),
    fld("Fetal abdomen"),
    fld("Fetal spine"),
    fld("Fetal limbs"),
    fld("Placenta"),
    fld("Amniotic fluid"),
    fld("Cervix"),
    fld("Umbilical cord"),
    fld("Other findings"),
  ].join("\n")),

  t(83, "Ecografía renal y vías urinarias", "Ultrasound", "Abdomen and pelvis", [
    fld("Right kidney"),
    fld("Left kidney"),
    fld("Bladder"),
    fld("Prostate (if applicable)"),
    fld("Post-void residual"),
    fld("Other findings"),
  ].join("\n")),

  t(84, "Ecografía testicular", "Ultrasound", "Abdomen and pelvis", [
    fld("Right testis"),
    fld("Left testis"),
    fld("Epididymis"),
    fld("Spermatic cords"),
    fld("Scrotal wall"),
    fld("Hydrocele"),
    fld("Doppler findings"),
    fld("Other findings"),
  ].join("\n")),

  t(85, "Ecografía musculoesquelética", "Ultrasound", "Lower limbs", [
    fld("Target structure"),
    fld("Tendons"),
    fld("Muscles"),
    fld("Bursae"),
    fld("Joint"),
    fld("Neurovascular structures"),
    fld("Subcutaneous tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(86, "Ecografía de hombro", "Ultrasound", "Upper limbs", [
    fld("Supraspinatus tendon"),
    fld("Infraspinatus tendon"),
    fld("Subscapularis tendon"),
    fld("Biceps tendon long head"),
    fld("Subacromial-subdeltoid bursa"),
    fld("Acromioclavicular joint"),
    fld("Glenohumeral joint"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(87, "Ecografía de rodilla", "Ultrasound", "Lower limbs", [
    fld("Quadriceps tendon"),
    fld("Patellar tendon"),
    fld("Medial collateral ligament"),
    fld("Lateral collateral ligament"),
    fld("Baker cyst"),
    fld("Joint effusion"),
    fld("Suprapatellar bursa"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  t(88, "Ecografía de cadera infantil", "Ultrasound", "Lower limbs", [
    fld("Right hip alpha angle"),
    fld("Right hip beta angle"),
    fld("Right hip Graf classification"),
    fld("Left hip alpha angle"),
    fld("Left hip beta angle"),
    fld("Left hip Graf classification"),
    fld("Femoral head coverage"),
    fld("Other findings"),
  ].join("\n")),

  t(89, "Doppler renal", "Ultrasound", "Abdomen and pelvis", [
    fld("Right kidney morphology"),
    fld("Right renal artery Doppler"),
    fld("Right intrarenal resistive indices"),
    fld("Left kidney morphology"),
    fld("Left renal artery Doppler"),
    fld("Left intrarenal resistive indices"),
    fld("Aorta at renal level"),
    fld("Other findings"),
  ].join("\n")),

  t(90, "Doppler portal y hepático", "Ultrasound", "Abdomen and pelvis", [
    fld("Liver parenchyma"),
    fld("Main portal vein"),
    fld("Right and left portal branches"),
    fld("Hepatic veins"),
    fld("Hepatic artery"),
    fld("Spleen and splenic vein"),
    fld("Ascites"),
    fld("Other findings"),
  ].join("\n")),

  t(91, "Ecografía de tobillo y pie", "Ultrasound", "Lower limbs", [
    fld("Achilles tendon"),
    fld("Peroneal tendons"),
    fld("Posterior tibial tendon"),
    fld("Plantar fascia"),
    fld("Tibiotalar joint"),
    fld("Soft tissues"),
    fld("Other findings"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  PROCEDIMIENTOS (Procedures)
  // ═══════════════════════════════════════════
  t(92, "Arteriografía diagnóstica", "Procedures", "Abdomen and pelvis", [
    fld("Access site"),
    fld("Target vessel"),
    fld("Findings"),
    fld("Run-off"),
    fld("Complications"),
    fld("Other findings"),
  ].join("\n")),

  t(93, "Biopsia guiada por imagen", "Procedures", "Abdomen and pelvis", [
    fld("Target lesion"),
    fld("Guidance modality"),
    fld("Needle type and gauge"),
    fld("Number of passes"),
    fld("Specimen adequacy"),
    fld("Complications"),
    fld("Post-procedure check"),
  ].join("\n")),

  t(94, "Drenaje percutáneo", "Procedures", "Abdomen and pelvis", [
    fld("Collection location and size"),
    fld("Guidance modality"),
    fld("Catheter type and size"),
    fld("Aspirated material"),
    fld("Post-procedure position"),
    fld("Complications"),
    fld("Other findings"),
  ].join("\n")),

  t(95, "Histerosalpingografía", "Procedures", "Abdomen and pelvis", [
    fld("Uterine cavity"),
    fld("Right fallopian tube"),
    fld("Left fallopian tube"),
    fld("Peritoneal spill"),
    fld("Other findings"),
  ].join("\n")),

  t(96, "Cistografía", "Procedures", "Abdomen and pelvis", [
    fld("Bladder morphology"),
    fld("Bladder wall"),
    fld("Vesicoureteral reflux"),
    fld("Urethra (if included)"),
    fld("Other findings"),
  ].join("\n")),

  // ═══════════════════════════════════════════
  //  RECIST 1.1
  // ═══════════════════════════════════════════
  t(97, "RECIST 1.1 – Seguimiento oncológico", "RECIST", "Thorax", [
    fld("Información clínica"),
    fld("Comparación"),
    "***Lesiones diana***:",
    fld("Lesión diana 1"),
    fld("Lesión diana 2"),
    fld("Lesión diana 3"),
    fld("Lesión diana 4"),
    fld("Lesión diana 5"),
    "***Lesiones no diana***:",
    fld("Lesión no diana 1"),
    fld("Lesión no diana 2"),
    fld("Lesión no diana 3"),
    fld("Lesiones nuevas"),
    fld("Hallazgos adicionales"),
  ].join("\n")),
];
