import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { Logo } from "@/components/ui/logo";

export default function LegalPage() {
  return (
    <div className="min-h-screen bg-[#0a0a1a] text-gray-300">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="flex items-center gap-3 mb-10">
          <Link href="/" className="text-gray-500 hover:text-white transition-colors">
            <ArrowLeft className="h-5 w-5" />
          </Link>
          <Logo size="md" forceDark />
        </div>

        <h1 className="text-3xl font-bold text-white mb-2">Terms of Use, Privacy Policy & Liability Disclaimer</h1>
        <p className="text-sm text-gray-500 mb-10">Last updated: April 2026</p>

        <div className="space-y-10 leading-relaxed">
          {/* 1. Nature of the Service */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Nature of the Service</h2>
            <p>
              Radiogen.AI is a <strong className="text-white">report drafting assistance tool</strong> designed exclusively for licensed radiologists and qualified medical professionals. The platform uses artificial intelligence to help structure and draft radiology reports based on the radiologist&apos;s own dictation.
            </p>
            <p className="mt-3">
              Radiogen.AI is <strong className="text-white">NOT</strong> a diagnostic tool. It does not perform image analysis, does not interpret medical images, and does not generate autonomous clinical diagnoses or therapeutic recommendations.
            </p>
          </section>

          {/* 2. Limitation of Liability */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Limitation of Liability</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                All clinical content generated by Radiogen.AI is derived <strong className="text-white">exclusively from the radiologist&apos;s dictation</strong>. The AI does not add clinical findings, diagnoses, or pathological assessments that were not dictated by the user.
              </li>
              <li>
                The <strong className="text-white">radiologist is solely responsible</strong> for reviewing, validating, modifying, and approving every report before it is delivered to patients, referring physicians, or incorporated into any medical record.
              </li>
              <li>
                Radiogen.AI and its operators <strong className="text-white">assume no liability</strong> for clinical decisions, diagnostic errors, omissions, or any adverse patient outcomes arising from the use of reports generated with this tool.
              </li>
              <li>
                The user acknowledges that AI-generated text may contain errors, inaccuracies, or inappropriate phrasing, and accepts full responsibility for validating the final output.
              </li>
            </ul>
          </section>

          {/* 3. Professional Responsibility */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. Professional Responsibility</h2>
            <p>
              By using Radiogen.AI, the radiologist confirms that:
            </p>
            <ul className="list-disc pl-6 space-y-2 mt-3">
              <li>They hold a valid medical license and are qualified to interpret radiological studies and issue radiology reports.</li>
              <li>They will review every AI-generated report in its entirety before signing, delivering, or archiving it.</li>
              <li>They understand that the AI is a drafting assistant and that the final medical judgment rests entirely with them.</li>
              <li>They will not use the platform to replace professional radiological evaluation.</li>
            </ul>
          </section>

          {/* 4. Data Privacy */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Data Privacy & Security</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>
                <strong className="text-white">No patient-identifiable data is required or stored.</strong> The platform processes anonymous dictation text only. Users must not include patient names, IDs, dates of birth, or any other personally identifiable information (PII) in their dictation.
              </li>
              <li>
                Dictation text and generated reports are stored in the user&apos;s account for style learning and report history purposes. This data is encrypted at rest and in transit.
              </li>
              <li>
                API keys configured by the administrator are encrypted using AES-256-GCM before storage.
              </li>
              <li>
                Radiogen.AI does not sell, share, or transfer user data to third parties for marketing or commercial purposes.
              </li>
              <li>
                AI processing is performed through the language model provider configured by the administrator (e.g., OpenAI, DeepSeek, Anthropic). Dictation text is sent to these providers for processing. Users should review the privacy policies of the configured AI provider.
              </li>
              <li>
                Users may request deletion of their account and all associated data at any time by contacting the administrator.
              </li>
            </ul>
          </section>

          {/* 5. Prohibited Uses */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Prohibited Uses</h2>
            <ul className="list-disc pl-6 space-y-2">
              <li>Using Radiogen.AI as a substitute for professional radiological evaluation.</li>
              <li>Including patient-identifiable information in dictations or clinical context fields.</li>
              <li>Distributing AI-generated reports without prior review and validation by a qualified radiologist.</li>
              <li>Reverse engineering, decompiling, or attempting to extract the source code or algorithms of the platform.</li>
              <li>Sharing account credentials with unauthorized individuals.</li>
            </ul>
          </section>

          {/* 6. Intellectual Property */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Intellectual Property</h2>
            <p>
              The Radiogen.AI platform, including its code, design, algorithms, and documentation, is the intellectual property of its operators. Reports generated by the user belong to the user and their institution. The platform retains no ownership over the clinical content produced by its users.
            </p>
          </section>

          {/* 7. Service Availability */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Service Availability</h2>
            <p>
              Radiogen.AI is provided &quot;as is&quot; without warranties of any kind, express or implied. We do not guarantee uninterrupted service availability. The platform depends on third-party AI providers and infrastructure, which may experience downtime or service degradation outside our control.
            </p>
          </section>

          {/* 8. Changes to Terms */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Changes to These Terms</h2>
            <p>
              We reserve the right to modify these terms at any time. Users will be notified of material changes. Continued use of the platform after notification constitutes acceptance of the updated terms.
            </p>
          </section>

          {/* 9. Contact */}
          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Contact</h2>
            <p>
              For questions, data deletion requests, or legal inquiries, please contact us at{" "}
              <a href="mailto:legal@radiogen.ai" className="text-blue-400 hover:text-blue-300">legal@radiogen.ai</a>.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-white/10 text-center text-sm text-gray-500">
          &copy; {new Date().getFullYear()} Radiogen.AI. All rights reserved.
        </div>
      </div>
    </div>
  );
}
